  const DL_EDU = [
    {
      id: "dl_edu_01",
      cat: "Cohorts",
      icon: "📅",
      title: "Nine students for a fifteen-seat cohort",
      desc: "Cohort 1 starts on Sunday. Nine of 15 seats are paid at $1,800 each and you break even at 13. Tariq says run it anyway. Your ads freelancer says push the start by four weeks and fill it properly.",
      when: (s) => s.sector.id === "edtech" && s.week >= 3 && s.week <= 10,
      A: { title: "Start on Sunday with nine", fx: { cash: -2500, pmf: 3, morale: 4, clarity: -3 }, log: "Nine laptops, one whiteboard, Tariq on the back row. By Thursday the class had a WhatsApp group with its own memes.",
           echo: { after: [10, 18], icon: "🤝", title: "The nine bring their friends", text: "Seven of the nine got job offers. Their posts did what your ads couldn't: 23 applications for the next cohort name one of them as the reason.", fx: { users: 200, mrrPct: 0.06, pmf: 2 } } },
      B: { title: "Push the start by four weeks", fx: { mrrPct: 0.04, users: -60, churn: 0.3, clarity: 3 }, log: "Three students asked for their deposits back. Five stayed. One brought a cousin who paid in full." },
    },
    {
      id: "dl_edu_02",
      cat: "Admissions",
      icon: "👔",
      title: "A father wants to pay upfront, and to watch",
      desc: "Yousef failed your admissions test by 6 points. His father offers $2,400 by transfer today if you admit him, and wants a weekly WhatsApp report on attendance and grades. Cohort 2 still has four empty seats.",
      when: (s) => s.sector.id === "edtech" && s.week >= 4 && s.week <= 12,
      A: { title: "Admit him and send the reports", fx: { cash: 2400, morale: -3, pmf: -2 }, log: "The money arrived before lunch. Your lead instructor now writes a report every Thursday night.",
           echo: { after: [7, 12], icon: "🧾", title: "The father wants his money back", text: "Yousef stopped coming in week 6. His father sat in your reception for two hours and left with a $1,800 refund and a promise to tell every family he knows.", fx: { cash: -1800, clarity: -6, users: -40 } } },
      B: { title: "Hold the bar, offer the prep course", fx: { clarity: -2, pmf: 2, mrrPct: -0.02 }, log: "The father called it bureaucracy. Yousef signed up for the free 3-week prep course, on his own.",
           echo: { after: [8, 14], icon: "🎓", title: "Yousef passes on the second try", text: "Yousef passed the test by 11 points and finished in the top third of his cohort. His father now forwards your posts to the family group.", fx: { users: 80, pmf: 2 } } },
    },
    {
      id: "dl_edu_03",
      cat: "Instructors",
      icon: "🏦",
      title: "A bank offers your lead instructor double",
      desc: "Hazem, rated 4.8 out of 5 by three cohorts, has an offer from a bank's AI team at $9,000 a month. Cohort 4 has six weeks left, and half of them enrolled after watching his YouTube videos.",
      when: (s) => s.sector.id === "edtech" && s.week >= 10 && s.monthlyRevenue >= 3000,
      A: { title: "Match it with salary and equity", fx: { baseBurn: 1300, equity: -1, morale: 4, pmf: 2 }, log: "Hazem stayed. The other instructors now know exactly what a counter-offer looks like.",
           echo: { after: [12, 22], icon: "💼", title: "Two more instructors want a bank offer", text: "Two instructors came back from recruiter calls with numbers. Neither has an offer yet. Both mentioned Hazem's package in the same sentence.", fx: { baseBurn: 700, morale: -4 } } },
      B: { title: "Let him go, promote his assistant", fx: { morale: -4, pmf: -3, churn: 0.5, xp: 30 }, log: "Hazem's farewell session ran an hour over. Dina, his teaching assistant, takes the cohort on Sunday.",
           echo: { after: [10, 20], icon: "🌱", title: "Dina's cohort finishes the strongest yet", text: "Dina turned the hardest module into short daily exercises. Completion hit 91%, and applicants this month asked for her class by name.", fx: { pmf: 4, churn: -0.5, morale: 4 } } },
    },
    {
      id: "dl_edu_04",
      cat: "Outcomes",
      icon: "📊",
      title: "Your rival's billboards say 94% placement",
      desc: "SkillUp Arabia counts internships, freelance gigs and graduates hired as its own teaching assistants. Your honest number is 61% in tech jobs within 180 days. Counted their way, yours would be 89%.",
      when: (s) => s.sector.id === "edtech" && s.monthlyRevenue >= 4000,
      A: { title: "Count it their way and say 89%", fx: { users: 350, mrrPct: 0.08, pmf: -2 }, log: "The new landing page went live on Tuesday. Applications rose 40% in two weeks.",
           echo: { after: [12, 24], icon: "📉", title: "A graduate posts the real list", text: "A graduate counted her own cohort and posted it: 9 of 22 in tech jobs, 4 of them as your teaching assistants. Parents shared it faster than any ad.", fx: { users: -300, churn: 0.8, trust: -5 } } },
      B: { title: "Publish 61% and the method", fx: { mrrPct: -0.03, trust: 3, pmf: 3, clarity: 2 }, log: "You published every graduate, every role, every salary band on one page. Sales says it's the hardest number in the market to sell.",
           echo: { after: [10, 20], icon: "🏛", title: "Employers start quoting your report", text: "An HR director at a hiring partner forwarded your outcomes report to two other companies. One asked to interview your whole next cohort.", fx: { mrrPct: 0.07, users: 150, trust: 3 } } },
    },
    {
      id: "dl_edu_05",
      cat: "Placement",
      icon: "🧊",
      title: "Your biggest hiring partner freezes hiring",
      desc: "Northwind Retail hired 11 of your last 30 graduates. This morning they froze junior hiring for two quarters. Cohort 5 graduates in three weeks, and every contract says: a tech job in 180 days or your money back.",
      when: (s) => s.sector.id === "edtech" && s.week >= 14 && s.monthlyRevenue >= 5000,
      A: { title: "Hire two people to find new employers", fx: { cash: -4000, baseBurn: 900, clarity: -4, pmf: 2 }, log: "Salma and Fady start Monday with a list of 140 companies and a cold-call script Tariq hates.",
           echo: { after: [8, 16], icon: "🤝", title: "Fourteen new hiring partners", text: "Salma's sheet now lists 14 companies that have hired at least one graduate. None takes more than 3 a quarter, and that is the point.", fx: { churn: -0.6, pmf: 3, mrrPct: 0.05 } } },
      B: { title: "Stretch the guarantee to 270 days for new students", fx: { clarity: 3, mrrPct: -0.02, trust: -2 }, log: "The new contract went out with the longer window. Cohort 5 still has the old one.",
           echo: { after: [6, 12], icon: "💸", title: "Cohort 5 asks for its money back", text: "Day 181 arrived for Cohort 5. Six graduates without tech jobs sent the same lawyer's letter, word for word, asking for a full refund.", fx: { cash: -7000, clarity: -6, trust: -3 } } },
    },
    {
      id: "dl_edu_06",
      cat: "Income share",
      icon: "💵",
      title: "23 graduates owe you 12% and aren't paying",
      desc: "58 graduates on income-share agreements are employed. 23 haven't sent a payslip in three months. A collections agency offers to chase them for 30% of whatever it recovers, starting with calls to their employers.",
      when: (s) => s.sector.id === "edtech" && s.week >= 16 && s.monthlyRevenue >= 3000,
      A: { title: "Hand the list to the agency", fx: { cash: 4500, morale: -3, pmf: -2 }, log: "The agency recovered $6,400 in five weeks and kept its cut. Two graduates blocked your number.",
           echo: { after: [6, 14], icon: "📱", title: "A collections call goes viral", text: "A graduate filmed the agency calling his manager about what he owes you. Half a million views later, applicants ask whether you'll call their boss too.", fx: { users: -300, churn: 0.7, trust: -3 } } },
      B: { title: "Chase them yourselves, with a grace plan", fx: { clarity: -6, cash: -1200, pmf: 2 }, log: "You called all 23 yourself. Eleven had lost their jobs or taken pay cuts. Nine agreed to a plan. Three stopped answering.",
           echo: { after: [10, 20], icon: "💰", title: "The income-share payments come in", text: "Treated like people, the graduates on grace plans became your most reliable payers. Income share now covers 18% of monthly revenue.", fx: { mrrPct: 0.07, pmf: 2 } } },
    },
    {
      id: "dl_edu_07",
      cat: "Government",
      icon: "🏛",
      title: "The ministry wants 600 funded seats",
      desc: "A national upskilling programme will fund 600 seats at $1,100 each, less than half your price. It pays 90 days after each student passes the ministry exam, and wants fingerprint attendance and a 40-page report per cohort.",
      when: (s) => s.sector.id === "edtech" && (s.stage >= 2 || s.week >= 22),
      A: { title: "Bid for all 600 seats", fx: { users: 1200, mrrPct: 0.12, baseBurn: 1200, clarity: -6, pmf: -2 }, log: "You won the tender. You also hired a full-time coordinator whose only job is the attendance portal.",
           echo: { after: [12, 24], icon: "⏳", title: "Invoice three is waiting for a stamp", text: "The ministry approved the exam results, but the payment needs a signature from an official on leave. $66,000 is stuck, and payroll is due on the 25th.", fx: { cash: -6000, clarity: -8, trust: -3 } } },
      B: { title: "Keep your price and skip the tender", fx: { pmf: 2, trust: -3, morale: 2 }, log: "Layla asked twice why you would turn down 600 students. SkillUp Arabia won the tender a week later." },
    },
    {
      id: "dl_edu_08",
      cat: "Corporate training",
      icon: "🏢",
      title: "A bank wants your AI course for 300 staff",
      desc: "A regional bank offers $180,000 to train 300 employees in applied AI over five months, under its own brand. It wants your three best instructors full-time and custom case studies. No placements, no refunds.",
      when: (s) => s.sector.id === "edtech" && (s.stage >= 2 || s.week >= 26) && s.monthlyRevenue >= 6000,
      A: { title: "Sign it and lend them the instructors", fx: { cash: 15000, pmf: -4, churn: 0.6, morale: -3 }, log: "The deposit cleared on Thursday. Your three best instructors now teach risk analysts in a tower across town.",
           echo: { after: [14, 26], icon: "📈", title: "The bank renews and tells its peers", text: "The bank renewed for 500 staff and introduced you to two insurers. Corporate training is now 30% of revenue, and it pays on time.", fx: { mrrPct: 0.1, cash: 3000, pmf: -2 } } },
      B: { title: "Decline and protect the bootcamp", fx: { pmf: 3, trust: -3, clarity: 2 }, log: "The bank's head of learning said she would keep your deck on file. Your instructors stayed with the cohort." },
    },
  ];
