  const DL_FIN = [
    {
      id: "dl_fin_01",
      cat: "Compliance",
      icon: "👔",
      title: "The licence needs a named compliance officer",
      desc: "The central bank's form has a box for your money-laundering reporting officer. Hana Al-Rashid spent 9 years in bank compliance and wants $5,500 a month, more than Tariq earns. A consultant offers to sign for $1,200 a month.",
      when: (s) => s.sector.id === "fintech" && s.week >= 3 && !s.mkt.licensed,
      A: { title: "Hire Hana full time", fx: { baseBurn: 1400, cash: -2000, trust: 4, cofounder: -4, clarity: 3 }, log: "Hana's first week produced a 40-row risk register and a question about who can approve refunds. Tariq asked, quietly, why she earns more than him.",
           echo: { after: [8, 16], icon: "🏛", title: "The inspector asks for Hana by name", text: "The central bank booked a full day for its on-site visit. Hana walked them through the risk register and the alert log, and they left before lunch.", fx: { trust: 6, clarity: 5, pmf: 2 } } },
      B: { title: "Use the consultant for now", fx: { baseBurn: 400, cofounder: 3, trust: -2 }, log: "The consultant signed the form on a Sunday. He also signs for four other applicants.",
           echo: { after: [6, 14], icon: "🧾", title: "Your AML policy names another company", text: "The central bank returned your file with 23 comments. Comment 7: page 31 of your anti-money-laundering policy mentions a firm that isn't yours.", fx: { trust: -6, clarity: -6, cash: -2500 } } },
    },
    {
      id: "dl_fin_02",
      cat: "Onboarding",
      icon: "🧩",
      title: "Six in ten merchants quit at the KYB step",
      desc: "Merchants sign up, then stop when you ask for the commercial registration, a bank letter and the owners' IDs. Sara in growth wants to let them go live on a phone number and collect the papers within 30 days.",
      when: (s) => s.sector.id === "fintech" && s.week >= 4,
      A: { title: "Go live first, papers later", fx: { users: 300, mrrPct: 0.06, pmf: 2, trust: -2 }, log: "Completed signups doubled in a week. Someone in ops started a spreadsheet tab called 'papers missing'.",
           echo: { after: [8, 18], icon: "🕵", title: "Forty merchants never sent their papers", text: "The sponsor bank's sample review found one of them: a 'gift shop' whose card traffic all came from a betting site. The bank wants a remediation plan in 14 days.", fx: { trust: -5, cash: -3000, clarity: -6, users: -150 } } },
      B: { title: "Keep full KYB and fix the form", fx: { cash: -1500, users: -80, pmf: 2, clarity: -2 }, log: "Tariq rebuilt the form so merchants can send documents as photos from their phones. Drop-off fell from 60% to 45%." },
    },
    {
      id: "dl_fin_03",
      cat: "Risk",
      icon: "🎲",
      title: "A gaming top-up site offers 4.5% on $180,000 a month",
      desc: "They sell in-game credits and will pay 4.5% instead of your usual 2.2%. Their last processor dropped them at a 1.6% chargeback rate. The card schemes start watching an acquirer's portfolio near 1%.",
      when: (s) => s.sector.id === "fintech" && s.mkt.licensed === true && s.monthlyRevenue >= 3000,
      A: { title: "Sign them with a 10% rolling reserve", fx: { mrrPct: 0.15, arpu: 3, trust: -3, clarity: -3 }, log: "They signed in a day. Their volume arrived the same week, mostly between midnight and 4am.",
           echo: { after: [6, 14], icon: "🚨", title: "A card scheme puts you on its watch list", text: "Disputes across your whole portfolio crossed 1.1%. The scheme's letter lists fines that rise every month until you are back under the line.", fx: { cash: -6000, trust: -6, churn: 0.4, clarity: -5 } } },
      B: { title: "Decline and tell them why", fx: { morale: -3, pmf: 2, trust: 2, clarity: 2 }, log: "Your sales lead lost the biggest commission of the year. The gaming site was live with Sahm Pay by Friday." },
    },
    {
      id: "dl_fin_04",
      cat: "Fraud",
      icon: "💳",
      title: "1,400 card tests at 2:40am",
      desc: "A fraud ring is pushing stolen cards through a florist's checkout in tiny payments to see which ones work. Mother's Day is on Saturday, and the florist is one of your best merchants.",
      when: (s) => s.sector.id === "fintech" && s.mkt.licensed === true && s.week >= 10,
      A: { title: "Freeze the florist's checkout now", fx: { churn: 0.3, mrrPct: -0.03, clarity: 3, trust: 1 }, log: "The attack stopped at 2:52am. The florist found out from a customer at 8am and called you 11 times." },
      B: { title: "Add velocity rules and stay live", fx: { techDebt: 4, clarity: -6, morale: -2, pmf: 2 }, log: "Tariq wrote rules until dawn: 3 tries per card, then a block. Most tests were stopped by 4am. The Mother's Day orders went through.",
           echo: { after: [5, 10], icon: "🧾", title: "The chargebacks from that night arrive", text: "The issuing banks caught up: 212 disputes from the cards that got through, each with a $15 fee. The florist's balance can't cover them, so yours does.", fx: { cash: -3500, trust: -2, clarity: -3 } } },
    },
    {
      id: "dl_fin_05",
      cat: "Pricing",
      icon: "🏷",
      title: "Northwind wants 1.4% or it moves to PayNest",
      desc: "Northwind Retail is 38% of the volume you process. You charge 2.1% plus $0.30; PayNest quoted them 1.4% plus $0.20 a payment. Interchange and scheme fees already cost you about 1.1%.",
      when: (s) => s.sector.id === "fintech" && s.mkt.licensed === true && s.monthlyRevenue >= 4000,
      A: { title: "Match 1.4% on a two-year contract", fx: { mrrPct: -0.1, arpu: -2, churn: -0.4, clarity: 2 }, log: "Northwind signed for two years. Your margin on their volume is now 0.3 points.",
           echo: { after: [8, 18], icon: "📨", title: "Three merchants ask for the Northwind price", text: "A Northwind supplier asked Omar what you charge them. Now three merchants want 1.4%, and one has the figure in writing.", fx: { arpu: -2, mrrPct: -0.04, clarity: -3 } } },
      B: { title: "Hold 1.9% and offer next-day settlement", fx: { cash: -3000, arpu: 1, clarity: -3, pmf: 1 }, log: "Northwind's finance team liked being paid the next morning. They asked for a week to think.",
           echo: { after: [6, 14], icon: "📉", title: "Northwind splits its volume", text: "Northwind moved its online store to PayNest and kept its branches with you. It is now 21% of your volume, not 38%.", fx: { mrrPct: -0.09, pmf: 2, clarity: 3 } } },
    },
    {
      id: "dl_fin_06",
      cat: "Operations",
      icon: "📊",
      title: "Settlement is off by $27,400",
      desc: "Ramy in finance found that three days of the bank's settlement files don't match your ledger. A timezone bug paid 61 merchants twice, and the money is already in their accounts.",
      when: (s) => s.sector.id === "fintech" && s.mkt.licensed === true && s.monthlyRevenue >= 5000,
      A: { title: "Recover it from their next payouts", fx: { cash: -2000, churn: 0.5, morale: -2, clarity: 3 }, log: "You sent 61 merchants a polite notice with a breakdown. 52 accepted the deduction. 9 called it theft on Instagram." },
      B: { title: "Absorb it and build automated recon", fx: { cash: -9000, techDebt: -6, churn: -0.2, clarity: -2 }, log: "You wrote off all $27,400 and Ramy and Tariq spent 3 weeks building a daily three-way match: bank, ledger, card scheme.",
           echo: { after: [10, 20], icon: "✅", title: "The recon engine catches the bank's mistake", text: "The 6am match flagged a $14,000 double debit by the sponsor bank. Ramy sent them the line items before their own team noticed.", fx: { cash: 8000, trust: 4, clarity: 4 } } },
    },
    {
      id: "dl_fin_07",
      cat: "Bank partner",
      icon: "🏦",
      title: "The sponsor bank wants your crypto merchants gone",
      desc: "The bank's new chief risk officer gives you 30 days to offboard 22 merchants in crypto on-ramps and digital goods, or the bank ends your sponsorship. Those merchants are 19% of your revenue.",
      when: (s) => s.sector.id === "fintech" && s.mkt.licensed === true && (s.stage >= 2 || s.week >= 20),
      A: { title: "Offboard all 22 by the deadline", fx: { mrrPct: -0.15, trust: 3, clarity: 3, morale: -3 }, log: "Twenty-two goodbye emails, each with 30 days' notice. Two merchants threatened to sue. The bank's next email was friendly." },
      B: { title: "Negotiate and open a second bank", fx: { cash: -6000, baseBurn: 600, clarity: -8, mrrPct: -0.04 }, log: "You kept 14 merchants under stricter monitoring and spent 3 weeks in a second bank's meeting rooms.",
           echo: { after: [8, 18], icon: "🤝", title: "A second bank signs", text: "The second bank approved your programme after months of questions. For the first time, no single bank can switch you off with one email.", fx: { trust: 8, mrrPct: 0.06, clarity: 4 } } },
    },
    {
      id: "dl_fin_08",
      cat: "Reliability",
      icon: "📅",
      title: "White Friday is 6x volume and the test broke at 4x",
      desc: "Your load test fell over at 4x normal traffic. This year White Friday lands on payday, your three largest merchants expect 6x, and it is 4 weeks away.",
      when: (s) => s.sector.id === "fintech" && s.mkt.licensed === true && (s.stage >= 2 || s.week >= 22),
      A: { title: "Freeze features and buy capacity", fx: { cash: -7000, baseBurn: 300, pmf: -2, morale: -2, techDebt: -4 }, log: "No releases for 4 weeks. Tariq ran the load test every night; on the last run it held at 7x." },
      B: { title: "Ask big merchants to stagger their sales", fx: { pmf: 2, clarity: -3, techDebt: 3 }, log: "Two merchants agreed to start their sale at 6pm instead of midnight. The third said its campaign was already printed.",
           echo: { after: [4, 6], icon: "💥", title: "Checkout times out at 9:02pm", text: "For 47 minutes on White Friday, 1 in 5 payments failed. Every failure showed your logo on someone else's checkout page.", fx: { mrrPct: -0.06, churn: 0.6, trust: -4, morale: -5 } } },
    },
  ];
