  const DL_HEALTH = [
    {
      id: "dl_health_01",
      cat: "Doctors",
      icon: "🩺",
      title: "No doctor on call after 10pm",
      desc: "Most of your doctors are hospital consultants who log in after their shifts end. Between 10pm and 1am patients wait 40 minutes for a call, and that is exactly when they measure and start to worry.",
      when: (s) => s.sector.id === "healthtech" && s.week >= 3 && s.week <= 14,
      A: { title: "Pay two doctors a night premium", fx: { baseBurn: 900, cash: -1000, churn: -0.5, pmf: 3 }, log: "Dr. Yousef and Dr. Mona took the late shift at 40% above the day rate. Average night wait fell to 6 minutes." },
      B: { title: "Close bookings after 10pm", fx: { users: -150, clarity: 3, pmf: -2 }, log: "The app now says 'Doctors are back at 8am'. Three patients replied with the same angry emoji.",
           echo: { after: [6, 14], icon: "🌫", title: "Dr. Now owns the night", text: "Dr. Now's new billboard on the ring road says 'A doctor at 2am, in 5 minutes'. Your night-time sign-ups dropped by a third the week it went up.", fx: { users: -200, churn: 0.3 } } },
    },
    {
      id: "dl_health_02",
      cat: "Clinical",
      icon: "🧾",
      title: "Antibiotics are buying five-star ratings",
      desc: "Dr. Rania Haddad, your medical director, audited 300 calls: 38% of sore-throat consults ended with an antibiotic, mostly for viral infections. Doctors who refuse get one-star reviews and fewer bookings.",
      when: (s) => s.sector.id === "healthtech" && s.week >= 5 && s.week <= 16,
      A: { title: "Enforce the prescribing protocol", fx: { churn: 0.4, users: -100, pmf: 2, morale: -3 }, log: "Rania sent the protocol on Sunday. By Thursday the app rating dropped from 4.8 to 4.5 and two doctors asked to talk.",
           echo: { after: [10, 20], icon: "🏦", title: "An insurer noticed your numbers", text: "An insurer's medical team compared prescribing rates across telehealth providers. Yours was the lowest. They asked for a meeting about a pilot.", fx: { mrrPct: 0.06, trust: 4, pmf: 2 } } },
      B: { title: "Leave it to each doctor's judgement", fx: { churn: -0.2, clarity: 2, culture: -3 }, log: "Ratings stayed high. Rania filed her audit in a folder and stopped mentioning it in meetings.",
           echo: { after: [10, 20], icon: "🔍", title: "The prescribing audit came back", text: "An insurer's audit put your antibiotic rate at twice the national clinic average. They paused new referrals until you send a stewardship plan.", fx: { mrrPct: -0.06, trust: -4 } } },
    },
    {
      id: "dl_health_03",
      cat: "Payers",
      icon: "🏦",
      title: "An insurer offers to put you in its network",
      desc: "Gulf Mutual will cover video consults for its 40,000 members at $28 instead of your $45 cash price. Claims settle in 90 days, and their last telehealth partner saw 1 in 5 claims rejected.",
      when: (s) => s.sector.id === "healthtech" && s.monthlyRevenue >= 2000 && s.week >= 8,
      A: { title: "Join the network", fx: { users: 600, arpu: -4, cash: -2500, pmf: 2 }, log: "You hired a claims coder and signed. Bookings from insured patients started the following Monday.",
           echo: { after: [8, 16], icon: "📭", title: "The claims queue", text: "Gulf Mutual paid 61% of the first quarter's claims. The rest came back for wrong diagnosis codes, plus one note: 'not medically necessary'.", fx: { cash: -4000, clarity: -5 } } },
      B: { title: "Stay cash-pay for now", fx: { arpu: 2, users: -100, pmf: -2 }, log: "You thanked them and declined. Two corporate prospects asked the same week whether you take insurance." },
    },
    {
      id: "dl_health_04",
      cat: "Devices",
      icon: "⚠",
      title: "The cheaper cuffs read high",
      desc: "Your new supplier's blood pressure cuffs cost $19 instead of $34 each. Nurse Huda checked 20 of them against a validated clinic device: most read 6 to 9 points high. 600 are already in patients' homes.",
      when: (s) => s.sector.id === "healthtech" && s.activeUsers >= 300 && s.week >= 8,
      A: { title: "Recall and replace all 600", fx: { cash: -7000, clarity: -4, churn: -0.3, trust: 2 }, log: "Couriers swapped the cuffs over two weeks. Huda wrote a calibration check into every new batch order." },
      B: { title: "Keep them, recheck at clinic visits", fx: { clarity: 3, techDebt: 5, pmf: -2 }, log: "Tariq added a note to the doctors' dashboard: 'cuff batch 7 may read high'. Not every doctor opens the notes.",
           echo: { after: [6, 14], icon: "🚨", title: "A GP raised a dose on your numbers", text: "A partner GP increased a patient's blood pressure medication after four weeks of high readings from batch 7 cuffs. The patient got dizzy at work. The GP rechecked by hand and called you.", fx: { churn: 0.6, trust: -4, users: -150 } } },
    },
    {
      id: "dl_health_05",
      cat: "Employers",
      icon: "🔒",
      title: "Northwind's HR wants names, not averages",
      desc: "Northwind Retail pays $49 per employee per month for 300 staff on the plan. Their HR head now wants a list of who has high blood sugar, 'so we can support them'. The renewal is in 6 weeks.",
      when: (s) => s.sector.id === "healthtech" && s.monthlyRevenue >= 3000,
      A: { title: "Send anonymous group data only", fx: { mrrPct: -0.05, pmf: 2, culture: 2 }, log: "You sent a dashboard: 14% of enrolled staff in the pre-diabetes range, no names, no group smaller than 10 people. HR said they'd discuss internally." },
      B: { title: "Build an opt-in sharing consent", fx: { mrrPct: 0.04, techDebt: 4, clarity: -2 }, log: "A new consent screen went live: 'Share my results with my employer'. 31 employees ticked it in the first week.",
           echo: { after: [6, 12], icon: "📉", title: "Northwind's staff stopped measuring", text: "A message went round Northwind's staff WhatsApp group: 'HR can see your sugar readings'. Weekly measurements halved, even among people who never opted in.", fx: { churn: 0.6, users: -200, pmf: -3 } } },
    },
    {
      id: "dl_health_06",
      cat: "Doctors",
      icon: "🚪",
      title: "Your medical director has a hospital offer",
      desc: "A private hospital offered Dr. Rania Haddad head of cardiology at twice what you pay her. She'll stay for 3% equity. Your licence names her as the responsible physician.",
      when: (s) => s.sector.id === "healthtech" && s.team.length >= 3 && s.week >= 10,
      A: { title: "Offer 2% with four-year vesting", fx: { equity: -2, morale: 4, cofounder: -3 }, log: "Rania took the 2% and asked for a seat in investor meetings. Tariq asked, quietly, how his own stake compares.",
           echo: { after: [10, 20], icon: "🤝", title: "Rania's old ward starts referring", text: "Rania's former department now sends its discharged heart-failure patients to you for home monitoring. 40 came in the first month.", fx: { users: 300, mrrPct: 0.06, pmf: 3 } } },
      B: { title: "Let her go, hire a part-time director", fx: { baseBurn: -400, morale: -6, pmf: -2 }, log: "Rania left with a warm farewell lunch. Dr. Adel covers medical governance on Tuesdays and Thursdays.",
           echo: { after: [6, 12], icon: "🏛", title: "The ministry asks who is responsible", text: "The licence renewal form asks for a full-time responsible physician. Dr. Adel also works at three clinics. The inspector gave you 30 days to fix it.", fx: { clarity: -6, cash: -2500 } } },
    },
    {
      id: "dl_health_07",
      cat: "Clinical AI",
      icon: "🤖",
      title: "Investors want 'AI diagnosis' on the deck",
      desc: "Tariq's model flags likely diabetes from 3 months of home glucose readings and agrees with your doctors 91% of the time. Layla says calling it 'AI diagnosis' would change your round.",
      when: (s) => s.sector.id === "healthtech" && (s.stage >= 2 || s.week >= 20),
      A: { title: "Launch it as AI diagnosis", fx: { trust: 8, users: 400, pmf: -2 }, log: "The launch post got 90,000 views. Your doctors found out about the feature from LinkedIn.",
           echo: { after: [8, 18], icon: "🏛", title: "A letter about medical software", text: "The ministry wrote: software that diagnoses is a medical device and must be registered before use. The feature came down that week. Two investors asked where it went.", fx: { trust: -10, users: -300, techDebt: 6 } } },
      B: { title: "Ship it as a flag for doctors to review", fx: { trust: -3, pmf: 3, techDebt: 3 }, log: "It shipped as 'Suggested for review'. Doctors confirm or dismiss each flag. Layla called it a missed headline." },
    },
    {
      id: "dl_health_08",
      cat: "Clinical",
      icon: "🚨",
      title: "A patient's 'heartburn' was a heart attack",
      desc: "Last Thursday a 52-year-old told one of your doctors about burning in his chest after dinner and was advised antacids. Two days later he was admitted with a heart attack. He survived. His son posted the call summary.",
      when: (s) => s.sector.id === "healthtech" && (s.stage >= 2 || s.week >= 22),
      A: { title: "Open a full review and call the family", fx: { cash: -3000, clarity: -6, users: -100, pmf: 2 }, log: "You called the son yourself and told him a review had started. Your malpractice insurer was not happy that you called first.",
           echo: { after: [10, 20], icon: "🛡", title: "The review became a protocol", text: "The chest-pain red-flag checklist your review produced was the reason a hospital group gave for choosing you to follow up their discharged cardiac patients.", fx: { mrrPct: 0.08, users: 250, trust: 4 } } },
      B: { title: "Let the malpractice insurer lead", fx: { cash: -500, clarity: 2, users: -200 }, log: "The insurer's lawyer sent the family a formal letter. The post had 4,000 shares by Sunday.",
           echo: { after: [6, 14], icon: "🏛", title: "The complaint reached the ministry", text: "The son filed a complaint with the health ministry. The inspector asked for your incident report and the doctor's chest-pain training record. Neither existed on paper.", fx: { trust: -6, clarity: -8, cash: -2500 } } },
    },
  ];
