  const DL_LIFE = [
    {
      id: "dl_life_01",
      cat: "Ethics",
      icon: "🔒",
      title: "A customer's data would make your pitch deck sing",
      desc: "Your best case study is Omar Sabry's company: real revenue, real growth, his team's names on the chart. He never agreed to be in a deck. The investor meeting is Thursday.",
      when: (s) => s.monthlyRevenue >= 2000,
      A: { title: "Use the real numbers without asking", fx: { trust: 5, clarity: -3 }, log: "The slide landed. A partner asked who the customer was, and you told them.",
           echo: { after: [8, 16], icon: "🕵", title: "Omar saw the deck", text: "A forwarded PDF reached Omar Sabry through a mutual friend. His figures were on slide 9. He is polite on the phone and has stopped answering WhatsApp messages.", fx: { mrrPct: -0.06, churn: 0.5 } } },
      B: { title: "Ask Omar first and wait", fx: { trust: -3, clarity: 3, xp: 15 }, log: "Omar agreed to anonymised figures only. The slide is vaguer, and one investor said so." },
    },
    {
      id: "dl_life_02",
      cat: "Ethics",
      icon: "🧾",
      title: "A client wants an invoice dated last quarter",
      desc: "A new enterprise client asks you to date their first invoice to March so it lands in last year's budget. It's $6,000 you would otherwise wait months for.",
      when: (s) => s.monthlyRevenue >= 1500,
      A: { title: "Backdate it and get paid", fx: { cash: 6000, clarity: -4 }, log: "The money arrived in four days. The invoice says March.",
           echo: { after: [14, 26], icon: "⚖", title: "The client's auditors have questions", text: "The client's year-end audit flagged an invoice dated before your contract was signed. Their finance team wants a call, and so does your accountant.", fx: { cash: -2500, clarity: -6, trust: -3 } } },
      B: { title: "Date it today and explain why", fx: { mrrPct: -0.03, culture: 3, xp: 20 }, log: "They grumbled and pushed the purchase to the next budget cycle. The contract still stands." },
    },
    {
      id: "dl_life_03",
      cat: "Ethics",
      icon: "📰",
      title: "A journalist asks how many users you have",
      desc: "The interview is going well. You have 4,100 active users. The reporter mentions the other startup in the piece claimed 20,000 and then leaves a pause for you to fill.",
      A: { title: "Round up generously", fx: { users: 400, trust: 3, clarity: -3 }, log: "The article said ten thousand. Sign-ups ticked up that week.",
           echo: { after: [10, 20], icon: "📉", title: "Someone did the maths", text: "An analyst compared your app-store rankings with the article's figure and posted the thread. Layla Fahmy sent it to you without comment.", fx: { trust: -8, users: -150 } } },
      B: { title: "Give the real number", fx: { morale: -3, trust: 3, xp: 20 }, log: "The piece described you as the smaller player. Two people on the team mentioned it at lunch." },
    },
    {
      id: "dl_life_04",
      cat: "Ethics",
      icon: "🧲",
      title: "Growth wants a harder cancellation flow",
      desc: "Your growth lead proposes four confirmation screens and a mandatory call before anyone can cancel. The model says churn drops by a third.",
      when: (s) => s.week >= 10,
      A: { title: "Ship the new flow", fx: { churn: -1, mrrPct: 0.04, culture: -4 }, log: "Cancellations fell in the first month. Support tickets containing the word trapped went up.",
           echo: { after: [8, 18], icon: "🐦", title: "Your cancellation flow goes viral", text: "A user's screen recording of your four-screen exit got more views than any launch you've ever done. The replies are not kind.", fx: { users: -300, churn: 0.8, pmf: -2 } } },
      B: { title: "Keep one-click cancel", fx: { churn: 0.3, culture: 3, pmf: 1 }, log: "The growth lead said fine, and quietly revised the forecast downward." },
    },
    {
      id: "dl_life_05",
      cat: "Ethics",
      icon: "💳",
      title: "A billing bug overcharged 140 customers",
      desc: "Tariq found it at midnight: for three months, annual plans were billed an extra month. Nobody has complained yet. A full refund comes to about $4,800.",
      A: { title: "Refund everyone and tell them", fx: { cash: -4800, churn: -0.3, cofounder: 3 }, log: "You sent the email at 9am. Seventeen customers replied to say thank you. One cancelled.",
           echo: { after: [10, 20], icon: "🫶", title: "A customer remembers the refund", text: "A finance director you refunded brings it up on a reference call with a prospect. The prospect signs the same week.", fx: { mrrPct: 0.05, xp: 15 } } },
      B: { title: "Fix it and refund only on request", fx: { cash: -400, cofounder: -5, clarity: -3, xp: 10 }, log: "The bug is fixed and three refunds went out. Tariq asked twice whether you had sent the email." },
    },
    {
      id: "dl_life_06",
      cat: "Ethics",
      icon: "🦈",
      title: "An investor wants your honest take on a competitor",
      desc: "Over coffee, a fund partner asks what you really think of Saqr Labs, who are raising at the same time. You know their CTO left in June and their churn is bad.",
      A: { title: "Tell them what you know", fx: { trust: 4, clarity: -2 }, log: "The partner took notes. Saqr Labs did not get a second meeting.",
           echo: { after: [8, 20], icon: "📨", title: "Your comments travelled", text: "Saqr Labs' founder messages you: an investor repeated your words to them, almost verbatim. Two engineers you hoped to hire are their close friends.", fx: { morale: -4, culture: -3, trust: -2 } } },
      B: { title: "Talk only about your own company", fx: { trust: -2, culture: 2, xp: 15 }, log: "The partner smiled and moved on. The meeting ended ten minutes early." },
    },
    {
      id: "dl_life_07",
      cat: "Personal",
      icon: "🎉",
      title: "A family wedding clashes with the fund's partner meeting",
      desc: "The only slot the partners have is Saturday at 11. Your cousin's wedding starts at 4 in Alexandria, a five-hour drive away. Your mother has already told everyone you're coming.",
      A: { title: "Take the meeting, miss the wedding", fx: { trust: 5, family: -10, clarity: -3 }, log: "The meeting went well. Your mother sent a photo of the empty chair with your name card on it.",
           echo: { after: [6, 14], icon: "🏠", title: "The wedding comes up again", text: "At a family lunch, an aunt asks why you missed your cousin's wedding. Your mother answers for you, a little too quickly.", fx: { family: -5, clarity: -3 } } },
      B: { title: "Ask Layla to move the meeting", fx: { trust: -4, family: 6, clarity: 4 }, log: "Layla moved it by a week. The partners noticed. You danced at the wedding and slept in the back seat all the way home." },
    },
    {
      id: "dl_life_08",
      cat: "Personal",
      icon: "❤",
      title: "Nour asks for one weekend with no laptop",
      desc: "Nour has booked two nights at a quiet place on the coast and asks, gently, that the laptop stays home. A customer launch is scheduled for Monday.",
      A: { title: "Go, and leave the laptop", fx: { partner: 10, clarity: 8, morale: -3 }, log: "Tariq handled two small fires alone. You came back Sunday night and slept nine hours.",
           echo: { after: [8, 16], icon: "🌅", title: "The weekend still shows", text: "Nour tells friends the coast trip was the best weekend of the year. You notice you've been sleeping better ever since.", fx: { partner: 4, clarity: 5 } } },
      B: { title: "Go, but bring the laptop", fx: { partner: -6, clarity: -2, churn: -0.2 }, log: "The launch went smoothly. Nour read a book on the balcony while you were on calls." },
    },
    {
      id: "dl_life_09",
      cat: "Personal",
      icon: "🧓",
      title: "Your father asks when you'll get a real job",
      desc: "At Friday dinner, your father mentions that a friend's son just joined a bank in Dubai on a very good salary. He doesn't ask a question. He just waits.",
      A: { title: "Show him the numbers", fx: { family: 4, clarity: -3 }, log: "You opened the dashboard on your phone. He studied it for a long time, then asked what MRR meant.",
           echo: { after: [10, 22], icon: "🤝", title: "Your father has been asking around", text: "An old colleague of your father's calls: he heard about your company and wants to introduce you to a client. Your father never mentioned it.", fx: { mrrPct: 0.04, family: 6 } } },
      B: { title: "Change the subject", fx: { clarity: 2, family: -4 }, log: "Your mother brought out dessert early. Nobody mentioned banks again that night." },
    },
    {
      id: "dl_life_10",
      cat: "Personal",
      icon: "🩺",
      title: "You've cancelled the doctor twice",
      desc: "The tightness in your chest comes back on Sunday nights. The clinic has a slot Tuesday at 10 sharp, exactly when Omar Sabry wants to walk through the renewal.",
      when: (s) => s.mentalClarity < 40 || s.week >= 30,
      A: { title: "Keep the appointment", fx: { clarity: 8, family: 2, mrrPct: -0.02 }, log: "The doctor says stress, and sleep, and asks what you do for a living. Omar rescheduled, a little stiffly." },
      B: { title: "Take Omar's call", fx: { mrrPct: 0.03, clarity: -6 }, log: "The renewal is signed. The clinic sent an automatic message offering a new slot.",
           echo: { after: [6, 14], icon: "🩺", title: "Sunday nights get worse", text: "The tightness now comes midweek too. Nour books the appointment without asking and drives you there.", fx: { clarity: -8, partner: -3, cash: -400 } } },
    },
    {
      id: "dl_life_11",
      cat: "Personal",
      icon: "💸",
      title: "Your savings ran out this month",
      desc: "You haven't paid yourself in five months and rent is due. Your uncle has offered $8,000 at no interest and with no deadline, which is its own kind of deadline.",
      when: (s) => s.week >= 16,
      A: { title: "Accept your uncle's loan", fx: { clarity: 6, family: -4 }, log: "The money arrived the next day with a voice note: pay it back whenever.",
           echo: { after: [12, 26], icon: "🏠", title: "Your uncle asks how things are going", text: "Your uncle hasn't mentioned the $8,000. But he asks about the company every time you visit, and now so does the rest of the family.", fx: { family: -4, clarity: -4 } } },
      B: { title: "Start paying yourself a small salary", fx: { cash: -3000, baseBurn: 600, clarity: 4, trust: -2 }, log: "It isn't much. Layla asked about the new line in the burn report." },
    },
    {
      id: "dl_life_12",
      cat: "Personal",
      icon: "🤝",
      title: "A friend's startup needs you for a month",
      desc: "Karim, a friend from university, is three weeks from running out of money and asks for help with his fundraising deck and a few investor introductions.",
      A: { title: "Give him your evenings", fx: { clarity: -5, partner: -3, xp: 30 }, log: "His deck got sharper. Your own to-do list got longer, and dinner got later.",
           echo: { after: [10, 24], icon: "🤝", title: "Karim closes his round", text: "Karim's round closed. He sends you two warm customer introductions and tells everyone who helped him get there.", fx: { mrrPct: 0.05, trust: 3 } } },
      B: { title: "Send him a list and say no", fx: { clarity: 4, family: -3 }, log: "Karim said he understood. His mother called your mother the following week." },
    },
    {
      id: "dl_life_13",
      cat: "Personal",
      icon: "😮‍💨",
      title: "You haven't slept past 5am in a month",
      desc: "You wake at 4:40 with your heart already running through the cash forecast. Nour has started sleeping in the other room so that at least one of you gets some rest.",
      when: (s) => s.mentalClarity < 40,
      A: { title: "Cut your week to fifty hours", fx: { clarity: 10, partner: 5, mrrPct: -0.03 }, log: "Some emails now wait until morning. Nobody seems to notice except you." },
      B: { title: "Push through until the round closes", fx: { clarity: -6, partner: -6, trust: 3 }, log: "You answer investor emails before dawn. Layla says your replies have never been faster.",
           echo: { after: [6, 14], icon: "🥴", title: "You make an expensive mistake", text: "Running on four hours of sleep, you approve a contract renewal at the old, lower price. Nobody catches it for a month.", fx: { cash: -3000, clarity: -4 } } },
    },
    {
      id: "dl_life_14",
      cat: "Personal",
      icon: "🧘",
      title: "A therapist has an opening on Wednesdays",
      desc: "A founder friend recommends a therapist who works with people like you: $90 a session, Wednesdays at 6. In your head you've been calling it burnout for a while.",
      when: (s) => s.mentalClarity < 40 || s.week >= 24,
      A: { title: "Book the first six sessions", fx: { cash: -540, clarity: 6, partner: 3 }, log: "The first session was mostly silence. The second one was not.",
           echo: { after: [8, 18], icon: "🧠", title: "Wednesdays are working", text: "You catch yourself pausing before replying to a hard email from Layla, and the reply is better for it. Nour says you laugh more.", fx: { clarity: 10, partner: 4, trust: 2 } } },
      B: { title: "Not now, maybe after the round", fx: { clarity: -5, pmf: 1, xp: 10 }, log: "You saved the therapist's number in your phone. Wednesday evenings went back to the roadmap." },
    },
    {
      id: "dl_life_15",
      cat: "Crisis",
      icon: "🚨",
      title: "The servers go down on launch day",
      desc: "Your launch post is live, 3,000 people are on the waitlist, and the app has been returning errors for 40 minutes. Tariq thinks it's the database.",
      A: { title: "Pause the launch and post an update", fx: { users: -200, clarity: 3, cofounder: 4 }, log: "You posted an honest update. The relaunch two days later got half the attention and none of the angry replies." },
      B: { title: "Throw money at bigger servers", fx: { cash: -4000, users: 600, techDebt: 8 }, log: "Bigger servers bought you the evening. The database problem is still there.",
           echo: { after: [6, 14], icon: "💥", title: "The database fails again", text: "Under ordinary Tuesday traffic, the same database error comes back. This time there's no launch to blame it on.", fx: { churn: 0.8, techDebt: 6, cofounder: -4 } } },
    },
    {
      id: "dl_life_16",
      cat: "Crisis",
      icon: "🐦",
      title: "Tariq's post is going viral for the wrong reasons",
      desc: "Tariq posted a late-night thread complaining about junior developers. It has 2 million views and your company's name in his bio. Two candidates have already withdrawn.",
      A: { title: "Ask Tariq to apologise publicly", fx: { cofounder: -8, culture: 4, morale: 2 }, log: "The apology was short and sincere enough. Tariq didn't speak to you until Thursday." },
      B: { title: "Stay quiet and let it pass", fx: { cofounder: 4, culture: -5 }, log: "The thread dropped off the feed within a week. The search results did not.",
           echo: { after: [8, 20], icon: "🔍", title: "The thread follows you into hiring", text: "Your best engineering candidate in months asks, in the final interview, whether your CTO still feels that way about juniors.", fx: { morale: -4, culture: -3, techDebt: 3 } } },
    },
    {
      id: "dl_life_17",
      cat: "Crisis",
      icon: "☣",
      title: "Customer emails turn up on a public forum",
      desc: "A security researcher sends you a link: 1,200 customer email addresses from an old export file, posted on a forum. Your lawyer says you may not be obliged to announce it.",
      when: (s) => s.activeUsers >= 300,
      A: { title: "Tell every customer today", fx: { churn: 0.6, users: -150, trust: 2, culture: 3 }, log: "The email went out at 6pm. Most replies asked one thing: is my password safe? It was." },
      B: { title: "Fix it and disclose only if asked", fx: { clarity: -4, cash: -800, users: 100 }, log: "The file is gone and the growth campaign kept running. The researcher asked twice whether you would disclose.",
           echo: { after: [10, 24], icon: "📰", title: "A newsletter found the forum post", text: "A tech newsletter writes up the leak and notes that you never told customers. Three of them forward it to you with one-line emails.", fx: { churn: 1, trust: -6, users: -250 } } },
    },
    {
      id: "dl_life_18",
      cat: "Crisis",
      icon: "🚪",
      title: "Your lead engineer resigns on demo day",
      desc: "Yasmin, who built half the product, hands in her notice at 8am. The investor demo is at 2pm, and she's the only one who knows the new feature's quirks.",
      A: { title: "Ask her to run the demo anyway", fx: { trust: 3, morale: -4, clarity: -3 }, log: "She did it, professionally, and left at 4. The investors never knew." },
      B: { title: "Demo the old version yourself", fx: { trust: -4, morale: 3, clarity: 2 }, log: "The demo was safe and slightly dull. Yasmin stayed late to write handover notes nobody had asked for.",
           echo: { after: [8, 18], icon: "📨", title: "Yasmin sends someone your way", text: "Yasmin recommends a former colleague who is looking for a new role. The interview takes twenty minutes to turn into an offer.", fx: { morale: 4, techDebt: -5 } } },
    },
    {
      id: "dl_life_19",
      cat: "Crisis",
      icon: "🏦",
      title: "Your payment provider froze your payouts",
      desc: "A spike in refunds triggered a review. $18,000 of customer payments is on hold for up to 90 days, and payroll is in 9 days.",
      when: (s) => s.monthlyRevenue >= 3000,
      A: { title: "Bridge payroll with a short-term loan", fx: { cash: 10000, baseBurn: 400, clarity: -3 }, log: "The bank approved it at 14% with a personal guarantee. Payroll went out on time.",
           echo: { after: [12, 24], icon: "💵", title: "The frozen payouts are released", text: "The provider releases the held funds with a one-line email. You pay the loan off early, minus the fees.", fx: { cash: 4000, clarity: 4 } } },
      B: { title: "Ask the team to defer a week's pay", fx: { cash: 3000, morale: -8, culture: -3 }, log: "Everyone agreed. Two people asked, privately, whether this would happen again." },
    },
    {
      id: "dl_life_20",
      cat: "Crisis",
      icon: "🏛",
      title: "A letter from the consumer protection authority",
      desc: "The authority wants to know, within 30 days, why your auto-renewal sends no reminder email. Your lawyer bills by the hour.",
      when: (s) => s.week >= 12,
      A: { title: "Hire a specialist firm", fx: { cash: -5000, clarity: 4, trust: 2 }, log: "The firm's reply ran to eleven pages and was very calm. The authority closed the file." },
      B: { title: "Write the reply yourselves", fx: { cash: -500, clarity: -6, xp: 25 }, log: "You and Tariq wrote it over two nights. You learned more about consumer law than you ever wanted to.",
           echo: { after: [8, 18], icon: "⚖", title: "The authority writes back", text: "The authority has follow-up questions on four points of your reply, and a fine for the missing reminders.", fx: { cash: -3000, clarity: -4 } } },
    },
    {
      id: "dl_life_21",
      cat: "Crisis",
      icon: "🌧",
      title: "The office flooded overnight",
      desc: "A pipe burst on the floor above. Four laptops, the whiteboard with next quarter's plan and most of the carpet are ruined. The landlord says the insurance will take weeks.",
      A: { title: "Go fully remote for a month", fx: { cash: 1500, culture: -4, morale: -2 }, log: "The rent you saved paid for new laptops. Video standups got shorter and quieter." },
      B: { title: "Rent a co-working space this week", fx: { cash: -3500, morale: 4, culture: 2 }, log: "The co-working space has good coffee and a loud team next door. Nobody missed a day.",
           echo: { after: [6, 14], icon: "🏢", title: "The insurance cheque arrives", text: "The insurer finally pays out for the laptops and the carpet. It's less than you hoped and more than you expected.", fx: { cash: 3000, clarity: 2 } } },
    },
    {
      id: "dl_life_22",
      cat: "Crisis",
      icon: "🌫",
      title: "A wave of fake one-star reviews",
      desc: "Overnight, 60 one-star reviews appeared on your app page, most from accounts created this week. Your rating fell from 4.6 to 3.1 in a day.",
      A: { title: "Report them and wait", fx: { users: -250, clarity: 2 }, log: "The platform removed most of them after eleven days. Downloads dipped in the meantime." },
      B: { title: "Ask happy customers to post reviews", fx: { users: 150, morale: 2, clarity: -3, cash: -500 }, log: "Forty customers posted reviews within a day. Two of them mentioned you had asked, which the platform does not love.",
           echo: { after: [6, 16], icon: "⚠", title: "The app store sends a warning", text: "The app store flags a pattern of solicited reviews and hides your page from search results for a fortnight.", fx: { users: -300, pmf: -1 } } },
    },
  ];
