  const DL_MKT = [
    {
      id: "dl_mkt_01",
      cat: "Sellers",
      icon: "📱",
      title: "Your best brand is slipping its WhatsApp into parcels",
      desc: "Buyers forward you a card found in Hana's parcels: her WhatsApp number and 10% off if you order direct next time. Her abaya label brings 14% of your orders and pays you 15% commission on each one.",
      when: (s) => s.sector.id === "ecommerce_marketplace" && s.week >= 4,
      A: { title: "Pull the cards and enforce the rules", fx: { mrrPct: -0.03, pmf: 2, clarity: -3 }, log: "Hana called it a misunderstanding and stopped the cards. Her new arrivals now reach your site a week after Instagram.",
           echo: { after: [8, 16], icon: "🛡", title: "Buyers stop vanishing after one order", text: "Two other brands quietly took their numbers out of their parcels. Buyers who used to disappear after a first order now reorder in the app, where returns are covered.", fx: { churn: -0.4, pmf: 2 } } },
      B: { title: "Cut her fee to 8% on repeat buyers", fx: { arpu: -2, churn: -0.3, morale: -2 }, log: "Hana agreed within the hour. Two other brands asked for the same deal by Thursday.",
           echo: { after: [10, 20], icon: "🧾", title: "Every brand wants the repeat-buyer rate", text: "Eleven sellers now pay 8% on repeat orders. Your take on returning buyers has almost halved, and they are the buyers you paid most to win.", fx: { arpu: -2, mrrPct: -0.03 } } },
    },
    {
      id: "dl_mkt_02",
      cat: "Curation",
      icon: "🔍",
      title: "Forty brands applied, and half sell the same phone cases",
      desc: "Tariq's self-serve signup brought 40 seller applications this week. Salma, your curator, would reject 22 of them: blurry photos, copied designs, the same phone cases from one factory. Meanwhile buyers search and find half-empty shelves.",
      when: (s) => s.sector.id === "ecommerce_marketplace" && s.week >= 3 && s.monthlyRevenue < 6000,
      A: { title: "Open the gates and fill the shelves", fx: { users: 400, mrrPct: 0.04, pmf: -3, churn: 0.3 }, log: "Listings tripled in a week. So did the number of phone cases on the home page.",
           echo: { after: [8, 18], icon: "🕳", title: "Your search page looks like every other souk", text: "Buyers now scroll past 60 identical phone cases to find the brands they came for. A review calls you a slower Souqly.", fx: { churn: 0.5, pmf: -3, arpu: -1 } } },
      B: { title: "Keep Salma's bar and onboard by hand", fx: { clarity: -4, morale: -3, pmf: 3 }, log: "Salma approved 18 brands and rewrote half their product pages herself. Growth stayed slow.",
           echo: { after: [10, 20], icon: "⭐", title: "Buyers start browsing for fun", text: "Time on site doubled and buyers started sharing your collections on WhatsApp. Two creators asked to feature your brands without being paid.", fx: { users: 300, churn: -0.4 } } },
    },
    {
      id: "dl_mkt_03",
      cat: "Unit economics",
      icon: "🧾",
      title: "Every order loses money after the courier",
      desc: "Youssef in finance breaks down the average $31 basket: $6.10 in commission and margin, then $3.20 courier, $0.90 packaging, $0.80 payment fees and $2.60 in returns. Each order loses $1.40 and free delivery from $20 is why buyers come.",
      when: (s) => s.sector.id === "ecommerce_marketplace" && s.monthlyRevenue >= 3000 && s.week >= 8,
      A: { title: "Raise free delivery to $45", fx: { arpu: 4, mrrPct: -0.05, users: -200, clarity: 3 }, log: "Orders dropped 18% in the first week. The average basket rose from $31 to $43 and stayed there." },
      B: { title: "Keep it and fix margin with volume", fx: { users: 250, mrrPct: 0.03, cash: -2500 }, log: "Orders kept climbing. So did the red line in Youssef's spreadsheet.",
           echo: { after: [6, 14], icon: "💸", title: "Volume made the hole deeper", text: "The courier added $0.40 per parcel on the new rate card. At your volume, free delivery now costs more each month than your two engineers.", fx: { cash: -2500, clarity: -5, trust: -3 } } },
    },
    {
      id: "dl_mkt_04",
      cat: "Take rate",
      icon: "🏷",
      title: "Layla wants the commission at 20%",
      desc: "At 15% your commission is the lowest in the market, and Layla's next-round model assumes 20%. Mazen, who manages sellers, says 9 of your top 30 brands told him a higher fee pushes them to their own online stores.",
      when: (s) => s.sector.id === "ecommerce_marketplace" && s.monthlyRevenue >= 5000,
      A: { title: "Raise it to 20% for everyone", fx: { mrrPct: 0.08, trust: 5, pmf: -2 }, log: "The email went out on a Sunday. Mazen spent the whole week on the phone.",
           echo: { after: [8, 16], icon: "🚪", title: "Three top brands open their own stores", text: "Three of the brands Mazen warned you about launched their own sites with free delivery. Their Instagram bios no longer link to you.", fx: { mrrPct: -0.06, users: -250, pmf: -2 } } },
      B: { title: "Keep 15% and sell paid placement", fx: { arpu: 2, techDebt: 4, pmf: -1, trust: -2 }, log: "Sellers can now pay for a home-page slot. The three biggest brands bought most of them." },
    },
    {
      id: "dl_mkt_05",
      cat: "Peak season",
      icon: "📅",
      title: "Eid orders tripled and the courier caps you at 400 a day",
      desc: "Ten days before Eid you're taking 1,100 orders a day. SwiftLine will only carry 400 a day under the 24-hour promise. A second courier wants $2,500 up front, and nobody has tested their drivers with your parcels.",
      when: (s) => s.sector.id === "ecommerce_marketplace" && s.monthlyRevenue >= 4000 && s.team.length >= 3,
      A: { title: "Pay the second courier, keep the promise", fx: { cash: -2500, users: 300, churn: -0.3, clarity: -4 }, log: "The new courier's vans arrived at the warehouse at midnight. Most Eid gifts landed on time.",
           echo: { after: [5, 10], icon: "📉", title: "The second courier's returns come back", text: "62 Eid parcels came back damaged or marked address not found. Buyers blamed you, not a courier they had never heard of.", fx: { churn: 0.5, cash: -1500, morale: -4 } } },
      B: { title: "Cap orders and promise after Eid", fx: { mrrPct: -0.06, churn: -0.2, morale: 4 }, log: "The banner said order by Tuesday for Eid. Hundreds of buyers went elsewhere, and the team slept on Eid eve." },
    },
    {
      id: "dl_mkt_06",
      cat: "Inventory",
      icon: "💰",
      title: "Buy 1,500 bottles of the oud oil everyone wants",
      desc: "A small perfumer's oud oil went viral and sold out on your site in 40 minutes. She offers you 1,500 bottles at $6 each, exclusive for 3 months, cash up front. Today you own no stock at all.",
      when: (s) => s.sector.id === "ecommerce_marketplace" && s.monthlyRevenue >= 3000 && s.week >= 10,
      A: { title: "Buy the whole batch", fx: { cash: -9000, mrrPct: 0.1, pmf: 2 }, log: "The pallet arrived on a Tuesday. You now own a warehouse shelf and a weekly stock count.",
           echo: { after: [8, 16], icon: "⏳", title: "The oud oil trend moves on", text: "The first weeks sold 400 bottles a week. Then 30. You cleared the last 600 at half price in a Ramadan bundle, and the shelf is finally empty.", fx: { cash: 1800, mrrPct: -0.03, clarity: -4 } } },
      B: { title: "Sell it on consignment at 15%", fx: { mrrPct: 0.03, trust: -2, arpu: -1 }, log: "She agreed, then sold her best batch to a rival who paid cash. You got the second batch." },
    },
    {
      id: "dl_mkt_07",
      cat: "Trust & safety",
      icon: "⚠",
      title: "Your bestselling sneaker seller is selling fakes",
      desc: "A buyer sent a side-by-side video: the $140 sneakers from your top seller, Fadi, have the wrong stitching. Fadi is 9% of your orders, 340 pairs shipped this year, and a brand's lawyer is copied on the email.",
      when: (s) => s.sector.id === "ecommerce_marketplace" && s.week >= 20,
      A: { title: "Delist Fadi and refund all 340 buyers", fx: { cash: -5000, mrrPct: -0.07, churn: -0.4, pmf: 2 }, log: "Refunds went out before most buyers knew there was a problem. Most of it came out of Fadi's held payouts. His lawyer called before lunch.",
           echo: { after: [6, 14], icon: "🛡", title: "Buyers trust the refund", text: "Buyers who got refunds without asking posted about it. Your authentic-or-your-money-back badge now converts better than any ad.", fx: { users: 400, churn: -0.4, trust: 3 } } },
      B: { title: "Refund one buyer and audit quietly", fx: { cash: -140, clarity: -6, trust: -2 }, log: "The buyer got her money back. Fadi swore the batch was original and sent a supplier invoice nobody could verify.",
           echo: { after: [8, 18], icon: "📰", title: "The video reaches 2 million views", text: "A sneaker account reposted the side-by-side video to 2 million views. The brand's lawyer sent a second letter, this one with a deadline.", fx: { churn: 0.8, users: -400, cash: -5000 } } },
    },
    {
      id: "dl_mkt_08",
      cat: "Competition",
      icon: "⚔",
      title: "Your top seller just launched a marketplace",
      desc: "Rami's homeware brand grew from 20 orders a month to 900 on your site. Now he's launched his own marketplace at 8% commission and is messaging your sellers one by one. He still lists with you.",
      when: (s) => s.sector.id === "ecommerce_marketplace" && (s.stage >= 2 || s.week >= 24),
      A: { title: "Lock top brands into 12-month exclusives", fx: { arpu: -3, churn: -0.5, cash: -3000, pmf: 2 }, log: "Twenty-two brands signed for a 10% fee and a home-page slot. Four said no.",
           echo: { after: [10, 20], icon: "🧊", title: "Rami's marketplace goes quiet", text: "Without the brands that mattered, Rami's site filled up with the phone cases you had rejected. He asked to talk about coming back.", fx: { mrrPct: 0.05, pmf: 2 } } },
      B: { title: "Delist Rami and spend on buyers", fx: { mrrPct: -0.05, users: 300, cash: -2500, morale: 3 }, log: "Rami's products vanished from your site on Sunday. By Monday his WhatsApp group had 31 of your sellers in it." },
    },
  ];
