  const DL_MENA = [
    {
      id: "dl_mena_01",
      cat: "Middle East",
      icon: "⚖",
      title: "An uncle offers wasta to unstick your licence",
      desc: "Your commercial registration and licence have said 'under review' for 9 weeks. No CR, no corporate bank account. Your uncle knows the deputy director: one call, no money. But favours here get collected.",
      A: { title: "Let your uncle make the call", fx: { clarity: 6, mrrPct: 0.05, family: 4, culture: -3 }, log: "The CR is approved 4 days later. Nobody asks how, and you notice you don't want anyone to.",
           echo: { after: [12, 24], icon: "🎲", title: "Your uncle collects the favour", text: "Your uncle's friend wants in on your first government tender, as the 'local partner' taking 30%. Saying no now costs more than it would have.", fx: { family: -6, clarity: -6, culture: -4 } } },
      B: { title: "Wait in the queue like everyone else", fx: { clarity: -6, mrrPct: -0.04, family: -3, culture: 4 }, log: "You resubmit the file with the missing stamp. Your uncle calls it pride. Tariq tells the story to the team at lunch, approvingly." },
    },
    {
      id: "dl_mena_02",
      cat: "Middle East",
      icon: "🏦",
      title: "The central bank's sandbox opens a new cohort",
      desc: "The central bank's regulatory sandbox takes 12 fintechs a year. The application runs 80 pages and wants a compliance officer on payroll. Inside, you can test with real money. Outside, you stay a vendor to a licensed bank.",
      when: (s) => s.sector.id === "fintech",
      A: { title: "Apply and hire a compliance officer", fx: { cash: -4000, baseBurn: 1200, trust: 6, clarity: -5 }, log: "Rania, 11 years in bank compliance, joins. The application goes in with a cover letter in Arabic and annexes in English.",
           echo: { after: [14, 26], icon: "✅", title: "You're in the sandbox", text: "The acceptance letter arrives on official letterhead. Two banks that ignored your emails now want a meeting, and Layla forwards the letter to everyone she knows.", fx: { trust: 10, mrrPct: 0.1, pmf: 4 } } },
      B: { title: "Stay a white-label vendor for the bank", fx: { mrrPct: 0.05, pmf: -3, morale: -3 }, log: "The partner bank keeps the licence, the customer and 40% of the margin. You keep shipping and invoicing." },
    },
    {
      id: "dl_mena_03",
      cat: "Middle East",
      icon: "☁",
      title: "A new rule says customer data must stay in the country",
      desc: "A data-residency regulation gives you 6 months to move personal data onto in-country servers. The local cloud costs 3x what you pay now and its managed database is a version behind. Tariq has already sighed twice.",
      A: { title: "Migrate to the local cloud now", fx: { baseBurn: 900, techDebt: 6, cofounder: -4, trust: 4 }, log: "Tariq spends 3 weeks rewriting the backup scripts. A 'Data hosted locally' badge goes on the pricing page.",
           echo: { after: [10, 20], icon: "🏢", title: "A government entity asks where its data lives", text: "A semi-government procurement team sends a 40-question security form. Question 1 is about data residency. You're one of only two bidders who can answer yes.", fx: { mrrPct: 0.12, trust: 4 } } },
      B: { title: "Request an extension and keep building", fx: { morale: 4, pmf: 2, clarity: -6 }, log: "Your lawyer files the extension request. The team keeps shipping features instead of moving databases.",
           echo: { after: [12, 22], icon: "⚠", title: "The extension was refused", text: "The regulator publishes its list of approved extensions. You're not on it. The migration now has to happen in 5 weeks, in your busiest month.", fx: { techDebt: 10, morale: -8 } } },
    },
    {
      id: "dl_mena_04",
      cat: "Middle East",
      icon: "🩺",
      title: "The health ministry says your app needs a licence",
      desc: "An inspector says your symptom checker counts as a medical device. The licence needs a clinical validation study with a hospital: 5 months and about $12,000. A competitor quietly renamed its app a 'wellness companion'.",
      when: (s) => s.sector.id === "healthtech",
      A: { title: "Fund the clinical study", fx: { cash: -8000, pmf: 4, trust: 6, clarity: -4 }, log: "Dr. Hala at a university hospital agrees to run the study. The first ethics committee meeting lasts 4 hours and ends with a request for more forms.",
           echo: { after: [16, 28], icon: "🏆", title: "The licence comes through", text: "You're the only licensed app in the category. Two insurers ask to list you on their member portals, and the 'wellness companion' just got a warning letter.", fx: { mrrPct: 0.15, trust: 8 } } },
      B: { title: "Rebrand it as a wellness app", fx: { pmf: -4, users: -150, clarity: 6, morale: 3 }, log: "The symptom checker becomes 'daily tips for your wellbeing'. Doctors stop recommending it. The inspector stops calling." },
    },
    {
      id: "dl_mena_05",
      cat: "Middle East",
      icon: "🧊",
      title: "Your gateway froze your money on a Thursday afternoon",
      desc: "The payment gateway froze $18,000 of settlements 'for review'. Your biggest client's bank transfer is now 3 months late. It's Thursday afternoon, the weekend starts tomorrow, and payroll is due Sunday.",
      when: (s) => s.monthlyRevenue >= 2000,
      A: { title: "Cover payroll from your own savings", fx: { family: -6, morale: 6, clarity: -6 }, log: "You make the transfer from your personal account at 11pm. Nobody on the team knows how close payroll came.",
           echo: { after: [6, 12], icon: "💵", title: "The money finally lands", text: "The gateway releases the $18,000 after 23 days and 4 emails to a risk team with no names. The client's transfer arrives the same week. You pay yourself back first.", fx: { clarity: 6, family: 4 } } },
      B: { title: "Delay payroll and tell the team why", fx: { morale: -10, culture: 4, clarity: 3 }, log: "You explain it in the team WhatsApp group. Four people reply with a heart. One doesn't reply at all." },
    },
    {
      id: "dl_mena_06",
      cat: "Middle East",
      icon: "💳",
      title: "Cash on delivery is 60% of your orders",
      desc: "60% of orders are cash on delivery and 1 in 4 gets refused at the door. The courier sits on your cash for two weeks. You want to push cards, but your processor just raised its fee from 2.2% to 2.9% overnight.",
      when: (s) => s.sector.id === "ecommerce_marketplace",
      A: { title: "Add a fee for cash on delivery", fx: { cash: 3000, users: -250, arpu: 2, churn: 0.4 }, log: "A small COD fee appears at checkout. Refused deliveries drop. So do orders from outside the capital.",
           echo: { after: [10, 18], icon: "📈", title: "Customers learn to pay by card", text: "Card payments are now 55% of orders. Refusals at the door are down by half, and the courier owes you a lot less money.", fx: { cash: 4000, arpu: 2 } } },
      B: { title: "Keep COD free and chase the courier", fx: { users: 300, cash: -3000, clarity: -4 }, log: "Order volume holds. You call the courier's finance manager every Tuesday. He now has you saved as 'the startup'." },
    },
    {
      id: "dl_mena_07",
      cat: "Middle East",
      icon: "🌅",
      title: "Ramadan: usage peaks at 2am and the team wants shorter days",
      desc: "Last Ramadan your usage tripled after Taraweeh and peaked at 2am. Marketing wants a $5,000 Ramadan campaign. The team wants office hours of 11am to 3pm. Someone has to watch the servers at suhoor.",
      A: { title: "Run the campaign and staff a night shift", fx: { cash: -5000, users: 900, morale: -6, techDebt: 4 }, log: "Tariq and two engineers work from iftar to suhoor. On the 12th of Ramadan the database falls over for 18 minutes, and they're awake to fix it.",
           echo: { after: [6, 12], icon: "📉", title: "The Ramadan users left after Eid", text: "Half the users who joined in Ramadan haven't opened the app since Eid. The other half are still here, and they still use it at midnight.", fx: { users: -300, pmf: 2 } } },
      B: { title: "Give short days and skip the campaign", fx: { morale: 8, culture: 4, users: -100, mrrPct: -0.03 }, log: "Standup moves to 11:15am. No campaign. A competitor's lantern ads are on every feed until Eid.",
           echo: { after: [8, 14], icon: "🫶", title: "The team remembers Ramadan", text: "In the anonymous team survey, 'how Ramadan was handled' is the most mentioned reason people like working here. Two candidates bring it up in interviews.", fx: { culture: 4, morale: 4 } } },
    },
    {
      id: "dl_mena_08",
      cat: "Middle East",
      icon: "🎉",
      title: "The team expects an Eid bonus",
      desc: "Nobody asked directly, but Ahmed in sales mentioned that his last employer paid half a month's salary before Eid. Doing the same would cost $7,000: about 3 weeks of runway.",
      when: (s) => s.team.length >= 3,
      A: { title: "Pay the Eid bonus", fx: { cash: -7000, morale: 10, culture: 3 }, log: "The bonus lands two days before Eid. Your phone fills with Eid stickers and one long voice note from Ahmed's mother." },
      B: { title: "Send gifts and a personal note instead", fx: { cash: -1200, morale: -5, clarity: 3 }, log: "Everyone gets a box of dates, a handwritten card and a voucher. Someone posts a photo of the box in the group with a polite thumbs-up.",
           echo: { after: [8, 16], icon: "🚪", title: "Ahmed takes another offer", text: "Ahmed resigns for a bank job 'with proper benefits'. In his exit chat he says the dates were very good.", fx: { morale: -6, mrrPct: -0.04 } } },
    },
    {
      id: "dl_mena_09",
      cat: "Middle East",
      icon: "📅",
      title: "August: the buyers are in London and the weddings are at home",
      desc: "Your 4 biggest deals wait on people who are in London or Salalah until September. Meanwhile your cousin and your best friend from university both get married in the same week. The burn doesn't take a holiday.",
      when: (s) => s.monthlyRevenue >= 2000,
      A: { title: "Fly to London and chase the deals", fx: { cash: -4500, family: -8, xp: 40 }, log: "You spend 9 days pitching people in polo shirts in Knightsbridge cafés. Your mother sends the wedding videos, one by one.",
           echo: { after: [8, 14], icon: "🤝", title: "The London coffee closes a deal", text: "The CFO you met in a London café signs in September, while 3 other deals are still 'waiting for the new budget'.", fx: { mrrPct: 0.12, trust: 3 } } },
      B: { title: "Stay home for the weddings and slow down", fx: { family: 8, clarity: 6, mrrPct: -0.04 }, log: "You dance at both weddings and sleep past 8am for the first time in a year. The pipeline doesn't move at all." },
    },
    {
      id: "dl_mena_10",
      cat: "Middle East",
      icon: "🏠",
      title: "Your parents found you a government job",
      desc: "Your father's friend can get you a ministry position: stable salary, housing allowance, out by 2:30pm. Your mother has already told your aunts. They want an answer before Friday lunch.",
      A: { title: "Decline it, in person, with respect", fx: { family: -10, clarity: 6, morale: 3 }, log: "You explain over lunch. Your father says nothing for a long time, then asks how many months of runway you have.",
           echo: { after: [14, 26], icon: "❤", title: "Your father brings up the startup", text: "At a family gathering, your father tells an uncle about your company and uses the word 'founder' in English. He has been reading about it.", fx: { family: 10, clarity: 4 } } },
      B: { title: "Ask for a year before deciding", fx: { family: 4, clarity: -6, xp: 20 }, log: "Your mother tells the aunts it is 'being arranged'. The offer, and the question, now have a deadline.",
           echo: { after: [20, 30], icon: "⏳", title: "The year is almost up", text: "Your father's friend calls about the ministry position again. The startup is still alive, and now you have to say no to a man who waited for you.", fx: { family: -8, clarity: -4 } } },
    },
    {
      id: "dl_mena_11",
      cat: "Middle East",
      icon: "👥",
      title: "Your aunt needs a job for her son",
      desc: "Your aunt calls: her son Karim graduated 8 months ago and is 'just sitting at home'. He's kind, unfocused and has never worked in a company. She has already told him you'll find something.",
      A: { title: "Hire Karim as an operations assistant", fx: { family: 8, baseBurn: 700, culture: -4, morale: -3 }, log: "Karim starts on Sunday. He is first in the office every morning and last to finish reading any document.",
           echo: { after: [10, 20], icon: "🌱", title: "Karim found his thing", text: "Karim turned out to be excellent with couriers and angry customers. Support complaints are down, and he now has opinions about the CRM.", fx: { churn: -0.5, morale: 4 } } },
      B: { title: "Help him find a job somewhere else", fx: { family: -8, culture: 3, clarity: -3 }, log: "You spend two evenings rewriting Karim's CV. Your aunt thanks you in a tone that means the opposite." },
    },
    {
      id: "dl_mena_12",
      cat: "Middle East",
      icon: "🏛",
      title: "A government fund will match your round, with conditions",
      desc: "A state-backed fund offers to match Layla's cheque if you move your HQ to its city, reach 60% local hires within 18 months, and give it a board observer seat.",
      when: (s) => s.stage <= 2,
      A: { title: "Take the match and the conditions", fx: { cash: 25000, trust: 6, baseBurn: 1200, equity: -3 }, log: "The term sheet comes in Arabic and English, with the Arabic version prevailing. Your lawyer reads it twice.",
           echo: { after: [14, 26], icon: "🔍", title: "The fund's quarterly compliance pack", text: "Every quarter the fund asks for payslips, residency data and a headcount by nationality. Your finance person now loses 3 days to it each time.", fx: { clarity: -5, baseBurn: 300 } } },
      B: { title: "Close the round with angels only", fx: { cash: 8000, equity: -2, trust: -3, clarity: 4 }, log: "Layla brings in 3 angels for a smaller round. You keep your HQ, your board and a nagging question about the money you didn't take." },
    },
    {
      id: "dl_mena_13",
      cat: "Middle East",
      icon: "🚀",
      title: "Demo day is in another city",
      desc: "The accelerator's demo day is in Riyadh; your team and customers are in Cairo. Going means two weeks away, $3,500 in flights and hotel, and 4 minutes on stage in front of 300 investors.",
      when: (s) => s.stage <= 2,
      A: { title: "Fly in and pitch on stage", fx: { cash: -3500, trust: 6, clarity: -4, morale: -3 }, log: "You rehearse the 4 minutes 31 times. On stage the clicker dies at slide 6 and you finish without it.",
           echo: { after: [6, 14], icon: "👼", title: "A demo-day investor follows up", text: "A family-office partner from the second row sends a WhatsApp: 'Still raising?' His first cheque would be bigger than your last round.", fx: { trust: 8, cash: 10000, equity: -2 } } },
      B: { title: "Send a recorded pitch and keep selling", fx: { mrrPct: 0.05, trust: -4, morale: 2 }, log: "Your video plays between two live pitches with the audio too low. Back in Cairo, you close two deals that week." },
    },
    {
      id: "dl_mena_14",
      cat: "Middle East",
      icon: "🐳",
      title: "A competitor backed by a sovereign fund enters your market",
      desc: "A new player launched with a $40M round led by a sovereign fund, a free year for every customer and billboards on every highway. Three of your customers forwarded you its launch email.",
      when: (s) => s.week >= 12,
      A: { title: "Hold your price and over-serve customers", fx: { churn: 1, pmf: 4, morale: -3, mrrPct: -0.05 }, log: "You call every top customer yourself. Omar Sabry says he'll stay, 'but give me a reason by next quarter'.",
           echo: { after: [16, 28], icon: "🔥", title: "The free year ends", text: "The competitor ends its free tier and triples its prices to show revenue to its fund. Four customers who left you come back, slightly embarrassed.", fx: { mrrPct: 0.1, churn: -1 } } },
      B: { title: "Move to the segment they ignore", fx: { pmf: -4, techDebt: 5, clarity: 5, churn: -0.5 }, log: "You stop fighting for their customers and go after the small businesses their sales team never calls." },
    },
    {
      id: "dl_mena_15",
      cat: "Middle East",
      icon: "🎯",
      title: "Saudi Arabia or Egypt as your second market?",
      desc: "Saudi means bigger contracts, 4x the price point, a local entity, work visas and a nationalisation quota for every hire. Egypt means 110 million people, cheap talent and a currency that lost half its value in two years.",
      when: (s) => s.stage >= 2 || s.monthlyRevenue >= 5000,
      A: { title: "Go to Saudi Arabia", fx: { cash: -10000, baseBurn: 1200, arpu: 6, clarity: -4 }, log: "You hire Faisal as country manager and learn that your next two hires must be Saudi before the visa for your engineer gets approved.",
           echo: { after: [14, 26], icon: "📈", title: "Your first Saudi enterprise contract", text: "A Riyadh logistics group signs a two-year contract. One customer now pays more each month than your first 50 did combined.", fx: { mrrPct: 0.15, trust: 5 } } },
      B: { title: "Go to Egypt", fx: { users: 1200, cash: -3000, arpu: -3, morale: 4 }, log: "You hire 6 people in Cairo for what one senior hire costs in Dubai. The pricing page now has a second currency.",
           echo: { after: [10, 20], icon: "📉", title: "The pound moves again", text: "The Egyptian pound drops another 20% overnight. Revenue from Egypt is flat in pounds and down in dollars, but the Cairo team is the strongest you've had.", fx: { mrrPct: -0.05, morale: 4 } } },
    },
    {
      id: "dl_mena_16",
      cat: "Middle East",
      icon: "💻",
      title: "Your product isn't really Arabic-first",
      desc: "Your app was built in English and translated. In user tests, Gulf users trip over Egyptian phrasing, dates break in right-to-left, and the charts read backwards. A proper Arabic-first interface is 10 weeks of work.",
      A: { title: "Rebuild the interface Arabic-first", fx: { cash: -5000, mrrPct: -0.03, techDebt: -6, pmf: 5 }, log: "Mariam, your new UX writer, drafts every screen in Arabic first. Tariq finds 214 hardcoded 'left' values in the CSS.",
           echo: { after: [10, 20], icon: "🤩", title: "Users say it speaks like them", text: "App store reviews start saying the app 'speaks like us'. Conversion from Arabic-language ads is up by a third.", fx: { users: 800, pmf: 3 } } },
      B: { title: "Fix the worst bugs and move on", fx: { cash: -800, techDebt: 4, pmf: -2, morale: 3 }, log: "The date bug is fixed. The charts still run left to right, and the Saudi onboarding still greets people with an Egyptian 'ezayak'." },
    },
    {
      id: "dl_mena_17",
      cat: "Exit",
      icon: "🦈",
      title: "A super-app offers to acqui-hire your team",
      desc: "A regional super-app wants your engineers, not your product. The offer is $1.2M, mostly as retention bonuses for the team. Your investors would get their money back and little else.",
      when: (s) => s.week >= 25 && s.monthlyRevenue >= 10000,
      A: { title: "Decline and tell the team about it", fx: { morale: 6, culture: 4, cofounder: -4, trust: 3 }, log: "You tell the team at Sunday standup. Someone asks how much. You tell them that too.",
           echo: { after: [8, 16], icon: "🕵", title: "The super-app recruits your engineers directly", text: "Two of your engineers get messages from the super-app's recruiter with salaries you can't match. One of them says yes.", fx: { morale: -8, techDebt: 6 } } },
      B: { title: "Negotiate a better price", fx: { clarity: -6, trust: 4, morale: -4, xp: 40 }, log: "Your lawyer asks for an NDA and a data room. The team notices you're taking a lot of calls in the stairwell." },
    },
    {
      id: "dl_mena_18",
      cat: "Exit",
      icon: "🤝",
      title: "Your main competitor proposes a merger",
      desc: "Yousef, who runs your fiercest competitor, invites you to dinner and proposes a 50/50 merger. Together you'd own the market. Apart, you're both burning money on the same discounts.",
      when: (s) => s.week >= 25 && s.monthlyRevenue >= 10000,
      A: { title: "Explore the merger", fx: { clarity: -6, trust: 6, mrrPct: 0.06, cofounder: -6 }, log: "Due diligence starts. You learn that Yousef's churn is worse than yours, and he learns that your margins are.",
           echo: { after: [10, 20], icon: "⚔", title: "Who will be CEO?", text: "The talks reach the last question: who runs the combined company. Yousef says his board insists on him. Tariq says if it's Yousef, he's out.", fx: { cofounder: -8, clarity: -6 } } },
      B: { title: "Decline and keep competing", fx: { cash: -3000, morale: 4, clarity: 4 }, log: "You pay for dinner. The next morning, his team launches a 40% discount." },
    },
    {
      id: "dl_mena_19",
      cat: "Exit",
      icon: "💰",
      title: "An investor offers to buy some of your shares",
      desc: "The growth fund leading your next round offers to buy 3% of the company from you directly, paid into your personal account. Layla thinks founders who take money off the table lose their hunger.",
      when: (s) => s.week >= 25 && s.monthlyRevenue >= 10000,
      A: { title: "Sell the shares", fx: { equity: -3, clarity: 10, family: 8, trust: -5 }, log: "You pay off the apartment and your parents' car loan. For the first time in two years, you sleep through the night.",
           echo: { after: [10, 20], icon: "📓", title: "Layla raises it at the board", text: "At the next board meeting Layla asks how 'personally committed' you still are. She says it with a smile. It goes in the minutes.", fx: { boardTrust: -6, trust: -4 } } },
      B: { title: "Keep every share", fx: { clarity: -4, trust: 4, partner: -5 }, log: "You decline politely. Nour asks, very calmly, how much longer the two of you will live like this." },
    },
    {
      id: "dl_mena_20",
      cat: "Exit",
      icon: "🔒",
      title: "A strategic buyer wants 60 days of exclusivity",
      desc: "A regional logistics group sends a letter of intent at a valuation you didn't dare say out loud. The catch: 60 days of exclusivity, with no talks with any other buyer or investor.",
      when: (s) => s.week >= 25 && s.monthlyRevenue >= 10000,
      A: { title: "Sign the exclusivity letter", fx: { clarity: -6, trust: 5, morale: -4, xp: 50 }, log: "The data room opens. Their 14 analysts ask for every contract since day one.",
           echo: { after: [8, 14], icon: "📉", title: "The buyer cuts the price at the last minute", text: "Two days before exclusivity ends, the buyer 'revisits the valuation' by 35%. Every other conversation went cold during those two months.", fx: { trust: -8, clarity: -8 } } },
      B: { title: "Refuse exclusivity and invite other offers", fx: { trust: -4, clarity: -3, xp: 30 }, log: "The buyer says they'll 'reflect' and goes quiet. Layla asks why you'd turn away the only offer on the table.",
           echo: { after: [8, 18], icon: "🐳", title: "Two buyers at the table", text: "A rival group asks for a meeting. The first buyer comes back with a better offer and no exclusivity. Layla calls it the best email of her year.", fx: { trust: 8, clarity: 4 } } },
    },
    {
      id: "dl_mena_21",
      cat: "Exit",
      icon: "🧩",
      title: "A telecom wants to license your tech, not buy you",
      desc: "A national telecom wants to white-label your platform for its 20 million subscribers: $15,000 a month, a 3-year contract, exclusive in the country. It doesn't want your company, just your best engineers' time.",
      when: (s) => s.week >= 25 && s.monthlyRevenue >= 10000,
      A: { title: "Sign the licensing deal", fx: { mrrPct: 0.18, cash: 15000, pmf: -4, techDebt: 8, morale: -4 }, log: "The contract is 64 pages. Clause 31 says you can't sell to any other telecom in the country.",
           echo: { after: [12, 24], icon: "🔄", title: "The telecom's roadmap becomes yours", text: "The telecom now sends a monthly 'priority list'. Three of your engineers work only on it, and your own product hasn't shipped a feature in two months.", fx: { pmf: -4, morale: -4 } } },
      B: { title: "Hold out for an acquisition", fx: { clarity: -4, trust: 4, pmf: 2 }, log: "You tell them you're open to a bigger conversation. They say they'll take it to the committee." },
    },
  ];
