  const DL_PEOPLE = [
    {
      id: "dl_ppl_01",
      cat: "People",
      icon: "👥",
      title: "Your first hire wants to lead engineering",
      desc: "Karim joined when there was no salary and no office. Now he wants the Head of Engineering title. He is loyal, fast and liked, and he has never managed anyone.",
      when: (s) => s.team.length >= 4,
      A: { title: "Promote Karim", fx: { morale: 6, culture: 3, techDebt: 5 }, log: "Karim announced it himself in the team channel. Three people replied with the same fire emoji.",
           echo: { after: [10, 20], icon: "🕳", title: "Karim's team is drowning", text: "Karim's sprint reviews now run two hours and ship very little. Two engineers have quietly asked to report to Tariq instead.", fx: { morale: -6, techDebt: 6, cofounder: -4 } } },
      B: { title: "Hire a senior lead above him", fx: { cash: -3000, baseBurn: 600, morale: -6, techDebt: -4, culture: -2 }, log: "You paid a recruiter and found a lead with ten years behind her. Karim took the news without a word and went back to his desk." },
    },
    {
      id: "dl_ppl_02",
      cat: "People",
      icon: "🏠",
      title: "Your best designer wants to go fully remote",
      desc: "Rana is moving to Amman with her husband. She wants to keep her job from there, full time, with no office days. Nobody on the team works remotely yet.",
      A: { title: "Approve it and make it work", fx: { morale: 4, culture: -3, clarity: -2 }, log: "Rana now joins standup from a kitchen in Amman. The rest of the team keeps forgetting to unmute.",
           echo: { after: [8, 16], icon: "📝", title: "Rana's written reviews caught on", text: "Rana's written design reviews became the template. The whole team now writes decisions down before the meeting, not after.", fx: { culture: 4, techDebt: -3 } } },
      B: { title: "Keep the office rule", fx: { morale: -5, culture: 2, cash: -2500 }, log: "Rana gave notice two weeks later. The recruiter's fee for her replacement came to $2,500." },
    },
    {
      id: "dl_ppl_03",
      cat: "People",
      icon: "⚔",
      title: "Two engineers are fighting in public",
      desc: "Youssef and Hana disagree about the API rewrite. It started in a pull request and ended in a 1am Slack thread the whole company read over breakfast.",
      when: (s) => s.team.length >= 4,
      A: { title: "Sit them down and make the call", fx: { morale: -4, techDebt: -3, clarity: -3, xp: 30 }, log: "You chose Hana's design. Youssef said \"fine\" in a voice that meant the opposite." },
      B: { title: "Split them into separate squads", fx: { morale: 3, techDebt: 4, culture: -3 }, log: "Each of them now owns half the codebase. The Slack channel went quiet overnight.",
           echo: { after: [6, 14], icon: "🧩", title: "Two squads, two login systems", text: "Youssef's squad and Hana's squad each built their own authentication flow. Merging them will take a full sprint.", fx: { techDebt: 7, morale: -4 } } },
    },
    {
      id: "dl_ppl_04",
      cat: "People",
      icon: "💸",
      title: "Your star engineer wants a 30% raise",
      desc: "Salma has an offer from a bank in Dubai. She'd rather stay, she says, but she sent you the offer letter as a PDF at 11pm. You can't afford it without cutting somewhere else.",
      when: (s) => s.team.length >= 3,
      A: { title: "Match the offer", fx: { baseBurn: 900, morale: 3, clarity: -2 }, log: "Salma signed the new contract the same morning. Your spreadsheet now shows one month less runway.",
           echo: { after: [10, 20], icon: "😬", title: "Everyone knows what Salma earns", text: "The number came out over lunch. Three people have asked for a \"market adjustment\" conversation this month.", fx: { morale: -6, baseBurn: 400, culture: -3 } } },
      B: { title: "Offer equity instead of cash", fx: { equity: -1, baseBurn: 200, morale: -3, culture: 2 }, log: "Salma took a small raise and a block of options. She said she'd think about whether options pay rent." },
    },
    {
      id: "dl_ppl_05",
      cat: "People",
      icon: "🤝",
      title: "The candidate is Nour's friend",
      desc: "Hadi went to university with Nour and needs a job. He interviewed well enough. The other finalist, a stranger from a job board, was clearly sharper.",
      A: { title: "Hire Hadi", fx: { partner: 6, culture: -4, techDebt: 3 }, log: "Hadi started on Sunday. Nour cooked dinner for both of you that night." },
      B: { title: "Hire the stronger stranger", fx: { partner: -6, techDebt: -3, culture: 3 }, log: "The new hire shipped her first fix in three days. Dinner at home was quiet that week." },
    },
    {
      id: "dl_ppl_06",
      cat: "People",
      icon: "🕵",
      title: "An engineer is moonlighting for a competitor",
      desc: "Mazen's name shows up in the commit history of a rival's public repository, every night between 10pm and 2am. He also owns your billing service, alone.",
      when: (s) => s.team.length >= 3,
      A: { title: "Let him go today", fx: { morale: -5, culture: 4, techDebt: 4, cash: -2000 }, log: "Mazen left with one month's severance and his laptop wiped. Nobody else knows how billing works.",
           echo: { after: [8, 16], icon: "🛠", title: "The billing service finally got rewritten", text: "The engineer who inherited billing rewrote the parts only Mazen understood. Deploys stopped breaking on Thursdays.", fx: { techDebt: -6, morale: 3 } } },
      B: { title: "Warn him and keep him", fx: { culture: -6, morale: 2, clarity: -3 }, log: "Mazen apologised and promised it was over. Two engineers saw him leave your office smiling." },
    },
    {
      id: "dl_ppl_07",
      cat: "People",
      icon: "📉",
      title: "Layoffs or pay cuts",
      desc: "Runway is down to five months. You can cut 3 roles, or cut everyone's salary by 20%, yours included. Tariq says either way, decide by Thursday.",
      when: (s) => s.team.length >= 5,
      A: { title: "Cut 3 roles", fx: { baseBurn: -800, morale: -12, culture: -4, trust: 4 }, log: "Three people packed their desks on a Tuesday. The ones who stayed went to lunch together and didn't invite you." },
      B: { title: "Cut everyone's pay by 20%", fx: { baseBurn: -600, morale: -7, culture: 4, clarity: -3 }, log: "Nobody left. The all-hands ended with one question: when does it come back?",
           echo: { after: [10, 22], icon: "📭", title: "The pay cut is still in place", text: "Months later, nobody's salary has been restored. Your two best engineers took recruiter calls this week.", fx: { morale: -8, culture: -3 } } },
    },
    {
      id: "dl_ppl_08",
      cat: "People",
      icon: "🧩",
      title: "Tariq doesn't want this hire",
      desc: "Ziad would be your first head of sales. He closed big deals at his last company. Tariq met him for an hour and called him \"a very good LinkedIn post\".",
      when: (s) => s.monthlyRevenue >= 2000,
      A: { title: "Hire Ziad anyway", fx: { cofounder: -10, mrrPct: 0.06, baseBurn: 1000 }, log: "Ziad booked six meetings in his first week. Tariq didn't come to his welcome lunch.",
           echo: { after: [8, 18], icon: "📊", title: "Ziad's pipeline is mostly air", text: "Ziad's pipeline looks huge on the dashboard, but half the deals have been \"closing next week\" for a month. Tariq has stopped commenting.", fx: { mrrPct: -0.04, cofounder: -6 } } },
      B: { title: "Pass and keep looking", fx: { cofounder: 6, clarity: -3, mrrPct: -0.02 }, log: "You told Ziad no. You're still the one doing every sales call, now with Tariq's quiet gratitude." },
    },
    {
      id: "dl_ppl_09",
      cat: "People",
      icon: "⚖",
      title: "Your first HR complaint",
      desc: "Dina, a junior developer, emails you about comments a senior engineer keeps making in code reviews. She asks you not to make it \"a big thing\". There is no HR person.",
      when: (s) => s.team.length >= 5,
      A: { title: "Bring in an outside investigator", fx: { cash: -4000, culture: 6, morale: -2, clarity: -2 }, log: "An external consultant interviewed six people over two weeks. The engineer received a written warning.",
           echo: { after: [8, 16], icon: "🫶", title: "A candidate heard how you handled it", text: "A senior candidate said a friend on your team told her how the complaint was handled. She signed the next day.", fx: { culture: 3, morale: 4 } } },
      B: { title: "Handle it yourself, quietly", fx: { clarity: -5, culture: -3, morale: 2, xp: 30 }, log: "You had a long coffee with the engineer. He said he'd been joking. Dina said thank you and nothing else.",
           echo: { after: [10, 24], icon: "🚨", title: "The complaint came back louder", text: "A second complaint about the same engineer arrived, this time copied to Layla Fahmy.", fx: { trust: -6, culture: -5, morale: -4 } } },
    },
    {
      id: "dl_ppl_10",
      cat: "People",
      icon: "🌱",
      title: "The early team's options are almost vested",
      desc: "Your first five employees are close to fully vested. The next round could be a year away. A refresh grant would come out of your own stake.",
      when: (s) => s.stage >= 2,
      A: { title: "Grant a refresh from your stake", fx: { equity: -2, morale: 8, culture: 4 }, log: "You handed out new option letters one by one. Karim read his twice and hugged you.",
           echo: { after: [12, 26], icon: "🌅", title: "The early team stayed", text: "Four of the first five are still here a year on. Recruiters stopped messaging them because nobody answers.", fx: { morale: 4, techDebt: -4 } } },
      B: { title: "Wait for the next round", fx: { morale: -5, trust: 3, clarity: 2 }, log: "Layla liked the clean cap table. The early team noticed nobody brought it up." },
    },
    {
      id: "dl_ppl_11",
      cat: "Money",
      icon: "💵",
      title: "Pay yourself, or buy more runway",
      desc: "You haven't taken a salary in over a year. Nour has been paying the rent. A $1,200 monthly salary would cost you about a month of runway by year end.",
      when: (s) => s.week >= 12,
      A: { title: "Pay yourself $1,200 a month", fx: { baseBurn: 1200, partner: 8, clarity: 6, trust: -2 }, log: "The first payslip was small and felt enormous. Nour framed it as a joke and put it on the fridge." },
      B: { title: "Stay at zero", fx: { partner: -8, family: -4, clarity: -4, trust: 3 }, log: "Layla called it disciplined. Your father asked, again, when the company would pay you.",
           echo: { after: [10, 20], icon: "🌧", title: "Nour's spreadsheet", text: "Nour put the household budget on the kitchen table and asked, quietly, how many more months.", fx: { partner: -8, clarity: -6 } } },
    },
    {
      id: "dl_ppl_12",
      cat: "Money",
      icon: "🦈",
      title: "A competitor wants to invest",
      desc: "Sanad Systems, a bigger rival, offers $25,000 for 4% with no board seat. Their head of strategy says it's \"just a friendly partnership\".",
      when: (s) => s.stage >= 2,
      A: { title: "Take Sanad's money", fx: { cash: 25000, equity: -4, trust: -6 }, log: "The money landed in four days. Layla read the press note and didn't reply for a week.",
           echo: { after: [10, 22], icon: "🔍", title: "Sanad wants a quarterly sync", text: "Sanad's team now asks for a quarterly call about your product plans. Two prospects asked if you're being acquired.", fx: { mrrPct: -0.05, trust: -4 } } },
      B: { title: "Decline politely", fx: { trust: 4, clarity: -4, morale: -2 }, log: "You said no. Sanad's head of strategy said the door stays open, in a tone that suggested otherwise." },
    },
    {
      id: "dl_ppl_13",
      cat: "Money",
      icon: "🏦",
      title: "The bank wants your apartment as collateral",
      desc: "A local bank will lend the company $30,000 at a fair rate. The catch is a personal guarantee, secured on the apartment you share with Nour.",
      when: (s) => s.monthlyRevenue >= 3000,
      A: { title: "Sign the personal guarantee", fx: { cash: 30000, baseBurn: 700, family: -6, partner: -6, clarity: -5 }, log: "You signed eleven pages in a branch office that smelled of carpet. Nour read every one of them first.",
           echo: { after: [16, 28], icon: "🧾", title: "The bank's quarterly review", text: "The bank now wants management accounts every quarter. Your Sunday nights belong to a spreadsheet.", fx: { clarity: -5, xp: 20 } } },
      B: { title: "Walk away from the loan", fx: { clarity: 3, partner: 3, morale: -3, mrrPct: -0.03 }, log: "You froze the two hires the loan would have paid for. Nour slept better than you did." },
    },
    {
      id: "dl_ppl_14",
      cat: "Money",
      icon: "🏷",
      title: "Raise prices on existing customers",
      desc: "Your earliest customers pay half of what new ones do. A 25% increase for everyone would fix the margins. Omar Sabry has already heard a rumour.",
      when: (s) => s.monthlyRevenue >= 2000,
      A: { title: "Raise prices 25% for everyone", fx: { mrrPct: 0.15, churn: 1.2, trust: 3 }, log: "The email went out on a Monday. By Wednesday you had forty replies, most of them polite.",
           echo: { after: [6, 14], icon: "📈", title: "The price rise settled", text: "Most customers grumbled and stayed. The ones who left were the ones filing half the support tickets.", fx: { churn: -0.8, morale: 3 } } },
      B: { title: "Grandfather existing customers", fx: { mrrPct: 0.03, churn: -0.3, trust: -3 }, log: "Only new customers pay the new price. Omar sent a thank-you voice note." },
    },
    {
      id: "dl_ppl_15",
      cat: "Money",
      icon: "🧾",
      title: "Northwind wants 120-day payment terms",
      desc: "Northwind Retail will triple its contract, but its procurement team insists on paying 120 days after each invoice. You'd be funding their purchase for four months.",
      when: (s) => s.monthlyRevenue >= 4000,
      A: { title: "Accept 120-day terms", fx: { mrrPct: 0.12, cash: -6000, clarity: -4 }, log: "The contract is signed. Revenue is up on paper, and your bank balance is down in reality.",
           echo: { after: [12, 22], icon: "⏳", title: "Northwind's invoice is late", text: "Day 120 came and went. Northwind's accounts payable says the invoice \"is in the system\".", fx: { cash: -5000, clarity: -5 } } },
      B: { title: "Push back to 45 days", fx: { mrrPct: 0.04, clarity: -2, xp: 30 }, log: "Northwind signed a smaller pilot on 45-day terms. Their buyer called you \"a tough negotiator\", not warmly." },
    },
    {
      id: "dl_ppl_16",
      cat: "Money",
      icon: "🏢",
      title: "An office to win the hiring war",
      desc: "Two senior candidates turned you down after visiting the co-working space. A real office with your name on the door would add about $1,400 a month.",
      when: (s) => s.team.length >= 4,
      A: { title: "Lease the office", fx: { baseBurn: 1400, morale: 8, culture: 5 }, log: "Tariq assembled the desks himself. The team stayed late the first week just because they could.",
           echo: { after: [8, 18], icon: "🤩", title: "Candidates came to the office", text: "Two senior engineers accepted offers after an afternoon in the new space. One said the coffee machine closed it.", fx: { morale: 4, techDebt: -4 } } },
      B: { title: "Stay in the co-working space", fx: { morale: -4, culture: -2, clarity: 2, trust: 2 }, log: "You booked the meeting room for interviews again. Someone else's birthday cake was on the table." },
    },
    {
      id: "dl_ppl_17",
      cat: "Money",
      icon: "👼",
      title: "Layla offers a bridge, with teeth",
      desc: "Layla Fahmy offers a $30,000 bridge note to get you to the next round. The terms: a 35% discount and a valuation cap well below what you pitched.",
      when: (s) => !!s.org.board,
      A: { title: "Take the bridge", fx: { cash: 30000, equity: -4, boardTrust: -3 }, log: "The note was signed over WhatsApp and a PDF. Your next round just got more expensive." },
      B: { title: "Decline and cut the burn", fx: { baseBurn: -700, morale: -6, boardTrust: 4, trust: 2 }, log: "You cancelled two tools and a contractor. Layla said she respected it, and meant it.",
           echo: { after: [8, 18], icon: "🏛", title: "The board noticed the discipline", text: "At the board meeting, Layla pointed to your burn chart and moved on. The next agenda item took four minutes.", fx: { boardTrust: 5, trust: 4 } } },
    },
    {
      id: "dl_ppl_18",
      cat: "Money",
      icon: "💳",
      title: "A cheaper payment provider",
      desc: "A new payment provider offers fees 1.1% lower than your current one. Their compliance team is three people, and their reviews mention frozen payouts.",
      when: (s) => s.monthlyRevenue >= 2000,
      A: { title: "Switch providers", fx: { baseBurn: -500, techDebt: 5 }, log: "Tariq migrated the integration over a weekend. The first monthly statement was noticeably smaller.",
           echo: { after: [6, 16], icon: "🧊", title: "Your payouts are frozen", text: "The new provider held 9 days of payouts for a \"routine compliance review\". Payroll went out late.", fx: { cash: -6000, morale: -6, trust: -3 } } },
      B: { title: "Keep the current provider", fx: { arpu: -1, clarity: 2, trust: 2 }, log: "You stayed. The fees are higher, and the money arrives every Tuesday without fail." },
    },
  ];
