  const DL_PRODUCT = [
    {
      id: "dl_prod_01",
      cat: "Product",
      icon: "🤝",
      title: "Omar Sabry wants his ERP connected first",
      desc: "Omar's company pays you $2,400 a month and will double it if you integrate with their old ERP. Tariq estimates 5 weeks of work. Nobody else uses that ERP.",
      when: (s) => s.monthlyRevenue >= 3000,
      A: { title: "Build the integration", fx: { mrrPct: 0.1, techDebt: 6, pmf: -3, cofounder: -4 }, log: "Omar sent a thumbs-up voice note. Tariq cleared the next 5 weeks of the roadmap.",
           echo: { after: [10, 20], icon: "🕳", title: "The ERP connector breaks again", text: "Omar's IT team upgraded their ERP over the weekend. The connector only you maintain stopped syncing, and Tariq spent Sunday rebuilding it.", fx: { techDebt: 6, morale: -5, cofounder: -4 } } },
      B: { title: "Say no and keep the roadmap", fx: { mrrPct: -0.02, pmf: 3, trust: -2 }, log: "Omar said he understood. His next email was two lines shorter than usual." },
    },
    {
      id: "dl_prod_02",
      cat: "Product",
      icon: "📊",
      title: "The free dashboard everyone loves",
      desc: "The public dashboard drives 31% of weekly sessions and earns nothing. It costs $900 a month in servers, and every paid feature waits behind its bug list.",
      when: (s) => s.activeUsers >= 500,
      A: { title: "Shut the dashboard down", fx: { baseBurn: -600, users: -250, pmf: -2, clarity: 4 }, log: "The shutdown banner went up on Monday. By Wednesday there were 40 angry replies on the forum." },
      B: { title: "Keep it and pay the bill", fx: { cash: -1500, techDebt: 4, users: 100, clarity: -2 },
           log: "The dashboard stays. So does the server invoice.",
           echo: { after: [12, 24], icon: "📈", title: "The dashboard starts selling for you", text: "A procurement manager found you through the free dashboard and asked for a quote. Then two more did. Sales now calls it the front door.", fx: { users: 300, mrrPct: 0.05, pmf: 2 } } },
    },
    {
      id: "dl_prod_03",
      cat: "Product",
      icon: "🔄",
      title: "Tariq wants to rewrite the core",
      desc: "Tariq has a 14-page document explaining why the codebase can't take another year. He wants 10 weeks with no new features. Sales wants the export tool by the end of the month.",
      when: (s) => s.techDebt >= 40,
      A: { title: "Approve the rewrite", fx: { techDebt: -12, mrrPct: -0.04, pmf: -3, cofounder: 8 }, log: "Tariq printed the plan and taped it to the wall. The export tool moved to next quarter.",
           echo: { after: [10, 18], icon: "✅", title: "The new core is live", text: "The rewrite shipped three weeks late, but pages load twice as fast and the Monday bug triage now takes 20 minutes instead of a morning.", fx: { techDebt: -8, morale: 6, churn: -0.4 } } },
      B: { title: "Patch it and keep shipping", fx: { pmf: 2, techDebt: 5, cofounder: -10 }, log: "The export tool shipped on time. Tariq closed his document without a word.",
           echo: { after: [8, 16], icon: "🚨", title: "The 2am page", text: "The database locked up at 2am during a bulk import. Tariq fixed it by 5am and posted one line in Slack: same root cause as the rewrite document.", fx: { techDebt: 6, morale: -6, churn: 0.5 } } },
    },
    {
      id: "dl_prod_04",
      cat: "Product",
      icon: "🤖",
      title: "Everyone is shipping an AI assistant",
      desc: "Layla forwards a list of 6 competitors who added an AI assistant this quarter. Hers is a short note: investors will ask. Tariq says a decent one takes 4 weeks and a serious API bill.",
      when: (s) => s.week >= 10,
      A: { title: "Build the AI assistant", fx: { cash: -4000, baseBurn: 600, trust: 6, users: 300, techDebt: 4 }, log: "The assistant launched with a waitlist and a purple gradient. Signups spiked for a week.",
           echo: { after: [8, 14], icon: "🧾", title: "The model bill arrives", text: "The AI assistant's API invoice came in at three times the estimate. Most of the usage is people asking it to say hello.", fx: { cash: -3000, clarity: -4 } } },
      B: { title: "Fix what customers asked for", fx: { trust: -5, pmf: 3, clarity: 3 }, log: "You told Layla the assistant can wait. Her reply was a single 'noted'." },
    },
    {
      id: "dl_prod_05",
      cat: "Product",
      icon: "📱",
      title: "Native app or a better mobile site",
      desc: "68% of new signups come from phones, and the mobile site feels like a desktop page squeezed into a pocket. An agency quotes $6,000 for native apps. Your own team could fix the web in 3 weeks.",
      when: (s) => s.activeUsers >= 800,
      A: { title: "Hire the agency for native apps", fx: { cash: -6000, baseBurn: 400, users: 500, techDebt: 4 }, log: "The agency sent a 40-slide kickoff deck. Now you maintain three codebases.",
           echo: { after: [12, 22], icon: "⭐", title: "The app store reviews come in", text: "The app sits at 4.6 stars, and push reminders bring people back on Thursdays. Retention on mobile is now better than on desktop.", fx: { users: 600, churn: -0.5 } } },
      B: { title: "Rebuild the mobile web in-house", fx: { cash: -1200, users: 150, pmf: 2, morale: -4 }, log: "The team spent 3 weeks testing on borrowed phones. Mobile signups ticked up." },
    },
    {
      id: "dl_prod_06",
      cat: "Product",
      icon: "🧩",
      title: "Someone is scraping you to build on top",
      desc: "A developer called Karim Haddad has been scraping your app to power his own tool, with 300 users. He emails asking for an official API instead of a lawsuit.",
      when: (s) => s.stage >= 2,
      A: { title: "Open a public API", fx: { techDebt: 6, pmf: 3, users: 300, clarity: -4 }, log: "Docs went live on a Thursday. Karim's tool switched over within a day.",
           echo: { after: [14, 26], icon: "🤝", title: "A small ecosystem appears", text: "Four tools now plug into your API, and two of their customers upgraded to your top plan to get higher limits. Karim calls it a partnership.", fx: { mrrPct: 0.06, trust: 3 } } },
      B: { title: "Block the scraper and stay closed", fx: { clarity: 3, techDebt: -2, users: -100, pmf: -2 }, log: "The scraper was blocked by Friday. Karim posted a thread about it that got 2,000 likes." },
    },
    {
      id: "dl_prod_07",
      cat: "Product",
      icon: "🏷",
      title: "Launch a free tier",
      desc: "A competitor just launched free forever, and your trial signups dropped 22% in a month. Layla thinks a free tier would fill the funnel. Your support person already works until 9pm.",
      when: (s) => s.mkt.pmf >= 30 && (s.sector.id === "saas_ai" || s.sector.id === "edtech"),
      A: { title: "Launch the free tier", fx: { users: 1200, baseBurn: 500, arpu: -2, trust: 4 }, log: "Free signups went past 1,000 in the first week. The paid plan page got fewer clicks.",
           echo: { after: [8, 16], icon: "📨", title: "Free users fill the inbox", text: "Free accounts now send 70% of support tickets and pay 0% of the bills. Your support person asked whether free means free help too.", fx: { morale: -6, cash: -2000, churn: 0.3 } } },
      B: { title: "Stay paid-only and sharpen the trial", fx: { users: -100, arpu: 2, trust: -3, pmf: 1 }, log: "You extended the trial to 21 days and rewrote the onboarding emails. Layla was unconvinced." },
    },
    {
      id: "dl_prod_08",
      cat: "Product",
      icon: "⚠",
      title: "Your payment processor keeps going down",
      desc: "The processor failed 3 times this month, once for 4 hours on salary day. Switching means a 6-week migration and re-certifying with two banks. They're offering service credits to stay.",
      when: (s) => s.sector.id === "fintech",
      A: { title: "Migrate to a new processor", fx: { cash: -5000, morale: -6, churn: -0.5, techDebt: -4 }, log: "The team spent 3 weekends on bank certification calls. Nobody has mentioned the old processor since." },
      B: { title: "Take the credits and stay", fx: { cash: 1500, churn: 0.5, trust: -3 }, log: "The processor sent a credit note and a promise about new infrastructure.",
           echo: { after: [6, 14], icon: "💥", title: "Another outage, on payday", text: "The processor went down again on the 25th, right when salaries landed. Your support line had 200 calls before noon.", fx: { churn: 1, mrrPct: -0.06, clarity: -5 } } },
    },
    {
      id: "dl_prod_09",
      cat: "Product",
      icon: "🛠",
      title: "Fourteen kinds of button",
      desc: "Your designer Hana counted 14 different button styles in the app. She wants 6 weeks to build a proper design system. The roadmap has 3 features promised to customers in that window.",
      when: (s) => s.team.length >= 4,
      A: { title: "Give Hana the 6 weeks", fx: { cash: -2500, pmf: -2, morale: 5, techDebt: -5 }, log: "Hana's design system file has 212 components. Two promised features slipped.",
           echo: { after: [10, 20], icon: "🚀", title: "Features ship in days now", text: "New screens are built from Hana's components in an afternoon. The last 3 features shipped in the time one used to take.", fx: { techDebt: -6, pmf: 3, morale: 4 } } },
      B: { title: "Ship the promised features", fx: { pmf: 3, techDebt: 5, morale: -4, culture: -3 }, log: "All 3 features shipped. Hana's message to you was polite and very short." },
    },
    {
      id: "dl_prod_10",
      cat: "Product",
      icon: "🩺",
      title: "Moving patient records to a new database",
      desc: "The old database can't meet the new data residency rules. Tariq can migrate 80,000 patient records in one weekend, or run both systems in parallel for 3 months.",
      when: (s) => s.sector.id === "healthtech" && s.week >= 15,
      A: { title: "Do it in one weekend", fx: { cash: -2000, techDebt: -10, clarity: -8, churn: 0.5 }, log: "Tariq and two engineers worked from Friday night to Sunday at 6pm. 31 records needed manual fixes." },
      B: { title: "Run both systems for 3 months", fx: { baseBurn: 700, techDebt: -4, morale: -3, clarity: 2 }, log: "Every record is now written twice. The cloud bill noticed before anyone else did.",
           echo: { after: [12, 20], icon: "🛡", title: "The auditor finds nothing", text: "The regulator's auditor spent two days in your systems and left with no findings. The parallel run left a clean trail for every record.", fx: { trust: 6, baseBurn: -700, xp: 40 } } },
    },
    {
      id: "dl_prod_11",
      cat: "Growth",
      icon: "📰",
      title: "Trusted by 500+ companies",
      desc: "Your new marketing lead Salma wants the homepage to say 'Trusted by 500+ companies'. You have 140 paying teams. Counting every trial ever started, it's technically true.",
      A: { title: "Publish the 500+ claim", fx: { users: 400, mrrPct: 0.04, culture: -4 }, log: "The new homepage went live. Demo requests went up the same week.",
           echo: { after: [10, 22], icon: "🕵", title: "A journalist counts your customers", text: "A tech newsletter compared your 500+ claim with your own case studies page. Two prospects forwarded the article to you with a question mark.", fx: { trust: -6, users: -200, clarity: -6 } } },
      B: { title: "Say 140 teams and mean it", fx: { users: 100, culture: 4, morale: -2, clarity: 2 }, log: "The homepage now says 140 teams. Salma rewrote the campaign over the weekend and didn't hide her mood." },
    },
    {
      id: "dl_prod_12",
      cat: "Growth",
      icon: "💸",
      title: "60% off before the fundraise",
      desc: "Your seed meeting is in 8 weeks. A 60% discount for 3 months would roughly double new signups before then. Layla says nobody reads cohort tables at the first meeting.",
      when: (s) => s.stage <= 2 && s.week >= 12,
      A: { title: "Run the discount", fx: { users: 900, arpu: -4, trust: 6, cash: -2500 }, log: "The growth chart in the deck now bends upwards. The revenue line underneath it doesn't.",
           echo: { after: [12, 20], icon: "📉", title: "The discount cliff", text: "The 3 months of 60% off ended. Half the discount cohort cancelled on the renewal page, and the investors who funded you watched it happen in the monthly update.", fx: { churn: 1.5, mrrPct: -0.08, trust: -5 } } },
      B: { title: "Pitch with the real numbers", fx: { trust: -3, clarity: 5, arpu: 1 }, log: "The deck shows slower growth and clean retention. One partner asked why you weren't growing faster." },
    },
    {
      id: "dl_prod_13",
      cat: "Growth",
      icon: "🤩",
      title: "An influencer with 1.2M followers",
      desc: "A lifestyle influencer in Dubai offers 3 posts and a story series for $12,000. Her agency sends a media kit with 1.2M followers and 6% engagement. Half your marketing budget for the quarter.",
      when: (s) => s.cash >= 30000 && (s.sector.id === "ecommerce_marketplace" || s.sector.id === "edtech"),
      A: { title: "Sign the influencer", fx: { cash: -12000, users: 1500, churn: 0.6 }, log: "The first post went up on Thursday evening. Your servers noticed by 9pm.",
           echo: { after: [6, 12], icon: "📉", title: "The influencer crowd moves on", text: "Most of the people who signed up from the influencer's posts never came back after the first week. The cohort chart looks like a ski slope.", fx: { users: -400, churn: 0.4 } } },
      B: { title: "Split it across 15 micro-creators", fx: { cash: -4000, users: 400, clarity: -4, pmf: 1 }, log: "You now manage 15 WhatsApp threads with creators. The signups are smaller and stickier." },
    },
    {
      id: "dl_prod_14",
      cat: "Growth",
      icon: "💵",
      title: "Pay $20 for every referral",
      desc: "Your growth hire Youssef wants to pay $20 cash for every referred user who signs up. Credits worked poorly last time. Cash moves people, he says.",
      A: { title: "Pay cash for referrals", fx: { cash: -4000, users: 1000, churn: 0.4 }, log: "The referral link spread through university group chats within a week.",
           echo: { after: [5, 10], icon: "🕵", title: "The referral ring", text: "Youssef found 300 accounts created from the same few phones, all referred by one user who has collected the referral cash for each of them.", fx: { cash: -2500, users: -300, clarity: -4 } } },
      B: { title: "Offer account credits instead", fx: { users: 300, arpu: -1, clarity: -2, cash: -800 }, log: "Credits went out. Referrals came in slowly, mostly from people who already loved you." },
    },
    {
      id: "dl_prod_15",
      cat: "Growth",
      icon: "🧲",
      title: "Invite all your contacts",
      desc: "Youssef's test of a pre-ticked 'invite all your contacts' box tripled invites. It also brought 40 complaints in two days, one from someone's former manager.",
      when: (s) => s.activeUsers >= 300,
      A: { title: "Keep the box pre-ticked", fx: { users: 1200, churn: 0.8, pmf: -3, culture: -4 }, log: "Invites keep flowing. So do screenshots of your invite email on social media." },
      B: { title: "Untick it and ask nicely", fx: { users: 150, culture: 4, trust: -3, morale: 2 }, log: "Invites fell back to normal. Youssef quietly removed the test from his growth report.",
           echo: { after: [10, 20], icon: "🫶", title: "People trust your emails", text: "Your invite and notification emails now get opened at twice the industry rate. Users say they don't mute you, which is rare.", fx: { churn: -0.6, pmf: 2 } } },
    },
    {
      id: "dl_prod_16",
      cat: "Growth",
      icon: "🏢",
      title: "A telecom wants to bundle you",
      desc: "Sahel Telecom wants to bundle your product into its business plans across 4 countries. They want a 30% revenue share and 2 years of exclusivity in the region.",
      when: (s) => s.stage >= 2 && s.monthlyRevenue >= 5000,
      A: { title: "Sign the bundle deal", fx: { mrrPct: 0.15, arpu: -3, clarity: -5, trust: 4 }, log: "The contract was 47 pages. Sahel's logo went on your homepage by Monday.",
           echo: { after: [12, 24], icon: "⚔", title: "Sahel wants a say in the roadmap", text: "Sahel's account team now sends a weekly feature list, marked as priority. Their customers are a third of your revenue, and they know it.", fx: { pmf: -4, cofounder: -6, morale: -5 } } },
      B: { title: "Decline and sell direct", fx: { trust: -4, clarity: 3, culture: 2, mrrPct: 0.02 }, log: "Sahel's partnerships manager said the door stays open. He didn't sound like he meant it." },
    },
    {
      id: "dl_prod_17",
      cat: "Growth",
      icon: "🎪",
      title: "Main stage in Riyadh, three weeks out",
      desc: "A speaker dropped out and the organisers of a big tech conference in Riyadh offer you the main stage. The new version you'd want to demo is half-built.",
      when: (s) => s.week >= 8,
      A: { title: "Take the stage and demo it", fx: { users: 800, trust: 5, techDebt: 8, morale: -8 }, log: "The demo worked on the second try. The video of your talk has 40,000 views.",
           echo: { after: [4, 10], icon: "😬", title: "The conference signups hit the bugs", text: "People who signed up after the Riyadh talk found the half-built features you demoed. Your support inbox has a new tag: 'saw it on stage'.", fx: { churn: 0.8, clarity: -4 } } },
      B: { title: "Decline and ship it properly", fx: { clarity: 4, morale: 4, trust: -4 }, log: "The organisers gave the slot to a competitor. You watched the livestream from the office." },
    },
    {
      id: "dl_prod_18",
      cat: "Growth",
      icon: "📡",
      title: "Run ads in a new country",
      desc: "Organic signups from Cairo doubled last quarter without any marketing. Youssef wants $6,000 for a paid campaign there and an Arabic-speaking support hire.",
      when: (s) => s.monthlyRevenue >= 6000 || s.stage >= 2,
      A: { title: "Launch the Cairo campaign", fx: { cash: -6000, users: 900, arpu: -2, baseBurn: 300 }, log: "The campaign went live with Egyptian Arabic copy. The cost per signup was half the home market's.",
           echo: { after: [14, 26], icon: "🌱", title: "Cairo starts paying", text: "The Cairo users who joined from the campaign are converting to paid plans. Three of them are companies with more than 200 staff.", fx: { mrrPct: 0.08, pmf: 2 } } },
      B: { title: "Double down at home", fx: { mrrPct: 0.03, users: 100, trust: -2, clarity: 2 }, log: "The budget went to the home market. Cairo keeps signing up on its own, slowly." },
    },
  ];
