  const DL_SAAS = [
    {
      id: "dl_saas_01",
      cat: "Enterprise sales",
      icon: "🧪",
      title: "Northwind wants a free 90-day pilot",
      desc: "Northwind Retail's head of digital wants your agent on 3 call-centre queues for 90 days, free. No success criteria, no price agreed, and their IT team needs 4 weeks before you even get API access.",
      when: (s) => s.sector.id === "saas_ai" && s.week >= 3 && s.week <= 12,
      A: { title: "Start the free pilot now", fx: { users: 150, pmf: 2, clarity: -4, cash: -1200 }, log: "Tariq set up the sandbox on a Sunday. The kickoff call had 14 people on it and nobody from finance.",
           echo: { after: [10, 16], icon: "⏳", title: "The pilot ended in next year's budget", text: "Northwind's team loved the dashboards. Their CFO had never heard of the pilot. The deal is now pencilled in for the next fiscal year.", fx: { clarity: -6, morale: -5, trust: -3 } } },
      B: { title: "Ask for $6,000 and written success criteria", fx: { cash: 6000, pmf: -2, trust: -2, morale: -2 }, log: "Procurement took 5 weeks to raise a $6,000 purchase order. Meanwhile Flowly started a free pilot in the queue next door.",
           echo: { after: [10, 18], icon: "✅", title: "The pilot converted on day 61", text: "The criteria said 30% of tickets resolved without a human. You hit 34%. The contract discussion took one meeting.", fx: { mrrPct: 0.05, trust: 3 } } },
    },
    {
      id: "dl_saas_02",
      cat: "Data & trust",
      icon: "🔒",
      title: "Their lawyer asks if their data trains your model",
      desc: "A Gulf bank's legal team sent a clause: zero retention, no training, data stays in-country. Your model provider keeps prompts for 30 days by default. The zero-retention tier costs $1,100 a month more.",
      when: (s) => s.sector.id === "saas_ai" && s.week >= 4 && s.week <= 14,
      A: { title: "Pay for zero retention and sign", fx: { baseBurn: 1100, trust: 3, mrrPct: 0.06 }, log: "You signed the clause on a Thursday night. The provider's enterprise contract arrived the next morning, with a 12-month minimum.",
           echo: { after: [8, 16], icon: "🛡", title: "Your data clause becomes a sales asset", text: "Two other banks asked for your data processing agreement before the first call. Their legal teams approved it in a week instead of a quarter.", fx: { mrrPct: 0.06, clarity: 3 } } },
      B: { title: "Keep the default and strip personal data", fx: { cash: -800, pmf: 2, mrrPct: -0.02, clarity: -3 }, log: "Tariq built a filter that removes names and IBANs before any prompt leaves your servers. The bank's lawyers will review it next quarter." },
    },
    {
      id: "dl_saas_03",
      cat: "AI quality",
      icon: "💥",
      title: "The agent invented a refund policy in the demo",
      desc: "In front of Northwind's COO, your agent told a test customer that orders can be refunded within 60 days. Their policy says 14. The room went quiet. Go-live is scheduled for Sunday.",
      when: (s) => s.sector.id === "saas_ai" && s.week >= 8 && s.monthlyRevenue >= 2500,
      A: { title: "Delay go-live and build an evaluation suite", fx: { mrrPct: -0.05, techDebt: -6, pmf: 3, clarity: -4 }, log: "You told the COO it needs 3 more weeks. Tariq's team wrote 400 test questions from Northwind's real policy documents.",
           echo: { after: [8, 14], icon: "✅", title: "The agent learned to say it doesn't know", text: "Every answer now cites the policy page it came from. Northwind's quality team approved the third queue without a meeting.", fx: { churn: -0.4, trust: 2, mrrPct: 0.04 } } },
      B: { title: "Go live Sunday with human approval on refunds", fx: { mrrPct: 0.03, techDebt: 5, cofounder: -3, morale: -2 }, log: "Go-live happened on schedule. Every refund answer now waits for one of Northwind's agents to click approve.",
           echo: { after: [6, 12], icon: "🚨", title: "A refund nobody approved", text: "The approval queue hit 900 items on a busy Friday, so someone switched it off. The agent promised a full refund on a 4-month-old order. It was on social media by Saturday.", fx: { churn: 0.8, trust: -4, morale: -5 } } },
    },
    {
      id: "dl_saas_04",
      cat: "Unit economics",
      icon: "💸",
      title: "The model bill ate a third of your margin",
      desc: "Northwind's agent now handles 38,000 tickets a month on a flat per-seat plan. Your inference bill went from $900 to $4,600 a month. Gross margin fell from 85% to 61%, and Layla noticed first.",
      when: (s) => s.sector.id === "saas_ai" && s.monthlyRevenue >= 4000 && s.week >= 10,
      A: { title: "Route simple tickets to a smaller model", fx: { baseBurn: -700, techDebt: 4, pmf: -2, churn: 0.3 }, log: "70% of tickets now go to the small model and the bill halved. The first complaint about a mangled Arabic reply came on day 3.",
           echo: { after: [8, 14], icon: "📉", title: "The small model doesn't speak Khaleeji", text: "Northwind's Riyadh queue now escalates 3 times more tickets than the Cairo one. Their ops manager sent you a spreadsheet of 60 bad replies.", fx: { churn: 0.6, pmf: -2 } } },
      B: { title: "Add usage pricing at renewal", fx: { arpu: 4, mrrPct: 0.05, churn: 0.4, clarity: -5 }, log: "Northwind's procurement took 6 weeks to model the new price. They signed seats plus usage, with a cap you'll reach by spring." },
    },
    {
      id: "dl_saas_05",
      cat: "Model risk",
      icon: "⚠",
      title: "Your model provider is retiring your model",
      desc: "An email at 1am: the model version your agents run on retires in 60 days. The new version formats answers differently and 23% of your test cases fail. A local cloud offers to host an open-weight model in-region.",
      when: (s) => s.sector.id === "saas_ai" && s.week >= 12,
      A: { title: "Migrate to the new version and move on", fx: { cash: -1000, techDebt: 3, pmf: 2, morale: -2 }, log: "Three weeks of rewriting prompts. The new model is better in English and slightly worse with Arabic numbers.",
           echo: { after: [10, 20], icon: "🌫", title: "The provider was down for 7 hours", text: "A regional outage on a Monday morning. Every one of your clients' agents went silent at once, and you had nowhere to switch them.", fx: { churn: 0.7, trust: -4, clarity: -6 } } },
      B: { title: "Build a switch layer and add an in-region model", fx: { cash: -4000, techDebt: 6, cofounder: 4, pmf: 1 }, log: "Tariq's team spent 6 weeks on the abstraction layer. Two clients asked why nothing new shipped this month.",
           echo: { after: [10, 20], icon: "🛡", title: "The day the big provider went down", text: "A 7-hour outage hit every company on the main provider. Your agents switched to the in-region model in 4 minutes. Two banks asked for a meeting.", fx: { mrrPct: 0.04, trust: 4, churn: -0.3 } } },
    },
    {
      id: "dl_saas_06",
      cat: "Accounts",
      icon: "🚪",
      title: "Your champion at Northwind just resigned",
      desc: "Hana Al-Qahtani, who brought you into Northwind and defended your budget twice, is joining a bank. Her replacement starts in 3 weeks with a vendor consolidation plan. Your renewal is in 10 weeks.",
      when: (s) => s.sector.id === "saas_ai" && s.monthlyRevenue >= 5000,
      A: { title: "Spend two weeks multi-threading Northwind", fx: { cash: -2500, clarity: -6, churn: -0.3, mrrPct: 0.02 }, log: "You met their IT lead, the call-centre director and finance. Finance had never seen your ROI numbers. Now they have them on one page." },
      B: { title: "Follow Hana to the bank", fx: { mrrPct: 0.06, trust: 2, clarity: -3 }, log: "Hana introduced you to the bank's CIO on her second day. The pilot paperwork started that week.",
           echo: { after: [8, 14], icon: "📉", title: "Northwind's renewal went to tender", text: "The new head of digital put your contract into an RFP with Flowly and Nimbus AI. You kept the account, at 40% less.", fx: { mrrPct: -0.1, morale: -4 } } },
    },
    {
      id: "dl_saas_07",
      cat: "Deployment",
      icon: "🏛",
      title: "A ministry wants it on their own servers",
      desc: "A government entity will sign $180,000 a year if the agent runs fully on-prem: their data centre, no internet, an open-weight model on GPUs they'll buy next year. Your product has only ever run in the cloud.",
      when: (s) => s.sector.id === "saas_ai" && (s.stage >= 2 || s.week >= 20),
      A: { title: "Sign and build the on-prem edition", fx: { cash: 12000, baseBurn: 400, techDebt: 10, pmf: -3, morale: -4 }, log: "The signing had a photographer. Tariq spent the evening drawing two architectures on the whiteboard instead of one.",
           echo: { after: [12, 24], icon: "🕳", title: "Two products, one team", text: "Every cloud release now needs a separate on-prem build, a USB drive and a security escort. Three engineers do nothing else, and the cloud roadmap slowed to a crawl.", fx: { techDebt: 8, morale: -6, pmf: -2 } } },
      B: { title: "Offer a private tenant in a local cloud region", fx: { pmf: 2, trust: -3, cash: -1500 }, log: "Their IT director took your architecture diagram to the committee. The committee meets once a quarter." },
    },
    {
      id: "dl_saas_08",
      cat: "Business model",
      icon: "🧾",
      title: "Services are now 45% of your revenue",
      desc: "Your implementation team builds custom connectors for every new client at $150 an hour, and it pays salaries. A Series A analyst read your numbers: blended gross margin 54%. Her note says consultancy.",
      when: (s) => s.sector.id === "saas_ai" && (s.stage >= 2 || s.week >= 22) && s.monthlyRevenue >= 6000,
      A: { title: "Hand implementations to a partner firm", fx: { mrrPct: -0.08, trust: 5, pmf: 3, morale: -3 }, log: "A Cairo integrator took over implementations for a 15% referral fee. Two of your engineers moved with the work.",
           echo: { after: [10, 20], icon: "📈", title: "Margin is back above 75%", text: "With the top connectors packaged as product, new clients go live in 3 weeks instead of 11. The fund's analyst asked for an updated deck.", fx: { trust: 4, mrrPct: 0.05 } } },
      B: { title: "Keep services and the cash they bring", fx: { cash: 4000, trust: -4, techDebt: 4, pmf: -2 }, log: "The services team billed 600 hours this month. The product team shipped one feature." },
    },
  ];
