  const MAIL_FIN = [
    {
      kind: "mail",
      id: "mx_fin_01",
      when: (s) => s.sector.id === "fintech" && s.week >= 5,
      from: "🤖 Kareem · FraudShield AI",
      title: "Regulators will require AI fraud screening by Q3",
      body: "Our model blocks 99.7% of fraud with zero false positives. Central banks are moving fast. The pilot is $2,000 a month and we can start Monday.",
      left: { label: "Start the $2,000 pilot", fx: { cash: -2000, clarity: -3 }, log: "The model flagged your own test payments as fraud. The 'requirement' turned out to be a conference panel." },
      right: { label: "Archive", log: "Archived. No regulator has sent you that rule, and they would have." },
    },
    {
      kind: "mail",
      id: "mx_fin_02",
      when: (s) => s.sector.id === "fintech" && !s.mkt.licensed && s.week >= 6,
      from: "🏛 Central bank · Licensing department",
      title: "Proof of minimum capital required",
      body: "Your file is complete except proof of paid-up minimum capital held in a blocked account. Please submit the bank certificate within 10 working days.",
      left: { label: "Lock the capital from runway", fx: { cash: -12000, trust: 4, clarity: -3 }, log: "$12,000 now sits in an account you can't touch. The certificate went in on day 4 of the deadline." },
      right: { label: "Ask Layla to fund it", fx: { equity: -2, trust: -2, clarity: 2 }, log: "Layla wired the capital for 2 points of equity. Her email said this should have been in the plan." },
      ignore: { fx: { trust: -4, clarity: -5 }, log: "The deadline passed without a certificate. Your file went back to the bottom of the queue." },
    },
    {
      kind: "mail",
      id: "mx_fin_03",
      when: (s) => s.sector.id === "fintech" && s.mkt.licensed === true && s.week >= 12,
      from: "🏦 Dalia · Sponsor bank, risk team",
      title: "3 AML alerts closed with no notes",
      body: "Our sample found 3 alerts closed without notes, and 1 that may need a suspicious transaction report. We need the case files by Thursday.",
      left: { label: "Rebuild the files properly", fx: { clarity: -5, morale: -3, trust: 2 }, log: "Two late nights reopening alerts. You filed one report with the financial intelligence unit and sent Dalia every note." },
      right: { label: "Send what we have", fx: { clarity: 2, trust: -3 }, log: "Dalia replied within the hour: this is not a case file. She copied her manager." },
      ignore: { fx: { mrrPct: -0.05, trust: -5 }, log: "Nothing reached the bank by Thursday. It capped your new merchant approvals at 5 a week until further notice." },
    },
    {
      kind: "mail",
      id: "mx_fin_04",
      when: (s) => s.sector.id === "fintech" && s.mkt.licensed === true && s.monthlyRevenue >= 2500,
      from: "🛍 Mona · Founder, abaya label",
      title: "I lost a chargeback I can prove",
      body: "A customer disputed a $640 order she signed for. Your dashboard says I lost and owe the $15 fee. Nobody ever asked me for the delivery proof.",
      left: { label: "Re-file it with her proof", fx: { clarity: -3, churn: -0.2, techDebt: 2 }, log: "You re-filed with the signed delivery note. Tariq added an evidence upload to the dispute screen the same week." },
      right: { label: "Refund her fees and apologise", fx: { cash: -300, churn: -0.1, pmf: -1 }, log: "You refunded the fee and a month of charges. Mona was polite. The dispute screen still has no upload button." },
    },
  ];
