  const MAIL_HEALTH = [
    {
      kind: "mail",
      id: "mx_health_01",
      when: (s) => s.sector.id === "healthtech" && s.week >= 4,
      from: "📧 Kevin · ComplyMed Certification",
      title: "URGENT: your app is not HIPAA certified",
      body: "Clinics will reject any telehealth app without our HIPAA Certified badge. Fast-track certification in 10 days for $1,800. Only 3 slots left this month.",
      left: { label: "Buy the certificate", fx: { cash: -1800, clarity: -2 }, log: "A PDF badge arrived. HIPAA is a US law with no official certificate, and the clinic in Riyadh asked about local data rules instead." },
      right: { label: "Archive", log: "Archived. Your buyers ask where patient data is stored, not for a badge." },
    },
    {
      kind: "mail",
      id: "mx_health_02",
      when: (s) => s.sector.id === "healthtech" && s.week >= 9,
      from: "🏛 Health ministry · E-health unit",
      title: "E-prescriptions must go through the national platform",
      body: "From next quarter, every prescription issued after a virtual consult must be sent through the national e-prescription system. Integration deadline: 60 days.",
      left: { label: "Put Tariq on it now", fx: { techDebt: -3, clarity: -4, pmf: -1 }, log: "Tariq paused the roadmap and spent three weeks on the ministry's test server. Your doctors' prescriptions now reach any pharmacy." },
      right: { label: "Ask for an extension", fx: { clarity: 2, trust: -2 }, log: "The unit granted 30 more days and copied your licence file on the reply." },
      ignore: { fx: { mrrPct: -0.08, churn: 0.5 }, log: "Day 61: pharmacies stopped accepting your doctors' prescriptions. Patients came back to the app asking why." },
    },
    {
      kind: "mail",
      id: "mx_health_03",
      when: (s) => s.sector.id === "healthtech" && s.monthlyRevenue >= 1500,
      from: "🩺 Dr. Samir Khalil · Partner clinic",
      title: "I'll send you my diabetes patients, but",
      body: "I have 30 patients a month who need home glucose monitoring. Other platforms pay me $15 per patient I refer. What can you do?",
      left: { label: "Pay the referral fee", fx: { users: 200, cash: -1500, trust: -2 }, log: "Thirty patients a month started arriving. Your lawyer asked you to stop calling it a referral fee in writing." },
      right: { label: "Offer him their data, not cash", fx: { users: 80, techDebt: 3, pmf: 2 }, log: "You built Dr. Samir a weekly summary of his patients' readings. He sent eight patients and called it 'the first useful app'." },
    },
    {
      kind: "mail",
      id: "mx_health_04",
      when: (s) => s.sector.id === "healthtech" && s.week >= 12,
      from: "🤝 Omar Sabry · Care-plan patient",
      title: "My mother's readings stopped syncing",
      body: "Her glucose meter hasn't sent anything for 9 days. She's 74 and she thinks she broke it, so she stopped measuring. I pay for both our plans.",
      left: { label: "Send a nurse to the house", fx: { cash: -300, clarity: -2, churn: -0.3, pmf: 2 }, log: "Nurse Huda re-paired the meter in ten minutes and stayed for tea. Omar posted about it in his family group." },
      right: { label: "Courier a new meter", fx: { cash: -60, churn: 0.1 }, log: "The new meter arrived in two days. Omar's mother asked her grandson to set it up on Friday." },
      ignore: { fx: { churn: 0.4, mrrPct: -0.03 }, log: "No reply for a week. Omar cancelled both plans and booked his mother at the clinic near their house." },
    },
  ];
