  const MAIL_EXTRA = [
    {
      kind: "mail",
      id: "mx_noise_01",
      from: "📧 Rana · GrowthStack Agency",
      title: "We can 10x your SEO in 30 days",
      body: "Quick question: who handles your organic growth? We've helped 200+ startups rank on page one. Do you have 15 minutes this week?",
      left: { label: "Book a call", fx: { clarity: -3 }, log: "Forty minutes of slides. Nothing you could use." },
      right: { label: "Archive", log: "Archived. Thirty seconds well saved." },
    },
    {
      kind: "mail",
      id: "mx_noise_02",
      from: "🎓 ScaleUp Academy · Live masterclass",
      title: "LIVE: How we scaled to $10M ARR in 18 months",
      body: "Join 3,000 founders this Thursday. Seats are limited. Replay available for VIP members only.",
      left: { label: "Register and attend", fx: { clarity: -4 }, log: "Ninety minutes. The last twenty were a pitch for a $499 course." },
      right: { label: "Archive", log: "Archived. Thursday evening stays yours." },
    },
    {
      kind: "mail",
      id: "mx_noise_03",
      from: "📧 Karim · PipelinePro CRM",
      title: "Quick question",
      body: "Hi! Are you the right person to talk to about your sales process? If not, could you point me to who is?",
      left: { label: "Reply: what is it?", fx: { clarity: -3 }, log: "You replied once. You have now received six follow-ups in four days." },
      right: { label: "Archive", log: "Archived. The fifth follow-up will be archived too." },
    },
    {
      kind: "mail",
      id: "mx_noise_04",
      from: "🎪 Future Founders Summit · Dubai",
      title: "You've been selected to speak on our main stage",
      body: "Our committee loved your story. The speaker package is $2,500 and includes a 10-minute slot and a gala dinner seat.",
      left: { label: "Buy the speaker slot", fx: { cash: -2500, clarity: -3 }, log: "Your 10 minutes were at 9am on day two. Forty people, mostly other speakers." },
      right: { label: "Archive", log: "Archived. Real stages don't send invoices." },
    },
    {
      kind: "mail",
      id: "mx_noise_05",
      from: "📰 The Founder Digest · Weekly",
      title: "47 links every founder must read this week",
      body: "Hot takes, funding rounds, a thread on morning routines, and why everyone is wrong about pricing.",
      left: { label: "Read all 47", fx: { clarity: -4 }, log: "Two hours later you knew who raised what. Your own roadmap hadn't moved." },
      right: { label: "Archive", log: "Archived. Nothing in it was about your customers." },
    },
    {
      kind: "mail",
      id: "mx_noise_06",
      from: "📱 Sameh · Founder Brand Coach",
      title: "Your LinkedIn is leaving money on the table",
      body: "I helped 300 founders go viral. Join my free 7-day challenge: one post a day, and you'll never chase investors again.",
      left: { label: "Join the challenge", fx: { clarity: -5, morale: -2 }, log: "Day three: a post about what your morning coffee taught you about leadership. The team saw it." },
      right: { label: "Archive", log: "Archived. Your customers aren't on day three of a challenge." },
    },
    {
      kind: "mail",
      id: "mx_noise_07",
      from: "💼 Dina · Executive search",
      title: "Exciting VP Product role at a fast-growing scale-up",
      body: "Your profile caught my eye. The package is very competitive. Open to a confidential chat?",
      left: { label: "Hear them out", fx: { clarity: -3, cofounder: -3 }, log: "The call was vague. Tariq saw the calendar invite and didn't ask about it." },
      right: { label: "Archive", log: "Archived. You already have a job. It just doesn't pay yet." },
    },
    {
      kind: "mail",
      id: "mx_noise_08",
      from: "🏆 MENA Innovation Awards",
      title: "Congratulations! You're a finalist: Top 40 Under 40",
      body: "To confirm your place, please pay the $900 nomination fee. Includes a trophy and a certificate.",
      left: { label: "Pay the fee", fx: { cash: -900, clarity: -1 }, log: "You won. So did everyone else who paid. The trophy is heavier than it looks." },
      right: { label: "Archive", log: "Archived. An award you pay for is an invoice with a ribbon." },
    },
    {
      kind: "mail",
      id: "mx_noise_09",
      from: "🤖 Ziad · ChainLoop Labs",
      title: "Let's tokenise your user community",
      body: "Your users could own a piece of your growth. We handle the token, the whitepaper and the Telegram group.",
      left: { label: "Take the intro call", fx: { clarity: -4, trust: -1 }, log: "An hour of diagrams. Layla heard about it and sent a single question mark." },
      right: { label: "Archive", log: "Archived. Your users want the product to work." },
    },
    {
      kind: "mail",
      id: "mx_noise_10",
      from: "📧 Hassan · DevForce Outsourcing",
      title: "We noticed your website loads slowly",
      body: "Our team of 120 engineers can rebuild your platform in 6 weeks at a fraction of the cost. Free audit attached.",
      left: { label: "Open the free audit", fx: { clarity: -3 }, log: "A 30-page PDF that could describe any website. Tariq read it out loud for laughs." },
      right: { label: "Archive", log: "Archived. Your website loads fine." },
    },
    {
      kind: "mail",
      id: "mx_noise_11",
      from: "📧 Hana Qasim · Graduate researcher",
      title: "Survey request: 10 minutes for my thesis",
      body: "I'm interviewing 40 clinic and shop owners about the software they pay for. Could I ask you a few questions too?",
      left: { label: "Reply and help", fx: { clarity: -2, pmf: 2, xp: 20 }, log: "She shared her notes. 11 of her 40 interviews described the exact problem you solve." },
      right: { label: "Archive", fx: { pmf: -1 }, log: "Archived. A month later her findings went around every founder group. You weren't in them." },
    },
    {
      kind: "mail",
      id: "mx_noise_12",
      from: "📧 Accounts · Gulf Freight Group",
      title: "Quick question about invoicing",
      body: "We're on your monthly plan. Do you offer annual invoicing? Our finance system needs it before the new quarter.",
      left: { label: "Reply with an annual offer", fx: { cash: 3000, mrrPct: 0.03, clarity: -1 }, log: "They paid a year upfront and added two seats while they were at it." },
      right: { label: "Archive", fx: { mrrPct: -0.02 }, log: "Archived. Six weeks later they moved to a competitor that invoices annually." },
    },
    {
      kind: "mail",
      id: "mx_thread_01",
      after: { id: "demo_crash", side: "left", weeks: 6 },
      from: "📧 Omar Sabry · Key customer",
      title: "I told our CFO about the weekend you fixed it",
      body: "He wants your product in our two other branches. He also wants a proper proposal, not a WhatsApp message.",
      left: { label: "Send a proposal tonight", fx: { mrrPct: 0.08, clarity: -4 }, log: "Proposal sent at midnight. Signed by Thursday. You slept on Friday." },
      right: { label: "Ask for a case study first", fx: { users: 120, pmf: 2, mrrPct: 0.03 }, log: "Omar agreed to a case study. The expansion will wait a quarter." },
    },
    {
      kind: "mail",
      id: "mx_thread_02",
      after: { id: "demo_crash", side: "right", weeks: 8 },
      from: "📧 Omar Sabry · Key customer",
      title: "About that discount",
      body: "Our renewal is next month. We'd like to keep the discounted price. Two of my peers have asked what we pay.",
      left: { label: "Back to full price", fx: { mrrPct: 0.03, churn: 0.4, clarity: -2 }, log: "Omar paid full price. He also invited two of your competitors to pitch." },
      right: { label: "Keep the discount", fx: { arpu: -2, churn: -0.3 }, log: "Omar renewed. His peers asked for the same price within a week." },
      ignore: { fx: { mrrPct: -0.06 }, log: "No reply from you. His procurement team took that as a no." },
    },
    {
      kind: "mail",
      id: "mx_thread_03",
      after: { id: "poach", side: "left", weeks: 10 },
      from: "💼 Tariq Mansour · CTO",
      title: "Thinking like an owner now",
      body: "Our cloud bill is double what it should be. Give me two quiet weeks, no features, and I'll cut it in half.",
      left: { label: "Give him the two weeks", fx: { baseBurn: -500, cofounder: 6, pmf: -1 }, log: "The bill dropped by half. The roadmap slipped by two weeks. Tariq looked pleased for once." },
      right: { label: "Features first, sorry", fx: { pmf: 2, cofounder: -6, techDebt: 3 }, log: "Tariq shipped the features. He didn't mention the cloud bill again." },
    },
    {
      kind: "mail",
      id: "mx_thread_04",
      after: { id: "poach", side: "right", weeks: 12 },
      from: "💼 Tariq Mansour · CTO",
      title: "They called again. This time it wasn't money.",
      body: "Big Tech offered me a Head of Engineering title. Here I'm the guy who keeps the servers up. What am I building toward?",
      left: { label: "Give him a real stake", fx: { equity: -2, cofounder: 10, baseBurn: -300 }, log: "You moved part of his salary into equity. He stopped checking his phone in meetings." },
      right: { label: "Talk about the next two years", fx: { clarity: -4, cofounder: 4, morale: 2 }, log: "Three hours in a cafe. No title change, but a plan he helped write." },
      ignore: { fx: { cofounder: -12, morale: -6 }, log: "Tariq took the interview. He didn't take the job. He didn't tell you either." },
    },
    {
      kind: "mail",
      id: "mx_thread_05",
      after: { id: "angel_update", side: "left", weeks: 8 },
      from: "👼 Layla Fahmy · Lead angel",
      title: "Your update reached a fund partner",
      body: "I forwarded your honest update to Mariam at a seed fund. She liked that you led with the bad news. She has 20 minutes Tuesday.",
      left: { label: "Take the meeting", fx: { trust: 6, clarity: -4, xp: 30 }, log: "Mariam asked about churn first. You had the real number ready. She asked for the data room." },
      right: { label: "Not raising yet, thank her", fx: { clarity: 2, trust: -2 }, log: "Layla said the door stays open. Mariam's calendar may not." },
    },
    {
      kind: "mail",
      id: "mx_thread_06",
      after: { id: "refund", side: "left", weeks: 6 },
      from: "🧾 Customer · The one you refunded",
      title: "I'm back. And I'm bringing my team.",
      body: "You refunded 11 months without arguing. My new company needs 6 seats. Can we start this week?",
      left: { label: "Onboard them yourself", fx: { mrrPct: 0.05, pmf: 2, clarity: -4 }, log: "You ran the onboarding call yourself. They found two bugs and a feature idea." },
      right: { label: "Send the help docs", fx: { mrrPct: 0.03, churn: 0.2 }, log: "They signed up. Two of the 6 seats never logged in." },
    },
    {
      kind: "mail",
      id: "mx_thread_07",
      after: { id: "bank_pilot", side: "left", weeks: 10 },
      from: "🏦 Regional bank · Information security",
      title: "Audit scheduled for next week",
      body: "Ahead of converting the pilot to a full contract, our auditors will review the security policy you shared.",
      left: { label: "Hire a consultant now", fx: { cash: -4000, techDebt: -8, trust: 3 }, log: "The consultant rewrote half your weekend policy. The audit passed with three notes." },
      right: { label: "Patch it ourselves", fx: { techDebt: 4, clarity: -8, morale: -4 }, log: "Four late nights. The audit passed, just. The team won't forget that week." },
      ignore: { fx: { mrrPct: -0.1, trust: -3 }, log: "Nobody prepared. The pilot ended with a polite email on a Tuesday." },
    },
    {
      kind: "mail",
      id: "mx_thread_08",
      after: { id: "press", side: "right", weeks: 12 },
      from: "📰 Salma · Tech reporter",
      title: "You said not yet. Is it yet?",
      body: "I'm writing about 10 founders to watch this year. I remembered you. Deadline is Friday.",
      left: { label: "Give the interview", fx: { trust: 6, users: 150, clarity: -4 }, log: "She asked about your churn and your burn. The piece was fair, and it ran on Sunday." },
      right: { label: "Still not yet", fx: { clarity: 2, trust: -2 }, log: "The list ran with 10 founders. Layla asked why you weren't one of them." },
    },
  ];
