  const MAIL_SAAS = [
    {
      kind: "mail",
      id: "mx_saas_01",
      from: "📧 Yasmin · PromptOps Cloud",
      title: "Your AI agents aren't enterprise-ready without us",
      body: "Observability, evals, guardrails and red-teaming in one platform, $1,400 a month. Most AI startups fail InfoSec without it. 20 minutes on Thursday?",
      when: (s) => s.sector.id === "saas_ai" && s.week >= 5,
      left: { label: "Book the demo", fx: { clarity: -3 }, log: "Twenty minutes became fifty. The dashboard looked great and needed 3 months of integration you don't have." },
      right: { label: "Archive", log: "Archived. Your evals are 400 questions in a spreadsheet, and they work." },
    },
    {
      kind: "mail",
      id: "mx_saas_02",
      from: "🏛 National Data Office · Compliance",
      title: "AI processors of personal data must register",
      body: "Companies using AI to process personal data must register, name a data protection officer and file an impact assessment within 30 days.",
      when: (s) => s.sector.id === "saas_ai" && s.week >= 9,
      left: { label: "Register and file it properly", fx: { cash: -1500, clarity: -4, trust: 3 }, log: "A lawyer, two weeks and a 31-page assessment. Your registration number now opens every security questionnaire you answer." },
      right: { label: "Wait until a client asks", fx: { clarity: 2, mrrPct: -0.03 }, log: "You parked it. Two weeks later a bank's procurement asked for the registration number, and onboarding paused." },
      ignore: { fx: { mrrPct: -0.06, trust: -3 }, log: "A bank's procurement asked for your registration number. You didn't have one, and their onboarding stopped there." },
    },
    {
      kind: "mail",
      id: "mx_saas_03",
      from: "☁ Rami · Regional cloud, partnerships",
      title: "$20,000 in credits if you host your agents with us",
      body: "Credits for 12 months, GPUs in-country, and co-selling to our banking clients. One condition: we are your exclusive cloud for 24 months.",
      when: (s) => s.sector.id === "saas_ai" && s.week >= 12 && s.monthlyRevenue >= 3000,
      left: { label: "Take the credits and the deal", fx: { baseBurn: -900, mrrPct: 0.04, techDebt: 5 }, log: "Migration took Tariq 5 weeks. Their sales team introduced you to two banks. You're on their cloud for the next 24 months." },
      right: { label: "Decline the exclusivity", fx: { baseBurn: -300, clarity: 1 }, log: "Rami came back with $8,000 in credits and no exclusivity. No co-selling either." },
    },
    {
      kind: "mail",
      id: "mx_saas_04",
      from: "🤝 Omar Sabry · Design partner",
      title: "Your agent answered a Saudi customer in Egyptian again",
      body: "Third time this week. Our Riyadh customers write in Khaleeji and Arabizi, and the agent replies like a Cairo call centre. My team is screenshotting it.",
      when: (s) => s.sector.id === "saas_ai" && s.week >= 6,
      left: { label: "Build a dialect test set with him", fx: { cash: -800, clarity: -3, pmf: 3 }, log: "Omar's team sent 1,200 real tickets. Tariq built a dialect test set. Accuracy in Khaleeji went from 71% to 88%." },
      right: { label: "Force all replies to formal Arabic", fx: { techDebt: 2, churn: 0.3, pmf: -1 }, log: "Every reply now comes in formal Arabic. No more Egyptian. Omar says it sounds like a government letter." },
      ignore: { fx: { churn: 0.5, mrrPct: -0.04 }, log: "Omar's team switched the agent to English only. Usage in Riyadh dropped by a third." },
    },
  ];
