  const MAIL_EDU = [
    {
      kind: "mail",
      id: "mx_edu_01",
      when: (s) => s.sector.id === "edtech" && s.week >= 4,
      from: "📧 Bassem · CertChain Credentials",
      title: "Your certificates can be faked in 5 minutes",
      body: "Employers no longer trust PDF certificates. Our blockchain credentials end fraud for good. Setup is $4,000 plus $6 per graduate. Demo this week?",
      left: { label: "Book the demo", fx: { clarity: -3 }, log: "The demo was a QR code that opens a web page. No employer has ever asked you to verify a certificate." },
      right: { label: "Archive", log: "Archived. Employers open the GitHub link, not the PDF." },
    },
    {
      kind: "mail",
      id: "mx_edu_02",
      when: (s) => s.sector.id === "edtech" && s.week >= 10 && s.monthlyRevenue >= 3000,
      from: "🏛 Training Licensing Directorate · Inspections",
      title: "Your certificate wording breaks the licensing rules",
      body: "Your certificates say Diploma. Only accredited institutes may use that word. Correct every issued certificate within 30 days or your licence is suspended.",
      left: { label: "Reissue them all as certificates", fx: { cash: -1500, clarity: -3, trust: 2 }, log: "You reissued 214 certificates and emailed every graduate. Four asked whether their old one had been fake." },
      right: { label: "Start full accreditation", fx: { cash: -5000, baseBurn: 300, trust: 4, pmf: 2 }, log: "The accreditation file runs to 120 pages and needs a quality manager. The inspector gave you 90 days to show progress." },
      ignore: { fx: { trust: -5, users: -200, mrrPct: -0.08 }, log: "On day 31 an inspector arrived with a stamped notice. You couldn't enrol new students for three weeks." },
    },
    {
      kind: "mail",
      id: "mx_edu_03",
      when: (s) => s.sector.id === "edtech" && s.week % 52 >= 20 && s.week % 52 < 30 && s.monthlyRevenue >= 2000,
      from: "🤝 Rasha Kamal · Northwind Retail talent team",
      title: "Interviews pause until September",
      body: "Half our hiring managers travel in July and August. We'll interview your latest graduates after the summer. Can you keep them warm for us?",
      left: { label: "Run a paid summer project", fx: { cash: -2000, churn: -0.4, pmf: 2 }, log: "Twelve graduates built an inventory tool for a real client over 6 weeks. Three had offers by September." },
      right: { label: "Tell them to apply elsewhere", fx: { clarity: 2, churn: 0.4 }, log: "The graduates scattered. Four took the first offer they got, two of them outside tech." },
      ignore: { fx: { churn: 0.6, trust: -2 }, log: "Nobody heard from you for a month. Graduates started posting about the silence in the alumni group." },
    },
    {
      kind: "mail",
      id: "mx_edu_04",
      when: (s) => s.sector.id === "edtech" && s.activeUsers >= 400,
      from: "🕵 Mazen · Current student",
      title: "Someone is selling our course on Telegram",
      body: "A channel with 8,000 members sells all your recorded lessons for $15. It already has last week's AI module. Thought you should know.",
      left: { label: "Send takedowns, watermark videos", fx: { cash: -1200, techDebt: 3, clarity: -2 }, log: "Telegram removed the channel in nine days. Two new ones appeared. Every video now carries the viewer's email." },
      right: { label: "Let it go, sell the mentoring", fx: { arpu: -1, users: 100, pmf: 2 }, log: "You stopped guarding the videos and doubled live code reviews. Three people from the channel applied for the paid cohort." },
    },
  ];
