  const MAIL_MKT = [
    {
      kind: "mail",
      id: "mx_mkt_01",
      when: (s) => s.sector.id === "ecommerce_marketplace" && s.week >= 4,
      from: "📧 Hazem · CartPulse AI",
      title: "Your abandoned carts cost you $40,000 a year",
      body: "We scanned your storefront: 71% of carts are abandoned. Our AI recovery suite is $600 a month and pays for itself in week one, guaranteed.",
      left: { label: "Start the free trial", fx: { cash: -1200, clarity: -3 }, log: "The trial renewed itself twice at $600 a month. It recovered 9 carts, mostly buyers who were coming back anyway." },
      right: { label: "Archive", log: "Archived. Most of those carts were people comparing delivery fees." },
    },
    {
      kind: "mail",
      id: "mx_mkt_02",
      when: (s) => s.sector.id === "ecommerce_marketplace" && s.monthlyRevenue >= 2500,
      from: "🏛 Consumer Protection · E-commerce unit",
      title: "Every listing must show the seller's trade licence",
      body: "Under the e-commerce rules, each listing must show the seller's commercial registration number and a returns policy in Arabic. You have 30 days to comply.",
      left: { label: "Audit every listing now", fx: { cash: -1500, clarity: -5, trust: 2 }, log: "Salma's team checked 2,300 listings in a week. 140 sellers had no licence and came off the site." },
      right: { label: "Ask for a 60-day extension", fx: { clarity: -3, techDebt: 2 }, log: "The extension came back approved for 30 days, not 60. The audit happened anyway, in a rush." },
      ignore: { fx: { cash: -5000, trust: -4 }, log: "An inspector ordered 3 random items. Two listings had no licence number. The fine arrived by courier." },
    },
    {
      kind: "mail",
      id: "mx_mkt_03",
      when: (s) => s.sector.id === "ecommerce_marketplace" && s.monthlyRevenue >= 3500,
      from: "📦 Khaled · SwiftLine Couriers",
      title: "Your parcel rate goes up next month",
      body: "Fuel and driver costs are up. Your rate goes from $3.20 to $3.80 a parcel next month, unless you commit to 3,000 parcels a month for 12 months.",
      left: { label: "Commit to 3,000 a month", fx: { baseBurn: 300, churn: -0.2, clarity: 2 }, log: "You signed. The rate held, and in slow months you'll pay for parcels you never send." },
      right: { label: "Bring in a second courier", fx: { baseBurn: -200, clarity: -5, techDebt: 3 }, log: "A second courier now covers the north of the city. Ops tracks two dashboards and two sets of excuses." },
      ignore: { fx: { baseBurn: 400, mrrPct: -0.02 }, log: "The new rate card applied on its own. Every order now earns $0.60 less, and nobody decided it." },
    },
    {
      kind: "mail",
      id: "mx_mkt_04",
      when: (s) => s.sector.id === "ecommerce_marketplace" && s.week >= 10,
      from: "🛍 Dalia · repeat buyer since launch",
      title: "My Eid gift arrived open, a day late",
      body: "I've ordered 41 times. The perfume for my mother came on the second day of Eid with the seal broken. I'm not angry. I just want to know you still care.",
      left: { label: "Call her and refund it", fx: { cash: -150, clarity: -2, churn: -0.2 }, log: "You called her yourself. She shared the call in her stories, and three of her friends ordered that week." },
      right: { label: "Send the apology code", fx: { clarity: 1, churn: 0.2 }, log: "She got a 10% code by email. Her next order, three weeks later, was on Souqly." },
    },
  ];
