  const NOTES_C = {
    POP_001: {
      lesson: "Vesting protects the founder who stays. A co-founder who leaves in month eight should not walk away owning half the company.",
      example: "Four years with a one-year cliff is the norm, and most seed investors ask for founder vesting to be in place before they wire money.",
      read: "Venture Deals, Brad Feld and Jason Mendelson",
      page: "vesting",
      skills: { A: { fundraising: -1 }, B: { fundraising: 1 } },
    },
    POP_002: {
      lesson: "Launch early to learn, but sort bugs by what they break. Lost data and wrong invoices are never minor.",
      example: "Reid Hoffman's line, that if your first version doesn't embarrass you, you launched too late, is about missing features, not broken payments.",
      read: "The Lean Startup, Eric Ries",
      page: "tech_debt",
      skills: { A: { discovery: 1 }, B: { discovery: -1, integrity: 1 } },
    },
    POP_003: {
      lesson: "Every week a bully stays, your quiet good people update their CVs. The numbers one person brings hide the people you lose.",
      example: "Netflix's public culture deck put it bluntly: on a dream team there are no brilliant jerks, because the cost to teamwork is too high.",
      read: "The No Asshole Rule, Robert Sutton",
      page: "no_jerks",
      skills: { A: { hiring: -1 }, B: { hiring: 1 } },
    },
    POP_004: {
      lesson: "In an outage, the first honest update buys you hours of patience. A cover story buys you minutes, until someone checks.",
      example: "Public post-mortems became standard at many infrastructure companies because users forgive downtime faster than they forgive spin.",
      read: "Site Reliability Engineering, Betsy Beyer et al.",
      page: "transparency",
      skills: { A: { integrity: 1, frugality: -1 }, B: { integrity: -1 } },
    },
    POP_005: {
      lesson: "Desperate money is the most expensive money. Read the control terms, vetoes and board seats, before you read the price.",
      example: "Founders who gave away board control early often learned that the board, not the market, decided when they would be replaced.",
      read: "Secrets of Sand Hill Road, Scott Kupor",
      page: "term_sheet",
      skills: { A: { fundraising: -1 }, B: { fundraising: 1, selfcare: -1 } },
    },
    POP_006: {
      lesson: "A viral spike is a sample, not a channel. Check how many new users are still active two weeks later before you scale spend.",
      example: "Spikes from one post or press hit usually fade within weeks. Teams that tracked cohort retention knew if they had growth or just a good day.",
      read: "Traction, Gabriel Weinberg and Justin Mares",
      page: "vanity",
      skills: { A: { frugality: -1, discovery: 1 }, B: { frugality: 1 } },
    },
    POP_007: {
      lesson: "A researcher who writes to you privately is doing you a favour. Thank her, pay her, fix it, and tell the customers affected.",
      example: "Many software companies publish a disclosure policy, and enterprise security questionnaires now often ask whether you have one.",
      read: "Security Engineering, Ross Anderson",
      page: "security",
      skills: { A: { integrity: 1, frugality: -1 }, B: { integrity: -1, frugality: 1 } },
    },
    POP_008: {
      lesson: "Compliance is cheap before an audit and expensive during one. A short retention policy reviewed by a lawyer is money well spent.",
      example: "Saudi Arabia, the UAE and Egypt have all passed personal data protection laws in recent years, and enterprise buyers now ask about them.",
      read: "Privacy by Design, Ann Cavoukian",
      page: "mena_regulation",
      skills: { A: { frugality: -1, integrity: 1 }, B: { selfcare: -1, frugality: 1 } },
    },
    POP_009: {
      lesson: "You can't win a salary war with a big company. Compete on scope, ownership and equity, and ask what she actually wants.",
      example: "Startups that kept senior engineers often did it with a fresh equity grant and a bigger role, not by matching cash they couldn't sustain.",
      read: "The Hard Thing About Hard Things, Ben Horowitz",
      page: "culture",
      skills: { A: { frugality: -1, hiring: 1 }, B: { frugality: 1 } },
    },
    POP_010: {
      lesson: "Bespoke work for one logo is a services contract. Price it like one, or make sure it ends up in the product for everyone.",
      example: "Many startups selling to businesses found their first enterprise pilot turned into a second product nobody else used, maintained by their best engineers.",
      read: "Crossing the Chasm, Geoffrey Moore",
      page: "custom_work",
      skills: { A: { discovery: -1 }, B: { discovery: 1 } },
    },
    POP_011: {
      lesson: "Your judgment is the company's scarcest resource. Rest is maintenance on it, scheduled before it breaks, not after.",
      example: "Founders who took a planned week off usually found the team coped fine, and the absence showed which decisions really needed them.",
      read: "Reboot, Jerry Colonna",
      page: "burnout",
      skills: { A: { selfcare: 1 }, B: { selfcare: -1, frugality: 1 } },
    },
    POP_012: {
      lesson: "A prepayment is the cheapest financing you will find, but a 30% discount resets your price. Trade a smaller discount or a shorter term.",
      example: "Annual prepay at a 10-20% discount is common in SaaS. Deeper cuts usually tell the buyer the seller needed cash more than they needed savings.",
      read: "Monetizing Innovation, Madhavan Ramanujam and Georg Tacke",
      page: "alt_funding",
      skills: { A: { frugality: 1 }, B: { fundraising: 1 } },
    },
    ORG_BOARD: {
      lesson: "A target you accept becomes your target. If you disagree, push back before the vote, with numbers, not after the miss.",
      example: "Experienced CEOs send the board deck days early and call each director first, so nothing important gets decided for the first time in the room.",
      read: "Startup Boards, Brad Feld and Mahendra Ramsinghani",
      page: "board",
      skills: { A: { fundraising: 1 }, B: { integrity: 1 } },
    },
    ORG_COFOUNDER: {
      lesson: "Co-founder resentment rarely starts with equity. Ask what credit and voice they want first; shares and titles are the last tool.",
      example: "Research on founding teams finds co-founder conflict among the most common reasons early startups fail, usually after months of unspoken grievances.",
      read: "The Founder's Dilemmas, Noam Wasserman",
      page: "cofounder",
      skills: { A: { hiring: 1, fundraising: -1 }, B: { hiring: -1, integrity: 1 } },
    },
    ST_NOUR: {
      lesson: "The company will ask for one more month forever. The people outside it can't wait forever. Book them like a board meeting.",
      example: "Founders who kept their relationships through hard years often describe fixed, non-negotiable time: one evening a week, one weekend a month.",
      read: "Startup Life, Brad Feld and Amy Batchelor",
      page: "family",
      skills: { A: { selfcare: 1 }, B: { selfcare: -1 } },
    },
  };
