  const NOTES_A = {
    dl_prod_01: {
      lesson: "A customer who pays for a one-off integration is buying a slice of your roadmap. Charge for the upkeep too, or say no.",
      example: "Many B2B startups built a connector for their biggest account and spent the next two years maintaining a product nobody else used.",
      read: "Inspired, Marty Cagan",
      page: "custom_work",
      skills: { A: { frugality: 1, discovery: -1 }, B: { discovery: 1, integrity: 1 } },
    },
    dl_prod_02: {
      lesson: "Usage that never turns into revenue is a cost centre with a fan club. Measure what each free feature converts, then decide.",
      example: "Free tools often bring traffic that loves the product and never pays. Some become the best sales channel; most just raise the server bill.",
      read: "Lean Analytics, Alistair Croll and Benjamin Yoskovitz",
      page: "burn_multiple",
      skills: { A: { frugality: 1, discovery: -1 }, B: { discovery: 1, frugality: -1 } },
    },
    dl_prod_03: {
      lesson: "Full rewrites take longer than planned and freeze the business. Rebuild in slices behind the running system whenever you can.",
      example: "Netscape's decision to rewrite its browser from scratch is the classic warning: years without a release while competitors kept shipping.",
      read: "Things You Should Never Do, Part I, Joel Spolsky",
      page: "tech_debt",
      skills: { A: { hiring: 1, discovery: -1 }, B: { discovery: 1, hiring: -1 } },
    },
    dl_prod_04: {
      lesson: "Build what your customers are asking for, not what your competitors announced. Investors fund traction, not feature lists.",
      example: "Every hype cycle produces a wave of features shipped for the press release and quietly removed a year later because nobody used them.",
      read: "Competing Against Luck, Clayton Christensen",
      page: "pmf",
      skills: { A: { fundraising: 1, frugality: -1 }, B: { discovery: 1, fundraising: -1 } },
    },
    dl_prod_05: {
      lesson: "Before you pay for a new platform, watch five real users sign up on their phones. The fix is often smaller than the quote.",
      example: "Plenty of startups paid an agency for native apps and found users still preferred the link they got on WhatsApp, which opens the web.",
      read: "The Mom Test, Rob Fitzpatrick",
      page: "mom_test",
      skills: { A: { discovery: -1 }, B: { frugality: 1, discovery: 1 } },
    },
    dl_prod_06: {
      lesson: "Someone hacking around your product is free research. Find out what they need before deciding whether to block or bless them.",
      example: "Many public APIs started because outside developers were already scraping the product. Twitter's early ecosystem grew from third-party clients.",
      read: "Platform Revolution, Parker, Van Alstyne and Choudary",
      page: "experiments",
      skills: { A: { discovery: 1, frugality: -1 }, B: { frugality: 1, discovery: -1 } },
    },
    dl_prod_07: {
      lesson: "A free tier is a marketing budget paid in support hours and servers. Know what it costs per user before you match a competitor.",
      example: "Freemium works when the free users cost almost nothing and a steady share upgrades. When support is human, free users can sink a small team.",
      read: "Monetizing Innovation, Madhavan Ramanujam and Georg Tacke",
      page: "pricing",
      skills: { A: { fundraising: 1, frugality: -1 }, B: { frugality: 1, discovery: 1 } },
    },
    dl_prod_08: {
      lesson: "When a critical supplier fails your customers, the credits go to you but the damage goes to them. Price the next outage, not this one.",
      example: "Companies that kept a flaky vendor for the discount usually migrated anyway, after a worse outage and under far more pressure.",
      read: "Site Reliability Engineering, Betsy Beyer et al.",
      page: "crisis",
      skills: { A: { integrity: 1, frugality: -1 }, B: { frugality: 1, integrity: -1 } },
    },
    dl_prod_09: {
      lesson: "Consistency work pays back slowly and invisibly. Do it when you can name the features it will speed up, not just the mess it cleans.",
      example: "Teams that built a design system early often ship screens in days; teams that built it too early polished components for features that died.",
      read: "Atomic Design, Brad Frost",
      page: "tech_debt",
      skills: { A: { hiring: 1, integrity: -1 }, B: { integrity: 1, hiring: -1 } },
    },
    dl_prod_10: {
      lesson: "With regulated data, the boring plan is the fast plan. Run old and new side by side until the numbers match.",
      example: "Health and finance migrations that went big-bang tend to produce the incident reports; parallel runs produce the clean audits.",
      read: "Release It!, Michael Nygard",
      page: "mena_regulation",
      skills: { A: { frugality: 1, integrity: -1 }, B: { integrity: 1, frugality: -1 } },
    },
    dl_prod_11: {
      lesson: "A number on your homepage is a promise someone will check. Use the claim you can defend in a room with a journalist.",
      example: "Inflated customer counts are among the first things diligence teams and reporters test. The correction always gets more readers than the claim.",
      read: "Obviously Awesome, April Dunford",
      page: "ethics",
      skills: { A: { integrity: -1 }, B: { integrity: 1 } },
    },
    dl_prod_12: {
      lesson: "Growth bought just before a raise shows up in the next board meeting. Investors read retention eventually; make sure yours survives it.",
      example: "Many startups showed a beautiful signup curve at seed, then spent the next round explaining why the discounted cohorts left.",
      read: "Venture Deals, Brad Feld and Jason Mendelson",
      page: "fundraise_timing",
      skills: { A: { fundraising: 1, integrity: -1 }, B: { integrity: 1, fundraising: -1 } },
    },
    dl_prod_13: {
      lesson: "Judge a channel by what a paying customer costs and how long they stay, not by reach. Followers are not customers.",
      example: "Big influencer posts often bring a spike that churns within weeks; many small creators with the right audience tend to bring steadier users.",
      read: "Traction, Gabriel Weinberg and Justin Mares",
      page: "unit_economics",
      skills: { A: { frugality: -1 }, B: { discovery: 1, frugality: 1 } },
    },
    dl_prod_14: {
      lesson: "Pay for referrals and you attract people who love the payment. Reward something only a real user would value.",
      example: "PayPal paid cash for signups early on and it worked, at a huge cost. Dropbox gave free storage instead, a reward that only mattered to users.",
      read: "Hacking Growth, Sean Ellis and Morgan Brown",
      page: "churn",
      skills: { A: { discovery: -1, frugality: -1 }, B: { frugality: 1 } },
    },
    dl_prod_15: {
      lesson: "Growth taken without consent is borrowed against your reputation. Every pre-ticked box is a complaint you have scheduled.",
      example: "LinkedIn settled a class action over the reminder emails it sent to users' imported contacts. Annoyed recipients remember the sender.",
      read: "Deceptive Patterns, Harry Brignull",
      page: "vanity",
      skills: { A: { integrity: -1, discovery: 1 }, B: { integrity: 1 } },
    },
    dl_prod_16: {
      lesson: "A distribution partner gives you reach and takes your pricing power. Read the exclusivity clause before the revenue line.",
      example: "Startups bundled by a telecom or bank often grew fast and then found the partner owned the customer relationship and set the price.",
      read: "Crossing the Chasm, Geoffrey Moore",
      page: "channels",
      skills: { A: { fundraising: 1, discovery: -1 }, B: { discovery: 1, fundraising: -1 } },
    },
    dl_prod_17: {
      lesson: "A big stage multiplies whatever you show. Demo what works today, and protect the team from a crunch that the audience never sees.",
      example: "Live demos of unfinished software are a startup tradition. So is the month of bug fixing and tired engineers that follows the applause.",
      read: "The Lean Startup, Eric Ries",
      page: "burnout",
      skills: { A: { selfcare: -1, fundraising: 1 }, B: { selfcare: 1, hiring: 1 } },
    },
    dl_prod_18: {
      lesson: "Organic demand in a new market is a signal, not a mandate. Learn why they came before you pay to bring more.",
      example: "Startups that followed organic pull into a new country did best when they first called those users and learned what they wanted.",
      read: "The Mom Test, Rob Fitzpatrick",
      page: "expansion",
      skills: { A: { discovery: 1, frugality: -1 }, B: { frugality: 1, discovery: -1 } },
    },
    dl_ppl_01: {
      lesson: "Loyalty earns trust, not a management job. If you promote a builder, give them a coach and a way back without shame.",
      example: "Many early engineers promoted to lead were miserable within a year. The ones who got training and a clear manager path often thrived.",
      read: "The Making of a Manager, Julie Zhuo",
      page: "delegation",
      skills: { A: { hiring: -1, integrity: 1 }, B: { hiring: 1, frugality: -1 } },
    },
    dl_ppl_02: {
      lesson: "Remote work fails when only one person is remote. If you say yes, move the team's decisions into writing for everyone.",
      example: "Distributed companies that thrive write things down by default. Hybrid teams often leave the one remote person out of hallway decisions.",
      read: "Remote, Jason Fried and David Heinemeier Hansson",
      page: "culture",
      skills: { A: { hiring: 1 }, B: { hiring: -1, frugality: -1 } },
    },
    dl_ppl_03: {
      lesson: "Public fights are a vacuum where a decision should be. Make the call, write down why, and let the losing side disagree and commit.",
      example: "Teams that split people to avoid a fight often end up with two systems doing the same job, and the original argument still unresolved.",
      read: "Radical Candor, Kim Scott",
      page: "no_jerks",
      skills: { A: { hiring: 1, selfcare: -1 }, B: { selfcare: 1, hiring: -1 } },
    },
    dl_ppl_04: {
      lesson: "Every counter-offer sets a salary policy, whether you meant it or not. Decide the rule you would want everyone to know.",
      example: "Startups that matched one outside offer often faced three more within months. Clear salary bands make the next conversation easier.",
      read: "No Rules Rules, Reed Hastings and Erin Meyer",
      page: "transparency",
      skills: { A: { hiring: 1, frugality: -1 }, B: { frugality: 1, hiring: -1 } },
    },
    dl_ppl_05: {
      lesson: "Hiring through family and friends feels like trust and works like debt. Hire on the same bar, then explain it kindly at home.",
      example: "In many Arab markets referrals from family are the main hiring channel. The companies that grow keep the interview bar the same for everyone.",
      read: "Who, Geoff Smart and Randy Street",
      page: "mena_wasta",
      skills: { A: { selfcare: 1, hiring: -1 }, B: { hiring: 1, selfcare: -1 } },
    },
    dl_ppl_06: {
      lesson: "If one person alone owns a critical system, you have a security problem before you have a people problem. Fix the single point of failure.",
      example: "Many breaches and outages trace back to one engineer with sole access. Shared ownership and access reviews are cheap insurance.",
      read: "An Elegant Puzzle, Will Larson",
      page: "security",
      skills: { A: { integrity: 1, frugality: -1 }, B: { frugality: 1, integrity: -1 } },
    },
    dl_ppl_07: {
      lesson: "Cut once, cut deep enough, and tell people the plan. Small repeated cuts cost more trust than one hard decision.",
      example: "Founders who cut too little often had to cut again within a quarter. Teams forgive a hard call faster than a slow series of them.",
      read: "The Hard Thing About Hard Things, Ben Horowitz",
      page: "runway",
      skills: { A: { frugality: 1, hiring: -1 }, B: { integrity: 1, selfcare: -1 } },
    },
    dl_ppl_08: {
      lesson: "Overruling your co-founder on a key hire spends trust you will need later. If you go ahead, agree on how you will both judge it.",
      example: "Co-founder splits often start with a hire one of them never wanted. A shared 90-day scorecard turns the argument into a test.",
      read: "The Founder's Dilemmas, Noam Wasserman",
      page: "cofounder",
      skills: { A: { fundraising: 1, hiring: -1 }, B: { hiring: 1 } },
    },
    dl_ppl_09: {
      lesson: "A quiet complaint is a test of whether people can trust you with the next one. Protect the reporter first, then fix the behaviour.",
      example: "Startups without HR often handle the first complaint informally. The ones that hired outside help early tended to avoid the second, louder one.",
      read: "Radical Candor, Kim Scott",
      page: "no_jerks",
      skills: { A: { integrity: 1, frugality: -1 }, B: { frugality: 1, hiring: -1 } },
    },
    dl_ppl_10: {
      lesson: "When your early people vest out, they become free agents. Refresh grants before the cliff, not after the resignation.",
      example: "Many startups lost their first engineers right after full vesting. Refresh grants are standard practice in companies that kept them.",
      read: "The Holloway Guide to Equity Compensation, Joshua Levy",
      page: "vesting",
      skills: { A: { hiring: 1, fundraising: -1 }, B: { fundraising: 1, hiring: -1 } },
    },
    dl_ppl_11: {
      lesson: "A founder who can't pay rent makes desperate decisions. A modest salary is an operating cost, not a luxury.",
      example: "Investors generally expect founders to draw a small salary. Founders who took nothing for years often burned out or took worse deals out of fear.",
      read: "The Founder's Dilemmas, Noam Wasserman",
      page: "family",
      skills: { A: { selfcare: 1, frugality: -1 }, B: { frugality: 1, selfcare: -1 } },
    },
    dl_ppl_12: {
      lesson: "A competitor's money comes with a competitor's attention. Ask what information rights they get before you ask about the valuation.",
      example: "Strategic investments from rivals can scare off later investors and acquirers, who worry the rival already sees your numbers.",
      read: "Venture Deals, Brad Feld and Jason Mendelson",
      page: "term_sheet",
      skills: { A: { fundraising: -1, frugality: 1 }, B: { fundraising: 1 } },
    },
    dl_ppl_13: {
      lesson: "A personal guarantee moves company risk onto your home and your family. Only sign if you would still sign after the worst quarter.",
      example: "Debt can be cheaper than equity for a startup with revenue. The founders who regretted it were the ones who put their home on the line.",
      read: "The Founder's Dilemmas, Noam Wasserman",
      page: "alt_funding",
      skills: { A: { fundraising: 1, selfcare: -1 }, B: { selfcare: 1 } },
    },
    dl_ppl_14: {
      lesson: "Early customers paying old prices are a thank-you that never ends. Raise with notice, a reason and a timeline, not a surprise invoice.",
      example: "SaaS companies that gave loyal customers months of notice and a clear reason usually kept most of them through a price rise.",
      read: "Monetizing Innovation, Madhavan Ramanujam and Georg Tacke",
      page: "pricing",
      skills: { A: { frugality: 1, integrity: -1 }, B: { integrity: 1, frugality: -1 } },
    },
    dl_ppl_15: {
      lesson: "Revenue you collect in four months is a loan you give today. Model the cash gap before you celebrate the bigger contract.",
      example: "Large retailers and government buyers in the region often pay late. Many profitable-on-paper startups ran out of cash waiting for invoices.",
      read: "Default Alive or Default Dead?, Paul Graham",
      page: "default_alive",
      skills: { A: { frugality: -1, fundraising: 1 }, B: { frugality: 1 } },
    },
    dl_ppl_16: {
      lesson: "Candidates judge the company by what they can see. Fix the pitch, the process and the people before you fix the furniture.",
      example: "Senior hires usually turn down startups over role and pay, not desks. Still, a visit to a chaotic space can tip a close call.",
      read: "Who, Geoff Smart and Randy Street",
      page: "hire_slow",
      skills: { A: { hiring: 1, frugality: -1 }, B: { frugality: 1, hiring: -1 } },
    },
    dl_ppl_17: {
      lesson: "A bridge with a low cap prices your company before the market does. Compare it with cutting burn, not with running out.",
      example: "Bridge notes with steep discounts often set the price the next lead investor anchors on. Some founders cut costs and raised later on better terms.",
      read: "Venture Deals, Brad Feld and Jason Mendelson",
      page: "dilution",
      skills: { A: { fundraising: -1 }, B: { frugality: 1, hiring: -1 } },
    },
    dl_ppl_18: {
      lesson: "In payments, the cheapest provider is the one that never freezes your money. Check their compliance team before their fees.",
      example: "Founders in the region tell the same story: a cheaper processor, a sudden compliance review, and weeks of payouts held back.",
      read: "Payments Systems in the U.S., Carol Coye Benson",
      page: "mena_payments",
      skills: { A: { frugality: 1, discovery: -1 }, B: { discovery: 1, frugality: -1 } },
    },
  };
