  const NOTES_B = {
    dl_life_01: {
      lesson: "A customer's numbers belong to the customer. Asking first costs a few days; using them without asking can cost the account and the reference.",
      example: "Founders who ask usually get a yes, and often a quote too. Investors also notice when a deck shows data the customer clearly never cleared.",
      read: "The Trusted Advisor, David Maister",
      page: "transparency",
      skills: { A: { integrity: -1 }, B: { integrity: 1, fundraising: -1 } },
    },
    dl_life_02: {
      lesson: "Bending a date on an invoice is cheap once and expensive forever: it trains a client to expect it and puts your books on the wrong side of an audit.",
      example: "Procurement teams ask for this more often than founders expect. A clear 'we can't, but here's a prepayment discount' usually keeps the deal.",
      read: "The Hard Thing About Hard Things, Ben Horowitz",
      page: "ethics",
      skills: { A: { integrity: -1, frugality: 1 }, B: { integrity: 1 } },
    },
    dl_life_03: {
      lesson: "Every number you give the press becomes a number you must beat later. Say the real one and explain the trend behind it.",
      example: "Inflated launch numbers often resurface in due diligence, when an investor compares the old article with the dashboard.",
      read: "Trust Me, I'm Lying, Ryan Holiday",
      page: "vanity",
      skills: { A: { integrity: -1 }, B: { integrity: 1, discovery: 1 } },
    },
    dl_life_04: {
      lesson: "A cancellation flow that traps people lowers churn on paper and raises it in reputation. Ask leavers why instead of making them crawl out.",
      example: "In 2023 the US FTC sued Amazon over how hard it was to cancel Prime. Regulators everywhere now treat cancellation friction as a consumer issue.",
      read: "Deceptive Patterns, Harry Brignull",
      page: "churn",
      skills: { A: { integrity: -1, frugality: 1 }, B: { integrity: 1, discovery: 1 } },
    },
    dl_life_05: {
      lesson: "Money you took by mistake is not revenue. Refunding before anyone asks turns a bug into the reason customers trust your billing.",
      example: "Companies that email 'we overcharged you, it's already refunded' tend to get thank-you replies. The ones found out later get screenshots.",
      read: "Radical Candor, Kim Scott",
      page: "transparency",
      skills: { A: { integrity: 1, frugality: -1 }, B: { frugality: 1, integrity: -1 } },
    },
    dl_life_06: {
      lesson: "Investors remember how you talk about others and assume you'll talk about them the same way. Win on your own numbers.",
      example: "Ecosystems in Riyadh, Dubai and Cairo are small; gossip about a rival's CTO tends to reach that CTO within a week, with your name attached.",
      read: "Secrets of Sand Hill Road, Scott Kupor",
      page: "fundraise_timing",
      skills: { A: { fundraising: 1, integrity: -1 }, B: { integrity: 1 } },
    },
    dl_life_07: {
      lesson: "Most meetings can move; most family moments can't. Ask before you assume the investor's calendar is fixed.",
      example: "Partners reschedule all the time. A founder who says 'I have a family wedding, can we do Sunday?' rarely loses the deal over it.",
      read: "Startup Life, Brad Feld and Amy Batchelor",
      page: "family",
      skills: { A: { fundraising: 1, selfcare: -1 }, B: { selfcare: 1 } },
    },
    dl_life_08: {
      lesson: "A launch that can't survive two days without you is a launch with a single point of failure. Write the runbook, then actually leave.",
      example: "Founders who practise short, real disconnections early tend to build teams that can run a launch without them in the room.",
      read: "Startup Life, Brad Feld and Amy Batchelor",
      page: "delegation",
      skills: { A: { selfcare: 1, hiring: 1 }, B: { selfcare: -1 } },
    },
    dl_life_09: {
      lesson: "Parents worry in the currency they know: salaries. Give them a timeline and a fallback, not a pitch deck.",
      example: "Many founders in the region say the turning point with family was sharing a simple plan: 'if this isn't working by June, here's what I'll do'.",
      read: "Crucial Conversations, Kerry Patterson et al.",
      page: "family",
      skills: { A: { integrity: 1 }, B: { selfcare: -1 } },
    },
    dl_life_10: {
      lesson: "Chest pain isn't a calendar item to negotiate. Customers move calls; bodies don't reschedule.",
      example: "A renewal call moved by two hours almost never costs a renewal. Founders who ignore symptoms for a year often lose months later.",
      read: "Reboot, Jerry Colonna",
      page: "burnout",
      skills: { A: { selfcare: 1 }, B: { selfcare: -1, discovery: 1 } },
    },
    dl_life_11: {
      lesson: "A founder who can't pay rent makes worse decisions. A small salary is a runway cost, not a luxury; family loans have terms even when unwritten.",
      example: "Seed investors generally expect founders to pay themselves a modest living wage; it rarely raises an eyebrow in diligence.",
      read: "The Psychology of Money, Morgan Housel",
      page: "runway",
      skills: { A: { frugality: 1, selfcare: -1 }, B: { selfcare: 1, frugality: -1 } },
    },
    dl_life_12: {
      lesson: "Generosity compounds in small ecosystems, but your evenings are your company's scarcest resource. Give the highest-leverage hour, not the month.",
      example: "A single warm introduction usually does more for a struggling founder than weeks of deck edits.",
      read: "Give and Take, Adam Grant",
      page: "mena_wasta",
      skills: { A: { integrity: 1, selfcare: -1 }, B: { frugality: 1 } },
    },
    dl_life_13: {
      lesson: "Sleep is a decision-making tool. A founder on five hours is negotiating the round with a worse brain than the investor across the table.",
      example: "Research on sleep deprivation shows judgement degrades long before people notice it themselves.",
      read: "Why We Sleep, Matthew Walker",
      page: "burnout",
      skills: { A: { selfcare: 1 }, B: { fundraising: 1, selfcare: -1 } },
    },
    dl_life_14: {
      lesson: "Burnout named early is cheaper than burnout discovered in a board meeting. Treat support as infrastructure, not indulgence.",
      example: "More founders now say openly they see a therapist or coach; several founder communities in the region run peer circles for this.",
      read: "Reboot, Jerry Colonna",
      page: "burnout",
      skills: { A: { selfcare: 1, frugality: -1 }, B: { frugality: 1, selfcare: -1 } },
    },
    dl_life_15: {
      lesson: "In an outage, the first job is honest communication, the second is diagnosis. Spending money before you know the cause often buys nothing.",
      example: "In 2017 GitLab lost production data and live-streamed its recovery. Many users said the openness made them trust the company more.",
      read: "Site Reliability Engineering, Beyer et al. (Google)",
      page: "crisis",
      skills: { A: { integrity: 1 }, B: { frugality: -1 } },
    },
    dl_life_16: {
      lesson: "A co-founder's public words are the company's words. Deal with it privately and fast, and let the apology be theirs, not dictated.",
      example: "Viral outrage usually fades in days, but candidates and customers search the company name for months afterward.",
      read: "So You've Been Publicly Shamed, Jon Ronson",
      page: "no_jerks",
      skills: { A: { hiring: 1 }, B: { hiring: -1 } },
    },
    dl_life_17: {
      lesson: "When customer data leaks, the cover-up is what people remember. Disclose quickly, say exactly what leaked and what you changed.",
      example: "Uber concealed a 2016 breach and paid the hackers to stay quiet; its former security chief was later convicted over the cover-up.",
      read: "The Hard Thing About Hard Things, Ben Horowitz",
      page: "security",
      skills: { A: { integrity: 1 }, B: { integrity: -1, frugality: 1 } },
    },
    dl_life_18: {
      lesson: "If one person leaving breaks your demo, the problem is older than today. Show what works reliably and write down what only one head knows.",
      example: "Investors rarely fund the feature they saw; they fund how the founder handled the day. A calm demo of the old version often lands fine.",
      read: "The Hard Thing About Hard Things, Ben Horowitz",
      page: "delegation",
      skills: { A: { fundraising: 1, hiring: -1 }, B: { integrity: 1 } },
    },
    dl_life_19: {
      lesson: "Payment providers can hold your money at any time. Keep a payroll buffer outside the processor, and ask about reserve terms before you sign.",
      example: "Rolling reserves and review holds after refund spikes are standard processor policy, and they usually arrive with little warning.",
      read: "Default Alive or Default Dead?, Paul Graham",
      page: "default_alive",
      skills: { A: { frugality: -1, hiring: 1 }, B: { integrity: 1, hiring: -1 } },
    },
    dl_life_20: {
      lesson: "A regulator's letter is a deadline and a signal. Fix the product issue first; a good reply describes a change you've already shipped.",
      example: "Authorities in the region increasingly enforce auto-renewal and refund rules; a prompt, specific reply often closes the file.",
      read: "Regulatory Hacking, Evan Burfield",
      page: "mena_regulation",
      skills: { A: { frugality: -1, integrity: 1 }, B: { frugality: 1 } },
    },
    dl_life_21: {
      lesson: "A disaster is a chance to test which parts of the office you actually need. Decide on purpose, not by default.",
      example: "Plenty of teams discovered during forced remote periods that they needed a room twice a week, not five days.",
      read: "Remote: Office Not Required, Jason Fried and David Heinemeier Hansson",
      page: "culture",
      skills: { A: { frugality: 1 }, B: { hiring: 1, frugality: -1 } },
    },
    dl_life_22: {
      lesson: "Real reviews are an asset you build before you need them. Ask happy customers routinely, never only in a crisis, and never with rewards.",
      example: "App stores remove review bombs when you document the pattern, but slowly. Apps with steady review requests recover faster.",
      read: "Contagious, Jonah Berger",
      page: "channels",
      skills: { A: { integrity: 1 }, B: { discovery: 1 } },
    },
    dl_mena_01: {
      lesson: "Wasta is a loan with no written terms. If you use it, know what you're willing to give back before the call is made.",
      example: "Saudi, UAE and Egyptian registries have moved much of licensing online, which has made the queue shorter and the favour less necessary.",
      read: "Wasta: The Hidden Force in Middle Eastern Society, Cunningham and Sarayrah",
      page: "mena_wasta",
      skills: { A: { selfcare: 1, integrity: -1 }, B: { integrity: 1, frugality: -1 } },
    },
    dl_mena_02: {
      lesson: "In regulated finance, the licence is the moat. A sandbox is expensive, slow and the cheapest way to own the customer.",
      example: "SAMA, the UAE central bank and Egypt's central bank all run fintech sandboxes; many regional payments startups used them as the road to a licence.",
      read: "Regulatory Hacking, Evan Burfield",
      page: "mena_regulation",
      skills: { A: { fundraising: 1, frugality: -1 }, B: { frugality: 1 } },
    },
    dl_mena_03: {
      lesson: "Data residency rules only tighten. Migrating early is costly; migrating late is costly and rushed.",
      example: "Saudi's personal data law and cloud rules pushed global providers to open in-country regions; vendors already local won government tenders first.",
      read: "Regulatory Hacking, Evan Burfield",
      page: "mena_regulation",
      skills: { A: { integrity: 1, frugality: -1 }, B: { discovery: 1 } },
    },
    dl_mena_04: {
      lesson: "Renaming a product to dodge a regulator changes the label, not the risk. Decide what you are, then build the evidence for it.",
      example: "Saudi's SFDA and UAE health regulators both regulate software as a medical device; a clinical study also becomes a strong sales asset with hospitals.",
      read: "Regulatory Hacking, Evan Burfield",
      page: "mena_regulation",
      skills: { A: { integrity: 1, frugality: -1 }, B: { frugality: 1, integrity: -1 } },
    },
    dl_mena_05: {
      lesson: "A Thursday freeze before a Sunday payroll is a calendar risk you can plan for. Keep one payroll in a bank you control.",
      example: "Founders in Riyadh and Cairo learn that a Friday-Saturday weekend and slow corporate payments make a one-month cash buffer the minimum, not a luxury.",
      read: "Default Alive or Default Dead?, Paul Graham",
      page: "mena_payments",
      skills: { A: { hiring: 1, selfcare: -1 }, B: { integrity: 1, hiring: -1 } },
    },
    dl_mena_06: {
      lesson: "Cash on delivery is a trust gap, not a payment method. Close it with reasons to pay upfront before you add penalties.",
      example: "Regional e-commerce players reduced COD mainly with card discounts, wallets and instalment options, while charging COD fees only on low-margin items.",
      read: "Obviously Awesome, April Dunford",
      page: "mena_payments",
      skills: { A: { frugality: 1, discovery: -1 }, B: { discovery: 1, frugality: -1 } },
    },
    dl_mena_07: {
      lesson: "Ramadan changes when people use your product, not just how much. Plan the month like a season: staffing, campaigns and rest.",
      example: "Across the Gulf and Egypt, app usage and ad prices peak late at night in Ramadan; teams that plan night cover early avoid burning out by the last ten days.",
      read: "The Culture Map, Erin Meyer",
      page: "mena_seasons",
      skills: { A: { discovery: 1, hiring: -1 }, B: { hiring: 1, discovery: -1 } },
    },
    dl_mena_08: {
      lesson: "Customs become expectations. Whatever you decide about Eid, explain it in person, before Eid, with the numbers.",
      example: "An Eid bonus is custom, not law, in most private companies in the region, but staff compare notes; silence reads as a cut.",
      read: "The Culture Map, Erin Meyer",
      page: "mena_seasons",
      skills: { A: { hiring: 1, frugality: -1 }, B: { frugality: 1 } },
    },
    dl_mena_09: {
      lesson: "In the Gulf, summer is a sales season with holes in it. Close before June or plan for September, and protect the weeks family will remember.",
      example: "Experienced enterprise founders in Riyadh and Dubai build their pipeline to close by the second quarter and treat July and August as preparation months.",
      read: "Four Thousand Weeks, Oliver Burkeman",
      page: "mena_seasons",
      skills: { A: { discovery: 1, selfcare: -1 }, B: { selfcare: 1 } },
    },
    dl_mena_10: {
      lesson: "Your parents are buying security for you. Respect the offer, and show them what security looks like in your plan.",
      example: "Across the region, government jobs still carry status and stability; founders who share a dated plan with parents usually get more patience.",
      read: "Crucial Conversations, Kerry Patterson et al.",
      page: "family",
      skills: { A: { integrity: 1 }, B: { selfcare: 1 } },
    },
    dl_mena_11: {
      lesson: "Hiring family to keep the peace usually just moves the conflict into the office. Help generously, but outside your payroll.",
      example: "Family businesses in the Gulf are often built on relatives, but many founders find a first job elsewhere is the kinder gift to a cousin.",
      read: "Who: The A Method for Hiring, Geoff Smart and Randy Street",
      page: "hire_slow",
      skills: { A: { hiring: -1 }, B: { hiring: 1 } },
    },
    dl_mena_12: {
      lesson: "Government money has a price tag in conditions. Read the relocation and hiring clauses as carefully as the valuation.",
      example: "Saudi programmes such as the regional HQ rules made Riyadh moves common; founders who budgeted for them early found the money worth it.",
      read: "Secrets of Sand Hill Road, Scott Kupor",
      page: "alt_funding",
      skills: { A: { fundraising: 1, hiring: -1 }, B: { fundraising: -1, frugality: 1 } },
    },
    dl_mena_13: {
      lesson: "Stage time is worth its cost only if you've booked the meetings around it. Plan the week, not the four minutes.",
      example: "Founders who flew to Riyadh for demo days with 15 pre-booked meetings tended to get more from them than those who only pitched.",
      read: "Pitch Anything, Oren Klaff",
      page: "fundraise_timing",
      skills: { A: { fundraising: 1, frugality: -1 }, B: { frugality: 1, discovery: 1 } },
    },
    dl_mena_14: {
      lesson: "You can't outspend a sovereign fund. You can out-know your customers. Compete where money is not the advantage.",
      example: "Heavily funded free-year launches often lose customers when the free year ends; incumbents who stayed close to users kept them.",
      read: "Zero to One, Peter Thiel",
      page: "pmf",
      skills: { A: { discovery: 1, frugality: -1 }, B: { discovery: 1 } },
    },
    dl_mena_15: {
      lesson: "Pick a second market for the customer you can serve best, not the map. Saudi rewards patience and presence; Egypt rewards scale and efficiency.",
      example: "Saudi's Nitaqat quotas and entity setup take months; Egypt's 2022 to 2024 currency slide hurt firms pricing in pounds while paying costs in dollars.",
      read: "The Culture Map, Erin Meyer",
      page: "expansion",
      skills: { A: { fundraising: 1, frugality: -1 }, B: { frugality: 1 } },
    },
    dl_mena_16: {
      lesson: "Arabic-first is not a translation; it's a design decision about layout, dates, numbers and dialect. Users feel the difference immediately.",
      example: "Regional apps that won Gulf users often wrote copy in neutral Modern Standard Arabic and tested right-to-left charts with real users.",
      read: "Don't Make Me Think, Steve Krug",
      page: "pmf",
      skills: { A: { discovery: 1, frugality: -1 }, B: { frugality: 1, discovery: -1 } },
    },
    dl_mena_17: {
      lesson: "An acqui-hire prices your team, not your company. Know who it really pays, and tell your investors before they hear it elsewhere.",
      example: "In acqui-hires most of the value usually goes to retention packages; investors often get their money back and little more.",
      read: "Venture Deals, Brad Feld and Jason Mendelson",
      page: "exits",
      skills: { A: { integrity: 1 }, B: { fundraising: 1 } },
    },
    dl_mena_18: {
      lesson: "A merger of equals is rarely equal. Agree who runs what before you agree on the split, or the dinner becomes a long divorce.",
      example: "Uber agreed in 2019 to buy its regional rival Careem rather than keep burning cash against it, and kept Careem's brand and founders.",
      read: "Getting to Yes, Roger Fisher and William Ury",
      page: "exits",
      skills: { A: { fundraising: 1, frugality: 1 }, B: { frugality: -1 } },
    },
    dl_mena_19: {
      lesson: "A modest secondary can make a founder braver, not lazier. Keep it small, disclose it to the board, and stop worrying about rent.",
      example: "Founder secondaries are common in growth rounds; investors mostly worry when the founder sells a large slice early.",
      read: "Secrets of Sand Hill Road, Scott Kupor",
      page: "dilution",
      skills: { A: { selfcare: 1, fundraising: -1 }, B: { fundraising: 1, selfcare: -1 } },
    },
    dl_mena_20: {
      lesson: "Exclusivity is the buyer's strongest lever. Shorten it, tie it to milestones, and know your walk-away price before you sign.",
      example: "Valuations in a letter of intent often drop during diligence, once competing bidders are locked out.",
      read: "Venture Deals, Brad Feld and Jason Mendelson",
      page: "exits",
      skills: { A: { fundraising: -1 }, B: { fundraising: 1 } },
    },
    dl_mena_21: {
      lesson: "A big licensing deal is revenue that can quietly become your whole company. Price the engineers' time and the exclusivity, not just the logo.",
      example: "Startups that white-label for one national telecom often find their roadmap set by the telecom's procurement calendar.",
      read: "The Innovator's Dilemma, Clayton Christensen",
      page: "custom_work",
      skills: { A: { frugality: 1, discovery: -1 }, B: { fundraising: 1, frugality: -1 } },
    },
  };
