// الانتربرونور الصغير · The Little Entrepreneur: all game text and numbers.
//
// Plain data, English and Arabic side by side, so it can be reviewed and
// extended without touching game.js. Rules for writers:
//   - The child is never "he" or "she". English says "you". Arabic avoids
//     second-person present tense and imperatives (they are gendered): use
//     past tense (بعت، اخترت), verbal nouns for option labels (خفض السعر),
//     unvocalised suffixes (كشكك، زبائنك) and "هيا نـ..." for buttons.
//   - Every number in the English must appear, identically, in the Arabic.
//   - Coins are a generic currency: "coins" / "عملة".
//   - fx keys: coins, energy, smiles, quality (0-100 meters), honest (+1/-1),
//     mods: [{ k, x, weeks }] where k is demand | cost | share | energyUse | bonus.
//     Mods start with the NEXT sell day (dilemmas come after selling).
//   - Echo after: [min, max] weeks later (2..5). The game adds "week N" itself.
//   - C (the third door) needs Energy >= needs (70).
//   - when: { minWeek, minCoins, rainNext } (all optional).

var LITTLE = {

  // ───────────────────────── Businesses ─────────────────────────
  // cost = coins to make one item. prices = [cheap, fair, high].
  // base = customers on a normal sunny day at a fair price.
  // spoils = leftovers are wasted (true) or kept for next week (false).
  businesses: {
    juice: {
      img: "lemon", icon: "🍋", cost: 1, prices: [2, 3, 5], base: 9, spoils: true,
      weather: { sunny: 1, hot: 1.45, rainy: 0.5 },
      name: { en: "Juice stand", ar: "كشك العصير" },
      item: { en: "cups", ar: "أكواب" },
      tag: { en: "Fresh lemonade on hot days. Cheap to make, but it spoils.", ar: "ليموناضة طازجة في الأيام الحارّة. تكلفتها قليلة، لكنها لا تدوم." },
    },
    art: {
      img: "artist_palette", icon: "🎨", cost: 2, prices: [3, 5, 8], base: 6, spoils: false,
      weather: { sunny: 1, hot: 0.9, rainy: 0.8 },
      name: { en: "Drawings & bracelets", ar: "رسومات وأساور" },
      item: { en: "pieces", ar: "قطع" },
      tag: { en: "Handmade and pretty. Leftovers keep for next week.", ar: "صنع يدوي وجميل. وما يتبقّى يُحفظ للأسبوع القادم." },
    },
    bike: {
      img: "bicycle", icon: "🚲", cost: 1, prices: [2, 3, 5], base: 9, spoils: false,
      weather: { sunny: 1.1, hot: 0.9, rainy: 0.5 },
      name: { en: "Bike wash & fix", ar: "غسيل الدراجات وإصلاحها" },
      item: { en: "wash kits", ar: "عدّة غسيل" },
      tag: { en: "Soap, water and a wrench. Rain keeps customers away.", ar: "صابون وماء ومفتاح ربط. والمطر يُبعد الزبائن." },
    },
    cakes: {
      img: "birthday_cake", icon: "🎂", cost: 2, prices: [3, 5, 8], base: 6, spoils: true,
      weather: { sunny: 1, hot: 0.8, rainy: 1.1 },
      name: { en: "Cakes & cookies", ar: "كيك وكوكيز" },
      item: { en: "cakes", ar: "كيكات" },
      tag: { en: "Everyone loves cake. It costs more to make, and it doesn't last.", ar: "الجميع يحب الكيك. تكلفته أعلى، ولا يبقى طازجًا طويلًا." },
    },
  },

  // ───────────────────────── Savings goals ─────────────────────────
  goals: [
    { id: "ball", img: "soccer_ball", coins: 100, name: { en: "A football", ar: "كرة قدم" } },
    { id: "books", img: "books", coins: 160, name: { en: "A book set", ar: "مجموعة كتب" } },
    { id: "gift", img: "wrapped_gift", coins: 220, name: { en: "A gift for Mum", ar: "هدية لماما" } },
    { id: "bike", img: "bicycle", coins: 300, name: { en: "A new bike", ar: "دراجة جديدة" } },
  ],

  avatars: ["girl", "boy", "child", "cat_face"],

  weather: {
    sunny: { img: "sun", en: "Sunny", ar: "مشمس" },
    hot: { img: "hot_face", en: "Very hot", ar: "حارّ جدًا" },
    rainy: { img: "cloud_with_rain", en: "Rainy", ar: "ممطر" },
  },

  prices: [
    { en: "Cheap", ar: "رخيص" },
    { en: "Fair", ar: "معتدل" },
    { en: "High", ar: "غالٍ" },
  ],

  activities: {
    poster: { img: "placard", en: "Make a poster", ar: "صنع ملصق", hint: { en: "More customers", ar: "زبائن أكثر" } },
    practise: { img: "cooking", en: "Practise", ar: "تدريب", hint: { en: "Better quality", ar: "جودة أعلى" } },
    study: { img: "books", en: "Study", ar: "مذاكرة", hint: { en: "Homework done", ar: "إنجاز الواجبات" } },
    rest: { img: "soccer_ball", en: "Rest & play", ar: "راحة ولعب", hint: { en: "More energy", ar: "طاقة أكثر" } },
  },

  // ───────────── Grandpa's ideas from the game itself (stickers) ─────────────
  ideas: {
    profit: { img: "coin", en: "Profit is the coins that came in, minus the coins you spent.", ar: "الربح هو النقود التي دخلت، ناقص النقود التي صُرفت." },
    waste: { img: "grimacing_face", en: "Leftovers that spoil are coins thrown in the bin. Making fewer is a skill.", ar: "البقايا التي تفسد نقودٌ تُرمى في سلّة المهملات. وصنع كمية أقل مهارة." },
    soldout: { img: "package", en: "Selling out feels great, but some customers went home with nothing.", ar: "نفاد البضاعة شعور رائع، لكن بعض الزبائن عادوا بلا شيء." },
    stock: { img: "package", en: "Things that don't spoil can wait for next week's customers.", ar: "ما لا يفسد يمكنه انتظار زبائن الأسبوع القادم." },
    sleepy: { img: "yawning_face", en: "Tired sellers make small mistakes. Rest is part of the job.", ar: "مع التعب تقع أخطاء صغيرة. والراحة جزء من العمل." },
    homework: { img: "books", en: "Homework comes first. The stand will still be there next week.", ar: "الواجبات أولًا. والكشك سيبقى في مكانه الأسبوع القادم." },
    poster: { img: "placard", en: "People can't buy from a stand they don't know about.", ar: "لا أحد يشتري من كشك لا يعرف بوجوده." },
    quality: { img: "glowing_star", en: "Better quality brings customers back, and they bring friends.", ar: "الجودة الأعلى تعيد الزبائن، وهم يُحضرون أصدقاءهم." },
    high: { img: "money_bag", en: "A high price means fewer customers. Sometimes that's still more profit.", ar: "السعر الغالي يعني زبائن أقل. وأحيانًا يبقى الربح أكبر." },
    saving: { img: "pig_face", en: "Every coin you don't spend today walks your goal one step closer.", ar: "كل عملة لا تُصرف اليوم تقرّب الهدف خطوة." },
  },

  // ───────────────────────── Interface text ─────────────────────────
  ui: {
    title: { en: "The Little Entrepreneur", ar: "الانتربرونور الصغير" },
    subtitle: { en: "Run a tiny business for one summer. Grandpa will help.", ar: "مشروع صغير لصيف واحد. وجدّو موجود للمساعدة." },
    newGame: { en: "New summer", ar: "صيف جديد" },
    resume: { en: "Continue summer", ar: "متابعة الصيف" },
    howTo: { en: "How to play", ar: "طريقة اللعب" },
    parents: { en: "For parents", ar: "للأهل" },
    stickers: { en: "Sticker book", ar: "دفتر الملصقات" },
    langBtn: { en: "العربية", ar: "English" },
    theme: { en: "Light or dark", ar: "فاتح أو داكن" },
    back: { en: "Back", ar: "رجوع" },
    next: { en: "Next", ar: "التالي" },
    ok: { en: "OK!", ar: "حسنًا!" },
    home: { en: "Home", ar: "الرئيسية" },

    setupTitle: { en: "Your summer business", ar: "مشروع الصيف" },
    nameQ: { en: "Your first name", ar: "اسمك الأول" },
    namePh: { en: "Type your name", ar: "الاسم هنا" },
    nameNote: { en: "Your name stays on this device.", ar: "الاسم يبقى على هذا الجهاز فقط." },
    avatarQ: { en: "Pick your picture", ar: "صورتك في اللعبة" },
    bizQ: { en: "Pick a business", ar: "نوع المشروع" },
    goalQ: { en: "What are you saving for?", ar: "حلم الادّخار" },
    start: { en: "Let's go!", ar: "هيا نبدأ!" },
    needName: { en: "Type your name first", ar: "الاسم أولًا من فضلك" },

    coins: { en: "Coins", ar: "نقود" },
    energy: { en: "Energy", ar: "طاقة" },
    smiles: { en: "Smiles", ar: "ابتسامات" },
    week: { en: "Week {n} of 12", ar: "الأسبوع {n} من 12" },
    goal: { en: "Goal", ar: "الهدف" },

    planTitle: { en: "Plan your week", ar: "خطة الأسبوع" },
    forecast: { en: "Market day weather", ar: "طقس يوم السوق" },
    nextWeek: { en: "Next week", ar: "الأسبوع القادم" },
    priceQ: { en: "Price for one", ar: "سعر الواحدة" },
    makeQ: { en: "How many to make?", ar: "كم نصنع؟" },
    makeCost: { en: "Costs {n} coins", ar: "التكلفة بالعملات: {n}" },
    inStock: { en: "+{n} left from last week", ar: "+{n} من الأسبوع الماضي" },
    guess: { en: "Grandpa guesses about {n} customers", ar: "توقّع جدّو لعدد الزبائن: {n} تقريبًا" },
    tooPoor: { en: "Not enough coins for that many", ar: "النقود لا تكفي لهذا العدد" },
    activityQ: { en: "One more thing this week", ar: "نشاط الأسبوع" },
    open: { en: "Open the stand!", ar: "هيا نفتح الكشك!" },
    quality: { en: "Quality", ar: "الجودة" },
    homeworkWarn: { en: "Mum asked about homework. Two weeks without studying!", ar: "ماما سألت عن الواجبات. مرّ أسبوعان بلا مذاكرة!" },
    sleepyWarn: { en: "You're sleepy. Numbers look wobbly, and mistakes happen.", ar: "النعاس واضح. الأرقام تتمايل، والأخطاء واردة." },

    sellTitle: { en: "Market day!", ar: "يوم السوق!" },
    skip: { en: "Skip", ar: "هيا نتخطّى" },
    customersCame: { en: "{n} customers came", ar: "عدد الزبائن: {n}" },

    resultsTitle: { en: "How did it go?", ar: "كيف كان اليوم؟" },
    sold: { en: "Sold", ar: "المبيع" },
    coinsIn: { en: "Coins in", ar: "نقود دخلت" },
    coinsSpent: { en: "Coins spent", ar: "نقود صُرفت" },
    profit: { en: "Profit", ar: "الربح" },
    wasted: { en: "Leftovers wasted", ar: "بقايا ضاعت" },
    kept: { en: "Leftovers kept for next week", ar: "بقايا محفوظة للأسبوع القادم" },
    partnerCut: { en: "Partner's half", ar: "نصف الشريك" },
    bonus: { en: "Regular customer", ar: "زبون دائم" },
    mistake: { en: "Oops! Wrong change", ar: "أوه! باقٍ خاطئ" },
    soldOut: { en: "Sold out! {n} customers went home with nothing.", ar: "نفدت البضاعة! عاد {n} من الزبائن بلا شيء." },
    profitSum: { en: "{a} in − {b} spent = {c}", ar: "{a} دخلت − {b} صُرفت = {c}" },
    treatQ: { en: "Spend some coins on a treat?", ar: "شيء ممتع ببعض النقود؟" },
    treatYes: { en: "Ice cream: 4 coins, +8 energy", ar: "آيس كريم: 4 عملات، +8 طاقة" },
    treatBig: { en: "A new toy: 15 coins, +12 energy", ar: "لعبة جديدة: 15 عملة، +12 طاقة" },
    treatNo: { en: "No, save it", ar: "لا، للحصّالة" },

    ideaTitle: { en: "Grandpa's idea", ar: "فكرة جدّو" },
    newSticker: { en: "New sticker!", ar: "ملصق جديد!" },
    locked: { en: "Needs {n} energy", ar: "يلزم {n} طاقة" },
    thirdDoor: { en: "The wise door", ar: "الباب الحكيم" },
    echoFrom: { en: "This is because of what you did in week {n}.", ar: "هذا بسبب ما حدث في الأسبوع {n}." },

    closedTitle: { en: "The stand is closed this week", ar: "الكشك مغلق هذا الأسبوع" },
    closedMum: { en: "Mum sat down with you. \"3 weeks without homework. This week we study together, and the stand rests. It will be there next week.\"", ar: "جلست ماما بجانبك وقالت: «3 أسابيع بلا واجبات. هذا الأسبوع نذاكر معًا، والكشك يرتاح. سيبقى في مكانه الأسبوع القادم.»" },
    closedDad: { en: "Dad made two cups of tea. \"3 weeks without homework. This week is for homework, and the stand takes a little holiday.\"", ar: "حضّر بابا كوبين من الشاي وقال: «3 أسابيع بلا واجبات. هذا الأسبوع للواجبات، والكشك يأخذ إجازة صغيرة.»" },

    rescueTitle: { en: "Grandpa needs a hand", ar: "جدّو يحتاج مساعدة" },
    rescueText: { en: "Your coins ran out. Grandpa pays you 12 coins for watering his garden. A fresh start!", ar: "نفدت النقود. دفع جدّو 12 عملة مقابل سقي حديقته. بداية جديدة!" },

    goalHit: { en: "You reached your goal!", ar: "وصلت إلى الهدف!" },
    endTitle: { en: "The summer is over", ar: "انتهى الصيف" },
    endWin: { en: "You saved {a} coins. {b} is yours!", ar: "ادّخرت {a} من العملات. و{b} لك الآن!" },
    endNotYet: { en: "You saved {a} of {b} coins. That's {c}% of the way.", ar: "ادّخرت {a} من العملات من أصل {b}. هذا {c}% من الطريق." },
    endGrandpa: { en: "Grandpa says", ar: "جدّو يقول" },
    report: { en: "Report card", ar: "بطاقة التقييم" },
    skillMoney: { en: "Money", ar: "الحساب" },
    skillCustomers: { en: "Customers", ar: "العملاء" },
    skillBalance: { en: "Balance", ar: "التوازن" },
    skillHonesty: { en: "Honesty", ar: "الأمانة" },
    again: { en: "Another summer", ar: "صيف آخر" },
    totalProfit: { en: "Total profit", ar: "مجموع الربح" },
    weeksStudied: { en: "Weeks of homework", ar: "أسابيع الواجبات" },
    stickerCount: { en: "{a} of {b} stickers", ar: "الملصقات: {a} من {b}" },
    stickerEmpty: { en: "Play a summer to collect Grandpa's ideas.", ar: "كل صيف يضيف أفكارًا جديدة من جدّو." },

    credit: { en: "Pictures: needle-felted art made for this game. Fonts: Manrope and Readex Pro (OFL).", ar: "الصور: رسومات صوف ملبّد صُنعت لهذه اللعبة. الخطوط: Manrope و Readex Pro (رخصة OFL)." },
    resetQ: { en: "Start a new summer? This one will be lost.", ar: "بدء صيف جديد؟ سيضيع هذا الصيف." },
  },

  // Grandpa's end-of-season words. One line per skill, chosen by score.
  endLines: {
    win: { en: "You set a goal and you reached it. Most grown-ups find that hard.", ar: "وضعت هدفًا ووصلت إليه. وهذا صعب على كثير من الكبار." },
    notYet: { en: "You didn't reach it this time, and that's how everyone learns. Next summer you start knowing all of this.", ar: "لم يكتمل الهدف هذه المرة، وهكذا يتعلّم الجميع. والصيف القادم يبدأ ومعك كل هذه الخبرة." },
    moneyLow: { en: "Watch the leftovers: make about as many as Grandpa guesses.", ar: "الانتباه للبقايا مهم: الأفضل صنع عدد قريب من توقّع جدّو." },
    moneyHigh: { en: "Your counting was sharp. You knew what came in and what went out.", ar: "حسابك كان دقيقًا. كان واضحًا ما يدخل وما يخرج." },
    customersLow: { en: "Customers come back for good quality and fair prices.", ar: "الزبائن يعودون من أجل الجودة والسعر العادل." },
    customersHigh: { en: "People liked coming to your stand. That's worth a lot.", ar: "أحبّ الناس المجيء إلى كشكك. وهذا يساوي الكثير." },
    balanceLow: { en: "Rest and homework are part of a good business too.", ar: "الراحة والواجبات جزء من أي مشروع ناجح." },
    balanceHigh: { en: "You worked, rested and studied. That balance is rare.", ar: "عملت وارتحت وذاكرت. وهذا التوازن نادر." },
    honestyLow: { en: "Shortcuts feel fast. Trust lasts longer.", ar: "الطرق المختصرة تبدو سريعة. لكن الثقة تدوم أطول." },
    honestyHigh: { en: "You told the truth even when it cost coins. Customers noticed.", ar: "قلت الحقيقة حتى حين كلّفتك نقودًا. ولاحظ الزبائن ذلك." },
  },

  howTo: [
    { img: "lemon", en: "Pick a small business and a savings goal. You have 12 weeks of summer.", ar: "اختيار مشروع صغير وهدف للادّخار. أمامك 12 أسبوعًا من الصيف." },
    { img: "placard", en: "Each week: choose a price, how many to make, and one activity.", ar: "كل أسبوع: سعر، وكمية للصنع، ونشاط واحد." },
    { img: "coin", en: "Making things costs coins. Profit is coins in minus coins spent.", ar: "الصنع يكلّف نقودًا. والربح هو ما دخل ناقص ما صُرف." },
    { img: "high_voltage", en: "Watch your energy. Below 40 you get sleepy and make mistakes. At 70+ a wise third choice opens.", ar: "الطاقة مهمة. تحت 40 يأتي النعاس والأخطاء. ومن 70 فما فوق يُفتح خيار ثالث حكيم." },
    { img: "books", en: "Study at least every 3 weeks, or the stand closes for a week.", ar: "المذاكرة مرة كل 3 أسابيع على الأقل، وإلا أُغلق الكشك أسبوعًا." },
    { img: "old_man", en: "Grandpa shares an idea after each choice. Some choices come back weeks later.", ar: "جدّو يشارك فكرة بعد كل اختيار. وبعض الاختيارات تعود بعد أسابيع." },
  ],

  parentsNote: {
    en: [
      "The Little Entrepreneur is a free game for ages 8 to 12 about money basics: profit, saving, pricing, listening to customers, honesty and rest.",
      "Nothing leaves this device. There are no accounts, no ads, no analytics, no tracking and nothing to buy. Your child's name and progress are saved only in this browser.",
      "It loads nothing from other websites. After the first visit it also works offline.",
      "There are no harsh endings. A summer takes about 15 minutes.",
    ],
    ar: [
      "الانتربرونور الصغير لعبة مجانية للأعمار من 8 إلى 12 عن أساسيات المال: الربح والادّخار والتسعير والإصغاء للزبائن والأمانة والراحة.",
      "لا يخرج شيء من هذا الجهاز. لا حسابات ولا إعلانات ولا تحليلات ولا تتبّع ولا مشتريات. اسم طفلكم وتقدّمه محفوظان في هذا المتصفح فقط.",
      "لا تُحمِّل اللعبة شيئًا من مواقع أخرى. وبعد الزيارة الأولى تعمل دون اتصال أيضًا.",
      "لا توجد نهايات قاسية. ويستغرق الصيف الواحد نحو 15 دقيقة.",
    ],
  },

  // ───────────────────────── Dilemmas ─────────────────────────
  dilemmas: [

    // ── General (any business) ──
    {
      id: "g_partner", biz: "all", img: "handshake", when: { minWeek: 2 },
      title: { en: "Yousef wants to be your partner", ar: "يوسف يريد أن يصبح شريكك" },
      text: { en: "Your friend Yousef wants to join. He'll carry things, set up and call out to customers. In return he wants half of the profit, every week.", ar: "صديقك يوسف يريد الانضمام. سيحمل الأغراض ويرتّب الطاولة وينادي على الزبائن. وفي المقابل يريد نصف الربح كل أسبوع." },
      A: { label: { en: "Say yes: split 50/50", ar: "القبول: الربح مناصفة 50/50" },
           fx: { energy: 4, mods: [{ k: "share", x: 0.5, weeks: 4 }, { k: "demand", x: 1.35, weeks: 4 }, { k: "energyUse", x: 0.5, weeks: 4 }] },
           log: { en: "Yousef starts next week, for 4 weeks. More hands, more customers, half the profit.", ar: "يبدأ يوسف من الأسبوع القادم لمدة 4 أسابيع. أيدٍ أكثر، وزبائن أكثر، ونصف الربح." } },
      B: { label: { en: "Say no: keep it your own", ar: "الرفض: المشروع يبقى لك وحدك" },
           fx: { energy: -3 },
           log: { en: "Yousef said okay, but went quiet. All the carrying is still yours.", ar: "قال يوسف: حسنًا، لكنه صار قليل الكلام. وما زال حمل الأغراض كله عليك." },
           echo: { after: [2, 4], img: "shopping_cart",
                   title: { en: "Yousef has his own stand now", ar: "صار ليوسف كشك خاص به" },
                   text: { en: "Yousef opened a small stand on the next street. Some of your customers stop there first now.", ar: "فتح يوسف كشكًا صغيرًا في الشارع المجاور. وصار بعض زبائنك يمرّون عليه أولًا." },
                   fx: { mods: [{ k: "demand", x: 0.88, weeks: 3 }] } } },
      C: { needs: 70, label: { en: "Try it for two weeks, then decide together", ar: "تجربة الشراكة أسبوعين، ثم القرار معًا" },
           fx: { smiles: 3, mods: [{ k: "share", x: 0.5, weeks: 2 }, { k: "demand", x: 1.35, weeks: 2 }, { k: "energyUse", x: 0.5, weeks: 2 }] },
           log: { en: "You wrote the deal on paper: two weeks, then talk again. Yousef signed it with a smiley face.", ar: "كُتب الاتفاق على ورقة: أسبوعان، ثم نتكلّم من جديد. ووقّع يوسف بوجه مبتسم." } },
      idea: { en: "Half of a big cake can be more than a whole small one. Or less. The counting decides.", ar: "نصف كعكة كبيرة قد يكون أكبر من كعكة صغيرة كاملة، وقد يكون أصغر. الحساب هو الحَكَم." },
    },
    {
      id: "g_extra", biz: "all", img: "coin",
      title: { en: "There are extra coins in the cash box", ar: "في صندوق النقود عملات زائدة" },
      text: { en: "You counted the box twice. There are 6 coins more than you sold. Someone paid too much, and it was probably the lady with the green bag.", ar: "عددت الصندوق مرتين. فيه 6 عملات أكثر مما بعت. أحدهم دفع زيادة، وعلى الأرجح أنها السيدة صاحبة الحقيبة الخضراء." },
      A: { label: { en: "Keep them: it was her mistake", ar: "الاحتفاظ بها، فالخطأ خطؤها" },
           fx: { coins: 6, honest: -1 },
           log: { en: "6 more coins. The green bag is on your mind a little.", ar: "زادت النقود 6 عملات. وصارت الحقيبة الخضراء تشغل البال قليلًا." },
           echo: { after: [2, 4], img: "grimacing_face",
                   title: { en: "The lady with the green bag", ar: "السيدة صاحبة الحقيبة الخضراء" },
                   text: { en: "She came back and said, kindly, that her change was wrong last time. There was nothing good to say.", ar: "عادت وقالت بلطف إن الباقي كان خاطئًا في المرة الماضية. ولم يكن هناك كلام مناسب يقال." },
                   fx: { smiles: -5 } } },
      B: { label: { en: "Find her and give them back", ar: "البحث عنها وإرجاع النقود" },
           fx: { energy: -4, honest: 1, smiles: 2 },
           log: { en: "She laughed and said nobody had ever run after her to give money back.", ar: "ضحكت وقالت إن أحدًا لم يركض خلفها من قبل ليُرجع لها نقودًا." },
           echo: { after: [2, 5], img: "heart_hands",
                   title: { en: "She told her friends", ar: "أخبرت صديقاتها" },
                   text: { en: "The lady with the green bag came back with two friends. \"This is the honest stand,\" she told them.", ar: "عادت السيدة صاحبة الحقيبة الخضراء ومعها صديقتان، وقالت لهما: «هذا هو الكشك الأمين.»" },
                   fx: { smiles: 5, mods: [{ k: "demand", x: 1.15, weeks: 2 }] } } },
      idea: { en: "Trust is like savings: slow to build, quick to spend.", ar: "الثقة مثل الادّخار: تُبنى ببطء وتُصرف بسرعة." },
    },
    {
      id: "g_game", biz: "all", img: "video_game", when: { minCoins: 40 },
      title: { en: "The new video game is out today", ar: "اللعبة الجديدة نزلت اليوم" },
      text: { en: "Everyone at the summer club is talking about it. It costs 30 coins. You have the coins right now, but they are part of your savings.", ar: "الكل في النادي الصيفي يتكلّم عنها. سعرها 30 عملة. النقود موجودة الآن، لكنها جزء من مدّخراتك." },
      A: { label: { en: "Buy it today", ar: "شراؤها اليوم" },
           fx: { coins: -30, energy: 10 },
           log: { en: "You played until dinner. It really was fun. The piggy bank is lighter.", ar: "لعبت حتى موعد العشاء. كانت ممتعة فعلًا. والحصّالة صارت أخفّ." } },
      B: { label: { en: "Wait and keep saving", ar: "الانتظار ومواصلة الادّخار" },
           fx: { energy: -2 },
           log: { en: "The piggy bank stays heavy. Your friends will tell you all about the game.", ar: "بقيت الحصّالة ثقيلة. وسيحكي لك الأصدقاء كل شيء عن اللعبة." },
           echo: { after: [3, 5], img: "video_game",
                   title: { en: "The game is cheaper now", ar: "صارت اللعبة أرخص" },
                   text: { en: "The shop put the same game on sale for 18 coins, 12 less than before. Waiting can pay.", ar: "خفّض المتجر سعر اللعبة نفسها إلى 18 عملة، أي أقل بـ12 من قبل. الانتظار قد يكون مربحًا." },
                   fx: { energy: 4 } } },
      idea: { en: "Saving means picking what you want most over what you want right now.", ar: "الادّخار يعني تقديم الحلم الكبير على الرغبة السريعة." },
    },
    {
      id: "g_grandma", biz: "all", img: "old_woman",
      title: { en: "Grandma offers to pay for your supplies", ar: "جدّتك تعرض دفع ثمن المستلزمات" },
      text: { en: "Grandma says she'll pay for your supplies for the next 3 weeks. Every coin from selling would be yours to keep.", ar: "تقول جدّتك إنها ستدفع ثمن المستلزمات خلال 3 أسابيع قادمة. فيصير ثمن كل ما يُباع ربحًا كاملًا." },
      A: { label: { en: "Say thank you and accept", ar: "الشكر والقبول" },
           fx: { quality: -6, mods: [{ k: "cost", x: 0, weeks: 3 }] },
           log: { en: "Supplies are free for 3 weeks, but Grandma picks them, and they're not quite what you use. Your profit will look huge.", ar: "المستلزمات مجانية لـ3 أسابيع، لكن جدّتك هي من تختارها، وليست تمامًا ما اعتدت عليه. وسيبدو الربح كبيرًا جدًا." } },
      B: { label: { en: "Thank her, but pay your own way", ar: "الشكر، ودفع التكاليف بنفسك" },
           fx: { energy: 5 },
           log: { en: "Grandma smiled and gave you a hug instead. Every cost is still on your list.", ar: "ابتسمت جدّتك وعانقتك بدلًا من ذلك. وبقيت كل تكلفة في الحساب." } },
      C: { needs: 70, label: { en: "Ask her to teach you her tricks instead", ar: "طلب درس من جدّتك بدل المال" },
           fx: { quality: 15, energy: -4 },
           log: { en: "Grandma spent an afternoon showing you how she makes things neat and tasty. Your work looks better already.", ar: "قضت جدّتك عصرًا كاملًا تشرح حيلها في الإتقان. وصار عملك أجمل من الآن." } },
      idea: { en: "A gift is lovely. Just remember what things really cost.", ar: "الهدية جميلة. لكن التكلفة الحقيقية يجب أن تبقى في الحساب." },
    },
    {
      id: "g_friends", biz: "all", img: "speech_balloon", when: { minWeek: 3 },
      title: { en: "Your friends want a lower price", ar: "أصدقاؤك يريدون سعرًا أقل" },
      text: { en: "Hamza and Mariam come every week. \"We're your friends,\" they say. \"Friends pay half.\"", ar: "حمزة ومريم يأتيان كل أسبوع. يقولان: «نحن أصدقاؤك، والأصدقاء يدفعون النصف.»" },
      A: { label: { en: "Give friends half price", ar: "نصف السعر للأصدقاء" },
           fx: { coins: -4, smiles: 4 },
           log: { en: "Hamza and Mariam brought 3 more friends. They all asked for the friends' price.", ar: "أحضر حمزة ومريم 3 أصدقاء آخرين، وكلهم طلبوا سعر الأصدقاء." },
           echo: { after: [2, 4], img: "speech_balloon",
                   title: { en: "Everyone is a friend now", ar: "الجميع صاروا أصدقاء" },
                   text: { en: "Half the street says they are your friend now. The friends' price costs more than you thought.", ar: "نصف الشارع صار يقول إنه من أصدقائك. وسعر الأصدقاء صار يكلّف أكثر مما توقّعت." },
                   fx: { coins: -6, smiles: 2 } } },
      B: { label: { en: "Same price for everyone", ar: "سعر واحد للجميع" },
           fx: { smiles: -2 },
           log: { en: "Mariam was grumpy for a minute, then paid. Hamza paid and asked to be first in line next week.", ar: "تضايقت مريم دقيقة ثم دفعت. ودفع حمزة وطلب أن يكون أول الطابور الأسبوع القادم." } },
      idea: { en: "A price is a promise. If it changes for some people, others will ask too.", ar: "السعر وعد. وإذا تغيّر لبعض الناس، سيطلب الآخرون الشيء نفسه." },
    },
    {
      id: "g_free", biz: "all", img: "house", when: { minWeek: 2 },
      title: { en: "A neighbour wants free help \"for practice\"", ar: "جارة تطلب مساعدة مجانية «من أجل الخبرة»" },
      text: { en: "Auntie Huda wants help in her little shop on Saturday mornings for the next two weeks. \"No pay,\" she says, \"but it's great practice!\" Saturday is your best selling day.", ar: "تطلب الخالة هدى مساعدة في دكانها الصغير صباح كل سبت خلال الأسبوعين القادمين. تقول: «بلا أجر، لكنها خبرة رائعة!» والسبت أفضل يوم للبيع." },
      A: { label: { en: "Say yes, for the practice", ar: "القبول من أجل الخبرة" },
           fx: { quality: 8, smiles: 3, mods: [{ k: "demand", x: 0.75, weeks: 2 }] },
           log: { en: "You learned how a real shop works. Your own stand opens late on Saturdays for two weeks.", ar: "تعلّمت كيف يعمل دكان حقيقي. وكشكك يفتح متأخرًا أيام السبت لأسبوعين." } },
      B: { label: { en: "Say no, politely", ar: "الاعتذار بلطف" },
           fx: { smiles: -2 },
           log: { en: "Auntie Huda said she understood. She looked a little disappointed.", ar: "قالت الخالة هدى إنها تفهم. وبدت خائبة الأمل قليلًا." } },
      C: { needs: 70, label: { en: "One free morning, then 3 coins a morning", ar: "صباح واحد مجانًا، ثم 3 عملات عن كل صباح" },
           fx: { quality: 4, mods: [{ k: "demand", x: 0.85, weeks: 2 }] },
           log: { en: "She thought about it and agreed. Your time has a price now.", ar: "فكّرت قليلًا ثم وافقت. صار لوقتك ثمن." },
           echo: { after: [2, 3], img: "money_bag",
                   title: { en: "Auntie Huda pays, and talks", ar: "الخالة هدى تدفع، وتتحدّث" },
                   text: { en: "Auntie Huda paid 3 coins and told every customer in her shop about your stand.", ar: "دفعت الخالة هدى 3 عملات، وأخبرت كل زبائن دكانها عن كشكك." },
                   fx: { coins: 3, smiles: 4 } } },
      idea: { en: "Your time is worth something. Practice is good, and so is being paid.", ar: "وقتك له قيمة. الخبرة شيء جميل، والأجر أيضًا." },
    },
    {
      id: "g_brother", biz: "all", img: "boy",
      title: { en: "Your little brother wants to help", ar: "أخوك الصغير يريد المساعدة" },
      text: { en: "Ziad is 6. He really, really wants to help. He is also very slow, and he drops things.", ar: "عمر زياد 6 سنوات. يريد المساعدة بشدّة، لكنه بطيء جدًا، ويُسقط الأشياء." },
      A: { label: { en: "Let Ziad help", ar: "السماح لزياد بالمساعدة" },
           fx: { coins: -3, smiles: 4, energy: -3 },
           log: { en: "Ziad dropped two things and gave a customer a high five. Customers loved him.", ar: "أسقط زياد شيئين، وتبادل تحية الكفّ مع أحد الزبائن. وأحبّه الزبائن." },
           echo: { after: [3, 5], img: "boy",
                   title: { en: "Ziad is getting faster", ar: "زياد صار أسرع" },
                   text: { en: "Ziad can count coins up to 20 now. Today he gave the change all by himself.", ar: "صار زياد يعدّ النقود حتى 20. واليوم أعاد الباقي وحده." },
                   fx: { smiles: 3, mods: [{ k: "energyUse", x: 0.75, weeks: 3 }] } } },
      B: { label: { en: "Give him a job at home instead", ar: "مهمة له في البيت بدلًا من ذلك" },
           fx: { coins: 2, energy: -2 },
           log: { en: "The stand ran fast. Ziad drew a sad face and stuck it on your door.", ar: "سار العمل في الكشك بسرعة. ورسم زياد وجهًا حزينًا وألصقه على باب غرفتك." } },
      C: { needs: 70, label: { en: "One small job: saying hello to customers", ar: "مهمة صغيرة واحدة: الترحيب بالزبائن" },
           fx: { smiles: 5, energy: -2 },
           log: { en: "Ziad's only job was to say hello. He took it very seriously.", ar: "كانت مهمة زياد الوحيدة أن يقول: أهلًا. وأخذها بجدية كبيرة." } },
      idea: { en: "Helpers get better when someone teaches them. That takes time at first.", ar: "المساعد يتحسّن عندما يعلّمه أحد. وهذا يحتاج وقتًا في البداية." },
    },
    {
      id: "g_share", biz: "all", img: "heart_hands",
      title: { en: "Malak has no money today", ar: "ملك ليس معها نقود اليوم" },
      text: { en: "Your friend Malak stops by the stand every day and looks. Today she whispers that she has no money at all.", ar: "صديقتك ملك تمرّ على الكشك كل يوم وتنظر. واليوم همست بأنها لا تملك أي نقود." },
      A: { label: { en: "Give her one for free", ar: "إعطاؤها شيئًا مجانًا" },
           fx: { coins: -2, smiles: 2 },
           log: { en: "Malak said thank you 3 times, then stayed to help you tidy up.", ar: "قالت ملك: شكرًا، 3 مرات، ثم بقيت تساعد في الترتيب." },
           echo: { after: [2, 4], img: "sparkles",
                   title: { en: "Malak brings a surprise", ar: "ملك تُحضر مفاجأة" },
                   text: { en: "Malak made a little sign with your stand's name in glitter. People keep stopping to look at it.", ar: "صنعت ملك لافتة صغيرة باسم كشكك بالبريق اللامع. والناس يتوقّفون للنظر إليها." },
                   fx: { smiles: 2, mods: [{ k: "demand", x: 1.12, weeks: 2 }] } } },
      B: { label: { en: "Offer her a small job to earn one", ar: "عرض مهمة صغيرة مقابل هدية" },
           fx: { coins: -2, energy: 2, mods: [{ k: "energyUse", x: 0.85, weeks: 2 }] },
           log: { en: "Malak wiped the table and earned her treat. She looked proud, and offered to help again.", ar: "مسحت ملك الطاولة وكسبت مكافأتها. وبدت فخورة، وعرضت المساعدة مرة أخرى." } },
      idea: { en: "Sharing costs a little. What it gives back is hard to count.", ar: "المشاركة تكلّف قليلًا. لكن ما تعيده يصعب عدّه." },
    },

    // ── Juice stand ──
    {
      id: "j_sour", biz: "juice", img: "lemon",
      title: { en: "A customer says the juice is too sour", ar: "زبون يقول إن العصير حامض جدًا" },
      text: { en: "Uncle Saeed takes one sip and makes a face. \"Too sour!\" he says, loud enough for the whole line to hear.", ar: "أخذ العم سعيد رشفة واحدة وتجهّم وجهه. وقال بصوت سمعه الطابور كله: «حامض جدًا!»" },
      A: { label: { en: "Say sorry and make him a new cup", ar: "الاعتذار وتحضير كوب جديد له" },
           fx: { coins: -1, smiles: 4 },
           log: { en: "He tried the new cup, nodded, and told the line it was fine now.", ar: "جرّب الكوب الجديد، وهزّ رأسه، وقال للطابور: «الآن صار ممتازًا.»" } },
      B: { label: { en: "Keep the recipe: lemonade is meant to be sour", ar: "إبقاء الوصفة: الليمون حامض بطبعه" },
           fx: { smiles: -3 },
           log: { en: "He shrugged and left half the cup. Two people behind him walked away.", ar: "هزّ كتفيه وترك نصف الكوب. ورحل شخصان كانا خلفه." } },
      C: { needs: 70, label: { en: "Ask him to taste 3 cups and pick the best", ar: "دعوته لتذوّق 3 أكواب واختيار الأفضل" },
           fx: { coins: -2, quality: 12, smiles: 3 },
           log: { en: "Uncle Saeed picked the middle one. That's your recipe now, and it's better.", ar: "اختار العم سعيد الكوب الأوسط. صارت هذه وصفتك الآن، وهي أطيب." } },
      idea: { en: "A complaint is free advice. You decide which part to keep.", ar: "الشكوى نصيحة مجانية. ولك أن تأخذ منها ما يفيد." },
    },
    {
      id: "j_fresh", biz: "juice", img: "cup_with_straw",
      title: { en: "Should the sign say \"100% fresh\"?", ar: "هل تقول اللافتة «طازج 100%»؟" },
      text: { en: "This week, lemons ran out, so you mixed fresh lemons with juice from a carton. Your cousin says to write \"100% fresh\" on the sign anyway. \"Nobody will know.\"", ar: "نفد الليمون هذا الأسبوع، فخُلط الليمون الطازج بعصير من علبة. وابن عمّك يقترح كتابة «طازج 100%» على اللافتة رغم ذلك، ويقول: «لن يعرف أحد.»" },
      A: { label: { en: "Write \"100% fresh\"", ar: "كتابة «طازج 100%»" },
           fx: { coins: 4, honest: -1 },
           log: { en: "The sign looked great. A lady said it was the freshest juice around.", ar: "بدت اللافتة رائعة. وقالت سيدة إنه أطزج عصير في الحي." },
           echo: { after: [2, 4], img: "package",
                   title: { en: "Someone saw the cartons", ar: "أحدهم رأى العلب" },
                   text: { en: "A boy saw the empty juice cartons in your bin and told his mum. She came to ask about the sign.", ar: "رأى ولد علب العصير الفارغة في سلّة المهملات وأخبر أمه، فجاءت تسأل عن اللافتة." },
                   fx: { smiles: -8 } } },
      B: { label: { en: "Write the truth on the sign", ar: "كتابة الحقيقة على اللافتة" },
           fx: { coins: -2, honest: 1 },
           log: { en: "The sign said \"fresh lemons + a little carton juice\". Most people bought anyway. One said thanks for being honest.", ar: "كُتب على اللافتة: «ليمون طازج مع قليل من عصير العلب». واشترى أغلب الناس على أي حال. وقال أحدهم: شكرًا على الصراحة." },
           echo: { after: [3, 5], img: "placard",
                   title: { en: "The honest sign", ar: "اللافتة الصادقة" },
                   text: { en: "A mum told the other parents that yours was the only honest sign at the market.", ar: "أخبرت إحدى الأمهات بقية الأهالي أن لافتتك هي الوحيدة الصادقة في السوق." },
                   fx: { smiles: 5 } } },
      idea: { en: "If a sign only works when nobody knows the truth, it's not a good sign.", ar: "إذا كانت اللافتة تنجح فقط لأن أحدًا لا يعرف الحقيقة، فهي ليست لافتة جيدة." },
    },
    {
      id: "j_copy", biz: "juice", img: "shopping_cart", when: { minWeek: 3 },
      title: { en: "Karim opened a juice stand next to yours", ar: "كريم فتح كشك عصير بجوار كشكك" },
      text: { en: "Karim is 14. He copied your sign, your cups, even your price. Now he's 5 steps away, and he's louder than you.", ar: "عمر كريم 14 سنة. نسخ لافتتك وأكوابك، وحتى سعرك. والآن يقف على بعد 5 خطوات، وصوته أعلى." },
      A: { label: { en: "Give a free biscuit with every cup", ar: "بسكويتة مجانية مع كل كوب" },
           fx: { smiles: 3, mods: [{ k: "cost", x: 1.5, weeks: 3 }, { k: "demand", x: 0.95, weeks: 3 }] },
           log: { en: "Your line is longer than his. Each cup costs you more now.", ar: "طابورك أطول من طابوره. لكن كل كوب صار يكلّف أكثر." },
           echo: { after: [2, 4], img: "cookie",
                   title: { en: "Karim gives two biscuits now", ar: "كريم صار يعطي بسكويتتين" },
                   text: { en: "Karim answered with two free biscuits per cup. Now you're both spending more to win the same customers.", ar: "ردّ كريم ببسكويتتين مجانيتين مع كل كوب. والآن ينفق كلاكما أكثر للفوز بالزبائن أنفسهم." },
                   fx: { coins: -4, mods: [{ k: "demand", x: 0.9, weeks: 2 }] } } },
      B: { label: { en: "Make yours better, not cheaper", ar: "تحسين العصير بدل خفض السعر" },
           fx: { quality: 10, energy: -5, mods: [{ k: "demand", x: 0.8, weeks: 3 }] },
           log: { en: "You spent an evening on a new recipe with fresh mint. Karim still has the louder voice.", ar: "قضيت أمسية كاملة على وصفة جديدة بالنعناع الطازج. وما زال صوت كريم أعلى." } },
      C: { needs: 70, label: { en: "Go and talk to him", ar: "الذهاب والتحدّث معه" },
           fx: { energy: -4, smiles: 2, mods: [{ k: "demand", x: 1.1, weeks: 3 }] },
           log: { en: "You agreed: he sells popcorn, you sell juice. Customers buy both now.", ar: "اتفقتما: هو يبيع الفشار، وكشكك يبيع العصير. والزبائن يشترون الاثنين الآن." } },
      idea: { en: "When someone copies you, the question is: what makes you, you?", ar: "عندما ينسخك أحد، يصبح السؤال: ما الذي يميّزك؟" },
    },
    {
      id: "j_rain", biz: "juice", img: "cloud_with_rain", when: { rainNext: true },
      title: { en: "Rain is coming on market day", ar: "المطر قادم في يوم السوق" },
      text: { en: "The forecast says rain next week. On wet days, not many people want cold juice.", ar: "النشرة تقول إن المطر سينزل الأسبوع القادم. وفي الأيام الماطرة قليلون يريدون عصيرًا باردًا." },
      A: { label: { en: "Sell warm mint tea for a week", ar: "بيع شاي النعناع الدافئ لأسبوع" },
           fx: { coins: -4, mods: [{ k: "demand", x: 1.7, weeks: 1 }] },
           log: { en: "You bought tea and mint for 4 coins. Next week, the cups will be warm.", ar: "اشتريت الشاي والنعناع بـ4 عملات. وفي الأسبوع القادم ستكون الأكواب دافئة." } },
      B: { label: { en: "Open for a short time and rest", ar: "فتح الكشك لوقت قصير والراحة" },
           fx: { energy: 12, mods: [{ k: "demand", x: 0.8, weeks: 1 }] },
           log: { en: "You'll open for an hour, then read under a blanket.", ar: "سيُفتح الكشك ساعة واحدة، ثم وقت للقراءة تحت البطانية." } },
      idea: { en: "Nobody can change the weather. What you sell can change.", ar: "لا أحد يغيّر الطقس. لكن ما يُباع يمكن أن يتغيّر." },
    },
    {
      id: "j_lemons", biz: "juice", img: "lemon", when: { minWeek: 3 },
      title: { en: "Lemons cost more this week", ar: "الليمون صار أغلى هذا الأسبوع" },
      text: { en: "The shop raised the price of lemons. Every cup now costs more to make. Your customers don't know that.", ar: "رفع المتجر سعر الليمون. وصار كل كوب يكلّف أكثر. والزبائن لا يعرفون ذلك." },
      A: { label: { en: "Pay more and keep the cups the same", ar: "دفع المزيد وإبقاء الأكواب كما هي" },
           fx: { smiles: 2, mods: [{ k: "cost", x: 2, weeks: 3 }] },
           log: { en: "Same cup, same taste. Each one costs you double for 3 weeks.", ar: "الكوب نفسه والطعم نفسه. لكن كل كوب يكلّف الضعف لمدة 3 أسابيع." } },
      B: { label: { en: "Use a little less lemon", ar: "استخدام ليمون أقل قليلًا" },
           fx: { quality: -10, mods: [{ k: "cost", x: 1.3, weeks: 3 }] },
           log: { en: "Your costs barely went up. The juice tastes a bit more like water.", ar: "التكلفة لم ترتفع إلا قليلًا. لكن العصير صار يشبه الماء أكثر." } },
      idea: { en: "When costs go up, profit goes down, unless something else changes. A price can change too.", ar: "عندما ترتفع التكلفة ينخفض الربح، ما لم يتغيّر شيء آخر. والسعر نفسه يمكن أن يتغيّر." },
    },
    {
      id: "j_cooler", biz: "juice", img: "ice", when: { minCoins: 20 },
      title: { en: "A cooler box would keep the juice cold", ar: "صندوق تبريد يُبقي العصير باردًا" },
      text: { en: "Uncle Saeed is selling his old cooler box for 15 coins. Cold juice tastes better, and nothing goes warm by noon.", ar: "يبيع العم سعيد صندوق التبريد القديم بـ15 عملة. العصير البارد أطيب، ولن يسخن شيء قبل الظهر." },
      A: { label: { en: "Buy the cooler box", ar: "شراء صندوق التبريد" },
           fx: { coins: -15, quality: 15 },
           log: { en: "Your stand has a cooler now. Your coin box is lighter.", ar: "صار في كشكك صندوق تبريد. وصار صندوق النقود أخفّ." },
           echo: { after: [3, 5], img: "ice",
                   title: { en: "The cooler is paying off", ar: "الصندوق بدأ يردّ ثمنه" },
                   text: { en: "On the hottest day, yours was the only cold juice on the street. People queued around the corner.", ar: "في أشدّ الأيام حرًّا، كان عصيرك هو العصير البارد الوحيد في الشارع. وامتدّ الطابور حتى ما بعد الزاوية." },
                   fx: { coins: 10, smiles: 3 } } },
      B: { label: { en: "Keep the coins and buy ice each week", ar: "الاحتفاظ بالنقود وشراء الثلج كل أسبوع" },
           fx: { energy: -3 },
           log: { en: "Carrying ice every morning is heavy, but your coins stay put.", ar: "حمل الثلج كل صباح متعب، لكن النقود بقيت في مكانها." } },
      idea: { en: "Spending coins on something that helps you earn more has a name: investing.", ar: "إنفاق المال على شيء يساعدك على كسب المزيد له اسم: الاستثمار." },
    },

    // ── Drawings & bracelets ──
    {
      id: "a_copy", biz: "art", img: "scissors", when: { minWeek: 3 },
      title: { en: "Someone is selling copies of your bracelets", ar: "أحدهم يبيع نسخًا من أساورك" },
      text: { en: "At the summer club, Omar is selling bracelets that look just like yours, for two coins less.", ar: "في النادي الصيفي، يبيع عمر أساور تشبه أساورك تمامًا، بسعر أقل بعملتين." },
      A: { label: { en: "Make new designs he hasn't seen", ar: "تصميمات جديدة لم يرها بعد" },
           fx: { quality: 12, energy: -6 },
           log: { en: "You stayed up drawing new patterns: stars, waves and tiny moons.", ar: "سهرت لرسم نقوش جديدة: نجوم وأمواج وأقمار صغيرة." },
           echo: { after: [2, 4], img: "sparkles",
                   title: { en: "Your new designs are a hit", ar: "تصميماتك الجديدة نجحت" },
                   text: { en: "Everyone wanted the tiny moons. Omar hasn't figured them out yet.", ar: "الجميع أراد الأقمار الصغيرة. ولم يكتشف عمر طريقتها بعد." },
                   fx: { mods: [{ k: "demand", x: 1.2, weeks: 2 }] } } },
      B: { label: { en: "Lower your price to match", ar: "خفض السعر لمنافسته" },
           fx: { coins: -4, smiles: 2, mods: [{ k: "demand", x: 0.95, weeks: 2 }] },
           log: { en: "Your customers stayed. Your profit on each bracelet got smaller.", ar: "بقي زبائنك. لكن ربح كل سوار صار أصغر." } },
      idea: { en: "It's hard to copy someone who keeps making new things.", ar: "من الصعب نسخ من يواصل صنع أشياء جديدة." },
    },
    {
      id: "a_name", biz: "art", img: "ribbon",
      title: { en: "A customer wants a bracelet with her name", ar: "زبونة تريد سوارًا باسمها" },
      text: { en: "Lina wants a bracelet with LINA in tiny beads. It takes as long as making 4 normal ones. She offers 16 coins.", ar: "تريد لينا سوارًا عليه اسمها LINA بخرز صغير. يحتاج وقتًا يساوي صنع 4 أساور عادية. وتعرض 16 عملة." },
      A: { label: { en: "Say yes and make it", ar: "القبول وصنعه" },
           fx: { coins: 14, energy: -8 },
           log: { en: "It took two evenings. 16 coins in, 2 spent on beads: 14 profit. Lina wore it the next day.", ar: "استغرق أمسيتين. دخلت 16 عملة، وصُرفت 2 على الخرز، والربح 14. ولبسته لينا في اليوم التالي." } },
      B: { label: { en: "Say no and keep making normal ones", ar: "الاعتذار ومواصلة الأساور العادية" },
           fx: { energy: 2, smiles: -1 },
           log: { en: "Lina went to look somewhere else. Your evenings stayed free.", ar: "ذهبت لينا تبحث في مكان آخر. وبقيت أمسياتك حرّة." } },
      idea: { en: "Special orders can pay more. They also take more time, and time is a cost too.", ar: "الطلبات الخاصة قد تدفع أكثر، لكنها تأخذ وقتًا أطول. والوقت تكلفة أيضًا." },
    },
    {
      id: "a_broke", biz: "art", img: "grimacing_face",
      title: { en: "A bracelet you sold broke", ar: "سوار بعته انقطع" },
      text: { en: "Nadia's bracelet snapped the day after she bought it. She doesn't know that a few were made with weak thread.", ar: "انقطع سوار نادية بعد يوم من شرائه. وهي لا تعرف أن بعض الأساور صُنعت بخيط ضعيف." },
      A: { label: { en: "Tell her and fix it for free", ar: "إخبارها وإصلاحه مجانًا" },
           fx: { coins: -2, honest: 1, smiles: 3, quality: 5 },
           log: { en: "You bought strong thread and fixed it the same day. Nadia was surprised.", ar: "اشتريت خيطًا قويًا وأصلحته في اليوم نفسه. وتفاجأت نادية." },
           echo: { after: [3, 5], img: "heart_hands",
                   title: { en: "Nadia came back", ar: "نادية عادت" },
                   text: { en: "Nadia bought two more bracelets for her cousins. \"These ones don't break,\" she told them.", ar: "اشترت نادية سوارين آخرين لبنات عمّها، وقالت لهن: «هذه لا تنقطع.»" },
                   fx: { coins: 8, smiles: 3 } } },
      B: { label: { en: "Say it must have been an accident", ar: "القول إنه حادث عابر" },
           fx: { honest: -1, energy: -2 },
           log: { en: "Nadia shrugged and threw it away. You still have a few with weak thread.", ar: "هزّت نادية كتفيها ورمته. وما زالت بعض الأساور بخيط ضعيف." },
           echo: { after: [2, 4], img: "grimacing_face",
                   title: { en: "More bracelets broke", ar: "انقطعت أساور أخرى" },
                   text: { en: "Two more bracelets with weak thread snapped. Their owners compared them at the summer club.", ar: "انقطع سواران آخران من ذوات الخيط الضعيف. وقارنها أصحابها في النادي الصيفي." },
                   fx: { smiles: -7 } } },
      idea: { en: "Saying \"my mistake\" early is cheaper than saying it late.", ar: "قول «أخطأت» مبكرًا أرخص من قوله متأخرًا." },
    },
    {
      id: "a_fair", biz: "art", img: "framed_picture", when: { minWeek: 2 },
      title: { en: "A table at the summer fair costs 8 coins", ar: "طاولة في معرض الصيف بـ8 عملات" },
      text: { en: "Next week's summer fair will have lots of visitors. A table costs 8 coins, and you'd need lots of pieces to fill it.", ar: "معرض الصيف الأسبوع القادم سيأتيه زوّار كثيرون. الطاولة بـ8 عملات، وملؤها يحتاج قطعًا كثيرة." },
      A: { label: { en: "Rent the table", ar: "استئجار الطاولة" },
           fx: { coins: -8, energy: -4, mods: [{ k: "demand", x: 1.7, weeks: 1 }] },
           log: { en: "The table is booked. Next week, make plenty!", ar: "حُجزت الطاولة. والأسبوع القادم يحتاج كمية كبيرة!" } },
      B: { label: { en: "Skip the fair", ar: "عدم المشاركة في المعرض" },
           fx: { quality: 5, energy: 3 },
           log: { en: "You spent fair day drawing at home. Your next pieces are your best yet.", ar: "قضيت يوم المعرض في الرسم بالبيت. وقطعك القادمة هي الأجمل حتى الآن." } },
      idea: { en: "Paying to be where the customers are can be worth it, if enough of them buy.", ar: "الدفع للوصول إلى حيث يوجد الزبائن قد يستحق، إذا اشترى عدد كافٍ منهم." },
    },
    {
      id: "a_teacher", biz: "art", img: "books", when: { minWeek: 4 },
      title: { en: "Teacher Noura wants 20 bracelets", ar: "المعلّمة نورة تريد 20 سوارًا" },
      text: { en: "She wants them for her class party, at 3 coins each. That's less than your usual price, and they cost two coins each to make.", ar: "تريدها لحفلة صفّها، بـ3 عملات للسوار. هذا أقل من سعرك المعتاد، وصنع السوار الواحد يكلّف عملتين." },
      A: { label: { en: "Accept the big order", ar: "قبول الطلب الكبير" },
           fx: { coins: 20, energy: -12 },
           log: { en: "20 bracelets in 3 evenings. 60 coins in, 40 spent, 20 profit. Your fingers are tired.", ar: "20 سوارًا في 3 أمسيات. دخلت 60 عملة، وصُرفت 40، والربح 20. وأصابعك متعبة." } },
      B: { label: { en: "Offer 3 at your normal price", ar: "عرض 3 أساور بالسعر المعتاد" },
           fx: { coins: 9, energy: -3 },
           log: { en: "She took 3. Less work, fewer coins, and a free evening.", ar: "أخذت 3. عمل أقل، ونقود أقل، وأمسية حرّة." } },
      idea: { en: "Selling lots at a low price can earn more than a few at a high price. Or not. Do the maths first.", ar: "البيع الكثير بسعر منخفض قد يربح أكثر من القليل بسعر غالٍ، وقد لا يربح. الحساب أولًا." },
    },
    {
      id: "a_fav", biz: "art", img: "framed_picture",
      title: { en: "Someone wants your favourite drawing", ar: "أحدهم يريد رسمتك المفضّلة" },
      text: { en: "It's your drawing of Grandpa's garden. It's not for sale, but a man offers 15 coins for it.", ar: "إنها رسمتك لحديقة جدّو. لم تكن للبيع، لكن رجلًا عرض 15 عملة." },
      A: { label: { en: "Sell it", ar: "بيعها" },
           fx: { coins: 15, energy: -4 },
           log: { en: "He framed it the same day. The wall at home looks a bit empty.", ar: "وضعها في إطار في اليوم نفسه. والجدار في البيت يبدو فارغًا قليلًا." } },
      B: { label: { en: "Keep it", ar: "الاحتفاظ بها" },
           fx: { energy: 4 },
           log: { en: "It stays on your wall. You offered to draw him a new one.", ar: "بقيت على جدارك. وعرضت عليه رسم واحدة جديدة." } },
      idea: { en: "Not everything has to be for sale. Knowing what isn't is useful too.", ar: "ليس كل شيء للبيع. ومعرفة ما ليس للبيع مفيدة أيضًا." },
    },

    // ── Bike wash & fix ──
    {
      id: "b_scratch", biz: "bike", img: "wrench",
      title: { en: "You scratched a customer's bike", ar: "خدش في دراجة أحد الزبائن" },
      text: { en: "While fixing Faisal's chain, the wrench slipped and left a small scratch on his new red bike. He hasn't seen it.", ar: "أثناء إصلاح سلسلة دراجة فيصل، انزلق المفتاح وترك خدشًا صغيرًا في دراجته الحمراء الجديدة. ولم يره بعد." },
      A: { label: { en: "Show him and say sorry", ar: "إخباره والاعتذار" },
           fx: { coins: -4, honest: 1, smiles: 2 },
           log: { en: "You didn't charge him for the fix. Faisal said it was fine, really.", ar: "لم يُؤخذ منه أجر الإصلاح. وقال فيصل إن الأمر لا يهم، حقًا." },
           echo: { after: [2, 4], img: "bicycle",
                   title: { en: "Faisal brought his sister's bike", ar: "فيصل أحضر دراجة أخته" },
                   text: { en: "Faisal brought his sister's bike, and his cousin's. \"You're the one who tells the truth,\" he said.", ar: "أحضر فيصل دراجة أخته، ودراجة ابن عمّه، وقال: «كشكك هو الذي يقول الحقيقة.»" },
                   fx: { coins: 6, smiles: 3 } } },
      B: { label: { en: "Say nothing", ar: "السكوت" },
           fx: { honest: -1, coins: 4 },
           log: { en: "Faisal paid and rode off. The scratch went with him.", ar: "دفع فيصل وانطلق بدراجته. وذهب الخدش معه." },
           echo: { after: [2, 5], img: "grimacing_face",
                   title: { en: "Faisal found the scratch", ar: "فيصل وجد الخدش" },
                   text: { en: "Faisal found the scratch and remembered the wrench. He told his friends to wash their bikes at home.", ar: "وجد فيصل الخدش وتذكّر المفتاح. ونصح أصدقاءه بغسل دراجاتهم في البيت." },
                   fx: { smiles: -6 } } },
      idea: { en: "Everyone who works makes mistakes. What happens next is what people remember.", ar: "كل من يعمل يخطئ. وما يحدث بعد الخطأ هو ما يتذكّره الناس." },
    },
    {
      id: "b_rain", biz: "bike", img: "cloud_with_rain", when: { rainNext: true },
      title: { en: "Rain is coming on wash day", ar: "المطر قادم في يوم الغسيل" },
      text: { en: "The forecast says rain next week. Nobody washes a bike in the rain. But after rain, every bike is muddy.", ar: "النشرة تقول إن المطر سينزل الأسبوع القادم. لا أحد يغسل دراجته تحت المطر. لكن بعد المطر تصبح كل الدراجات موحلة." },
      A: { label: { en: "Make a \"mud buster\" poster for after the rain", ar: "ملصق «مطاردة الوحل» لما بعد المطر" },
           fx: { coins: -2, mods: [{ k: "demand", x: 1.7, weeks: 1 }] },
           log: { en: "The poster says: \"Muddy bike? We fix that.\" It's up by the park gate.", ar: "يقول الملصق: «دراجة موحلة؟ الحل عندنا.» وقد عُلّق عند بوابة الحديقة." } },
      B: { label: { en: "Fix flat tyres in the garage instead", ar: "إصلاح الإطارات المثقوبة في المرآب بدلًا من ذلك" },
           fx: { quality: 8, energy: -4, mods: [{ k: "demand", x: 1.2, weeks: 1 }] },
           log: { en: "You learned to patch a tyre. Dry, warm, and useful.", ar: "تعلّمت ترقيع الإطار. مكان جاف ودافئ، وعمل مفيد." } },
      idea: { en: "Nobody can change the weather. What you sell can change.", ar: "لا أحد يغيّر الطقس. لكن ما يُباع يمكن أن يتغيّر." },
    },
    {
      id: "b_tools", biz: "bike", img: "wrench", when: { minCoins: 25 },
      title: { en: "A real tool kit costs 20 coins", ar: "عدّة أدوات حقيقية بـ20 عملة" },
      text: { en: "You've been borrowing Dad's old tools. A proper kit with a pump and tyre levers costs 20 coins.", ar: "كانت أدوات بابا القديمة مستعارة طوال الوقت. وعدّة كاملة فيها منفاخ وأدوات للإطارات بـ20 عملة." },
      A: { label: { en: "Buy the tool kit", ar: "شراء عدّة الأدوات" },
           fx: { coins: -20, quality: 18 },
           log: { en: "Shiny new tools. Every fix is faster now.", ar: "أدوات جديدة لامعة. وصار كل إصلاح أسرع." },
           echo: { after: [3, 5], img: "wrench",
                   title: { en: "The tool kit is paying off", ar: "العدّة بدأت تردّ ثمنها" },
                   text: { en: "With the new pump you fixed 4 flat tyres in one morning. That's 12 coins you couldn't have earned before.", ar: "بالمنفاخ الجديد أصلحت 4 إطارات في صباح واحد. هذه 12 عملة لم يكن كسبها ممكنًا من قبل." },
                   fx: { coins: 12 } } },
      B: { label: { en: "Keep borrowing Dad's tools", ar: "مواصلة استعارة أدوات بابا" },
           fx: { energy: -2 },
           log: { en: "Dad's tools are old but they work. Your coins stay in the box.", ar: "أدوات بابا قديمة لكنها تعمل. والنقود بقيت في الصندوق." } },
      idea: { en: "Spending coins on something that helps you earn more has a name: investing.", ar: "إنفاق المال على شيء يساعدك على كسب المزيد له اسم: الاستثمار." },
    },
    {
      id: "b_brakes", biz: "bike", img: "thinking_face",
      title: { en: "Brakes you've never fixed before", ar: "مكابح خارج خبرتك" },
      text: { en: "Sami's brakes squeak and he wants them fixed today. You've never fixed brakes. He'll pay 6 coins.", ar: "مكابح دراجة سامي تصرّ، ويريد إصلاحها اليوم. لم يسبق لك إصلاح مكابح. وسيدفع 6 عملات." },
      A: { label: { en: "Try it and hope", ar: "المحاولة على أمل النجاح" },
           fx: { coins: 6 },
           log: { en: "The squeak stopped. You're not totally sure why.", ar: "توقّف الصرير. والسبب غير واضح تمامًا." },
           echo: { after: [2, 4], img: "grimacing_face",
                   title: { en: "Sami's brakes are squeaking again", ar: "مكابح سامي تصرّ من جديد" },
                   text: { en: "Sami came back. The brakes squeak louder than before. You gave him his 6 coins back.", ar: "عاد سامي. المكابح تصرّ أعلى من قبل. وأُعيدت له عملاته الـ6." },
                   fx: { coins: -6, smiles: -3 } } },
      B: { label: { en: "Tell him the truth: \"Not yet\"", ar: "قول الحقيقة: «ليس بعد»" },
           fx: { smiles: -1, honest: 1 },
           log: { en: "Sami went to the big bike shop. He said thanks for being honest.", ar: "ذهب سامي إلى محل الدراجات الكبير. وقال: شكرًا على الصراحة." } },
      C: { needs: 70, label: { en: "Ask Grandpa to teach you, fix it tomorrow", ar: "طلب درس من جدّو، والإصلاح غدًا" },
           fx: { coins: 6, quality: 10, energy: -6 },
           log: { en: "Grandpa showed you on his old bike. Sami's brakes are quiet now.", ar: "شرح جدّو الطريقة على دراجته القديمة. ومكابح سامي هادئة الآن." } },
      idea: { en: "\"I don't know yet\" is how learning starts.", ar: "«لا أعرف بعد» هي بداية التعلّم." },
    },
    {
      id: "b_regular", biz: "bike", img: "bell", when: { minWeek: 2 },
      title: { en: "Mr Adel wants a weekly deal", ar: "السيد عادل يريد اتفاقًا أسبوعيًا" },
      text: { en: "He'll bring his bike every week for the next 6 weeks, if you take one coin off each time.", ar: "سيُحضر دراجته كل أسبوع خلال 6 أسابيع قادمة، بشرط خصم عملة واحدة في كل مرة." },
      A: { label: { en: "Accept the weekly deal", ar: "قبول الاتفاق الأسبوعي" },
           fx: { smiles: 1, mods: [{ k: "bonus", x: 2, weeks: 6 }, { k: "energyUse", x: 1.1, weeks: 6 }] },
           log: { en: "Every Saturday, Mr Adel's bike will be waiting. Steady coins, a bit less each time, and one more job every week.", ar: "كل سبت ستكون دراجة السيد عادل في الانتظار. نقود ثابتة، أقل قليلًا كل مرة، ومهمة إضافية كل أسبوع." } },
      B: { label: { en: "Keep your normal price", ar: "إبقاء السعر المعتاد" },
           fx: { coins: 4, smiles: -1 },
           log: { en: "He paid 4 coins for today's wash. He said he'd come \"sometimes\".", ar: "دفع 4 عملات لغسلة اليوم. وقال إنه سيأتي «أحيانًا»." } },
      idea: { en: "A regular customer is worth a small discount. Steady coins help you plan.", ar: "الزبون الدائم يستحق خصمًا صغيرًا. والنقود الثابتة تساعد على التخطيط." },
    },
    {
      id: "b_friend", biz: "bike", img: "package",
      title: { en: "Your best friend needs help on wash day", ar: "أعزّ أصدقائك يحتاج المساعدة يوم الغسيل" },
      text: { en: "Omar's family is moving house next Saturday and he asked you to help carry boxes. Saturday is your busiest wash day.", ar: "عائلة عمر تنتقل إلى بيت جديد يوم السبت القادم، وطلب المساعدة في حمل الصناديق. والسبت أكثر أيام الغسيل زحامًا." },
      A: { label: { en: "Help Omar move", ar: "مساعدة عمر في الانتقال" },
           fx: { energy: -5, mods: [{ k: "demand", x: 0.5, weeks: 1 }] },
           log: { en: "You carried 14 boxes. Omar's mum made the best sandwiches.", ar: "حملت 14 صندوقًا. وأعدّت أم عمر أطيب الشطائر." },
           echo: { after: [3, 5], img: "handshake",
                   title: { en: "Omar returns the favour", ar: "عمر يردّ الجميل" },
                   text: { en: "Omar spent a whole Saturday at your stand, handing out towels and calling customers.", ar: "قضى عمر يوم سبت كاملًا في كشكك، يوزّع المناشف وينادي على الزبائن." },
                   fx: { mods: [{ k: "energyUse", x: 0.5, weeks: 1 }, { k: "demand", x: 1.2, weeks: 1 }] } } },
      B: { label: { en: "Keep the stand open", ar: "إبقاء الكشك مفتوحًا" },
           fx: { energy: -4, smiles: 1 },
           log: { en: "Saturday was busy. You kept thinking about Omar's boxes.", ar: "كان السبت مزدحمًا. وبقيت صناديق عمر في البال." } },
      idea: { en: "Friends and work both need your time. Neither can have all of it.", ar: "الأصدقاء والعمل كلاهما يحتاج وقتك. ولا يأخذه أحدهما كله." },
    },

    // ── Cakes & cookies ──
    {
      id: "c_toomany", biz: "cakes", img: "cupcake",
      title: { en: "You made too many cakes", ar: "كيكات أكثر من اللازم" },
      text: { en: "Mum's friends ordered and then cancelled. There are 8 extra cakes on the kitchen table, and they won't stay fresh for long.", ar: "طلبت صديقات ماما ثم ألغين الطلب. وعلى طاولة المطبخ 8 كيكات زائدة، ولن تبقى طازجة طويلًا." },
      A: { label: { en: "Sell them tomorrow at half price", ar: "بيعها غدًا بنصف السعر" },
           fx: { coins: 10, energy: -5, smiles: -1 },
           log: { en: "Yesterday's cakes, half price. They sold, and a few people noticed they weren't fresh.", ar: "كيكات الأمس بنصف السعر. بيعت، ولاحظ بعض الناس أنها ليست طازجة." } },
      B: { label: { en: "Give them to the neighbours", ar: "إهداؤها للجيران" },
           fx: { smiles: 5 },
           log: { en: "The whole building had cake tonight. The plates came back with thank-you notes.", ar: "أكل كل من في العمارة كيكًا الليلة. وعادت الأطباق ومعها بطاقات شكر." },
           echo: { after: [2, 4], img: "birthday_cake",
                   title: { en: "The neighbours ordered", ar: "الجيران طلبوا" },
                   text: { en: "Auntie Huda liked the cake so much that she ordered 6 for her daughter's party.", ar: "أعجب الكيك الخالة هدى كثيرًا فطلبت 6 كيكات لحفلة ابنتها." },
                   fx: { coins: 12 } } },
      C: { needs: 70, label: { en: "Turn them into cake pops and sell them", ar: "تحويلها إلى كرات كيك وبيعها" },
           fx: { coins: 14, energy: -8, quality: 4 },
           log: { en: "Crumbs, a little chocolate, and sticks. The cake pops sold out in an hour.", ar: "فتات وقليل من الشوكولاتة وأعواد. ونفدت كرات الكيك في ساعة." } },
      idea: { en: "Extras are coins already spent. Plan what to do with them, or make fewer.", ar: "الزيادة نقود صُرفت بالفعل. والحل خطة لها، أو صنع كمية أقل." },
    },
    {
      id: "c_burnt", biz: "cakes", img: "cookie",
      title: { en: "One tray got a little burnt", ar: "صينية احترقت قليلًا" },
      text: { en: "The bottoms of 6 cookies are dark. They still taste okay. Sort of.", ar: "قاعدة 6 قطع من الكوكيز صارت داكنة. طعمها مقبول، تقريبًا." },
      A: { label: { en: "Sell them cheap as \"extra crispy\"", ar: "بيعها رخيصة باسم «مقرمشة جدًا»" },
           fx: { coins: 4, honest: 1, smiles: 1 },
           log: { en: "The sign said \"extra crispy, half price\". A grandpa bought all 6 for his tea.", ar: "قالت اللافتة: «مقرمشة جدًا، بنصف السعر». واشترى جدٌّ لطيف القطع الـ6 كلها ليأكلها مع الشاي." } },
      B: { label: { en: "Throw them away", ar: "التخلّص منها" },
           fx: { coins: -2, quality: 6 },
           log: { en: "Only perfect cookies on your table. Those 6 cost you, though.", ar: "لا شيء على طاولتك إلا الكوكيز المثالية. لكن تلك القطع الـ6 كلّفتك." } },
      idea: { en: "Being clear about what you sell lets customers decide for themselves.", ar: "الوضوح فيما يُباع يترك القرار للزبائن." },
    },
    {
      id: "c_nuts", biz: "cakes", img: "peanuts",
      title: { en: "A customer asks: any nuts?", ar: "زبونة تسأل: هل فيه مكسّرات؟" },
      text: { en: "Mona's little boy can't eat nuts. You're not sure: you used Mum's flour mix and didn't read the bag.", ar: "ابن منى الصغير لا يستطيع أكل المكسّرات. والجواب غير مؤكد: استُخدم خليط دقيق ماما، ولم تُقرأ العبوة." },
      A: { label: { en: "Say \"I'm not sure\" and don't sell it", ar: "قول الحقيقة: «غير مؤكد»، وعدم البيع" },
           fx: { coins: -3, honest: 1, smiles: 2 },
           log: { en: "Mona thanked you and bought juice next door instead. You read the bag: \"may contain nuts\".", ar: "شكرتك منى واشترت عصيرًا من الكشك المجاور. وبعدها قُرئت العبوة: «قد يحتوي على مكسّرات»." },
           echo: { after: [2, 4], img: "cupcake",
                   title: { en: "Mona came back", ar: "منى عادت" },
                   text: { en: "Mona asked for a nut-free batch just for her son, made with flour you checked. She paid extra.", ar: "طلبت منى دفعة خالية من المكسّرات لابنها، بدقيق مضمون. ودفعت مبلغًا إضافيًا." },
                   fx: { coins: 8, smiles: 4 } } },
      B: { label: { en: "Say \"No nuts, I think\"", ar: "قول: «لا مكسّرات على الأغلب»" },
           fx: { coins: 3, honest: -1 },
           log: { en: "Mona bought two. That evening you read the bag: \"may contain nuts\".", ar: "اشترت منى قطعتين. وفي المساء قُرئت العبوة: «قد يحتوي على مكسّرات»." },
           echo: { after: [2, 3], img: "thinking_face",
                   title: { en: "Mona read the label", ar: "منى قرأت الملصق" },
                   text: { en: "Mona checked with Mum before her son took a bite, so he was fine. She was kind about it, but she buys somewhere else now.", ar: "سألت منى ماما قبل أن يأكل ابنها شيئًا، فكان بخير. وكانت لطيفة في كلامها، لكنها صارت تشتري من مكان آخر." },
                   fx: { smiles: -6 } } },
      idea: { en: "When you're not sure, \"I don't know\" is the safe answer.", ar: "عند الشك، «لا أعرف» هو الجواب الآمن." },
    },
    {
      id: "c_party", biz: "cakes", img: "birthday_cake", when: { minWeek: 2 },
      title: { en: "A big birthday order by Thursday", ar: "طلب كبير لعيد ميلاد قبل الخميس" },
      text: { en: "Mrs Rana wants 20 cupcakes for her son's birthday. She'll pay 60 coins. Supplies cost 40, and you'd bake two evenings after homework.", ar: "تريد السيدة رنا 20 كب كيك لعيد ميلاد ابنها، وستدفع 60 عملة. المستلزمات بـ40، والخبز يحتاج أمسيتين بعد الواجبات." },
      A: { label: { en: "Say yes and stay up late", ar: "القبول والسهر" },
           fx: { coins: 20, energy: -15 },
           log: { en: "20 cupcakes, two late nights, 20 coins of profit. You yawned all through breakfast.", ar: "20 كب كيك، وليلتان من السهر، و20 عملة ربحًا. وتثاءبت طوال الفطور." },
           echo: { after: [2, 4], img: "partying_face",
                   title: { en: "Party guests want cupcakes", ar: "ضيوف الحفلة يريدون كب كيك" },
                   text: { en: "Some of the party guests asked their parents where the cupcakes came from.", ar: "سأل بعض ضيوف الحفلة أهاليهم من أين جاء الكب كيك." },
                   fx: { mods: [{ k: "demand", x: 1.2, weeks: 2 }] } } },
      B: { label: { en: "Say no: it's too much", ar: "الاعتذار: الطلب كبير جدًا" },
           fx: { energy: 3, smiles: -1 },
           log: { en: "Mrs Rana bought a cake from the bakery. You slept well.", ar: "اشترت السيدة رنا كعكة من المخبز. ونمت جيدًا." } },
      C: { needs: 70, label: { en: "Make 12, and ask Mum to help", ar: "صنع 12 فقط، وطلب مساعدة ماما" },
           fx: { coins: 12, energy: -6, smiles: 2 },
           log: { en: "Mrs Rana was happy with 12. Baking with Mum was the best part.", ar: "رضيت السيدة رنا بـ12. وكان الخبز مع ماما أجمل جزء." } },
      idea: { en: "A big order is great until it costs your sleep. Count the energy, not just the coins.", ar: "الطلب الكبير رائع ما لم يأخذ النوم. والطاقة تُحسب مثل النقود." },
    },
    {
      id: "c_flour", biz: "cakes", img: "woman", when: { minWeek: 3 },
      title: { en: "Mum says the flour isn't free", ar: "ماما تقول إن الدقيق ليس مجانيًا" },
      text: { en: "Mum's flour and sugar are almost gone. \"Your cakes have been using my things,\" she says, smiling. \"What shall we do about it?\"", ar: "دقيق ماما وسكّرها أوشكا على النفاد. قالت مبتسمة: «كيكاتك تستخدم أغراضي. ماذا نفعل؟»" },
      A: { label: { en: "Pay Mum 6 coins for what you used", ar: "دفع 6 عملات لماما ثمنًا لما استُخدم" },
           fx: { coins: -6, energy: 3 },
           log: { en: "Mum put the coins in a jar marked \"oven\". Your profit got smaller, and more real.", ar: "وضعت ماما العملات في برطمان مكتوب عليه «الفرن». صار الربح أصغر، وأصدق." } },
      B: { label: { en: "Buy your own supplies from now on", ar: "شراء المستلزمات من نقودك من الآن" },
           fx: { mods: [{ k: "cost", x: 1.25, weeks: 4 }] },
           log: { en: "Every bag of flour comes out of your coins now. Each cake costs a bit more to make.", ar: "صار كل كيس دقيق يُدفع من نقودك. وكل كيكة تكلّف أكثر قليلًا." } },
      idea: { en: "Hidden costs are still costs. Profit is what's left after paying for everything.", ar: "التكاليف المخفية تكاليف أيضًا. والربح هو ما يبقى بعد دفع كل شيء." },
    },
    {
      id: "c_butter", biz: "cakes", img: "shopping_cart", when: { minWeek: 2 },
      title: { en: "Cheaper butter at the corner shop", ar: "زبدة أرخص في دكان الزاوية" },
      text: { en: "The corner shop has cheaper butter. It would make every cake cheaper to bake, but the cakes taste a bit flat.", ar: "في دكان الزاوية زبدة أرخص. ستجعل كل كيكة أرخص في الخَبز، لكن طعمها سيصبح باهتًا قليلًا." },
      A: { label: { en: "Switch to the cheaper butter", ar: "التحوّل إلى الزبدة الأرخص" },
           fx: { quality: -12, mods: [{ k: "cost", x: 0.6, weeks: 4 }] },
           log: { en: "Your costs dropped. The cakes look the same.", ar: "انخفضت التكلفة. والكيكات تبدو كما هي." } },
      B: { label: { en: "Keep the good butter", ar: "الإبقاء على الزبدة الجيدة" },
           fx: { quality: 4 },
           log: { en: "Same cost, same taste. Your cakes stay the best on the street.", ar: "التكلفة نفسها والطعم نفسه. وكيكاتك تبقى الأطيب في الشارع." } },
      idea: { en: "Cheaper supplies raise profit only if customers keep coming.", ar: "المستلزمات الأرخص ترفع الربح فقط إذا استمرّ الزبائن في المجيء." },
    },
  ],
};

if (typeof module !== "undefined") module.exports = LITTLE;
