// تينبرونور · Teenpreneur: all game text and numbers.
//
// Plain data, English and Arabic side by side, so it can be reviewed and
// extended without touching game.js. Rules for writers:
//   - The player is never "he" or "she". English says "you". Arabic avoids
//     second-person present tense and imperatives (they are gendered): use
//     past tense (بعت، اخترت), verbal nouns for option labels (رفض العرض),
//     unvocalised suffixes (عملك، زبائنك) and "هيا نـ..." for buttons.
//   - Every number in the English must appear, identically, in the Arabic.
//   - Coins are a generic currency: "coins" / "عملة". No real brands, no loans, no gambling.
//   - fx keys: coins, energy, rep, quality, grades (0-100 meters), honest (+1/-1),
//     mods: [{ k, x, weeks }] where k is demand | cost | share | energyUse | bonus.
//     Mods start with the NEXT work week (dilemmas come after the week's work).
//   - Echo after: [min, max] weeks later. The game adds "week N" itself.
//   - C (the third door) needs Energy >= needs (70).
//   - when: { minWeek, minCoins, examNext, quietNext } (all optional).

var TEEN = {

  // ───────────────────────── Side hustles ─────────────────────────
  // cost = coins to prepare one unit. prices = [low, fair, premium].
  // base = customers in a normal week at a fair price.
  // spoils = unused units are lost (true) or kept for next week (false).
  // cal = demand in each kind of week.
  businesses: {
    tutor: {
      img: "books", cost: 2, prices: [8, 12, 18], base: 4.5, spoils: true,
      cal: { normal: 1, busy: 0.8, exams: 1.6, quiet: 1 },
      name: { en: "Tutoring younger kids", ar: "دروس للأصغر سنًّا" },
      item: { en: "lesson slots", ar: "مواعيد دروس" },
      tag: { en: "Maths and English help. Exam season is your rush.", ar: "مساعدة في الرياضيات والإنجليزية. وموسم الامتحانات هو موسمك." },
    },
    tech: {
      img: "mobile_phone", cost: 3, prices: [10, 15, 24], base: 4, spoils: true,
      cal: { normal: 1, busy: 1.2, exams: 0.8, quiet: 1 },
      name: { en: "Phone & laptop help", ar: "مساعدة في الهواتف واللابتوب" },
      item: { en: "help slots", ar: "مواعيد مساعدة" },
      tag: { en: "Setups, cleanups and small fixes for neighbours.", ar: "إعداد وتنظيف وإصلاحات صغيرة للجيران." },
    },
    design: {
      img: "artist_palette", cost: 2, prices: [14, 20, 30], base: 2.55, spoils: false,
      cal: { normal: 1, busy: 1.4, exams: 0.8, quiet: 0.8 },
      name: { en: "Design for local shops", ar: "تصميم للمحلات القريبة" },
      item: { en: "post packs", ar: "باقات منشورات" },
      tag: { en: "Menus, posters and social posts. Ready packs keep.", ar: "قوائم وملصقات ومنشورات. والباقات الجاهزة لا تضيع." },
    },
    bake: {
      img: "cupcake", cost: 4, prices: [7, 10, 15], base: 8.6, spoils: true,
      cal: { normal: 1, busy: 1.4, exams: 0.9, quiet: 0.8 },
      name: { en: "Baking & selling", ar: "خَبز وبيع" },
      item: { en: "boxes", ar: "علب" },
      tag: { en: "Brownies and cookies. Busy weeks sell out, leftovers go stale.", ar: "براونيز وكوكيز. تنفد في أسابيع الزحمة، والبقايا لا تدوم." },
    },
    resell: {
      img: "shopping_bags", cost: 5, prices: [10, 14, 20], base: 5, spoils: false,
      cal: { normal: 1, busy: 1.3, exams: 0.8, quiet: 0.9 },
      name: { en: "Thrift & resell", ar: "شراء المستعمل وإعادة بيعه" },
      item: { en: "items", ar: "قطع" },
      tag: { en: "Find good things cheap, clean them up, sell them on.", ar: "أشياء جيدة بسعر قليل، تُنظَّف ثم تُباع من جديد." },
    },
    code: {
      img: "laptop", cost: 5, prices: [25, 40, 60], base: 1.3, spoils: false,
      cal: { normal: 1, busy: 1.1, exams: 0.9, quiet: 1.1 },
      name: { en: "Small coding jobs", ar: "مشاريع برمجة صغيرة" },
      item: { en: "project kits", ar: "قوالب مشاريع" },
      tag: { en: "Simple websites for clubs and shops. Few clients, big jobs.", ar: "مواقع بسيطة للأندية والمحلات. عملاء قليلون، ومشاريع كبيرة." },
    },
  },

  // ───────────────────────── Savings goals ─────────────────────────
  goals: [
    { id: "phone", img: "mobile_phone", coins: 1000, name: { en: "A better phone", ar: "هاتف أفضل" } },
    { id: "course", img: "graduation_cap", coins: 1700, name: { en: "A summer course", ar: "دورة صيفية" } },
    { id: "laptop", img: "laptop", coins: 2300, name: { en: "A laptop", ar: "لابتوب" } },
    { id: "uni", img: "classical", coins: 2600, name: { en: "A university fund", ar: "صندوق للجامعة" } },
  ],

  avatars: ["girl", "boy", "woman_technologist", "man_technologist"],

  // What kind of week it is. Exam seasons are fixed; the rest is random.
  calendar: {
    normal: { img: "calendar", en: "A normal week", ar: "أسبوع عادي" },
    busy: { img: "party_popper", en: "Holiday rush", ar: "زحمة العطلة" },
    exams: { img: "memo", en: "Exam season", ar: "موسم الامتحانات" },
    quiet: { img: "cloud", en: "A quiet week", ar: "أسبوع هادئ" },
  },

  prices: [
    { en: "Low", ar: "منخفض" },
    { en: "Fair", ar: "معتدل" },
    { en: "Premium", ar: "مرتفع" },
  ],

  activities: {
    promote: { img: "placard", en: "Promote", ar: "ترويج", hint: { en: "More customers", ar: "زبائن أكثر" } },
    learn: { img: "brain", en: "Learn a skill", ar: "تعلّم مهارة", hint: { en: "Better quality", ar: "جودة أعلى" } },
    study: { img: "books", en: "Study", ar: "مذاكرة", hint: { en: "Grades up", ar: "درجات أعلى" } },
    rest: { img: "person_in_lotus_position", en: "Rest", ar: "راحة", hint: { en: "More energy", ar: "طاقة أكثر" } },
  },

  // ───────────── Nour's notes from the game itself (collected) ─────────────
  ideas: {
    profit: { img: "coin", en: "Profit is what came in minus what went out. Revenue alone tells you nothing.", ar: "الربح هو ما دخل ناقص ما خرج. والإيراد وحده لا يقول شيئًا." },
    waste: { img: "grimacing_face", en: "An empty slot or a stale box is money already spent. Prepare closer to real demand.", ar: "الموعد الفارغ أو العلبة البائتة مال صُرف بالفعل. والأفضل التحضير على قدر الطلب الحقيقي." },
    soldout: { img: "package", en: "Selling out feels great, but every customer you turn away might not come back.", ar: "نفاد الكمية شعور رائع، لكن كل زبون رجع بلا شيء قد لا يعود." },
    stock: { img: "package", en: "Stock that keeps is money waiting on a shelf. It still counts as spent.", ar: "البضاعة التي لا تفسد مال ينتظر على الرف. ويُحسب مصروفًا رغم ذلك." },
    tired: { img: "yawning_face", en: "Tired people make expensive mistakes. Sleep is part of the business plan.", ar: "التعب يصنع أخطاء مكلفة. والنوم جزء من خطة العمل." },
    grades: { img: "books", en: "School is the main job right now. The hustle is the side.", ar: "الدراسة هي العمل الأساسي الآن. والمشروع هو الجانبي." },
    promote: { img: "placard", en: "Nobody buys from a business they've never heard of.", ar: "لا أحد يشتري من مشروع لم يسمع به." },
    quality: { img: "glowing_star", en: "Good work brings repeat customers, and repeat customers bring their friends.", ar: "العمل الجيد يعيد الزبائن، والزبائن العائدون يُحضرون أصدقاءهم." },
    premium: { img: "money_bag", en: "A premium price means fewer customers. Sometimes that's still more profit, and less work.", ar: "السعر المرتفع يعني زبائن أقل. وأحيانًا يبقى الربح أكبر، والتعب أقل." },
    saving: { img: "pig_face", en: "Every coin not spent today moves the goal one step closer.", ar: "كل عملة لا تُصرف اليوم تقرّب الهدف خطوة." },
    exams: { img: "memo", en: "Exam seasons come every term. A smart plan sees them coming.", ar: "موسم الامتحانات يأتي كل فصل. والخطة الذكية تراه قبل أن يأتي." },
    reputation: { img: "speech_balloon", en: "Reputation is what people say about you when you're not in the room.", ar: "السمعة هي ما يقوله الناس عنك في غيابك." },
  },

  // ───────────────────────── Interface text ─────────────────────────
  ui: {
    title: { en: "Teenpreneur", ar: "تينبرونور" },
    subtitle: { en: "One school year. One side hustle. Aunt Nour has notes.", ar: "عام دراسي واحد. مشروع جانبي واحد. وخالتك نور عندها ملاحظات." },
    newGame: { en: "New school year", ar: "عام دراسي جديد" },
    resume: { en: "Continue", ar: "متابعة" },
    howTo: { en: "How to play", ar: "طريقة اللعب" },
    parents: { en: "For parents", ar: "للأهل" },
    stickers: { en: "Notebook", ar: "دفتر الأفكار" },
    langBtn: { en: "العربية", ar: "English" },
    theme: { en: "Light or dark", ar: "فاتح أو داكن" },
    back: { en: "Back", ar: "رجوع" },
    next: { en: "Next", ar: "التالي" },
    ok: { en: "Got it", ar: "تمام" },
    home: { en: "Home", ar: "الرئيسية" },

    setupTitle: { en: "Your side hustle", ar: "مشروعك الجانبي" },
    nameQ: { en: "Your first name", ar: "اسمك الأول" },
    namePh: { en: "Type your name", ar: "الاسم هنا" },
    nameNote: { en: "Your name stays on this device. Nothing is sent anywhere.", ar: "الاسم يبقى على هذا الجهاز. ولا يُرسل أي شيء إلى أي مكان." },
    avatarQ: { en: "Pick your picture", ar: "صورتك في اللعبة" },
    bizQ: { en: "Pick a side hustle", ar: "نوع المشروع" },
    goalQ: { en: "What are you saving for?", ar: "هدف الادّخار" },
    start: { en: "Start the year", ar: "هيا نبدأ العام" },
    needName: { en: "Type your name first", ar: "الاسم أولًا من فضلك" },

    coins: { en: "Coins", ar: "نقود" },
    energy: { en: "Energy", ar: "طاقة" },
    rep: { en: "Rep", ar: "سمعة" },
    grades: { en: "Grades", ar: "درجات" },
    week: { en: "Week {n} of 30", ar: "الأسبوع {n} من 30" },
    goal: { en: "Goal", ar: "الهدف" },

    planTitle: { en: "Plan your week", ar: "خطة الأسبوع" },
    forecast: { en: "This week", ar: "هذا الأسبوع" },
    nextWeek: { en: "Next week", ar: "الأسبوع القادم" },
    priceQ: { en: "Your price", ar: "السعر" },
    makeQ: { en: "How many to prepare?", ar: "كم نحضّر؟" },
    makeCost: { en: "Costs {n} coins", ar: "التكلفة بالعملات: {n}" },
    inStock: { en: "+{n} left from last week", ar: "+{n} من الأسبوع الماضي" },
    guess: { en: "Nour estimates about {n} customers", ar: "تقدير نور لعدد الزبائن: {n} تقريبًا" },
    tooPoor: { en: "Not enough coins for more", ar: "النقود لا تكفي لأكثر من ذلك" },
    activityQ: { en: "Your one extra thing this week", ar: "نشاط الأسبوع" },
    open: { en: "Start the week", ar: "هيا نبدأ الأسبوع" },
    quality: { en: "Quality", ar: "الجودة" },
    gradesWarn: { en: "Grades are slipping. Below 40, your parents pause the hustle.", ar: "الدرجات تتراجع. وتحت 40 يوقف الأهل المشروع مؤقتًا." },
    examWarn: { en: "Exam season: any week without studying costs more grades.", ar: "موسم الامتحانات: كل أسبوع بلا مذاكرة يكلّف درجات أكثر." },
    sleepyWarn: { en: "You're running on empty. Mistakes get more likely.", ar: "الطاقة شبه فارغة. والأخطاء صارت أقرب." },

    sellTitle: { en: "Work week", ar: "أسبوع العمل" },
    skip: { en: "Skip", ar: "هيا نتخطّى" },
    customersCame: { en: "{n} customers came", ar: "عدد الزبائن: {n}" },

    resultsTitle: { en: "How did the week go?", ar: "كيف كان الأسبوع؟" },
    sold: { en: "Sold", ar: "المبيع" },
    coinsIn: { en: "Coins in", ar: "نقود دخلت" },
    coinsSpent: { en: "Coins spent", ar: "نقود صُرفت" },
    profit: { en: "Profit", ar: "الربح" },
    wasted: { en: "Unused and lost", ar: "لم يُستخدم وضاع" },
    kept: { en: "Kept for next week", ar: "محفوظ للأسبوع القادم" },
    partnerCut: { en: "Partner's share", ar: "حصة الشريك" },
    bonus: { en: "Regular client", ar: "عميل دائم" },
    mistake: { en: "Tired mistake", ar: "خطأ بسبب التعب" },
    soldOut: { en: "Sold out! {n} customers left with nothing.", ar: "نفدت الكمية! رحل {n} من الزبائن بلا شيء." },
    profitSum: { en: "{a} in − {b} spent = {c}", ar: "{a} دخلت − {b} صُرفت = {c}" },
    treatQ: { en: "Spend some on yourself?", ar: "شيء لك ببعض النقود؟" },
    treatYes: { en: "Snacks and a film with friends: 8 coins, +8 energy", ar: "وجبات خفيفة وفيلم مع الأصدقاء: 8 عملات، +8 طاقة" },
    treatBig: { en: "New headphones: 40 coins, +12 energy", ar: "سماعات جديدة: 40 عملة، +12 طاقة" },
    treatNo: { en: "No, save it", ar: "لا، للادّخار" },

    ideaTitle: { en: "Nour's note", ar: "ملاحظة نور" },
    newSticker: { en: "New note!", ar: "فكرة جديدة!" },
    locked: { en: "Needs {n} energy", ar: "يلزم {n} طاقة" },
    thirdDoor: { en: "The smart move", ar: "الخطوة الذكية" },
    echoFrom: { en: "This is because of what you did in week {n}.", ar: "هذا بسبب ما حدث في الأسبوع {n}." },

    closedTitle: { en: "The hustle is paused this week", ar: "المشروع متوقف هذا الأسبوع" },
    closedMum: { en: "Mum looked at the grades and sat down. \"Below 40. This week is for school only. The business will still be there next week.\"", ar: "نظرت ماما إلى الدرجات وجلست وقالت: «تحت 40. هذا الأسبوع للدراسة فقط. والمشروع سيبقى في مكانه الأسبوع القادم.»" },
    closedDad: { en: "Dad closed the laptop gently. \"Below 40. One week of school only, then we talk about the business again.\"", ar: "أغلق بابا اللابتوب بهدوء وقال: «تحت 40. أسبوع للدراسة فقط، ثم نعود للحديث عن المشروع.»" },

    rescueTitle: { en: "Aunt Nour has a job", ar: "خالتك نور عندها عمل" },
    rescueText: { en: "Your coins ran out. Aunt Nour pays you 30 coins to help at her office for a weekend. A fresh start.", ar: "نفدت النقود. دفعت خالتك نور 30 عملة مقابل المساعدة في مكتبها عطلة أسبوع. بداية جديدة." },

    examTitle: { en: "Term {n} exam results", ar: "نتيجة امتحانات الفصل {n}" },
    examGreat: { en: "Grades: {n}. Your parents are proud, and word gets around that you're the one to ask.", ar: "الدرجات: {n}. الأهل فخورون، وصار الجميع يعرف أنك الشخص الذي يُسأل." },
    examOk: { en: "Grades: {n}. You passed, nothing more. Nour says the next term is a fresh page.", ar: "الدرجات: {n}. نجاح لا أكثر. ونور تقول إن الفصل القادم صفحة جديدة." },
    examLow: { en: "Grades: {n}. That's below 55, so your parents pause the business for this week. Time to catch up.", ar: "الدرجات: {n}. هذا أقل من 55، فأوقف الأهل المشروع هذا الأسبوع. وقت التعويض." },
    examLowFinal: { en: "Grades: {n}. A hard year at school. Next year, the hustle can wait during exams.", ar: "الدرجات: {n}. عام صعب في الدراسة. والعام القادم يمكن للمشروع أن ينتظر وقت الامتحانات." },

    goalHit: { en: "You reached your goal!", ar: "وصلت إلى الهدف!" },
    endTitle: { en: "The school year is over", ar: "انتهى العام الدراسي" },
    endWin: { en: "You saved {a} coins. {b} is yours!", ar: "ادّخرت {a} من العملات. و{b} لك الآن!" },
    endNotYet: { en: "You saved {a} of {b} coins. That's {c}% of the way.", ar: "ادّخرت {a} من العملات من أصل {b}. هذا {c}% من الطريق." },
    endMentor: { en: "Nour says", ar: "نور تقول" },
    report: { en: "Year report", ar: "تقرير العام" },
    skillMoney: { en: "Money", ar: "المال" },
    skillCustomers: { en: "Reputation", ar: "السمعة" },
    skillBalance: { en: "Balance", ar: "التوازن" },
    skillSchool: { en: "School", ar: "الدراسة" },
    skillHonesty: { en: "Integrity", ar: "النزاهة" },
    again: { en: "Another school year", ar: "عام دراسي آخر" },
    totalProfit: { en: "Total profit", ar: "مجموع الربح" },
    weeksStudied: { en: "Weeks of study", ar: "أسابيع المذاكرة" },
    finalGrades: { en: "Final grades", ar: "الدرجات النهائية" },
    stickerCount: { en: "{a} of {b} notes", ar: "الأفكار: {a} من {b}" },
    stickerEmpty: { en: "Play a school year to collect Nour's notes.", ar: "كل عام دراسي يضيف أفكارًا جديدة من نور." },

    credit: { en: "Pictures: handmade felt art made for these games. Fonts: Manrope and Readex Pro (OFL).", ar: "الصور: فن يدوي صُنع لهذه الألعاب. الخطوط: Manrope و Readex Pro (رخصة OFL)." },
    resetQ: { en: "Start a new school year? This one will be lost.", ar: "بدء عام دراسي جديد؟ سيضيع هذا العام." },
  },

  // Nour's end-of-year words. One line per skill, chosen by score.
  endLines: {
    win: { en: "You set a real goal and reached it while going to school. Most adults would struggle with that.", ar: "وضعت هدفًا حقيقيًا ووصلت إليه مع الدراسة. وهذا صعب على كثير من الكبار." },
    notYet: { en: "Not this year, and that's fine. You now know things most people learn at 25.", ar: "لم يكتمل هذا العام، ولا بأس. صار عندك ما يتعلّمه أغلب الناس في سن 25." },
    moneyLow: { en: "Watch what goes unused. Prepare close to my estimate, not to your hopes.", ar: "الانتباه لما يضيع مهم. التحضير يكون قريبًا من تقديري، لا من الأمنيات." },
    moneyHigh: { en: "You knew your numbers. That alone puts you ahead.", ar: "كانت أرقامك واضحة. وهذا وحده يضعك في المقدمة." },
    customersLow: { en: "Reputation is slow to build. Fair prices and good work, every week.", ar: "السمعة تُبنى ببطء. سعر عادل وعمل جيد، كل أسبوع." },
    customersHigh: { en: "People talk about your work. That's the best marketing there is.", ar: "الناس يتحدثون عن عملك. وهذا أفضل تسويق على الإطلاق." },
    balanceLow: { en: "Burnout is a business risk too. Rest is not lost time.", ar: "الإرهاق خطر على المشروع أيضًا. والراحة ليست وقتًا ضائعًا." },
    balanceHigh: { en: "You worked, rested and kept going all year. That's rare.", ar: "عملت وارتحت واستمررت طوال العام. وهذا نادر." },
    schoolLow: { en: "School comes first at your age. The hustle will still be there after exams.", ar: "الدراسة أولًا في هذا العمر. والمشروع سيبقى بعد الامتحانات." },
    schoolHigh: { en: "Good grades and a business. You proved you can carry both.", ar: "درجات جيدة ومشروع. وثبت أن حمل الاثنين ممكن." },
    honestyLow: { en: "Shortcuts feel fast. Trust lasts longer, and it's expensive to rebuild.", ar: "الطرق المختصرة تبدو سريعة. لكن الثقة تدوم أطول، وإعادة بنائها مكلفة." },
    honestyHigh: { en: "You did the right thing even when it cost you. People noticed.", ar: "اخترت الصواب حتى حين كلّفك. ولاحظ الناس ذلك." },
  },

  howTo: [
    { img: "briefcase", en: "Pick a side hustle and a savings goal. You have 30 weeks: one school year.", ar: "اختيار مشروع جانبي وهدف للادّخار. أمامك 30 أسبوعًا: عام دراسي كامل." },
    { img: "calendar", en: "Each week: set a price, decide how many to prepare, and pick one extra thing to do.", ar: "كل أسبوع: سعر، وكمية للتحضير، ونشاط إضافي واحد." },
    { img: "coin", en: "Preparing costs coins. Profit is coins in minus coins spent.", ar: "التحضير يكلّف نقودًا. والربح هو ما دخل ناقص ما صُرف." },
    { img: "high_voltage", en: "Watch your energy. Below 40, mistakes happen. At 70+, a smarter option opens.", ar: "الطاقة مهمة. تحت 40 تقع الأخطاء. ومن 70 فما فوق يُفتح خيار أذكى." },
    { img: "graduation_cap", en: "Grades drop each week you don't study. Below 40, your parents pause the business. Exams come 3 times a year.", ar: "الدرجات تنخفض كل أسبوع بلا مذاكرة. وتحت 40 يوقف الأهل المشروع. والامتحانات 3 مرات في العام." },
    { img: "woman_office_worker", en: "Aunt Nour leaves a note after each choice. Some choices come back weeks later.", ar: "خالتك نور تترك ملاحظة بعد كل اختيار. وبعض الاختيارات تعود بعد أسابيع." },
  ],

  parentsNote: {
    en: [
      "Teenpreneur is a free game for ages 13 to 17 about running a small side business: pricing, costs, profit, saving, reputation, integrity, and balancing all of it with school and rest.",
      "Nothing leaves this device. There are no accounts, no ads, no analytics, no tracking, no chat and nothing to buy. Your teen's name and progress are saved only on this device.",
      "It loads nothing from other websites. After the first visit it also works offline.",
      "The situations are realistic but safe: payment scams, late-paying clients, online comments, meeting new clients, and why school comes first. A school year takes about 40 minutes and can be paused at any time.",
    ],
    ar: [
      "تينبرونور لعبة مجانية للأعمار من 13 إلى 17 عن إدارة مشروع جانبي صغير: التسعير والتكاليف والربح والادّخار والسمعة والنزاهة، والتوازن بين كل ذلك وبين الدراسة والراحة.",
      "لا يخرج شيء من هذا الجهاز. لا حسابات ولا إعلانات ولا تحليلات ولا تتبّع ولا محادثات ولا مشتريات. اسم ابنكم أو ابنتكم وتقدّمهم محفوظان على هذا الجهاز فقط.",
      "لا تُحمِّل اللعبة شيئًا من مواقع أخرى. وبعد الزيارة الأولى تعمل دون اتصال أيضًا.",
      "المواقف واقعية لكنها آمنة: احتيال الدفع، والعملاء المتأخرون في الدفع، والتعليقات على الإنترنت، ومقابلة عملاء جدد، ولماذا تأتي الدراسة أولًا. ويستغرق العام الدراسي نحو 40 دقيقة، ويمكن إيقافه في أي وقت.",
    ],
  },

  // ───────────────────────── Dilemmas ─────────────────────────
  dilemmas: [

    // ── General (any side hustle) ──
    {
      id: "g_screenshot", biz: "all", img: "receipt", when: { minWeek: 2 },
      title: { en: "\"I already paid, here's the screenshot\"", ar: "«دفعت بالفعل، وهذه صورة الشاشة»" },
      text: { en: "A new customer wants a big order right now, worth 25 coins. They send a screenshot of a payment. Nothing has arrived on your side yet.", ar: "زبون جديد يريد طلبًا كبيرًا الآن، قيمته 25 عملة. وأرسل صورة شاشة لعملية دفع. ولم يصل شيء بعد." },
      A: { label: { en: "Hand it over: the screenshot looks real", ar: "التسليم، فالصورة تبدو حقيقية" },
           fx: { coins: -25 },
           log: { en: "The money never arrived. The screenshot was edited, and the account disappeared.", ar: "لم يصل المال أبدًا. كانت الصورة معدّلة، واختفى الحساب." } },
      B: { label: { en: "Wait until the money actually arrives", ar: "الانتظار حتى يصل المال فعلًا" },
           fx: { energy: -2 },
           log: { en: "The \"customer\" got angry, then vanished. A real buyer would have waited ten minutes.", ar: "غضب «الزبون» ثم اختفى. والمشتري الحقيقي كان سينتظر عشر دقائق." } },
      C: { needs: 70, label: { en: "Check with a parent, then set a rule: paid first, always", ar: "التحقق مع أحد الوالدين، ثم قاعدة: الدفع أولًا دائمًا" },
           fx: { rep: 2, quality: 3 },
           log: { en: "Your dad spotted the fake in seconds. Your new rule is on every price list now.", ar: "اكتشف بابا التزوير في ثوانٍ. والقاعدة الجديدة صارت على كل قائمة أسعار." } },
      idea: { en: "Money is real when it arrives, not when someone shows you a picture of it.", ar: "المال حقيقي عندما يصل، لا عندما يعرض أحدهم صورة له." },
    },
    {
      id: "g_meet", biz: "all", img: "door", when: { minWeek: 3 },
      title: { en: "A new client wants to meet at night", ar: "عميل جديد يريد اللقاء ليلًا" },
      text: { en: "Someone you only know online wants to meet at their place after 9 pm to \"discuss a big job\". They say to keep it between you two.", ar: "شخص معرفته عبر الإنترنت فقط يريد اللقاء في مكانه بعد الساعة 9 مساءً «لمناقشة عمل كبير». ويطلب أن يبقى الأمر بينكما." },
      A: { label: { en: "Go, and tell nobody", ar: "الذهاب دون إخبار أحد" },
           fx: { energy: -6, honest: -1 },
           log: { en: "The meeting felt strange and the \"big job\" was vague. You came home late with nothing.", ar: "كان اللقاء غريبًا و«العمل الكبير» غامضًا. ورجعت متأخرًا بلا شيء." },
           echo: { after: [1, 2], img: "woman",
                   title: { en: "Mum saw the messages", ar: "ماما رأت الرسائل" },
                   text: { en: "Mum wasn't angry about the business. She was scared. New family rule: new clients meet in public, in daylight, and someone at home knows.", ar: "لم تكن ماما غاضبة من المشروع، بل كانت خائفة. قاعدة جديدة في البيت: العملاء الجدد يُقابَلون في مكان عام، نهارًا، ومع علم أحد في البيت." },
                   fx: { energy: -6 } } },
      B: { label: { en: "Suggest a café, in daylight, and tell a parent", ar: "اقتراح مقهى نهارًا، وإخبار أحد الوالدين" },
           fx: { honest: 1, energy: -2 },
           log: { en: "They stopped replying. A real client doesn't mind meeting in a café.", ar: "توقّف عن الرد. والعميل الحقيقي لا يمانع اللقاء في مقهى." } },
      idea: { en: "Safe first, money second. A good client never asks you to hide anything.", ar: "الأمان أولًا، والمال ثانيًا. والعميل الجيد لا يطلب إخفاء أي شيء." },
    },
    {
      id: "g_bestie", biz: "all", img: "busts_in_silhouette", when: { minWeek: 2 },
      title: { en: "Your best friend wants it free", ar: "صديقك المقرّب يريده مجانًا" },
      text: { en: "Salma has been your friend since you were 6. \"You're not going to charge ME, right?\" She needs it every week.", ar: "سلمى صديقتك منذ عمر 6 سنوات. تقول: «أنا صديقتك، فالأمر مجاني، صح؟» وهي تحتاجه كل أسبوع." },
      A: { label: { en: "Free for Salma, always", ar: "مجانًا لسلمى دائمًا" },
           fx: { coins: -8, rep: 2 },
           log: { en: "Salma was thrilled. Then two of her friends asked for \"the Salma deal\".", ar: "فرحت سلمى كثيرًا. ثم طلبت صديقتان لها «عرض سلمى»." },
           echo: { after: [2, 4], img: "speech_balloon",
                   title: { en: "Everyone wants the Salma deal", ar: "الجميع يريد عرض سلمى" },
                   text: { en: "Half the class is asking for free now. Saying no is harder than it was at the start.", ar: "نصف الفصل يطلب المجان الآن. والرفض صار أصعب مما كان في البداية." },
                   fx: { coins: -12 } } },
      B: { label: { en: "A friends' price: 20% off", ar: "سعر الأصدقاء: خصم 20%" },
           fx: { coins: -2 },
           log: { en: "Salma laughed and said that was fair. She paid on time, every time.", ar: "ضحكت سلمى وقالت إن هذا عادل. ودفعت في موعدها كل مرة." } },
      C: { needs: 70, label: { en: "A trade: she promotes you, you help her", ar: "تبادل: هي تروّج لك، وأنت تساعدها" },
           fx: { rep: 3, mods: [{ k: "demand", x: 1.15, weeks: 3 }] },
           log: { en: "Salma told everyone she knows. She's better at talking than any poster.", ar: "أخبرت سلمى كل من تعرفه. وهي أفضل في الكلام من أي ملصق." } },
      idea: { en: "Friends deserve fairness, not free. A clear price protects the friendship too.", ar: "الأصدقاء يستحقون العدل، لا المجان. والسعر الواضح يحمي الصداقة أيضًا." },
    },
    {
      id: "g_comment", biz: "all", img: "exploding_head", when: { minWeek: 3 },
      title: { en: "A cruel comment under your post", ar: "تعليق قاسٍ تحت منشورك" },
      text: { en: "Someone wrote \"this is the worst thing I've ever paid for, total scam\" under your post. You've never seen their name before. 40 people liked it.", ar: "كتب أحدهم تحت منشورك: «أسوأ شيء دفعت فيه مالًا، احتيال كامل». ولم يمرّ اسمه عليك من قبل. وأعجب به 40 شخصًا." },
      A: { label: { en: "Reply and tell them exactly what you think", ar: "الرد بكل ما في القلب" },
           fx: { rep: -5, energy: -5 },
           log: { en: "The fight got 200 comments. New customers saw the shouting, not your work.", ar: "وصل الشجار إلى 200 تعليق. ورأى الزبائن الجدد الصراخ، لا العمل." } },
      B: { label: { en: "Don't reply. Report it, block, move on", ar: "عدم الرد، ثم الإبلاغ والحظر والمضي" },
           fx: { energy: -2 },
           log: { en: "It stung for a day. Nobody remembered it by the weekend.", ar: "آلم يومًا واحدًا. ولم يتذكره أحد بحلول العطلة." } },
      C: { needs: 70, label: { en: "One calm public reply: \"Message me and I'll make it right\"", ar: "رد هادئ واحد: «راسلني وسأصلح الأمر»" },
           fx: { rep: 4, energy: -3 },
           log: { en: "They never messaged. But three customers wrote underneath that you'd always been great.", ar: "لم يراسل أبدًا. لكن ثلاثة زبائن كتبوا تحته أن عملك كان ممتازًا دائمًا." } },
      idea: { en: "You can't control comments. You can control what readers see from you.", ar: "التعليقات خارج السيطرة. أما ما يراه الناس منك فهو بيدك." },
    },
    {
      id: "g_late", biz: "all", img: "hourglass_not_done", when: { minWeek: 4 },
      title: { en: "A client hasn't paid in 3 weeks", ar: "عميل لم يدفع منذ 3 أسابيع" },
      text: { en: "Mr. Adel owes you 30 coins. He keeps saying \"next week\". He wants more work this week.", ar: "الأستاذ عادل مدين لك بـ30 عملة. ويقول دائمًا: «الأسبوع القادم». ويريد عملًا جديدًا هذا الأسبوع." },
      A: { label: { en: "Keep working: he'll pay eventually", ar: "مواصلة العمل، فسيدفع في النهاية" },
           fx: { coins: -10, rep: 1 },
           log: { en: "More work went out. No money came in.", ar: "خرج عمل جديد. ولم يدخل أي مال." },
           echo: { after: [3, 5], img: "money_with_wings",
                   title: { en: "Mr. Adel moved away", ar: "الأستاذ عادل انتقل بعيدًا" },
                   text: { en: "Mr. Adel closed his shop and moved. The money he owed went with him.", ar: "أغلق الأستاذ عادل محلّه وانتقل. وذهب معه المال الذي كان عليه." },
                   fx: { energy: -4 } } },
      B: { label: { en: "Politely pause until he pays", ar: "التوقف بأدب حتى يدفع" },
           fx: { energy: -2 },
           log: { en: "He was surprised you said it. He didn't argue.", ar: "تفاجأ بأنك قلتها. ولم يجادل." },
           echo: { after: [1, 3], img: "money_bag",
                   title: { en: "Mr. Adel paid", ar: "الأستاذ عادل دفع" },
                   text: { en: "Mr. Adel paid all 30 coins and said sorry. Being clear worked.", ar: "دفع الأستاذ عادل الـ30 عملة كاملة واعتذر. الوضوح نجح." },
                   fx: { coins: 30 } } },
      idea: { en: "Agree on the price and the payday before the work starts. Write it down.", ar: "الاتفاق على السعر وموعد الدفع يكون قبل بدء العمل. ويُكتب." },
    },
    {
      id: "g_examclash", biz: "all", img: "memo", when: { examNext: true },
      title: { en: "A big order lands right before exams", ar: "طلب كبير قبل الامتحانات مباشرة" },
      text: { en: "Someone wants a job worth 40 coins, due next week. Next week is exam season.", ar: "أحدهم يريد عملًا قيمته 40 عملة، موعده الأسبوع القادم. والأسبوع القادم موسم امتحانات." },
      A: { label: { en: "Take it all: money is money", ar: "قبول الطلب كله، فالمال مال" },
           fx: { coins: 40, grades: -12, energy: -10 },
           log: { en: "You delivered at 2 am. The money is in. Your revision isn't.", ar: "سُلّم العمل الساعة 2 فجرًا. المال وصل. والمراجعة لم تحصل." } },
      B: { label: { en: "Say no: exams first", ar: "الاعتذار، فالامتحانات أولًا" },
           fx: { rep: -1, grades: 3 },
           log: { en: "They found someone else. Your desk is covered in notes, which is the point.", ar: "وجدوا شخصًا آخر. ومكتبك مغطى بالملخصات، وهذا هو المطلوب." } },
      C: { needs: 70, label: { en: "Offer half now, the rest after exams", ar: "عرض النصف الآن، والباقي بعد الامتحانات" },
           fx: { coins: 20, grades: -3 },
           log: { en: "They agreed. Most deadlines move if you ask early.", ar: "وافقوا. وأغلب المواعيد يمكن تحريكها إذا طُلب ذلك مبكرًا." } },
      idea: { en: "Saying \"not now\" is a business skill. So is knowing what matters most this month.", ar: "قول «ليس الآن» مهارة في العمل. ومعرفة الأهم هذا الشهر مهارة أيضًا." },
    },
    {
      id: "g_console", biz: "all", img: "video_game", when: { minCoins: 220 },
      title: { en: "The new console is out", ar: "الجهاز الجديد للألعاب نزل" },
      text: { en: "Everyone is talking about it. It costs 180 coins. You have that right now, but it's your savings.", ar: "الجميع يتحدّث عنه. سعره 180 عملة. والمبلغ موجود الآن، لكنه من مدّخراتك." },
      A: { label: { en: "Buy it today", ar: "الشراء اليوم" },
           fx: { coins: -180, energy: 12, grades: -3 },
           log: { en: "It really is great. The savings bar went back a long way.", ar: "إنه رائع فعلًا. وشريط الادّخار رجع كثيرًا إلى الوراء." } },
      B: { label: { en: "Wait and keep saving", ar: "الانتظار ومواصلة الادّخار" },
           fx: { energy: -2 },
           log: { en: "Your friends will tell you all about it. The savings stay where they are.", ar: "سيحكي الأصدقاء كل شيء عنه. والمدّخرات باقية في مكانها." },
           echo: { after: [4, 7], img: "video_game",
                   title: { en: "The price dropped", ar: "السعر انخفض" },
                   text: { en: "The same console is now 120 coins, 60 less. Waiting paid off.", ar: "صار الجهاز نفسه بـ120 عملة، أي أقل بـ60. والانتظار أثمر." },
                   fx: { energy: 4 } } },
      idea: { en: "Saving is choosing what you want most over what you want right now.", ar: "الادّخار هو تقديم الرغبة الأكبر على الرغبة السريعة." },
    },
    {
      id: "g_numbers", biz: "all", img: "notebook", when: { minWeek: 5 },
      title: { en: "Your parents want to see the numbers", ar: "الأهل يريدون رؤية الأرقام" },
      text: { en: "At dinner, Dad asks how the business is really doing. Last month you lost money twice and haven't mentioned it.", ar: "على العشاء سأل بابا عن حال المشروع فعلًا. والشهر الماضي حصلت خسارة مرتين ولم يُذكر ذلك." },
      A: { label: { en: "\"It's going great\" and change the subject", ar: "«كل شيء رائع»، ثم تغيير الموضوع" },
           fx: { honest: -1 },
           log: { en: "Dinner moved on. The two losses are still there, just unseen.", ar: "انتقل الحديث. والخسارتان ما زالتا هناك، لكن لا يراهما أحد." },
           echo: { after: [2, 4], img: "chart_decreasing",
                   title: { en: "The same mistake, again", ar: "الخطأ نفسه، مرة أخرى" },
                   text: { en: "The loss came back for the same reason. Nobody had looked at why.", ar: "عادت الخسارة للسبب نفسه. فلم ينظر أحد في السبب." },
                   fx: { coins: -15 } } },
      B: { label: { en: "Show the real notebook, losses and all", ar: "عرض الدفتر الحقيقي بخسائره" },
           fx: { honest: 1, quality: 5 },
           log: { en: "Dad spotted the leak in five minutes: you were preparing too much. He was impressed you kept notes at all.", ar: "اكتشف بابا الثغرة في خمس دقائق: التحضير كان أكثر من اللازم. وأُعجب بوجود دفتر أصلًا." } },
      C: { needs: 70, label: { en: "Build a simple spreadsheet together", ar: "بناء جدول بسيط معًا" },
           fx: { honest: 1, quality: 8, energy: -3 },
           log: { en: "Two columns, in and out. Now you can see every week at a glance.", ar: "عمودان: داخل وخارج. والآن يظهر كل أسبوع بنظرة واحدة." } },
      idea: { en: "Numbers you hide can't help you. Numbers you share get better.", ar: "الأرقام المخفية لا تساعد. والأرقام المشتركة تتحسّن." },
    },
    {
      id: "g_group", biz: "all", img: "puzzle_piece",
      title: { en: "Group project: nobody's doing anything", ar: "مشروع جماعي ولا أحد يعمل" },
      text: { en: "The group project is due in two weeks. Your three teammates have done nothing. It counts for your grades.", ar: "موعد تسليم المشروع الجماعي بعد أسبوعين. والزملاء الثلاثة لم يفعلوا شيئًا. وهو جزء من الدرجات." },
      A: { label: { en: "Do it all yourself", ar: "إنجازه بالكامل وحدك" },
           fx: { grades: 6, energy: -10 },
           log: { en: "It's good, and they'll get the same mark. You're exhausted.", ar: "خرج جيدًا، وسيأخذون الدرجة نفسها. والإرهاق واضح." } },
      B: { label: { en: "Message the group and split tasks", ar: "مراسلة المجموعة وتوزيع المهام" },
           fx: { grades: 3, energy: -3 },
           log: { en: "Two of them did their part. One didn't. Still better.", ar: "قام اثنان بدورهما، والثالث لا. لكنه أفضل." } },
      C: { needs: 70, label: { en: "A shared plan with names and dates", ar: "خطة مشتركة بالأسماء والمواعيد" },
           fx: { grades: 6, rep: 2, energy: -4 },
           log: { en: "With names next to tasks, everyone delivered. The teacher asked who organised it.", ar: "مع وجود الأسماء بجانب المهام، سلّم الجميع. وسأل المعلم من نظّم الأمر." } },
      idea: { en: "Delegating is a skill: a clear task, a clear name, a clear date.", ar: "التفويض مهارة: مهمة واضحة، واسم واضح، وموعد واضح." },
    },
    {
      id: "g_shoutout", biz: "all", img: "satellite_antenna", when: { minCoins: 80 },
      title: { en: "A shoutout from a big account", ar: "إعلان من حساب كبير" },
      text: { en: "An account with 50,000 followers offers to post about you for 60 coins. Most of their posts get very few comments.", ar: "حساب عليه 50,000 متابع يعرض الحديث عنك مقابل 60 عملة. وأغلب منشوراته تحصل على تعليقات قليلة جدًا." },
      A: { label: { en: "Pay for the shoutout", ar: "الدفع مقابل الإعلان" },
           fx: { coins: -60, mods: [{ k: "demand", x: 1.05, weeks: 1 }] },
           log: { en: "The post went up. You watched the likes come in.", ar: "نُشر المنشور. وتابعت الإعجابات وهي تصل." },
           echo: { after: [1, 2], img: "magnifying_glass_tilted_left",
                   title: { en: "Where are the customers?", ar: "أين الزبائن؟" },
                   text: { en: "Most of those followers were bought. Two new customers came.", ar: "أغلب المتابعين كانوا مشترين. وجاء زبونان جديدان فقط." },
                   fx: { energy: -2 } } },
      B: { label: { en: "Ask for their results from past shoutouts first", ar: "طلب نتائج إعلاناتهم السابقة أولًا" },
           fx: { quality: 3 },
           log: { en: "They didn't have any. That told you everything.", ar: "لم يكن لديهم أي نتائج. وهذا قال كل شيء." } },
      idea: { en: "Ask what results look like, not how big the number is.", ar: "السؤال يكون عن النتائج، لا عن حجم الرقم." },
    },
    {
      id: "g_partner", biz: "all", img: "handshake", when: { minWeek: 4 },
      title: { en: "Omar wants to be your partner", ar: "عمر يريد أن يصبح شريكك" },
      text: { en: "Your classmate Omar wants in. He's good with people and will do the running around. He wants half of the profit, every week.", ar: "زميلك عمر يريد الانضمام. يجيد التعامل مع الناس وسيتولى المشاوير. ويريد نصف الربح كل أسبوع." },
      A: { label: { en: "Yes: 50/50 for 5 weeks", ar: "القبول: 50/50 لمدة 5 أسابيع" },
           fx: { energy: 4, mods: [{ k: "share", x: 0.5, weeks: 5 }, { k: "demand", x: 1.4, weeks: 5 }, { k: "energyUse", x: 0.5, weeks: 5 }] },
           log: { en: "Omar starts next week, for 5 weeks. More customers, less running around, half the profit.", ar: "يبدأ عمر الأسبوع القادم لمدة 5 أسابيع. زبائن أكثر، ومشاوير أقل، ونصف الربح." } },
      B: { label: { en: "No: keep it yours", ar: "الرفض: المشروع يبقى لك" },
           fx: { energy: -2 },
           log: { en: "Omar said fine. He looked like he had a plan B.", ar: "قال عمر: حسنًا. وبدا أن عنده خطة بديلة." },
           echo: { after: [2, 4], img: "chart_increasing",
                   title: { en: "Omar started his own", ar: "عمر بدأ مشروعه الخاص" },
                   text: { en: "Omar is doing the same thing now, two streets away. Some of your customers try him first.", ar: "صار عمر يقدّم الشيء نفسه على بُعد شارعين. وبعض زبائنك يجرّبونه أولًا." },
                   fx: { mods: [{ k: "demand", x: 0.88, weeks: 3 }] } } },
      C: { needs: 70, label: { en: "A two-week trial, written down, then decide", ar: "تجربة أسبوعين مكتوبة، ثم القرار" },
           fx: { rep: 2, mods: [{ k: "share", x: 0.5, weeks: 2 }, { k: "demand", x: 1.4, weeks: 2 }, { k: "energyUse", x: 0.5, weeks: 2 }] },
           log: { en: "You both signed a one-page deal. Clear and fair.", ar: "وقّع الاثنان اتفاقًا من صفحة واحدة. واضح وعادل." } },
      idea: { en: "Half of a bigger pie can be more than a whole small one. Or less. Do the maths.", ar: "نصف كعكة كبيرة قد يكون أكبر من كعكة صغيرة كاملة، وقد يكون أصغر. الحساب هو الحَكَم." },
    },
    {
      id: "g_double", biz: "all", img: "coin",
      title: { en: "A client paid twice by mistake", ar: "عميل دفع مرتين بالخطأ" },
      text: { en: "Mrs. Hala paid 20 coins twice for the same job. She hasn't noticed.", ar: "دفعت السيدة هالة 20 عملة مرتين عن العمل نفسه. ولم تلاحظ." },
      A: { label: { en: "Keep it: her mistake", ar: "الاحتفاظ به، فالخطأ خطؤها" },
           fx: { coins: 20, honest: -1 },
           log: { en: "20 extra coins. It's on your mind a little.", ar: "20 عملة زيادة. والأمر يشغل البال قليلًا." },
           echo: { after: [2, 4], img: "grimacing_face",
                   title: { en: "Mrs. Hala checked her account", ar: "السيدة هالة راجعت حسابها" },
                   text: { en: "She found the double payment and asked about it. There was nothing good to say.", ar: "وجدت الدفعة المكررة وسألت عنها. ولم يكن هناك كلام مناسب يقال." },
                   fx: { coins: -20, rep: -6 } } },
      B: { label: { en: "Tell her and send it back", ar: "إخبارها وإرجاع المال" },
           fx: { honest: 1, rep: 2 },
           log: { en: "She said nobody had ever done that. She saved your number.", ar: "قالت إن أحدًا لم يفعل ذلك من قبل. وحفظت رقمك." },
           echo: { after: [2, 5], img: "heart_hands",
                   title: { en: "Mrs. Hala told her friends", ar: "السيدة هالة أخبرت صديقاتها" },
                   text: { en: "\"This is the honest one,\" she told three friends. They all became customers.", ar: "قالت لثلاث صديقات: «هذا هو الأمين». وصرن كلهن زبائن." },
                   fx: { rep: 5, mods: [{ k: "demand", x: 1.15, weeks: 3 }] } } },
      idea: { en: "Trust is like savings: slow to build, quick to spend.", ar: "الثقة مثل الادّخار: تُبنى ببطء وتُصرف بسرعة." },
    },
    {
      id: "g_burnout", biz: "all", img: "face_exhaling", when: { minWeek: 6 },
      title: { en: "Three late nights in a row", ar: "ثلاث ليالٍ متأخرة متتالية" },
      text: { en: "You've been up past 1 am three nights running. A client wants one more job this weekend for 15 coins.", ar: "السهر بعد الساعة 1 فجرًا تكرر ثلاث ليالٍ. وعميل يريد عملًا إضافيًا هذه العطلة مقابل 15 عملة." },
      A: { label: { en: "Push through: take the job", ar: "المواصلة وقبول العمل" },
           fx: { coins: 15, energy: -14, grades: -4 },
           log: { en: "Done. You fell asleep in first period on Monday.", ar: "تم. ونمت في الحصة الأولى يوم الإثنين." } },
      B: { label: { en: "Turn it down and sleep", ar: "الاعتذار والنوم" },
           fx: { energy: 16 },
           log: { en: "You slept 10 hours. Everything looked easier on Monday.", ar: "نمت 10 ساعات. وبدا كل شيء أسهل يوم الإثنين." } },
      idea: { en: "You are the business's only machine. Machines need maintenance.", ar: "أنت الآلة الوحيدة في المشروع. والآلات تحتاج صيانة." },
    },
    {
      id: "g_bulk", biz: "all", img: "package", when: { minCoins: 90 },
      title: { en: "Supplies in bulk, 30% cheaper", ar: "مستلزمات بالجملة، أرخص بـ30%" },
      text: { en: "A wholesaler offers you supplies for the next 6 weeks at 30% off, if you pay 50 coins now.", ar: "تاجر جملة يعرض مستلزمات الأسابيع الـ6 القادمة بخصم 30%، بشرط دفع 50 عملة الآن." },
      A: { label: { en: "Buy in bulk", ar: "الشراء بالجملة" },
           fx: { coins: -50, mods: [{ k: "cost", x: 0.4, weeks: 6 }] },
           log: { en: "50 coins out today. Every unit costs much less for 6 weeks.", ar: "خرجت 50 عملة اليوم. وكل وحدة تكلّف أقل بكثير لمدة 6 أسابيع." } },
      B: { label: { en: "Keep buying week by week", ar: "الشراء أسبوعًا بأسبوع" },
           fx: {},
           log: { en: "No big payment. No discount either.", ar: "لا دفعة كبيرة. ولا خصم أيضًا." } },
      idea: { en: "Bulk saves money only if you really use it all, and you can afford to pay up front.", ar: "الجملة توفّر فقط إذا استُخدم كل شيء فعلًا، وكان الدفع المسبق ممكنًا." },
    },
    {
      id: "g_fundraiser", biz: "all", img: "red_heart",
      title: { en: "The school fundraiser needs help", ar: "حملة تبرعات المدرسة تحتاج مساعدة" },
      text: { en: "The school is raising money for a classmate's family after a fire. They ask if your business can help.", ar: "المدرسة تجمع تبرعات لأسرة زميل بعد حريق. ويسألون إن كان مشروعك يستطيع المساعدة." },
      A: { label: { en: "Donate 20 coins", ar: "التبرع بـ20 عملة" },
           fx: { coins: -20, rep: 4 },
           log: { en: "Your name was on the thank-you list. It felt right.", ar: "كان اسمك في قائمة الشكر. وكان شعورًا صحيحًا." } },
      B: { label: { en: "Not this time", ar: "ليس هذه المرة" },
           fx: {},
           log: { en: "Others gave. That's okay too.", ar: "تبرّع آخرون. ولا بأس بذلك أيضًا." } },
      C: { needs: 70, label: { en: "Give one afternoon of work, all money to the family", ar: "عصر كامل من العمل، وكل المال للأسرة" },
           fx: { energy: -6, rep: 6, mods: [{ k: "demand", x: 1.1, weeks: 2 }] },
           log: { en: "You raised 3 times what you'd have donated. People saw what you can do.", ar: "جُمع 3 أضعاف ما كان سيُتبرّع به. ورأى الناس قدراتك." } },
      idea: { en: "A business is part of a community. Communities remember.", ar: "المشروع جزء من مجتمع. والمجتمع لا ينسى." },
    },
    {
      id: "g_contest", biz: "all", img: "trophy", when: { minWeek: 8 },
      title: { en: "A young entrepreneurs contest", ar: "مسابقة لرواد الأعمال الصغار" },
      text: { en: "The city runs a contest for teen businesses. Preparing the pitch takes a week of evenings.", ar: "المدينة تنظّم مسابقة لمشاريع المراهقين. وتحضير العرض يحتاج أمسيات أسبوع كامل." },
      A: { label: { en: "Enter", ar: "المشاركة" },
           fx: { energy: -8, grades: -2 },
           log: { en: "You stood up and pitched in front of 100 people. Your hands shook. You did it anyway.", ar: "وقفت وقدّمت العرض أمام 100 شخص. ارتجفت اليدان، وتمّ العرض رغم ذلك." },
           echo: { after: [2, 3], img: "trophy",
                   title: { en: "Third place", ar: "المركز الثالث" },
                   text: { en: "You came third and won 40 coins. A judge asked for your number.", ar: "حصلت على المركز الثالث وجائزة 40 عملة. وطلب أحد المحكّمين رقمك." },
                   fx: { coins: 40, rep: 4 } } },
      B: { label: { en: "Skip it this year", ar: "التخطي هذا العام" },
           fx: { energy: 2 },
           log: { en: "Maybe next year. This week stays calm.", ar: "ربما العام القادم. وهذا الأسبوع يبقى هادئًا." } },
      idea: { en: "Explaining your business out loud makes you understand it better.", ar: "شرح المشروع بصوت عالٍ يجعل فهمه أعمق." },
    },
    {
      id: "g_copywork", biz: "all", img: "framed_picture", when: { minWeek: 3 },
      title: { en: "Someone else's work, your name", ar: "عمل غيرك، باسمك" },
      text: { en: "An older student offers you their old work, ready to sell as yours. \"Nobody will know. 10 coins and it's yours.\"", ar: "طالب أكبر يعرض أعماله القديمة جاهزة للبيع باسمك. ويقول: «لن يعرف أحد. 10 عملات وتصبح لك.»" },
      A: { label: { en: "Buy it and sell it as yours", ar: "الشراء والبيع باسمك" },
           fx: { coins: 20, honest: -1 },
           log: { en: "It sold quickly. It doesn't feel like yours.", ar: "بيع بسرعة. لكنه لا يبدو كأنه لك." },
           echo: { after: [2, 4], img: "detective",
                   title: { en: "Someone recognised it", ar: "أحدهم تعرّف عليه" },
                   text: { en: "A customer had seen the same work last year, with another name on it. The story went around school.", ar: "رأى أحد الزبائن العمل نفسه العام الماضي باسم آخر. وانتشرت القصة في المدرسة." },
                   fx: { rep: -8 } } },
      B: { label: { en: "No thanks: make your own", ar: "شكرًا، والعمل يكون من صنعك" },
           fx: { honest: 1, quality: 5, energy: -4 },
           log: { en: "Slower. Yours. Better than you expected.", ar: "أبطأ. لكنه لك. وأفضل مما توقّعت." } },
      idea: { en: "Your name on someone else's work borrows trust you'll have to pay back.", ar: "اسمك على عمل غيرك يقترض ثقة سيُطلب ردّها." },
    },

    // ── Tutoring ──
    {
      id: "t_homework", biz: "tutor", img: "books",
      title: { en: "\"Just do my homework for me\"", ar: "«المطلوب كتابة الواجب فقط»" },
      text: { en: "Youssef, 12, offers double your price if you just write his homework. His mum thinks you're teaching him.", ar: "يوسف، عمره 12 سنة، يعرض ضعف السعر مقابل كتابة واجبه فقط. وأمه تظن أن هناك دروسًا." },
      A: { label: { en: "Do it: double pay", ar: "كتابته مقابل الضعف" },
           fx: { coins: 20, honest: -1 },
           log: { en: "Easy money. Youssef learned nothing.", ar: "مال سهل. ولم يتعلّم يوسف شيئًا." },
           echo: { after: [2, 4], img: "grimacing_face",
                   title: { en: "Youssef failed the test", ar: "يوسف رسب في الاختبار" },
                   text: { en: "His homework was perfect and his test was a disaster. His mum figured it out and told the other parents.", ar: "كان واجبه ممتازًا واختباره كارثة. وفهمت أمه الأمر وأخبرت بقية الأهالي." },
                   fx: { rep: -8, mods: [{ k: "demand", x: 0.8, weeks: 3 }] } } },
      B: { label: { en: "Refuse, and teach him to do it", ar: "الرفض، وتعليمه كيف يكتبه" },
           fx: { honest: 1, energy: -3 },
           log: { en: "He grumbled for ten minutes. Then he got it.", ar: "تذمّر عشر دقائق. ثم فهم." },
           echo: { after: [3, 5], img: "star-struck",
                   title: { en: "Youssef got 18 out of 20", ar: "يوسف حصل على 18 من 20" },
                   text: { en: "His mum sent a voice note to the class group. Three new families called.", ar: "أرسلت أمه رسالة صوتية في مجموعة الفصل. واتصلت ثلاث أسر جديدة." },
                   fx: { rep: 6, mods: [{ k: "demand", x: 1.2, weeks: 3 }] } } },
      idea: { en: "Tutoring sells understanding. Answers are free in the back of the book.", ar: "الدروس تبيع الفهم. أما الإجابات فمجانية في آخر الكتاب." },
    },
    {
      id: "t_group", biz: "tutor", img: "busts_in_silhouette", when: { minWeek: 3 },
      title: { en: "Teach three kids at once?", ar: "تدريس ثلاثة أطفال معًا؟" },
      text: { en: "Three parents ask for a group session. Cheaper for each family, more kids per hour for you.", ar: "ثلاثة من الأهالي يطلبون حصة جماعية. أرخص لكل أسرة، وأطفال أكثر في الساعة." },
      A: { label: { en: "Groups for everyone", ar: "حصص جماعية للجميع" },
           fx: { quality: -6, mods: [{ k: "demand", x: 1.4, weeks: 4 }] },
           log: { en: "More kids, more coins. The quiet ones get a bit lost.", ar: "أطفال أكثر ونقود أكثر. والهادئون منهم يضيعون قليلًا." } },
      B: { label: { en: "Stay one-to-one", ar: "البقاء على الدروس الفردية" },
           fx: { quality: 3 },
           log: { en: "Fewer kids, more attention each.", ar: "أطفال أقل، واهتمام أكبر بكل واحد." } },
      C: { needs: 70, label: { en: "Small groups by level", ar: "مجموعات صغيرة حسب المستوى" },
           fx: { quality: 2, mods: [{ k: "demand", x: 1.3, weeks: 4 }] },
           log: { en: "Same level, same pace. It works.", ar: "المستوى نفسه، والسرعة نفسها. وهذا ينجح." } },
      idea: { en: "Scaling up is good when quality scales with it.", ar: "التوسّع جيد عندما تتوسّع الجودة معه." },
    },
    {
      id: "t_reports", biz: "tutor", img: "memo",
      title: { en: "A parent wants progress reports", ar: "أحد الأهالي يريد تقارير تقدّم" },
      text: { en: "Mrs. Rania asks for a short note after every lesson. It takes 10 minutes each time.", ar: "تطلب السيدة رانيا ملاحظة قصيرة بعد كل درس. وتأخذ 10 دقائق في كل مرة." },
      A: { label: { en: "Write a short weekly note for every family", ar: "ملاحظة أسبوعية قصيرة لكل أسرة" },
           fx: { energy: -5, rep: 4, mods: [{ k: "demand", x: 1.1, weeks: 4 }] },
           log: { en: "Parents started forwarding your notes to each other.", ar: "صار الأهالي يتبادلون ملاحظاتك." } },
      B: { label: { en: "\"The results will speak\"", ar: "«النتائج ستتكلّم»" },
           fx: { rep: -2 },
           log: { en: "Mrs. Rania looked unsure. Parents like to know.", ar: "بدت السيدة رانيا غير مقتنعة. والأهالي يحبّون أن يعرفوا." } },
      idea: { en: "Customers don't only buy the work. They buy knowing what's happening.", ar: "الزبائن لا يشترون العمل فقط. بل يشترون معرفة ما يحدث." },
    },

    // ── Phone & laptop help ──
    {
      id: "k_photos", biz: "tech", img: "shield",
      title: { en: "A phone full of private photos", ar: "هاتف مليء بالصور الخاصة" },
      text: { en: "You're fixing a neighbour's phone. Your friend, watching, says: \"Open the gallery, let's see.\"", ar: "أثناء إصلاح هاتف جار، قال صديق يتفرّج: «ما رأيك نلقي نظرة على الصور؟»" },
      A: { label: { en: "Just a quick look", ar: "نظرة سريعة فقط" },
           fx: { honest: -1 },
           log: { en: "Nothing exciting. But your friend talks a lot.", ar: "لا شيء مثير. لكن صديقك يتكلّم كثيرًا." },
           echo: { after: [2, 3], img: "speech_balloon",
                   title: { en: "Your friend told someone", ar: "صديقك أخبر أحدًا" },
                   text: { en: "The neighbour heard that you went through her phone. Nobody wants that from a repair person.", ar: "سمعت الجارة أن هاتفها فُتح وتُصفّح. ولا أحد يريد هذا ممن يصلح هاتفه." },
                   fx: { rep: -10, mods: [{ k: "demand", x: 0.8, weeks: 3 }] } } },
      B: { label: { en: "No. Fix only what you were asked to fix", ar: "لا. إصلاح المطلوب فقط" },
           fx: { honest: 1, rep: 2 },
           log: { en: "Your friend called you boring. Your customers would call you trustworthy.", ar: "قال صديقك إنك ممل. والزبائن سيقولون إنك موثوق." } },
      C: { needs: 70, label: { en: "Ask customers to log out of private apps first", ar: "طلب تسجيل خروج الزبائن من التطبيقات الخاصة أولًا" },
           fx: { honest: 1, rep: 5 },
           log: { en: "It's on your price list now. Parents love it.", ar: "صار هذا على قائمة أسعارك. والأهالي يحبّونه." } },
      idea: { en: "When people hand you their phone, they're handing you their trust.", ar: "من يعطيك هاتفه يعطيك ثقته." },
    },
    {
      id: "k_part", biz: "tech", img: "hammer_and_wrench", when: { minWeek: 3 },
      title: { en: "A much cheaper replacement part", ar: "قطعة بديلة أرخص بكثير" },
      text: { en: "A screen protector and charger cost you 8 coins from the good supplier, or 2 from a no-name one. The customer won't see the difference.", ar: "واقي الشاشة والشاحن من المورّد الجيد بـ8 عملات، ومن مورّد مجهول بـ2. والزبون لن يرى الفرق." },
      A: { label: { en: "Use the cheap ones, say nothing", ar: "استخدام الرخيص دون ذكر ذلك" },
           fx: { coins: 12, honest: -1 },
           log: { en: "Higher margin this week.", ar: "هامش ربح أعلى هذا الأسبوع." },
           echo: { after: [2, 4], img: "warning",
                   title: { en: "A charger overheated", ar: "شاحن سخن بشدة" },
                   text: { en: "One cheap charger got very hot. The family came back, worried, and wanted their money back.", ar: "سخن أحد الشواحن الرخيصة بشدة. وعادت الأسرة قلقة وطلبت استرجاع المال." },
                   fx: { coins: -15, rep: -6 } } },
      B: { label: { en: "Tell the customer both options", ar: "عرض الخيارين على الزبون" },
           fx: { honest: 1, rep: 2 },
           log: { en: "Most picked the good one. They liked being asked.", ar: "اختار أغلبهم الجيد. وأحبّوا أن يُسألوا." } },
      idea: { en: "Cheap parts are a choice the customer should make, not you.", ar: "القطعة الرخيصة قرار الزبون، لا قرارك." },
    },
    {
      id: "k_again", biz: "tech", img: "counterclockwise", when: { minWeek: 4 },
      title: { en: "Your fix broke again", ar: "الإصلاح تعطّل مرة أخرى" },
      text: { en: "Uncle Samir's laptop has the same problem you fixed two weeks ago. He's not happy.", ar: "لابتوب العم سمير فيه المشكلة نفسها التي أُصلحت قبل أسبوعين. وهو غير راضٍ." },
      A: { label: { en: "Charge him again: it's a new visit", ar: "طلب أجر جديد، فهي زيارة جديدة" },
           fx: { coins: 10, rep: -5 },
           log: { en: "He paid, and he won't call again.", ar: "دفع، ولن يتصل مرة أخرى." } },
      B: { label: { en: "Fix it free", ar: "إصلاحه مجانًا" },
           fx: { energy: -5, rep: 3 },
           log: { en: "He grumbled, then thanked you.", ar: "تذمّر ثم شكرك." } },
      C: { needs: 70, label: { en: "Fix it free, and add a 30-day promise for everyone", ar: "إصلاح مجاني، ووعد بضمان 30 يومًا للجميع" },
           fx: { energy: -5, rep: 5, mods: [{ k: "demand", x: 1.15, weeks: 4 }] },
           log: { en: "\"30-day promise\" is on your poster now. People notice.", ar: "صارت عبارة «ضمان 30 يومًا» على ملصقك. والناس يلاحظون." } },
      idea: { en: "A promise you keep is worth more than an ad you pay for.", ar: "الوعد الذي يُحفظ أثمن من إعلان مدفوع." },
    },

    // ── Design ──
    {
      id: "d_logo", biz: "design", img: "label",
      title: { en: "\"Make it look like the famous logo\"", ar: "«أريده شبه الشعار المشهور»" },
      text: { en: "A shop owner wants a logo that's almost exactly a famous sportswear logo, with one letter changed.", ar: "صاحب محل يريد شعارًا يكاد يطابق شعار ماركة رياضية مشهورة، مع تغيير حرف واحد." },
      A: { label: { en: "Make it: the client is always right", ar: "تنفيذه، فالعميل على حق" },
           fx: { coins: 20, honest: -1 },
           log: { en: "He loved it. It took 20 minutes.", ar: "أحبّه كثيرًا. واستغرق 20 دقيقة." },
           echo: { after: [3, 5], img: "incoming_envelope",
                   title: { en: "A warning letter", ar: "خطاب إنذار" },
                   text: { en: "The shop got a letter from the big brand's lawyers. He had to change everything, and he blamed you.", ar: "وصل المحل خطاب من محامي الماركة الكبيرة. واضطر لتغيير كل شيء، وألقى اللوم عليك." },
                   fx: { rep: -7 } } },
      B: { label: { en: "Explain why not, and offer something original", ar: "شرح السبب، وعرض شيء أصلي" },
           fx: { honest: 1, quality: 5, energy: -3 },
           log: { en: "He wasn't sure at first. A week later he had it printed on everything.", ar: "لم يكن مقتنعًا في البداية. وبعد أسبوع طبعه على كل شيء." } },
      idea: { en: "Original work is slower to make and much safer to sell.", ar: "العمل الأصلي أبطأ في الصنع، وأكثر أمانًا في البيع." },
    },
    {
      id: "d_revisions", biz: "design", img: "counterclockwise", when: { minWeek: 3 },
      title: { en: "\"Just one more small change\"", ar: "«تعديل صغير أخير بس»" },
      text: { en: "A café owner has asked for 11 changes to one menu. Each one is \"the last\".", ar: "صاحب مقهى طلب 11 تعديلًا على قائمة واحدة. وكل تعديل هو «الأخير»." },
      A: { label: { en: "Keep saying yes", ar: "مواصلة القبول" },
           fx: { energy: -10 },
           log: { en: "Change 12 arrived at midnight.", ar: "وصل التعديل رقم 12 في منتصف الليل." } },
      B: { label: { en: "Two rounds included, extra rounds cost more", ar: "جولتا تعديل مشمولتان، والزيادة بأجر" },
           fx: { coins: 8, rep: -1 },
           log: { en: "He grumbled and paid. Then the changes slowed down a lot.", ar: "تذمّر ودفع. ثم قلّت التعديلات كثيرًا." } },
      C: { needs: 70, label: { en: "A one-page brief before starting any job", ar: "ملخص من صفحة قبل بدء أي عمل" },
           fx: { quality: 8, energy: 4 },
           log: { en: "When the client writes what they want first, the first draft is usually right.", ar: "عندما يكتب العميل ما يريده أولًا، تكون المسودة الأولى صحيحة غالبًا." } },
      idea: { en: "Scope is part of the price. Agree on it before you start.", ar: "حدود العمل جزء من السعر. ويُتّفق عليها قبل البدء." },
    },
    {
      id: "d_exposure", biz: "design", img: "smiling_face_with_sunglasses",
      title: { en: "\"I'll pay you in exposure\"", ar: "«الأجر هو الشهرة»" },
      text: { en: "A popular gym wants a full set of posters for free. \"Everyone will see your work.\"", ar: "نادٍ رياضي معروف يريد مجموعة ملصقات كاملة مجانًا. ويقول: «الجميع سيرى عملك.»" },
      A: { label: { en: "Do it for exposure", ar: "التنفيذ مقابل الشهرة" },
           fx: { energy: -6 },
           log: { en: "Your posters are all over the gym. Your name is tiny in a corner.", ar: "ملصقاتك في كل مكان في النادي. واسمك صغير جدًا في زاوية." },
           echo: { after: [2, 3], img: "chart_increasing",
                   title: { en: "Two paying clients saw it", ar: "عميلان يدفعان رأيا العمل" },
                   text: { en: "Two people from the gym asked who made the posters. Both paid.", ar: "سأل شخصان من النادي عمّن صنع الملصقات. وكلاهما دفع." },
                   fx: { mods: [{ k: "demand", x: 1.2, weeks: 2 }] } } },
      B: { label: { en: "Offer a fair discount instead", ar: "عرض خصم عادل بدلًا من ذلك" },
           fx: { coins: 12 },
           log: { en: "They paid half your normal price. That's still paid.", ar: "دفعوا نصف السعر المعتاد. ويبقى ذلك أجرًا." } },
      idea: { en: "Exposure can help, once. You can't pay for supplies with it.", ar: "الشهرة قد تفيد مرة. لكنها لا تدفع ثمن المستلزمات." },
    },

    // ── Baking ──
    {
      id: "b_nuts", biz: "bake", img: "cookie",
      title: { en: "\"Are these nut-free?\"", ar: "«هل هذه خالية من المكسرات؟»" },
      text: { en: "A mum asks if your brownies are safe for her son with a nut allergy. You made walnut cookies in the same kitchen yesterday.", ar: "سألت أم إن كانت البراونيز آمنة لابنها المصاب بحساسية المكسرات. وأمس صُنعت كوكيز بالجوز في المطبخ نفسه." },
      A: { label: { en: "\"Should be fine\"", ar: "«غالبًا لا مشكلة»" },
           fx: { coins: 10, honest: -1 },
           log: { en: "She bought two boxes.", ar: "اشترت علبتين." },
           echo: { after: [1, 3], img: "warning",
                   title: { en: "A scary afternoon", ar: "عصر مخيف" },
                   text: { en: "Her son had a reaction. He's okay, but she told every parent at school.", ar: "أُصيب ابنها بحساسية. وهو بخير الآن، لكنها أخبرت كل الأهالي في المدرسة." },
                   fx: { rep: -12, mods: [{ k: "demand", x: 0.75, weeks: 3 }] } } },
      B: { label: { en: "\"I can't promise. Same kitchen.\"", ar: "«لا أستطيع الوعد. المطبخ نفسه.»" },
           fx: { honest: 1, rep: 2 },
           log: { en: "She didn't buy, and thanked you for being straight.", ar: "لم تشترِ، وشكرتك على الصراحة." } },
      C: { needs: 70, label: { en: "Label every box with all ingredients", ar: "كتابة كل المكونات على كل علبة" },
           fx: { honest: 1, rep: 5, quality: 4 },
           log: { en: "It took one evening. Now parents trust your boxes.", ar: "استغرق أمسية واحدة. والآن يثق الأهالي في علبك." } },
      idea: { en: "When someone's health is involved, \"probably\" is not an answer.", ar: "عندما يتعلّق الأمر بالصحة، كلمة «غالبًا» ليست إجابة." },
    },
    {
      id: "b_rule", biz: "bake", img: "classical", when: { minWeek: 4 },
      title: { en: "School bans selling on campus", ar: "المدرسة تمنع البيع داخلها" },
      text: { en: "A new rule: no selling food at school. Half of your customers are classmates.", ar: "قاعدة جديدة: ممنوع بيع الطعام في المدرسة. ونصف زبائنك زملاء دراسة." },
      A: { label: { en: "Keep selling, quietly", ar: "مواصلة البيع بهدوء" },
           fx: { coins: 12, honest: -1 },
           log: { en: "Boxes passed under desks.", ar: "صارت العلب تمرّ تحت الطاولات." },
           echo: { after: [1, 3], img: "police_car_light",
                   title: { en: "The principal's office", ar: "مكتب المدير" },
                   text: { en: "You got caught. A call home, and a very long talk.", ar: "انكشف الأمر. مكالمة للبيت، وحديث طويل جدًا." },
                   fx: { rep: -4, energy: -8, grades: -4 } } },
      B: { label: { en: "Sell only after school, outside", ar: "البيع بعد المدرسة وخارجها فقط" },
           fx: { mods: [{ k: "demand", x: 0.85, weeks: 3 }] },
           log: { en: "Fewer sales for a while. Nobody in trouble.", ar: "مبيعات أقل لفترة. ولا مشاكل." } },
      C: { needs: 70, label: { en: "Ask the principal for a stall at the school fair", ar: "طلب طاولة في معرض المدرسة من المدير" },
           fx: { rep: 3, mods: [{ k: "demand", x: 1.3, weeks: 2 }] },
           log: { en: "She said yes, if 10% went to the library. Your best week ever followed.", ar: "وافقت، بشرط أن تذهب 10% للمكتبة. وجاء بعدها أفضل أسبوع على الإطلاق." } },
      idea: { en: "Rules change. Smart businesses ask what's allowed, not how to hide.", ar: "القواعد تتغيّر. والمشروع الذكي يسأل عن المسموح، لا عن طرق الإخفاء." },
    },
    {
      id: "b_burnt", biz: "bake", img: "fire",
      title: { en: "The oven burned a batch", ar: "الفرن حرق دفعة كاملة" },
      text: { en: "The bottoms of a whole batch are dark. They taste okay, just a bit bitter.", ar: "قاعدة الدفعة كلها داكنة. والطعم مقبول، لكن فيه مرارة خفيفة." },
      A: { label: { en: "Sell them as normal", ar: "بيعها كالمعتاد" },
           fx: { coins: 10, honest: -1, rep: -3 },
           log: { en: "Some customers noticed. One left a face emoji you didn't like.", ar: "لاحظ بعض الزبائن. وترك أحدهم وجهًا تعبيريًا غير لطيف." } },
      B: { label: { en: "Sell them cheap, and say why", ar: "بيعها بسعر قليل مع ذكر السبب" },
           fx: { coins: 4, honest: 1, rep: 1 },
           log: { en: "\"Slightly burnt special\" sold out. People like honesty with a joke.", ar: "نفد «عرض المحروق قليلًا». والناس يحبّون الصراحة مع خفة الدم." } },
      C: { needs: 70, label: { en: "Bin them, and learn the oven", ar: "رميها، ودراسة الفرن" },
           fx: { coins: -6, quality: 10 },
           log: { en: "You bought an oven thermometer. It's 20 degrees hotter than the dial says.", ar: "اشتُري مقياس حرارة للفرن. وهو أسخن بـ20 درجة مما يظهر على المؤشر." } },
      idea: { en: "Mistakes are cheaper when you learn from them once.", ar: "الأخطاء أرخص عندما يُتعلّم منها مرة واحدة." },
    },

    // ── Thrift & resell ──
    {
      id: "r_fake", biz: "resell", img: "detective",
      title: { en: "Designer sneakers, suspiciously cheap", ar: "حذاء ماركة بسعر مريب" },
      text: { en: "A seller online has \"designer\" sneakers for 15 coins a pair. Real ones resell for 60.", ar: "بائع على الإنترنت يعرض حذاء «ماركة» بـ15 عملة للزوج. والأصلي يُباع بـ60." },
      A: { label: { en: "Buy and resell as real", ar: "الشراء وبيعها كأصلية" },
           fx: { coins: 30, honest: -1 },
           log: { en: "They sold fast at a great price.", ar: "بيعت بسرعة وبسعر ممتاز." },
           echo: { after: [2, 4], img: "magnifying_glass_tilted_left",
                   title: { en: "A buyer checked them", ar: "مشترٍ فحصها" },
                   text: { en: "A buyer took them to a store. Fake. They posted about it with your name.", ar: "أخذها مشترٍ إلى متجر. مقلّدة. ونشر عن ذلك مع ذكر اسمك." },
                   fx: { coins: -30, rep: -10 } } },
      B: { label: { en: "Pass", ar: "التجاوز" },
           fx: {},
           log: { en: "Too good to be true usually isn't true.", ar: "ما يبدو أجمل من أن يُصدّق غالبًا لا يُصدّق." } },
      C: { needs: 70, label: { en: "Learn how to check if things are real", ar: "تعلّم كيفية التأكد من الأصلي" },
           fx: { quality: 10, energy: -4 },
           log: { en: "Stitching, labels, boxes. Now you can tell in a minute.", ar: "الخياطة والملصقات والعلب. والآن صار التمييز يحتاج دقيقة." } },
      idea: { en: "Selling something fake as real is borrowing against your name.", ar: "بيع المقلّد كأصلي اقتراض على اسمك." },
    },
    {
      id: "r_grandma", biz: "resell", img: "old_woman", when: { minWeek: 3 },
      title: { en: "A jacket worth much more", ar: "سترة تساوي أكثر بكثير" },
      text: { en: "An elderly lady is selling her late husband's vintage jacket for 5 coins. You know it resells for 40.", ar: "سيدة مسنّة تبيع سترة قديمة لزوجها الراحل بـ5 عملات. ومعروف لك أنها تُباع بـ40." },
      A: { label: { en: "Buy it for 5", ar: "شراؤها بـ5" },
           fx: { coins: 35 },
           log: { en: "A great flip. You didn't look back.", ar: "صفقة رائعة. ولم يكن هناك التفات إلى الوراء." } },
      B: { label: { en: "Tell her what it's worth and pay 20", ar: "إخبارها بقيمتها ودفع 20" },
           fx: { coins: 15, honest: 1 },
           log: { en: "She held your hand for a moment. Then she said she had a whole wardrobe.", ar: "أمسكت يدك لحظة. ثم قالت إن عندها خزانة كاملة." },
           echo: { after: [2, 3], img: "wrapped_gift",
                   title: { en: "The whole wardrobe", ar: "الخزانة كاملة" },
                   text: { en: "She called and offered you first pick of everything, at fair prices.", ar: "اتصلت وعرضت أن تكون أول من يختار من كل شيء، بأسعار عادلة." },
                   fx: { rep: 3, mods: [{ k: "cost", x: 0.7, weeks: 4 }] } } },
      idea: { en: "A good deal is one both sides would be happy to see written down.", ar: "الصفقة الجيدة هي التي يرضى الطرفان برؤيتها مكتوبة." },
    },
    {
      id: "r_room", biz: "resell", img: "package", when: { minWeek: 6 },
      title: { en: "Your room is full of stock", ar: "غرفتك امتلأت بالبضاعة" },
      text: { en: "There are bags of unsold things under your bed. Mum asks when they're leaving.", ar: "تحت السرير أكياس من أشياء لم تُبع. وماما تسأل متى ستخرج." },
      A: { label: { en: "Clearance weekend: everything cheap", ar: "عطلة تصفية: كل شيء رخيص" },
           fx: { coins: 18, energy: -4 },
           log: { en: "Most of it went. Your room has a floor again.", ar: "خرج أغلبها. وعادت أرضية الغرفة تظهر." } },
      B: { label: { en: "Keep it: it'll sell at full price eventually", ar: "الاحتفاظ بها، فستُباع بالسعر الكامل يومًا" },
           fx: { energy: -3 },
           log: { en: "Mum sighed. The bags stay.", ar: "تنهّدت ماما. والأكياس باقية." } },
      idea: { en: "Stock sitting still is money sitting still.", ar: "البضاعة الراكدة مال راكد." },
    },

    // ── Coding ──
    {
      id: "c_copy", biz: "code", img: "robot",
      title: { en: "\"Copy everything from that website\"", ar: "«انسخ كل شيء من هذا الموقع»" },
      text: { en: "A client wants a bot that copies all the photos and reviews from a competitor's site onto theirs. 40 coins.", ar: "عميل يريد برنامجًا ينسخ كل الصور والتقييمات من موقع منافس إلى موقعه. مقابل 40 عملة." },
      A: { label: { en: "Build it", ar: "بناؤه" },
           fx: { coins: 40, honest: -1 },
           log: { en: "It worked on the first try.", ar: "عمل من أول مرة." },
           echo: { after: [2, 4], img: "incoming_envelope",
                   title: { en: "The competitor noticed", ar: "المنافس لاحظ" },
                   text: { en: "The other shop found their photos and complained. Your client took the site down and told people it was your idea.", ar: "وجد المحل الآخر صوره واشتكى. فأغلق عميلك الموقع وقال للناس إنها كانت فكرتك." },
                   fx: { rep: -8 } } },
      B: { label: { en: "Decline, and offer to help them make their own", ar: "الاعتذار، وعرض المساعدة في صنع محتوى خاص" },
           fx: { honest: 1, rep: 2, energy: -2 },
           log: { en: "They took a day to think, then said yes, for less money.", ar: "فكّروا يومًا ثم وافقوا، بمال أقل." } },
      idea: { en: "Just because code can do something doesn't mean it should.", ar: "قدرة الكود على فعل شيء لا تعني أنه يجب أن يُفعل." },
    },
    {
      id: "c_password", biz: "code", img: "locked",
      title: { en: "A password in the chat", ar: "كلمة سر في المحادثة" },
      text: { en: "A client sends the main password for their shop's website in a group chat so you can \"just log in\".", ar: "أرسل عميل كلمة السر الرئيسية لموقع محلّه في مجموعة محادثة لتسهيل «الدخول وخلاص»." },
      A: { label: { en: "Use it: saves time", ar: "استخدامها، فهذا أسرع" },
           fx: { coins: 5 },
           log: { en: "In and out in ten minutes.", ar: "دخول وخروج في عشر دقائق." },
           echo: { after: [2, 4], img: "warning",
                   title: { en: "Someone else used it too", ar: "شخص آخر استخدمها أيضًا" },
                   text: { en: "Someone in that group logged in and changed the prices. The client asked if it was you.", ar: "دخل أحد أفراد المجموعة وغيّر الأسعار. وسأل العميل إن كان ذلك منك." },
                   fx: { rep: -6, energy: -5 } } },
      B: { label: { en: "Ask them to change it and make you your own login", ar: "طلب تغييرها وإنشاء حساب خاص لك" },
           fx: { honest: 1, rep: 4 },
           log: { en: "They didn't know that was possible. They thanked you.", ar: "لم يعرفوا أن هذا ممكن. وشكروك." } },
      idea: { en: "Good security is a service. Clients remember who protected them.", ar: "الأمان الجيد خدمة. والعملاء يتذكّرون من حماهم." },
    },
    {
      id: "c_deadline", biz: "code", img: "hourglass_not_done", when: { minWeek: 4 },
      title: { en: "This job is 3 times bigger than you thought", ar: "هذا العمل أكبر بـ3 أضعاف مما ظننت" },
      text: { en: "Halfway through, you realise the club's website will take three times as long as you promised.", ar: "في منتصف الطريق اتضح أن موقع النادي سيستغرق ثلاثة أضعاف الوقت الموعود." },
      A: { label: { en: "Rush it and deliver on time, bugs and all", ar: "الاستعجال والتسليم في الموعد بالأخطاء" },
           fx: { energy: -6, rep: -4 },
           log: { en: "Delivered on time. Half the buttons don't work.", ar: "سُلّم في الموعد. ونصف الأزرار لا تعمل." },
           echo: { after: [1, 2], img: "face_with_spiral_eyes",
                   title: { en: "The bug reports", ar: "بلاغات الأخطاء" },
                   text: { en: "The club sent a list of 14 problems. Fixing them took the whole weekend.", ar: "أرسل النادي قائمة بـ14 مشكلة. واستغرق إصلاحها العطلة كلها." },
                   fx: { energy: -8 } } },
      B: { label: { en: "Tell them early and agree a new date", ar: "إخبارهم مبكرًا والاتفاق على موعد جديد" },
           fx: { rep: 2, energy: -3 },
           log: { en: "They were fine with it. They said most people only say it on the last day.", ar: "لم يمانعوا. وقالوا إن أغلب الناس يقولونها في اليوم الأخير." } },
      C: { needs: 70, label: { en: "Cut it to what matters most, and deliver on time", ar: "الاكتفاء بالأهم والتسليم في الموعد" },
           fx: { quality: 8, rep: 3 },
           log: { en: "Three pages that work beat ten that don't.", ar: "ثلاث صفحات تعمل أفضل من عشر لا تعمل." } },
      idea: { en: "Bad news early is a favour. Bad news late is a problem.", ar: "الخبر السيئ المبكر معروف. والخبر السيئ المتأخر مشكلة." },
    },
  ],
};

if (typeof module !== "undefined") module.exports = TEEN;
