// Founder Fog book, chapters 2 to 12. Same rules as content.js. Each chapter: an opener (title, week,
// lead, one line from Hisham), 4 scenes that each end with "The fog lifts", and a tools page.
// The company is Daftar (دفتر), a small app that helps shops collect what customers owe them.
// Ideas and sources follow the game's Founder Playbook, with its Arabic titles.
const t = (en, ar) => ({ en, ar });
const lift = (ten, tar, den, dar, sen, sar) => ({ t: t(ten, tar), d: t(den, dar), ...(sen ? { src: t(sen, sar) } : {}) });
const sc = (art, title, text, l, extra = {}) => ({ art, title, text, lift: l, ...extra });
const eq = (a, op, b, c, la, lb, lc) => ({ type: "equation", eq: { a, op, b, c, la, lb, lc } });

module.exports = [
  // ───────── 2 ─────────
  {
    title: t("Looking for fit", "البحث عن التوافق"), week: 2, open: "c2open",
    lead: t("An idea is a guess. The first weeks of a company are about finding out, as cheaply as possible, which part of the guess is wrong.",
            "الفكرة تخمين. والأسابيع الأولى في عمر شركة هي لمعرفة الجزء الخاطئ من هذا التخمين، بأقل تكلفة ممكنة."),
    quote: t("Don't fall in love with the app. Fall in love with Umm Hany's shoebox.", "لا تقعوا في حب التطبيق. بل في حب علبة أحذية أم هاني."), quoteBy: t("Hisham", "هشام"),
    scenes: [
      sc("c2s1", t("A spreadsheet and a phone", "جدول وهاتف"),
        t("Tariq wanted 3 months to build the app. Hisham gave them one week and no code. So they made a spreadsheet of what 10 shops were owed, and Salma sent every payment reminder by hand from her own phone, politely, with the amount and the date. Umm Hany was paid in 12 days instead of 40. Nobody had seen an app. Tariq looked at the spreadsheet for a long time. “So this is the product,” he said. “For now,” said Hisham.",
          "أراد طارق 3 أشهر لبناء التطبيق. فأعطاهما هشام أسبوعًا واحدًا، بلا برمجة. فصنعا جدولًا بما يُستحق لـ10 محلات، وأرسلت سلمى كل تذكير بالدفع بيدها من هاتفها، بأدب، مع المبلغ والتاريخ. وحصلت أم هاني على أموالها في 12 يومًا بدلًا من 40. لم يرَ أحد تطبيقًا. وظل طارق ينظر إلى الجدول طويلًا، ثم قال: «إذن هذا هو المنتج.» فقال هشام: «حتى الآن.»"),
        lift("Run small experiments", "أجرِ تجارب صغيرة",
          "Build the smallest thing that can prove you wrong, measure what people actually do, and learn. What matters is how fast each loop goes.",
          "ابنِ أصغر شيء يمكن أن يثبت خطأك، وقِس ما يفعله الناس فعلًا، وتعلّم. المهم سرعة كل دورة.",
          "Eric Ries, The Lean Startup (2011)", "إريك ريس، The Lean Startup (2011)")),
      sc("c2s2", t("7 in the morning", "السابعة صباحًا"),
        t("Shops open early, so Salma did too. Every new shop got a visit at 7 in the morning, a cup of tea, and 20 minutes of her time. She set up their list herself and wrote down every question they asked. By the end of the month her notebook held 63 questions. The same 5 came up again and again. Tariq built answers to those 5, and nothing else.",
          "المحلات تفتح مبكرًا، فصارت سلمى تبدأ مبكرًا أيضًا. كل محل جديد كان يحصل على زيارة في السابعة صباحًا، وكوب شاي، و20 دقيقة من وقتها. كانت تُعدّ قائمتهم بنفسها، وتكتب كل سؤال يطرحونه. وفي آخر الشهر كان في دفترها 63 سؤالًا، يتكرر منها 5 مرة بعد مرة. فبنى طارق إجابات لهذه الـ5، ولا شيء غيرها."),
        lift("Do things that don't scale", "افعل ما لا يتوسّع",
          "Win the first users by hand, one at a time. It doesn't scale, and that is the point: you learn what they need before you automate it.",
          "اكسب المستخدمين الأوائل بيدك، واحدًا تلو الآخر. هذا لا يتوسّع، وهنا الفكرة: تتعلّم ما يحتاجونه قبل أن تؤتمته.",
          "Paul Graham, Do Things That Don't Scale (2013)", "بول غراهام، Do Things That Don't Scale (2013)")),
      sc("c2s3", t("500 sign-ups", "500 تسجيل"),
        t("Tariq posted a short video online, and by morning 500 shops had signed up. He took a screenshot of the number and sent it to everyone he knew. Hisham asked a different question. “How many used it twice?” Salma checked. 9. The other 491 had looked once and left. “500 is a nice number,” said Hisham. “9 is the one that tells you what to do.”",
          "نشر طارق مقطعًا قصيرًا على الإنترنت، وفي الصباح كان 500 محل قد سجّل. التقط صورة للرقم وأرسلها لكل من يعرف. أما هشام فسأل سؤالًا آخر: «كم محلًا استخدمه مرتين؟» راجعت سلمى: 9. أما الـ491 الباقون فنظروا مرة ورحلوا. قال هشام: «500 رقم جميل. لكن 9 هو الرقم الذي يخبرك بما يجب فعله.»"),
        lift("Vanity metrics", "مؤشرات الغرور",
          "Total sign-ups and downloads only go up and feel good. Watch the numbers that change what you do next, like people who come back.",
          "إجمالي التسجيلات والتنزيلات يرتفع دائمًا ويُشعر بالرضا. الأهم أرقام تغيّر خطوتك التالية، مثل من يعودون.",
          "Eric Ries, The Lean Startup (2011)", "إريك ريس، The Lean Startup (2011)"),
        eq("9", "÷", "500", "1.8%", t("came back", "عادوا"), t("signed up", "سجّلوا"), t("came back", "نسبة العودة"))),
      sc("c2s4", t("Very disappointed", "خيبة أمل كبيرة"),
        t("In week 6 Salma asked the 25 shops that used Daftar every week one question: how would you feel if you could no longer use it? 11 said very disappointed. That is 44%. Umm Hany said it louder than anyone. “Don't you dare,” she said, and laughed. Hisham nodded slowly. “Above 40% is a sign. Not a promise. A sign.” For the first time, the fog moved a little.",
          "في الأسبوع 6 سألت سلمى الـ25 محلًا التي تستخدم «دفتر» كل أسبوع سؤالًا واحدًا: كيف سيكون شعوركم لو لم يعد بإمكانكم استخدامه؟ قال 11 منهم: خيبة أمل كبيرة. أي 44%. وقالتها أم هاني بصوت أعلى من الجميع: «إياكم أن تفعلوا!» ثم ضحكت. هزّ هشام رأسه ببطء: «فوق 40% علامة. ليست وعدًا، بل علامة.» ولأول مرة تحرّك الضباب قليلًا."),
        lift("Product-market fit", "التوافق مع السوق",
          "Ask users how they would feel without your product. If 40% or more say very disappointed, you may be close to fit.",
          "اسأل المستخدمين عن شعورهم دون منتجك. إذا قال 40% أو أكثر «خيبة أمل كبيرة»، فقد تكون قريبًا من التوافق.",
          "Sean Ellis's 40% test", "اختبار الـ40% لشون إليس")),
    ],
    tools: {
      title: t("Tools for week 2", "أدوات الأسبوع 2"),
      sections: [
        { type: "lines", title: t("1. Our riskiest guess", "1. أخطر تخمين لدينا"), n: 2 },
        { type: "lines", title: t("2. The smallest test this week, and the result that would change our mind", "2. أصغر تجربة هذا الأسبوع، والنتيجة التي ستغيّر رأينا"), n: 3 },
        { type: "calc", title: t("3. The 40% question", "3. سؤال الـ40%"), op: "÷", a: t("very disappointed", "خيبة أمل كبيرة"), b: t("asked", "عدد من سُئلوا"), c: t("%", "%") },
      ],
    },
  },

  // ───────── 3 ─────────
  {
    title: t("The angel", "المستثمرة الملاك"), week: 5, open: "c3open",
    lead: t("The first money from outside always feels like a gift. It is a trade, and it is worth reading every line of it.",
            "أول مال من الخارج يبدو دائمًا كهدية. لكنه صفقة، وكل سطر فيها يستحق القراءة."),
    quote: t("Valuation is the number everyone talks about. Control is the one that hurts later.", "التقييم هو الرقم الذي يتحدث عنه الجميع. أما التحكّم فهو ما يؤلم لاحقًا."), quoteBy: t("Hisham", "هشام"),
    scenes: [
      sc("c3s1", t("$50,000 for 20%", "50,000 دولار مقابل 20%"),
        t("Layla Fahmy had run a bank's small business desk for 20 years. She had heard about Daftar from Umm Hany's brother, of all people. Over coffee she made an offer: $50,000 for 20% of the company. Tariq did the sum on a napkin. That meant the whole company was worth $250,000 after her money. Last month it had been worth nothing. Salma didn't say yes. She said, “Can we think about it for a week?”",
          "أدارت ليلى فهمي قسم المشروعات الصغيرة في بنك طوال 20 عامًا. وقد سمعت عن «دفتر» من أخي أم هاني تحديدًا. وعلى فنجان قهوة قدّمت عرضًا: 50,000 دولار مقابل 20% من الشركة. أجرى طارق الحساب على منديل: أي أن الشركة كلها تساوي 250,000 دولار بعد أموالها. وقبل شهر لم تكن تساوي شيئًا. لم تقل سلمى نعم، بل قالت: «هل نفكّر أسبوعًا؟»"),
        lift("Dilution", "تخفيف الحصة",
          "Every round sells part of the company. Dilution is fine when the company grows faster than your share shrinks.",
          "كل جولة تبيع جزءًا من الشركة. وتخفيف الحصة مقبول حين تنمو الشركة أسرع مما تتقلص حصتك.",
          "Brad Feld and Jason Mendelson, Venture Deals", "براد فيلد وجيسون مندلسون، Venture Deals"),
        eq("50,000", "÷", "250,000", "20%", t("her money ($)", "أموالها ($)"), t("value after ($)", "القيمة بعدها ($)"), t("of the company", "من الشركة"))),
      sc("c3s2", t("Why now?", "لماذا الآن؟"),
        t("“Shouldn't we wait until we're bigger?” asked Tariq. “Then we'd get a better price.” Hisham shook his head. “Raise when you have something moving and months left. Not when you're desperate.” They had 44% of shops saying very disappointed, and Salma still had 9 months of savings. A round usually takes months to close. If they waited until the money ran low, they would be negotiating from fear.",
          "سأل طارق: «ألا ننتظر حتى نكبر؟ سنحصل على سعر أفضل.» هزّ هشام رأسه: «اجمعا التمويل حين يكون لديكما شيء يتحرك، وأشهر متبقية. لا حين تكونان في ضيق.» كان لديهما 44% من المحلات يقولون «خيبة أمل كبيرة»، وما زال لدى سلمى مدّخرات تكفي 9 أشهر. والجولة تستغرق عادةً أشهرًا حتى تُغلق. ولو انتظرا حتى ينفد المال، لفاوضا من موقع الخوف."),
        lift("When to raise", "متى تجمع التمويل",
          "Raise with momentum and at least 6 months of runway. A round takes 3 to 6 months, so the real deadline is earlier than it looks.",
          "اجمع التمويل ومعك زخم ومدة صمود 6 أشهر على الأقل. الجولة تستغرق من 3 إلى 6 أشهر، فالموعد الحقيقي أبكر مما يبدو.",
          "Paul Graham, How to Raise Money (2013)", "بول غراهام، How to Raise Money (2013)")),
      sc("c3s3", t("The small print", "الشروط الصغيرة"),
        t("The term sheet was 3 pages. The price was on page 1. On page 3, in small letters, Layla would have a veto on every hire and on any spending above $2,000. Hisham put his finger on it. “This one is not about money. It is about who runs the company.” Salma called Layla and asked, plainly, to drop it. Layla smiled. “I wanted to see if you'd read it.” The veto went. The price stayed.",
          "كانت ورقة الشروط 3 صفحات. السعر في الصفحة 1. وفي الصفحة 3، بخط صغير، حق اعتراض لليلى على كل توظيف وعلى أي إنفاق يزيد عن 2,000 دولار. وضع هشام إصبعه عليه: «هذا البند ليس عن المال، بل عمّن يدير الشركة.» فاتصلت سلمى بليلى وطلبت حذفه بوضوح. ابتسمت ليلى: «أردت أن أرى هل ستقرئينه.» حُذف حق الاعتراض، وبقي السعر."),
        lift("Reading a term sheet", "قراءة ورقة الشروط",
          "A term sheet has economics (valuation, preference) and control (board seats, vetoes). Founders fixate on the price and sign away control.",
          "في ورقة الشروط بنود اقتصادية (التقييم، الأفضلية) وبنود تحكّم (مقاعد المجلس، حق الاعتراض). المؤسسون ينشغلون بالسعر ويتنازلون عن التحكّم.",
          "Brad Feld and Jason Mendelson, Venture Deals", "براد فيلد وجيسون مندلسون، Venture Deals")),
      sc("c3s4", t("The first update", "التحديث الأول"),
        t("On the first day of every month, Salma sent Layla one short email. 4 parts: the numbers, the wins, the problems, and one thing she needed. The first problem she wrote about was embarrassing: 3 shops had left because reminders went out on the wrong day. Layla replied in an hour. She didn't scold. She introduced them to a wholesaler called Omar Sabry, who sold to 300 shops on credit.",
          "في أول يوم من كل شهر كانت سلمى ترسل إلى ليلى رسالة قصيرة واحدة من 4 أجزاء: الأرقام، والإنجازات، والمشكلات، وطلب واحد. وكانت أول مشكلة كتبتها محرجة: 3 محلات رحلت لأن التذكيرات خرجت في اليوم الخطأ. ردّت ليلى خلال ساعة. لم تلُمها، بل عرّفتها على تاجر جملة اسمه عمر صبري، يبيع لـ300 محل بالآجل."),
        lift("Investor updates", "تحديثات المستثمرين",
          "A short monthly update: numbers, wins, problems and a specific ask. Investors who hear bad news early tend to help.",
          "تحديث شهري قصير: أرقام وإنجازات ومشكلات وطلب محدد. المستثمر الذي يسمع الأخبار السيئة مبكرًا يميل إلى المساعدة.",
          "Brad Feld and Jason Mendelson, Venture Deals", "براد فيلد وجيسون مندلسون، Venture Deals")),
    ],
    tools: {
      title: t("Tools for week 5", "أدوات الأسبوع 5"),
      sections: [
        { type: "calc", title: t("1. What share are we selling?", "1. أي حصة نبيع؟"), op: "÷", a: t("investment", "الاستثمار"), b: t("value after", "القيمة بعده"), c: t("% sold", "% مباعة") },
        { type: "checks", title: t("2. Term sheet: mark every line that lets someone else say no", "2. ورقة الشروط: علامة على كل بند يسمح لغيرك بقول لا"), items: [
          t("Valuation and option pool", "التقييم ومجمع خيارات الأسهم"), t("Liquidation preference", "أفضلية التصفية"),
          t("Board seats", "مقاعد مجلس الإدارة"), t("Vetoes on hiring, spending or new rounds", "حق الاعتراض على التوظيف أو الإنفاق أو الجولات الجديدة"),
        ] },
        { type: "checks", title: t("3. This month's update", "3. تحديث هذا الشهر"), items: [
          t("The numbers", "الأرقام"), t("The wins", "الإنجازات"), t("The problems", "المشكلات"), t("One specific ask", "طلب واحد محدد"),
        ] },
      ],
    },
  },

  // ───────── 4 ─────────
  {
    title: t("The big customer", "العميل الكبير"), week: 7, open: "c4open",
    lead: t("A big customer can make your year. It can also quietly take over your roadmap.",
            "العميل الكبير قد يصنع عامك. وقد يستولي على خطتك بهدوء."),
    quote: t("Every yes to one customer is a no to all the others. Say it with your eyes open.", "كل نعم لعميل واحد هي لا لكل الآخرين. فقُلها وعيناك مفتوحتان."), quoteBy: t("Hisham", "هشام"),
    scenes: [
      sc("c4s1", t("Just one feature", "ميزة واحدة فقط"),
        t("Omar Sabry's warehouse smelled of rice and cardboard. He liked Daftar. He would put all 300 of his shops on it, but only if they first built a special screen for him: credit limits per shop, his colours, his reports. A month of work for both founders. Tariq's eyes lit up. Salma asked, “Would any other customer use this screen?” Nobody could name one. They said no to the custom screen, and offered the product they had.",
          "كان مخزن عمر صبري تفوح منه رائحة الأرز والكرتون. أعجبه «دفتر»، وكان مستعدًا لوضع محلاته الـ300 كلها عليه، بشرط أن يبنيا له أولًا شاشة خاصة: حدود ائتمان لكل محل، وألوانه، وتقاريره. شهر عمل للمؤسسَين معًا. لمعت عينا طارق. أما سلمى فسألت: «هل سيستخدم هذه الشاشة أي عميل آخر؟» لم يستطع أحد أن يسمّي عميلًا. فرفضا الشاشة الخاصة، وعرضا المنتج الموجود."),
        lift("Custom work for one customer", "عمل مخصص لعميل واحد",
          "A big customer's custom request is a gift and a trap. It brings money now, and puts their name on your roadmap.",
          "طلب العميل الكبير المخصص هدية وفخ معًا. يجلب المال الآن، ويضع اسمه على خطتك.",
          "Marty Cagan, Inspired", "مارتي كاغان، Inspired")),
      sc("c4s2", t("$5 is too cheap", "5 دولارات رخيصة جدًا"),
        t("Before he walked them out, Omar asked the price. “$5 a month per shop,” said Salma. He laughed. “My shops lose more than that in a day of chasing.” That night they tried something frightening. The next 10 shops were quoted $8. 9 said yes. Nobody had pushed back on $5 because $5 was too low. The 3 extra dollars, times every shop, went almost straight to profit.",
          "قبل أن يودّعهما سأل عمر عن السعر. قالت سلمى: «5 دولارات شهريًا لكل محل.» فضحك: «محلاتي تخسر أكثر من ذلك في يوم واحد من الملاحقة.» وفي تلك الليلة جرّبا شيئًا مخيفًا: عرضا على المحلات الـ10 التالية سعر 8 دولارات. وافق 9 منها. لم يعترض أحد على 5 دولارات لأنها كانت أقل من اللازم. والدولارات الـ3 الإضافية، مضروبة في كل محل، ذهبت إلى الربح تقريبًا كما هي."),
        lift("Pricing", "التسعير",
          "Most founders underprice because they fear hearing no. If nobody ever pushes back on your price, it is too low.",
          "معظم المؤسسين يسعّرون بأقل من القيمة خوفًا من سماع «لا». إذا لم يعترض أحد على سعرك أبدًا، فهو منخفض.",
          "Madhavan Ramanujam and Georg Tacke, Monetizing Innovation (2016)", "مادهافان راماناجام وجورج تاكي، Monetizing Innovation (2016)")),
      sc("c4s3", t("Fast and messy", "سريع وفوضوي"),
        t("To move fast, Tariq had taken shortcuts everywhere. Now every small change broke 2 other things. A new reminder time took a week instead of an afternoon. “It's like we borrowed time,” Tariq said, “and now we're paying interest.” They made a rule: every Thursday afternoon, no new features. Only cleaning up. The first Thursday felt wasted. By the fourth, changes were fast again.",
          "ليتحرك بسرعة، اختصر طارق الطريق في كل مكان. والآن صار كل تغيير صغير يكسر شيئين آخرين. تعديل موعد التذكير استغرق أسبوعًا بدلًا من بعد ظهر واحد. قال طارق: «كأننا اقترضنا وقتًا، والآن ندفع الفائدة.» فوضعا قاعدة: كل خميس بعد الظهر، لا ميزات جديدة، بل تنظيف فقط. بدا الخميس الأول ضائعًا. وبحلول الخميس الرابع عادت التغييرات سريعة."),
        lift("Tech debt", "الدين التقني",
          "Shipping fast is borrowing. Messy code charges interest on every future change. Some debt is smart, if you pay it back on purpose.",
          "الإطلاق السريع اقتراض، والكود الفوضوي يفرض فائدة على كل تغيير لاحق. بعض الدين ذكي، إن سُدّد عن قصد.",
          "Ward Cunningham, The WyCash Portfolio Management System (1992)", "وارد كننغهام، The WyCash Portfolio Management System (1992)")),
      sc("c4s4", t("What if it leaks?", "ماذا لو تسرّبت؟"),
        t("6 weeks later Omar called back. He would try the normal product with 40 shops. But his IT manager had one question first: where is the shops' data, and who can see it? They had no good answer. Names, phone numbers and debts, for real families. They spent 2 weeks on it: backups, access only for those who need it, and a short page explaining it all in plain words. Omar's manager read it twice and signed.",
          "بعد 6 أسابيع عاد عمر واتصل. سيجرّب المنتج العادي مع 40 محلًا. لكن مدير التقنية لديه كان عنده سؤال أولًا: أين بيانات المحلات، ومن يستطيع رؤيتها؟ لم يكن لديهما جواب جيد. أسماء وأرقام هواتف وديون لعائلات حقيقية. فقضيا أسبوعين في ذلك: نسخ احتياطية، وصلاحيات لمن يحتاجها فقط، وصفحة قصيرة تشرح كل شيء بكلمات بسيطة. قرأها المدير مرتين، ثم وقّع."),
        lift("Security is a feature", "الأمان ميزة",
          "Startups treat security as a later problem, until one leak ends a contract. Customers buy trust before they buy features.",
          "الشركات الناشئة تؤجل الأمان، حتى يُنهي تسريب واحد عقدًا. والعميل يشتري الثقة قبل أن يشتري الميزات.",
          "IBM, Cost of a Data Breach Report", "IBM، Cost of a Data Breach Report")),
    ],
    tools: {
      title: t("Tools for week 7", "أدوات الأسبوع 7"),
      sections: [
        { type: "checks", title: t("1. Before saying yes to custom work", "1. قبل الموافقة على عمل مخصص"), items: [
          t("Would 3 other customers use it?", "هل سيستخدمه 3 عملاء آخرون؟"), t("Who looks after it a year from now?", "من سيرعاه بعد عام؟"),
          t("What do we stop doing to build it?", "ما الذي سنتوقف عنه لبنائه؟"), t("Does the price cover all of that?", "هل يغطي السعر كل ذلك؟"),
        ] },
        { type: "calc", title: t("2. A price test for the next 10 customers", "2. اختبار سعر لأول 10 عملاء قادمين"), op: "×", a: t("today's price", "سعر اليوم"), b: t("1.2", "1.2"), c: t("test price", "سعر الاختبار") },
        { type: "lines", title: t("3. Our 3 worst shortcuts, to clean up on Thursdays", "3. أسوأ 3 اختصارات لدينا، للتنظيف أيام الخميس"), n: 3 },
      ],
    },
  },

  // ───────── 5 ─────────
  {
    title: t("Four days without sleep", "أربعة أيام بلا نوم"), week: 9, open: "c5open",
    lead: t("Companies rarely die from one bad decision. More often the founders run out of patience with each other, or with themselves.",
            "نادرًا ما تموت الشركات بقرار سيئ واحد. الأغلب أن ينفد صبر المؤسسين على بعضهم، أو على أنفسهم."),
    quote: t("A co-founder is a marriage with a spreadsheet. Talk before you need to.", "الشريك المؤسس زواج معه جدول حسابات. تحدّثا قبل أن تحتاجا."), quoteBy: t("Hisham", "هشام"),
    scenes: [
      sc("c5s1", t("3 in the morning", "الثالثة فجرًا"),
        t("A release went wrong on Sunday, and Tariq stayed up to fix it. And Monday. And Tuesday. By Wednesday he hadn't really slept in 4 days. In the team meeting he snapped at Salma over a button colour. Everyone looked at the table. Afterwards he sat on the stairs with his head in his hands. “I'm fine,” he said, before she could ask. He was not fine. He was in the fog, and he could not see it.",
          "تعطّل إطلاق يوم الأحد، فسهر طارق لإصلاحه. ثم الاثنين، ثم الثلاثاء. وبحلول الأربعاء لم يكن قد نام نومًا حقيقيًا منذ 4 أيام. وفي اجتماع الفريق انفجر في سلمى بسبب لون زر. نظر الجميع إلى الطاولة. وبعد الاجتماع جلس على الدرج ورأسه بين يديه، وقال قبل أن تسأله: «أنا بخير.» لم يكن بخير. كان في الضباب، ولا يراه."),
        lift("Burnout", "الاحتراق",
          "Burnout is a slow leak, not a single crash: short nights, no exercise, every evening at work. A tired founder makes worse decisions and hides it well.",
          "الاحتراق تسرّب بطيء لا انهيار مفاجئ: ليالٍ قصيرة، ولا رياضة، وكل مساء في العمل. والمؤسس المتعب يتخذ قرارات أسوأ ويُخفي ذلك جيدًا.",
          "Michael A. Freeman et al., Are Entrepreneurs Touched with Fire? (2015)", "مايكل فريمان وزملاؤه، Are Entrepreneurs Touched with Fire? (2015)")),
      sc("c5s2", t("The talk they skipped", "الحديث الذي أجّلاه"),
        t("Hisham took them both to lunch and did not let them talk about the product. Who decides what gets built? Salma, after listening to customers. Who decides how? Tariq, always. What happens when they disagree? They sleep on it, then Salma breaks the tie on customers and Tariq on code. It took 2 hours. It should have taken place in week 1. Walking back, Tariq said, “I thought you didn't trust my work.” “I thought you didn't trust my judgement,” said Salma. Both were wrong.",
          "أخذهما هشام إلى الغداء ولم يسمح لهما بالحديث عن المنتج. من يقرّر ماذا يُبنى؟ سلمى، بعد الاستماع إلى العملاء. ومن يقرّر كيف؟ طارق، دائمًا. وماذا يحدث عند الخلاف؟ ينامان على الأمر، ثم تحسم سلمى ما يخص العملاء، ويحسم طارق ما يخص الكود. استغرق ذلك ساعتين، وكان يجب أن يحدث في الأسبوع 1. وفي طريق العودة قال طارق: «ظننتكِ لا تثقين بعملي.» فقالت سلمى: «وظننتك لا تثق بحكمي.» وكان كلاهما مخطئًا."),
        lift("The co-founder relationship", "العلاقة مع الشريك المؤسس",
          "Problems inside the founding team cause about 65% of failures in high-potential startups. Agree early on roles, who decides what, and what happens if someone leaves.",
          "مشكلات فريق التأسيس تقف وراء نحو 65% من حالات فشل الشركات الواعدة. اتفقوا مبكرًا على الأدوار، ومن يقرّر ماذا، وماذا يحدث إذا رحل أحد.",
          "Noam Wasserman, The Founder's Dilemmas (2012)", "نوام واسرمان، The Founder's Dilemmas (2012)")),
      sc("c5s3", t("Letting go of the keys", "التخلّي عن المفاتيح"),
        t("With Layla's money they had hired 2 developers, Mona and Hassan. But every release still went through Tariq, at night. Hisham asked Tariq what he wanted from a release. “No shop gets a wrong reminder,” he said. “Then give Mona that,” said Hisham. “Not the steps. The result.” Mona wrote her own checklist, better than his. Tariq slept 8 hours that Thursday, and nothing broke.",
          "بأموال ليلى وظّفا مطوّرَين: منى وحسن. لكن كل إطلاق ظل يمر عبر طارق، ليلًا. سأله هشام عمّا يريده من الإطلاق. قال: «ألا يصل أي محل تذكير خاطئ.» فقال هشام: «إذن أعطِ منى هذه النتيجة. لا الخطوات، بل النتيجة.» كتبت منى قائمة فحص خاصة بها، أفضل من قائمته. ونام طارق 8 ساعات ذلك الخميس، ولم يتعطّل شيء."),
        lift("Delegate outcomes, not tasks", "فوّض النتائج لا المهام",
          "As the team grows, your output is your team's output. Hand over the result you need, and let people own how they get there.",
          "مع نمو الفريق يصبح إنتاجك هو إنتاج فريقك. سلّم النتيجة المطلوبة، ودع الناس يملكون طريقة الوصول إليها.",
          "Andy Grove, High Output Management (1983)", "آندي غروف، High Output Management (1983)")),
      sc("c5s4", t("What the team already knew", "ما كان الفريق يعرفه"),
        t("On Sunday Salma gathered the 4 of them. She told them what had happened, plainly: the broken release, the bad week, the shouting, and the new rules. Nobody was surprised. Mona said, “We thought it was worse. We thought the money was gone.” Silence had made them imagine something darker than the truth. After the meeting, Hassan asked if he could own the reminders schedule. Of course he could.",
          "يوم الأحد جمعت سلمى الأربعة. أخبرتهم بما حدث بوضوح: الإطلاق المعطّل، والأسبوع السيئ، والصراخ، والقواعد الجديدة. لم يتفاجأ أحد. قالت منى: «ظننا الأمر أسوأ. ظننا أن المال نفد.» فالصمت جعلهم يتخيّلون ما هو أشد قتامة من الحقيقة. وبعد الاجتماع سأل حسن إن كان يستطيع تولّي جدول التذكيرات. وبالطبع كان يستطيع."),
        lift("Tell the team the truth", "قل الحقيقة للفريق",
          "When things go wrong, the team usually senses it already. Silence makes them imagine something worse. A founder who tells the truth earns trust.",
          "حين تسوء الأمور يشعر الفريق بذلك غالبًا. والصمت يجعلهم يتخيّلون الأسوأ. والمؤسس الذي يقول الحقيقة يكسب الثقة.",
          "Ben Horowitz, The Hard Thing About Hard Things (2014)", "بن هوروويتز، The Hard Thing About Hard Things (2014)")),
    ],
    tools: {
      title: t("Tools for week 9", "أدوات الأسبوع 9"),
      sections: [
        { type: "checks", title: t("1. The weekly co-founder check-in, 30 minutes, no product talk", "1. لقاء الشركاء الأسبوعي، 30 دقيقة، بلا حديث عن المنتج"), items: [
          t("What frustrated each of us this week?", "ما الذي أحبطنا هذا الأسبوع؟"), t("Is anyone carrying too much?", "هل يحمل أحدنا أكثر من طاقته؟"),
          t("Any decision we are avoiding?", "هل هناك قرار نتجنّبه؟"), t("How are we sleeping?", "كيف نومنا؟"),
        ] },
        { type: "lines", title: t("2. One result to hand over this month, and to whom", "2. نتيجة واحدة تُسلَّم هذا الشهر، ولمن"), n: 2 },
        { type: "tally", title: t("3. Nights with 7 hours of sleep this week", "3. ليالٍ بنوم 7 ساعات هذا الأسبوع"), n: 7 },
      ],
    },
  },

  // ───────── 6 ─────────
  {
    title: t("The clock", "الساعة"), week: 12, open: "c6open",
    lead: t("Every company has a clock: cash divided by burn. Most founders know roughly how much time is left. The ones who last know exactly.",
            "لكل شركة ساعة: النقد مقسومًا على الحرق. معظم المؤسسين يعرفون الوقت المتبقي تقريبًا. أما من يصمدون فيعرفونه بالضبط."),
    quote: t("Runway is the only number that tells you how much courage you can afford.", "مدة الصمود هي الرقم الوحيد الذي يخبرك بقدر الشجاعة الذي تستطيع تحمّله."), quoteBy: t("Hisham", "هشام"),
    scenes: [
      sc("c6s1", t("8 months", "8 أشهر"),
        t("In week 12 Salma put the real numbers on the whiteboard. Cash in the bank: $64,000. What went out each month, after what came in: $8,000. 8 months. Then Hisham asked about the 2 hires they had planned for next quarter. With them, the burn became $12,000, and the clock dropped to just over 5 months. Tariq went quiet. “Always count the plan,” said Hisham. “Not just today.”",
          "في الأسبوع 12 كتبت سلمى الأرقام الحقيقية على السبورة. النقد في البنك: 64,000 دولار. وما يخرج كل شهر بعد ما يدخل: 8,000 دولار. أي 8 أشهر. ثم سأل هشام عن التوظيفين المخطط لهما في الربع القادم. معهما يصبح الحرق 12,000 دولار، وتهبط الساعة إلى ما يزيد قليلًا على 5 أشهر. صمت طارق. قال هشام: «احسبا الخطة دائمًا، لا اليوم فقط.»"),
        lift("Runway", "مدة الصمود",
          "Cash divided by net monthly burn. Include planned hires, and remember a round takes months to close, so the real deadline is earlier.",
          "النقد مقسومًا على صافي الحرق الشهري. أدخِل التوظيفات المخطط لها، وتذكّر أن الجولة تستغرق أشهرًا، فالموعد الحقيقي أبكر.",
          "Paul Graham, Startups in 13 Sentences (2009)", "بول غراهام، Startups in 13 Sentences (2009)"),
        eq("64,000", "÷", "8,000", "8", t("cash ($)", "النقد ($)"), t("burn a month ($)", "الحرق الشهري ($)"), t("months", "أشهر"))),
      sc("c6s2", t("What a shop is worth", "كم يساوي المحل"),
        t("How much did it cost to win one shop? Salma added up her mornings, the printed flyers and the tea: about $40. And what was a shop worth? $8 a month, and shops stayed about 18 months. $144. “So each shop brings back more than 3 times what it costs,” said Tariq. “Good,” said Hisham. “Now check it every month. That number moves when you are not looking.”",
          "كم يكلّف كسب محل واحد؟ جمعت سلمى صباحاتها والمنشورات المطبوعة والشاي: نحو 40 دولارًا. وكم يساوي المحل؟ 8 دولارات شهريًا، والمحلات تبقى نحو 18 شهرًا. أي 144 دولارًا. قال طارق: «إذن كل محل يعيد أكثر من 3 أضعاف تكلفته.» قال هشام: «جيد. والآن راجعاه كل شهر. هذا الرقم يتحرك حين لا تنظران.»"),
        lift("Unit economics", "اقتصاديات الوحدة",
          "Every customer should be worth more than they cost to win. A common rule: lifetime value at least 3 times the cost to acquire.",
          "يجب أن يساوي كل عميل أكثر مما كلّف كسبه. والقاعدة الشائعة: قيمة العميل طوال عمره 3 أضعاف تكلفة اكتسابه على الأقل.",
          "David Skok, SaaS Metrics 2.0", "ديفيد سكوك، SaaS Metrics 2.0")),
      sc("c6s3", t("Burning for growth", "حرق من أجل النمو"),
        t("Last quarter they had burned $24,000. In that time, yearly revenue grew by $9,600. Tariq divided one by the other: 2.5. “Is that good?” Hisham tilted his hand. “Under 1 is excellent. Over 3 is trouble. 2.5 means every new dollar of revenue is expensive.” They looked at where the money went. The online ads had brought sign-ups, not shops. They switched them off the next morning.",
          "في الربع الماضي حرقا 24,000 دولار. وخلال المدة نفسها نما الإيراد السنوي بمقدار 9,600 دولار. قسم طارق الأول على الثاني: 2.5. «هل هذا جيد؟» أمال هشام يده: «أقل من 1 ممتاز. وفوق 3 مشكلة. أما 2.5 فيعني أن كل دولار إيراد جديد غالٍ.» فنظرا إلى أين ذهب المال. الإعلانات على الإنترنت جلبت تسجيلات، لا محلات. فأوقفاها صباح اليوم التالي."),
        lift("Burn multiple", "مضاعف الحرق",
          "Net burn divided by net new yearly revenue. Under 1 is amazing, above 3 is bad. It shows whether growth is being bought at any price.",
          "صافي الحرق مقسومًا على صافي الإيراد السنوي الجديد. أقل من 1 ممتاز، وفوق 3 سيئ. يكشف إن كان النمو يُشترى بأي ثمن.",
          "David Sacks, The Burn Multiple (2020)", "ديفيد ساكس، The Burn Multiple (2020)")),
      sc("c6s4", t("Two lines", "خطّان"),
        t("Hisham drew 2 lines on the whiteboard. One was costs, going up slowly. The other was revenue, going up faster. If nothing changed, the lines would cross in month 15. But the money ran out in month 8. “Right now you are default dead,” he said, calmly. “That's not a verdict. It's a to-do list.” Salma wrote 3 things under the lines: raise prices, cut the ads, and get Omar's 40 shops live.",
          "رسم هشام خطّين على السبورة. الأول للتكاليف، يصعد ببطء. والثاني للإيراد، يصعد أسرع. لو لم يتغيّر شيء، يتقاطع الخطان في الشهر 15. لكن المال ينفد في الشهر 8. قال بهدوء: «أنتما الآن ميّتان افتراضيًا. هذا ليس حكمًا، بل قائمة مهام.» فكتبت سلمى 3 أشياء تحت الخطّين: رفع الأسعار، وإيقاف الإعلانات، وتشغيل محلات عمر الـ40."),
        lift("Default alive", "حيّ افتراضيًا",
          "If costs and revenue growth stay as they are, do you reach profit before the money runs out? If not, you need a plan, not hope.",
          "لو بقيت التكاليف ونمو الإيراد على حالها، هل تصل إلى الربح قبل نفاد المال؟ إن لم يكن، فأنت تحتاج خطة لا أملًا.",
          "Paul Graham, Default Alive or Default Dead? (2015)", "بول غراهام، Default Alive or Default Dead? (2015)")),
    ],
    tools: {
      title: t("Tools for week 12", "أدوات الأسبوع 12"),
      sections: [
        { type: "calc", title: t("1. Company runway, with next quarter's hires", "1. مدة صمود الشركة، مع توظيفات الربع القادم"), op: "÷", a: t("cash", "النقد"), b: t("net burn a month", "صافي الحرق الشهري"), c: t("months", "أشهر") },
        { type: "calc", title: t("2. Unit economics", "2. اقتصاديات الوحدة"), op: "÷", a: t("value of a customer", "قيمة العميل"), b: t("cost to win one", "تكلفة كسبه"), c: t("aim for 3+", "الهدف 3 أو أكثر") },
        { type: "calc", title: t("3. Burn multiple, last quarter", "3. مضاعف الحرق للربع الماضي"), op: "÷", a: t("net burn", "صافي الحرق"), b: t("new yearly revenue", "الإيراد السنوي الجديد"), c: t("under 1 is great", "أقل من 1 ممتاز") },
      ],
    },
  },

  // ───────── 7 ─────────
  {
    title: t("The rival", "المنافس"), week: 14, open: "c7open",
    lead: t("Sooner or later someone else sees the same problem, with more money. What you do in the next month matters more than what they announced.",
            "عاجلًا أو آجلًا يرى غيرك المشكلة نفسها، ومعه مال أكثر. وما تفعله في الشهر التالي أهم مما أعلنه."),
    quote: t("Their money is their problem. Your customers are yours.", "أموالهم مشكلتهم. وعملاؤك مسؤوليتك."), quoteBy: t("Hisham", "هشام"),
    scenes: [
      sc("c7s1", t("$5 million", "5 ملايين دولار"),
        t("The news came on a Tuesday: a rival had raised $5 million to do what Daftar did. Tariq read it 3 times. Salma's phone started ringing with people asking if they were finished. Hisham was calm. “Most good businesses never take that kind of money. Your shops pay you every month. That is funding too.” They had 140 paying shops. The rival had a press release.",
          "جاء الخبر يوم ثلاثاء: منافس جمع 5 ملايين دولار ليفعل ما يفعله «دفتر». قرأه طارق 3 مرات. وبدأ هاتف سلمى يرنّ بأناس يسألون إن كانوا قد انتهوا. أما هشام فكان هادئًا: «معظم المشاريع الجيدة لا تأخذ مالًا كهذا أبدًا. محلاتكما تدفع لكما كل شهر، وهذا تمويل أيضًا.» كان لديهما 140 محلًا يدفع. وكان لدى المنافس بيان صحفي."),
        lift("Funding without VCs", "التمويل بلا رأس مال جريء",
          "Venture capital suits companies that can grow 10 times in a few years. Many good businesses can't, and grow on customer revenue instead.",
          "رأس المال الجريء يناسب شركات تستطيع النمو 10 أضعاف في سنوات قليلة. وكثير من المشاريع الجيدة لا تستطيع، فتنمو بإيراد عملائها.",
          "Jason Fried and David Heinemeier Hansson, Rework (2010)", "جيسون فرايد وديفيد هاينماير هانسون، Rework (2010)")),
      sc("c7s2", t("Free for 6 months", "مجانًا 6 أشهر"),
        t("The rival offered shops 6 months free. In 2 weeks, 12 of Daftar's shops left. Salma called every one of them, not to argue, just to ask why. Most said the same thing: free is free. A month later, 7 came back. The rival's reminders went out at night and annoyed their customers. Salma wrote down the lesson anyway. 12 out of 140 in a month was more than 8%. At that pace, half the shops would be gone in a year.",
          "عرض المنافس على المحلات 6 أشهر مجانًا. وخلال أسبوعين رحل 12 محلًا من محلات «دفتر». اتصلت سلمى بكل واحد منها، لا لتجادل، بل لتسأل عن السبب. قال أغلبهم الشيء نفسه: المجاني مجاني. وبعد شهر عاد 7 منها، لأن تذكيرات المنافس كانت تخرج ليلًا وتزعج زبائنهم. ومع ذلك كتبت سلمى الدرس: 12 من 140 في شهر يعني أكثر من 8%. وبهذه الوتيرة يرحل نصف المحلات خلال عام."),
        lift("Churn", "التسرّب",
          "The share of customers who leave each month. 5% a month sounds small, but it means losing about 46% of your customers in a year.",
          "نسبة العملاء الذين يغادرون كل شهر. 5% شهريًا تبدو قليلة، لكنها تعني خسارة نحو 46% من عملائك خلال عام.",
          "David Skok, SaaS Metrics 2.0", "ديفيد سكوك، SaaS Metrics 2.0")),
      sc("c7s3", t("The one channel", "القناة الواحدة"),
        t("They listed everything they had tried to find shops: online ads, flyers, a stand at a trade fair, short videos, Salma's early mornings. Then they wrote next to each one how many paying shops it had brought. One line stood out. Omar's 40 shops had come from one conversation with one wholesaler. Wholesalers already had the shops, and the trust. They stopped almost everything else and went to see 5 more wholesalers.",
          "كتبا كل ما جرّباه للعثور على محلات: إعلانات الإنترنت، والمنشورات، وجناح في معرض تجاري، والمقاطع القصيرة، وصباحات سلمى الباكرة. ثم كتبا بجانب كل واحدة عدد المحلات الدافعة التي جلبتها. برز سطر واحد: محلات عمر الـ40 جاءت من محادثة واحدة مع تاجر جملة واحد. فتجّار الجملة يملكون المحلات والثقة أصلًا. فأوقفا كل شيء تقريبًا، وذهبا لمقابلة 5 تجّار جملة آخرين."),
        lift("Find one channel that works", "اعثر على قناة واحدة تنجح",
          "There are many ways to grow, from ads to partnerships, and most startups grow through one main channel. Find it, then put your effort there.",
          "طرق النمو كثيرة، من الإعلانات إلى الشراكات، ومعظم الشركات الناشئة تنمو عبر قناة رئيسية واحدة. اعثر عليها، ثم ضع جهدك فيها.",
          "Gabriel Weinberg and Justin Mares, Traction (2014)", "غابرييل واينبرغ وجاستن ميريس، Traction (2014)")),
      sc("c7s4", t("Just round it up", "قرّبي الرقم فقط"),
        t("An investor wanted to see their numbers before a call. “Let's count every shop that ever signed up,” said Tariq, tired. “Everyone does it.” That would be 600, not 140. Salma thought about Umm Hany, who trusted them with her family's money, and about Layla, who read every line. She sent 140, with churn, and a note on the rival. The investor didn't invest. But 2 months later he sent them a wholesaler.",
          "أراد مستثمر رؤية أرقامهما قبل مكالمة. قال طارق متعبًا: «لنحسب كل محل سجّل في أي وقت. الجميع يفعل ذلك.» سيصبح الرقم 600 لا 140. فكّرت سلمى في أم هاني التي ائتمنتهما على مال عائلتها، وفي ليلى التي تقرأ كل سطر. وأرسلت 140، مع نسبة التسرّب، وملاحظة عن المنافس. لم يستثمر الرجل. لكنه بعد شهرين أرسل إليهما تاجر جملة."),
        lift("Ethics under pressure", "الأخلاق تحت الضغط",
          "Small exaggerations become habits, and habits become fraud. The pressure is real, and so is the line. Report the number you would defend in a year.",
          "المبالغات الصغيرة تصبح عادات، والعادات تصبح احتيالًا. الضغط حقيقي، والخط الفاصل حقيقي أيضًا. أبلغ عن الرقم الذي ستدافع عنه بعد عام.",
          "John Carreyrou, Bad Blood (2018)", "جون كاريرو، Bad Blood (2018)")),
    ],
    tools: {
      title: t("Tools for week 14", "أدوات الأسبوع 14"),
      sections: [
        { type: "calc", title: t("1. Monthly churn", "1. التسرّب الشهري"), op: "÷", a: t("customers lost", "العملاء المفقودون"), b: t("customers at start", "العملاء في البداية"), c: t("% a month", "% شهريًا") },
        { type: "checks", title: t("2. Channels tried, and paying customers from each", "2. القنوات المجرّبة، والعملاء الدافعون من كل منها"), items: [
          t("Ads", "الإعلانات"), t("Partners", "الشركاء"), t("Events", "الفعاليات"), t("Content", "المحتوى"), t("Direct sales", "البيع المباشر"), t("Referrals", "التوصيات"),
        ] },
        { type: "lines", title: t("3. Numbers we will never round up", "3. أرقام لن نقرّبها أبدًا"), n: 2 },
      ],
    },
  },

  // ───────── 8 ─────────
  {
    title: t("Ramadan", "رمضان"), week: 21, open: "c8open",
    lead: t("The region has its own calendar, its own ways to pay, and its own idea of what a good company owes its people.",
            "للمنطقة تقويمها الخاص، وطرقها الخاصة في الدفع، وفكرتها الخاصة عمّا تدين به الشركة الجيدة لناسها."),
    quote: t("Your users live in a calendar. Build for theirs, not for a template from somewhere else.", "مستخدموك يعيشون في تقويم. ابنِ له، لا لقالب من مكان آخر."), quoteBy: t("Hisham", "هشام"),
    scenes: [
      sc("c8s1", t("After iftar", "بعد الإفطار"),
        t("In Ramadan everything moved. Shops opened late, closed after midnight, and did half their business after iftar. Daftar's reminders still went out at 10 in the morning, when nobody was awake to pay. Hassan moved them to 9 at night. Payments went up by a third. The team changed too: shorter days, no meetings before noon, and a long table for iftar together on Thursdays.",
          "في رمضان تحرّك كل شيء. المحلات تفتح متأخرة وتغلق بعد منتصف الليل، ونصف بيعها بعد الإفطار. أما تذكيرات «دفتر» فظلت تخرج في العاشرة صباحًا، حين لا أحد مستيقظ ليدفع. فنقلها حسن إلى التاسعة مساءً، فارتفعت المدفوعات بمقدار الثلث. وتغيّر الفريق أيضًا: أيام أقصر، ولا اجتماعات قبل الظهر، ومائدة إفطار طويلة معًا كل خميس."),
        lift("Ramadan and the regional calendar", "رمضان وتقويم المنطقة",
          "Usage peaks after iftar, B2B slows down, and the team expects time and an Eid bonus. Plan the year around the region's calendar.",
          "يبلغ الاستخدام ذروته بعد الإفطار، ويتباطأ البيع للشركات، وينتظر الفريق وقتًا ومكافأة العيد. خطّط العام حول تقويم المنطقة.",
          "Common practice in the region", "ممارسة شائعة في المنطقة")),
      sc("c8s2", t("Frozen", "مُجمَّد"),
        t("On the 15th night of Ramadan the payment provider froze Daftar's payouts for a review. 3 days, maybe more. Shops were waiting for their money before Eid. Salma did not hide. She called the 20 biggest shops herself, sent every shop a short message every 6 hours, and said exactly what she knew and didn't know. On the fourth day the money moved. Not one shop left. Umm Hany sent a box of sweets.",
          "في الليلة 15 من رمضان جمّد مزوّد الدفع تحويلات «دفتر» للمراجعة. 3 أيام، وربما أكثر. والمحلات تنتظر أموالها قبل العيد. لم تختبئ سلمى. اتصلت بأكبر 20 محلًا بنفسها، وأرسلت إلى كل محل رسالة قصيرة كل 6 ساعات، وقالت بالضبط ما تعرفه وما لا تعرفه. وفي اليوم الرابع تحرّك المال. لم يرحل محل واحد. وأرسلت أم هاني علبة حلوى."),
        lift("Managing a crisis", "إدارة الأزمة",
          "In a crisis, speed and honesty beat polish. Say what happened, what you are doing, and when the next update comes, then keep that promise.",
          "في الأزمة تتفوّق السرعة والصدق على التجميل. قل ما حدث، وما تفعله، ومتى التحديث التالي، ثم أوفِ بالوعد.",
          "Ben Horowitz, The Hard Thing About Hard Things (2014)", "بن هوروويتز، The Hard Thing About Hard Things (2014)")),
      sc("c8s3", t("Cash on delivery", "الدفع عند الاستلام"),
        t("Half of what shops were owed would never arrive by card. Their customers paid in cash, at the door, or when the salary came. Tariq had built Daftar for card payments only. So they added the simplest thing: a button to mark a debt as paid in cash, with a photo of the receipt if the shop wanted. It was not elegant. It was how the street actually worked, and usage doubled.",
          "نصف ما يُستحق للمحلات لن يصل أبدًا بالبطاقة. فزبائنهم يدفعون نقدًا، عند الباب، أو حين يأتي الراتب. وكان طارق قد بنى «دفتر» للدفع بالبطاقة فقط. فأضافا أبسط شيء: زر لتسجيل الدين مدفوعًا نقدًا، مع صورة الإيصال إن أراد المحل. لم يكن أنيقًا، لكنه كان طريقة عمل الشارع فعلًا، فتضاعف الاستخدام."),
        lift("Payments in the region", "المدفوعات في المنطقة",
          "Cash on delivery, late payers and payment providers that freeze funds are normal here. Build for how people really pay.",
          "الدفع عند الاستلام، والمتأخرون في السداد، ومزوّدو الدفع الذين يجمّدون الأموال، أمور عادية هنا. ابنِ لطريقة الدفع الحقيقية.",
          "Common practice in the region", "ممارسة شائعة في المنطقة")),
      sc("c8s4", t("The Eid bonus", "مكافأة العيد"),
        t("After the freeze, cash was tight, and Eid was coming. The team expected a bonus, as every company in Cairo gave one. Tariq suggested skipping it this year. Salma thought about what the team would remember. They paid half the usual bonus, explained why in a short honest note, and the 2 founders took none. Mona told her mother it was the best company she had worked for.",
          "بعد التجميد ضاق النقد، والعيد قادم. وكان الفريق ينتظر مكافأة، كما تفعل كل شركة في القاهرة. اقترح طارق تخطّيها هذا العام. أما سلمى ففكّرت فيما سيتذكره الفريق. فدفعا نصف المكافأة المعتادة، وشرحا السبب في رسالة قصيرة صادقة، ولم يأخذ المؤسسان شيئًا. وقالت منى لأمها إنها أفضل شركة عملت فيها."),
        lift("Culture is what you do", "الثقافة هي ما تفعله",
          "Culture is not the values on the wall. It is how people behave when nobody is watching, and it is set by what the founders actually do.",
          "الثقافة ليست القيم المعلّقة على الجدار، بل كيف يتصرف الناس حين لا يراقبهم أحد، وتصنعها أفعال المؤسسين الحقيقية.",
          "Ben Horowitz, What You Do Is Who You Are (2019)", "بن هوروويتز، What You Do Is Who You Are (2019)")),
    ],
    tools: {
      title: t("Tools for week 21", "أدوات الأسبوع 21"),
      sections: [
        { type: "checks", title: t("1. Our year, in the region's calendar", "1. عامنا، في تقويم المنطقة"), items: [
          t("Ramadan", "رمضان"), t("Eid al-Fitr", "عيد الفطر"), t("Eid al-Adha", "عيد الأضحى"), t("Summer holidays", "إجازة الصيف"), t("Back to school", "العودة إلى المدارس"), t("Year end", "نهاية العام"),
        ] },
        { type: "lines", title: t("2. A crisis message: what happened, what we are doing, when the next update comes", "2. رسالة أزمة: ما حدث، وما نفعله، ومتى التحديث التالي"), n: 3 },
      ],
    },
  },

  // ───────── 9 ─────────
  {
    title: t("The first salesperson", "أول مندوب مبيعات"), week: 26, open: "c9open",
    lead: t("The first hires shape the company more than any plan. Hire slowly, and be honest quickly when it isn't working.",
            "أوائل الموظفين يشكّلون الشركة أكثر من أي خطة. وظّف ببطء، وكن صادقًا بسرعة حين لا ينجح الأمر."),
    quote: t("You can't hire someone to do a job you've never done yourself.", "لا يمكنك أن توظّف شخصًا لعمل لم تقم به أنت أبدًا."), quoteBy: t("Hisham", "هشام"),
    scenes: [
      sc("c9s1", t("Who sells?", "من يبيع؟"),
        t("Salma was tired of selling. 5 wholesalers had said yes to a meeting, and she wanted someone else to go. Hisham asked her to do the first 5 herself. “Find out what they ask, what makes them say yes, and what makes them hesitate. Write it down. That's the job description.” She went. 3 signed. Her notes became a 1-page script, and only then did they start looking for a salesperson.",
          "تعبت سلمى من البيع. وافق 5 تجّار جملة على لقاء، وأرادت أن يذهب غيرها. فطلب منها هشام أن تقوم بأول 5 لقاءات بنفسها: «اعرفي ماذا يسألون، وما يجعلهم يقولون نعم، وما يجعلهم يترددون. اكتبي ذلك. هذا هو الوصف الوظيفي.» فذهبت. ووقّع 3. وصارت ملاحظاتها نصًا من صفحة واحدة، وعندها فقط بدآ البحث عن مندوب مبيعات."),
        lift("The founder sells first", "المؤسس يبيع أولًا",
          "Early on, the founders sell. It is how you learn what customers need, and it is the only way to know what a good salesperson looks like.",
          "في البداية يبيع المؤسسون. هكذا تتعلّم ما يحتاجه العملاء، وهي الطريقة الوحيدة لمعرفة شكل مندوب المبيعات الجيد.",
          "Paul Graham, Do Things That Don't Scale (2013)", "بول غراهام، Do Things That Don't Scale (2013)")),
      sc("c9s2", t("Ziad", "زياد"),
        t("Ziad had a great handshake and a better slide deck. He booked 6 meetings in his first week, and the dashboard filled with deals. In week 4, in front of the team, he called Mona's reminder design “a student project.” Mona stopped talking in meetings. Hassan started looking at other jobs. Ziad was bringing in meetings. He was also emptying the room.",
          "كان لزياد مصافحة رائعة، وعرض تقديمي أروع. حجز 6 لقاءات في أسبوعه الأول، وامتلأت لوحة المتابعة بالصفقات. وفي الأسبوع 4، أمام الفريق، وصف تصميم منى للتذكيرات بأنه «مشروع طالب». فتوقفت منى عن الكلام في الاجتماعات، وبدأ حسن يبحث عن وظائف أخرى. كان زياد يجلب اللقاءات، وكان أيضًا يُفرغ الغرفة."),
        lift("No brilliant jerks", "لا مكان للعبقري المؤذي",
          "A talented person who belittles others costs more than they deliver: good people stop speaking up, then they leave.",
          "الموهوب الذي يحتقر الآخرين يكلّف أكثر مما يقدّم: يتوقف الجيدون عن الكلام، ثم يرحلون.",
          "Netflix Culture: Freedom & Responsibility (2009)", "Netflix Culture: Freedom & Responsibility (2009)")),
      sc("c9s3", t("A pipeline of air", "صفقات من هواء"),
        t("After 8 weeks the dashboard showed $90,000 of deals. Salma called 5 of them. 2 had never heard of Daftar. 3 had said “maybe later.” Nothing had closed. She had known for weeks and kept hoping. On a Sunday morning she told Ziad, kindly and clearly, that it was not working, paid him fairly, and thanked him. Then she told the team why. Mona spoke in the next meeting.",
          "بعد 8 أسابيع أظهرت اللوحة صفقات بقيمة 90,000 دولار. اتصلت سلمى بـ5 منها. 2 لم يسمعا بـ«دفتر» قط، و3 قالوا «ربما لاحقًا». لم يُغلق شيء. كانت تعرف منذ أسابيع، وظلت تأمل. وفي صباح يوم أحد أخبرت زيادًا، بلطف ووضوح، أن الأمر لا ينجح، ودفعت له بإنصاف، وشكرته. ثم أخبرت الفريق بالسبب. وتكلّمت منى في الاجتماع التالي."),
        lift("Hire slowly, part ways quickly", "وظّف ببطء وافترق بسرعة",
          "A bad early hire costs far more than a salary: months of lost work and a team that has to compensate. The conversation you postpone gets more expensive.",
          "التوظيف الخاطئ المبكر يكلّف أكثر بكثير من راتب: أشهر من العمل الضائع وفريق يعوّض. والحديث الذي تؤجّله يزداد كلفة.",
          "Ben Horowitz, The Hard Thing About Hard Things (2014)", "بن هوروويتز، The Hard Thing About Hard Things (2014)")),
      sc("c9s4", t("Bad news on page 1", "الخبر السيئ في الصفحة 1"),
        t("Layla now sat on a small board with Salma and Tariq. Before the first meeting Salma did what Hisham had told her: she sent the papers 3 days early, and put the bad news on page 1. Ziad, the empty pipeline, and what it had cost. Layla read it before the meeting, so the meeting was not a surprise. It was a conversation about what to do next. It took 40 minutes.",
          "صارت ليلى عضوًا في مجلس صغير مع سلمى وطارق. وقبل الاجتماع الأول فعلت سلمى ما قاله هشام: أرسلت الأوراق قبل 3 أيام، ووضعت الخبر السيئ في الصفحة 1. زياد، والصفقات الفارغة، وما كلّفته. قرأت ليلى كل شيء قبل الاجتماع، فلم يكن الاجتماع مفاجأة، بل حديثًا عمّا يجب فعله بعد ذلك. واستغرق 40 دقيقة."),
        lift("Working with a board", "العمل مع مجلس الإدارة",
          "Treat the board as a group you lead, not an exam you sit. Send materials 3 days early and put bad news on the first page.",
          "عامل المجلس كمجموعة تقودها، لا كامتحان تجلس له. أرسل المواد قبل 3 أيام، وضع الأخبار السيئة في الصفحة الأولى.",
          "Brad Feld and Mahendra Ramsinghani, Startup Boards (2014)", "براد فيلد وماهيندرا رامسينغاني، Startup Boards (2014)")),
    ],
    tools: {
      title: t("Tools for week 26", "أدوات الأسبوع 26"),
      sections: [
        { type: "checks", title: t("1. Before any hire", "1. قبل أي توظيف"), items: [
          t("A real work sample, not just an interview", "عيّنة عمل حقيقية، لا مقابلة فقط"), t("2 reference calls we found ourselves", "مكالمتان مع مراجع وجدناها بأنفسنا"),
          t("Time with the whole team", "وقت مع الفريق كله"), t("How do they talk about past colleagues?", "كيف يتحدّث عن زملائه السابقين؟"),
        ] },
        { type: "lines", title: t("2. The sales script: what customers ask, and what makes them say yes", "2. نص البيع: ماذا يسأل العملاء، وما يجعلهم يقولون نعم"), n: 3 },
        { type: "lines", title: t("3. Page 1 of the next board pack: the bad news", "3. الصفحة 1 من أوراق المجلس القادمة: الخبر السيئ"), n: 2 },
      ],
    },
  },

  // ───────── 10 ─────────
  {
    title: t("The licence and the family", "الترخيص والعائلة"), week: 30, open: "c10open",
    lead: t("Some of the hardest parts of the year happen far from the product: in a regulator's office, at a bank, and at the family dinner table.",
            "بعض أصعب لحظات العام تحدث بعيدًا عن المنتج: في مكتب جهة تنظيمية، وفي بنك، وعلى مائدة العشاء العائلية."),
    quote: t("The rules are slow. Breaking them is slower.", "القواعد بطيئة. وكسرها أبطأ."), quoteBy: t("Hisham", "هشام"),
    scenes: [
      sc("c10s1", t("A letter from the regulator", "خطاب من الجهة التنظيمية"),
        t("In week 30 a letter arrived. Because Daftar now moved shops' money, it needed permission from the central bank, or a place in its test programme for young companies. The process would take months. Tariq wanted to keep going and deal with it later. Hisham shook his head. “In payments, later is how companies disappear.” They applied to the test programme the next week, and Salma started a folder that grew very thick.",
          "في الأسبوع 30 وصل خطاب. فلأن «دفتر» صار ينقل أموال المحلات، فهو يحتاج إذنًا من البنك المركزي، أو مكانًا في برنامجه التجريبي للشركات الناشئة. والإجراءات ستستغرق أشهرًا. أراد طارق الاستمرار والتعامل مع الأمر لاحقًا. فهزّ هشام رأسه: «في المدفوعات، لاحقًا هي الطريقة التي تختفي بها الشركات.» فتقدّما للبرنامج التجريبي في الأسبوع التالي، وبدأت سلمى ملفًا صار سميكًا جدًا."),
        lift("Regulation in the region", "التنظيم في المنطقة",
          "Payments, health and education are regulated. Central-bank test programmes, licences and data rules take months. Start early and plan around them.",
          "المدفوعات والصحة والتعليم قطاعات منظّمة. البرامج التجريبية للبنوك المركزية والتراخيص وقواعد البيانات تستغرق أشهرًا. ابدأ مبكرًا وخطّط حولها.",
          "Common practice in the region", "ممارسة شائعة في المنطقة")),
      sc("c10s2", t("An uncle who can make a call", "خال يستطيع إجراء مكالمة"),
        t("At a family lunch Salma's uncle heard about the folder. “I know someone,” he said. “One call, and it's done in a week.” It was tempting. Hisham's advice was simple: take the introduction, not the favour. Her uncle's friend explained which office handled their file and which papers were missing. Salma did everything the normal way, just with a map. It still took 3 months. Nobody could ever say they had cut a corner.",
          "في غداء عائلي سمع خال سلمى عن الملف، فقال: «أعرف شخصًا. مكالمة واحدة وينتهي الأمر في أسبوع.» كان العرض مغريًا. ونصيحة هشام كانت بسيطة: خذي التعارف، لا الخدمة. فشرح صديق خالها أي مكتب يتولّى ملفهما، وأي الأوراق ناقصة. ففعلت سلمى كل شيء بالطريقة المعتادة، لكن مع خريطة. واستغرق الأمر 3 أشهر رغم ذلك. ولم يستطع أحد يومًا أن يقول إنهما اختصرا الطريق."),
        lift("Relationships and wasta", "العلاقات والواسطة",
          "Relationships open doors here. Use them for introductions and advice, not for skipping the rules. A shortcut can become the risk that ends you.",
          "العلاقات تفتح الأبواب هنا. استخدمها للتعارف والنصيحة، لا لتجاوز القواعد. فالاختصار قد يصبح الخطر الذي ينهيك.",
          "Common practice in the region", "ممارسة شائعة في المنطقة")),
      sc("c10s3", t("Sign here", "وقّعي هنا"),
        t("To hold on until the licence came, the bank offered a $40,000 loan. On the last page, the bank wanted Salma's personal guarantee: if Daftar could not pay, her flat would. She held the pen for a long time. Then she put it down. They took a smaller loan of $15,000, against the company's monthly revenue, with no guarantee, and cut 2 planned hires instead. The flat stayed hers.",
          "للصمود حتى يأتي الترخيص عرض البنك قرضًا بـ40,000 دولار. وفي الصفحة الأخيرة أراد البنك ضمانًا شخصيًا من سلمى: إن لم يستطع «دفتر» السداد، فشقتها ستسدّد. أمسكت القلم طويلًا، ثم وضعته. وأخذا قرضًا أصغر بـ15,000 دولار، مقابل الإيراد الشهري للشركة، بلا ضمان شخصي، وألغيا توظيفين مخططًا لهما بدلًا من ذلك. وبقيت الشقة لها."),
        lift("A personal guarantee", "الضمان الشخصي",
          "A loan must be repaid whatever happens to the company. A personal guarantee puts your home behind it. Know exactly what you are signing.",
          "القرض يجب أن يُسدّد مهما حدث للشركة. والضمان الشخصي يضع بيتك خلفه. اعرف بالضبط على ماذا توقّع.")),
      sc("c10s4", t("A real job", "وظيفة حقيقية"),
        t("In week 38, at Friday dinner, Salma's mother finally asked. “When will you get a real job? Your cousin just got promoted at the bank.” The table went quiet. Salma did not argue. She took out her phone and showed her mother the runway, the shops, and Umm Hany's message. Then she promised one thing: Friday evenings would stay family time, no laptop. Her mother did not understand the numbers. She understood the promise.",
          "في الأسبوع 38، على عشاء الجمعة، سألتها أمها أخيرًا: «متى ستحصلين على وظيفة حقيقية؟ ابنة خالتك ترقّت للتو في البنك.» سكتت المائدة. لم تجادل سلمى. أخرجت هاتفها وأرت أمها مدة الصمود، والمحلات، ورسالة أم هاني. ثم وعدت بشيء واحد: أمسيات الجمعة ستبقى للعائلة، بلا حاسوب. لم تفهم أمها الأرقام. لكنها فهمت الوعد."),
        lift("Family and partner", "العائلة والشريك",
          "The people at home carry part of the risk. Tell them the real numbers, and protect a little time that belongs only to them.",
          "من في البيت يحملون جزءًا من المخاطرة. أخبرهم بالأرقام الحقيقية، واحمِ وقتًا قليلًا يخصّهم وحدهم.",
          "Brad Feld and Amy Batchelor, Startup Life (2013)", "براد فيلد وإيمي باتشلور، Startup Life (2013)")),
    ],
    tools: {
      title: t("Tools for week 30", "أدوات الأسبوع 30"),
      sections: [
        { type: "checks", title: t("1. Before signing any loan", "1. قبل توقيع أي قرض"), items: [
          t("Is there a personal guarantee? On what?", "هل يوجد ضمان شخصي؟ وعلى ماذا؟"), t("What happens if we miss 2 payments?", "ماذا يحدث إذا فاتنا قسطان؟"),
          t("Could we cut costs instead?", "هل يمكن خفض التكاليف بدلًا من ذلك؟"), t("Has a lawyer read it?", "هل قرأه محامٍ؟"),
        ] },
        { type: "lines", title: t("2. Which rules and licences apply to our business?", "2. أي القواعد والتراخيص تنطبق على مشروعنا؟"), n: 2 },
        { type: "lines", title: t("3. Who at home should know our runway, and which evening is theirs?", "3. من في البيت يجب أن يعرف مدة صمودنا، وأي أمسية لهم؟"), n: 2 },
      ],
    },
  },

  // ───────── 11 ─────────
  {
    title: t("The pivot", "التحوّل"), week: 44, open: "c11open",
    lead: t("Sometimes the data points somewhere you did not plan to go. The hard part is not seeing it. It is saying it out loud.",
            "أحيانًا تشير البيانات إلى مكان لم تخطط للذهاب إليه. الصعب ليس أن تراه، بل أن تقوله بصوت عالٍ."),
    quote: t("A pivot is not starting over. It is turning, with everything you learned in the car.", "التحوّل ليس بداية من الصفر. إنه انعطاف، وكل ما تعلّمته معك في السيارة."), quoteBy: t("Hisham", "هشام"),
    scenes: [
      sc("c11s1", t("90 days", "90 يومًا"),
        t("By week 44 Omar's company owed Daftar $12,000, and it was 90 days late. On paper, Daftar had its best quarter ever. In the bank, there was almost nothing. Salma finally understood Umm Hany's shoebox from the inside. “We're profitable and broke,” said Tariq. Hisham nodded. “Profit is an opinion. Cash is a fact.” Salma drove to Omar's warehouse with a printed statement and a cup of his favourite coffee.",
          "بحلول الأسبوع 44 كانت شركة عمر مدينة لـ«دفتر» بـ12,000 دولار، ومتأخرة 90 يومًا. على الورق كان هذا أفضل ربع في تاريخ «دفتر». وفي البنك لم يكن هناك شيء تقريبًا. وفهمت سلمى أخيرًا علبة أحذية أم هاني من الداخل. قال طارق: «نحن رابحون ومفلسون.» هزّ هشام رأسه: «الربح رأي. والنقد حقيقة.» فقادت سلمى سيارتها إلى مخزن عمر، ومعها كشف حساب مطبوع، وفنجان من قهوته المفضّلة."),
        lift("Cash is not profit", "النقد ليس الربح",
          "A sale you have not been paid for is a promise, not money. Watch how long customers take to pay, and chase it as hard as you sell."
          , "البيع الذي لم يُدفع ثمنه وعد لا مال. راقب المدة التي يستغرقها العملاء للدفع، وطالب بها بالجدية التي تبيع بها.")),
      sc("c11s2", t("The feature nobody asked for", "الميزة التي لم يطلبها أحد"),
        t("Months ago Tariq had added a small button: get paid early. Daftar would pay a shop what it was owed today, for a 2% fee, and collect later. Almost nobody used it. Then Mona looked at the data. The 30 shops that did use it grew 3 times faster, and none of them had left. Shops did not mainly want reminders. They wanted their money now. The fog in front of the company thinned, all at once.",
          "قبل أشهر أضاف طارق زرًا صغيرًا: احصل على أموالك مبكرًا. يدفع «دفتر» للمحل ما يُستحق له اليوم، مقابل رسوم 2%، ثم يحصّل لاحقًا. لم يستخدمه أحد تقريبًا. ثم نظرت منى في البيانات: المحلات الـ30 التي استخدمته نمت أسرع بـ3 أضعاف، ولم يرحل منها أحد. لم تكن المحلات تريد التذكيرات أساسًا، بل أرادت أموالها الآن. وانقشع الضباب أمام الشركة دفعة واحدة."),
        lift("Pivot or persevere", "التحوّل أم الاستمرار",
          "A pivot changes one part of the plan, such as the customer, the problem or the product, while keeping what you have learned.",
          "التحوّل يغيّر جزءًا واحدًا من الخطة، كالعميل أو المشكلة أو المنتج، مع الاحتفاظ بما تعلّمته.",
          "Eric Ries, The Lean Startup (2011)", "إريك ريس، The Lean Startup (2011)")),
      sc("c11s3", t("2x", "ضعفان"),
        t("To pay shops early they needed money to lend, and investors were interested now. One offer came with a beautiful valuation and one small line: a 2x participating preference. Hisham modelled it on the whiteboard. If Daftar sold one day for $3 million, that investor would take back twice their money first, and then a share of the rest. The founders would get far less than the valuation suggested. They took a lower valuation with a clean 1x preference.",
          "لتدفع للمحلات مبكرًا احتاجت إلى مال تُقرضه، وصار المستثمرون مهتمين الآن. جاء عرض بتقييم جميل وسطر صغير واحد: أفضلية تصفية بضعفين مع مشاركة. رسمها هشام على السبورة: لو بيع «دفتر» يومًا بـ3 ملايين دولار، يسترد ذلك المستثمر ضعف أمواله أولًا، ثم يأخذ حصة من الباقي. وسيحصل المؤسسان على أقل بكثير مما يوحي به التقييم. فقبلا تقييمًا أقل مع أفضلية نظيفة بضعف واحد."),
        lift("Liquidation preference", "أفضلية التصفية",
          "It decides who gets paid first when the company is sold. Model your share at a low, medium and high sale price before you sign.",
          "تحدد من يُدفع له أولًا عند بيع الشركة. احسب حصتك عند سعر بيع منخفض ومتوسط ومرتفع قبل أن توقّع.",
          "Brad Feld and Jason Mendelson, Venture Deals", "براد فيلد وجيسون مندلسون، Venture Deals")),
      sc("c11s4", t("One sentence", "جملة واحدة"),
        t("Before telling anyone, Salma made them write the new plan in one sentence. It took 2 evenings. “Daftar pays small shops today for what their customers owe them, and collects it kindly later.” They told the team first, then Layla, then Omar, then Umm Hany. Each one understood it in one hearing. Umm Hany asked only one question: “Can I have mine on Thursdays?”",
          "قبل إخبار أي أحد أصرّت سلمى على كتابة الخطة الجديدة في جملة واحدة. استغرق ذلك أمسيتين: «دفتر يدفع للمحلات الصغيرة اليوم ما يدين به زبائنها، ويحصّله لاحقًا بلطف.» أخبرا الفريق أولًا، ثم ليلى، ثم عمر، ثم أم هاني. وفهمها كل واحد من أول مرة. وسألت أم هاني سؤالًا واحدًا فقط: «هل يمكن أن آخذ أموالي أيام الخميس؟»"),
        lift("Say the plan in one sentence", "قُل الخطة في جملة واحدة",
          "If the plan doesn't fit in one sentence, the team will each carry a different version of it. Write it, then say it the same way to everyone.",
          "إن لم تتسع الخطة لجملة واحدة، سيحمل كل فرد في الفريق نسخة مختلفة منها. اكتبها، ثم قُلها بالطريقة نفسها للجميع.")),
    ],
    tools: {
      title: t("Tools for week 44", "أدوات الأسبوع 44"),
      sections: [
        { type: "calc", title: t("1. Months of revenue waiting to be paid", "1. أشهر من الإيراد تنتظر السداد"), op: "÷", a: t("owed to us", "المستحق لنا"), b: t("revenue a month", "الإيراد الشهري"), c: t("months", "أشهر") },
        { type: "lines", title: t("2. What do our best customers do that the others don't?", "2. ماذا يفعل أفضل عملائنا ولا يفعله الآخرون؟"), n: 2 },
        { type: "lines", title: t("3. Our plan in one sentence", "3. خطتنا في جملة واحدة"), n: 2 },
      ],
    },
  },

  // ───────── 12 ─────────
  {
    title: t("A year later", "بعد عام"), week: 52, open: "c12open",
    lead: t("The fog never fully lifts. A year in, the difference is not that you can see everything. It is that you know how to look.",
            "الضباب لا ينقشع تمامًا أبدًا. بعد عام، الفرق ليس أنك ترى كل شيء، بل أنك تعرف كيف تنظر."),
    quote: t("You don't beat the fog. You learn to read it.", "لا تهزم الضباب. بل تتعلّم قراءته."), quoteBy: t("Hisham", "هشام"),
    scenes: [
      sc("c12s1", t("The lines cross", "يتقاطع الخطّان"),
        t("In week 52 Salma redrew Hisham's 2 lines on the same whiteboard. The early-payment fees had changed everything. Monthly revenue: $21,000. Monthly costs: $19,500. For the first time the lines had crossed. Daftar could keep going even if no investor ever called again. Tariq took a photo of the whiteboard. This time it was the right number.",
          "في الأسبوع 52 أعادت سلمى رسم خطّي هشام على السبورة نفسها. رسوم الدفع المبكر غيّرت كل شيء. الإيراد الشهري: 21,000 دولار. والتكاليف الشهرية: 19,500 دولار. ولأول مرة تقاطع الخطّان. صار «دفتر» قادرًا على الاستمرار حتى لو لم يتصل أي مستثمر مرة أخرى. والتقط طارق صورة للسبورة. وهذه المرة كان الرقم هو الرقم الصحيح."),
        lift("Default alive", "حيّ افتراضيًا",
          "Default alive is something you earn: revenue that covers costs, so the company decides its future, not the next round.",
          "أن تكون حيًا افتراضيًا شيء تكسبه: إيراد يغطي التكاليف، فتقرر الشركة مستقبلها، لا الجولة القادمة.",
          "Paul Graham, Default Alive or Default Dead? (2015)", "بول غراهام، Default Alive or Default Dead? (2015)"),
        eq("21,000", "−", "19,500", "1,500", t("revenue a month ($)", "الإيراد الشهري ($)"), t("costs a month ($)", "التكاليف الشهرية ($)"), t("left over ($)", "الفائض ($)"))),
      sc("c12s2", t("An offer", "عرض"),
        t("A big regional company called. They wanted to buy Daftar. The number was more money than Salma had ever imagined, and less than she now believed the company could become. Hisham told them how his own sale had gone: the price, the 3 years he had to stay, the team he lost. “Selling is a fine ending,” he said. “Just make sure it's the ending you chose.” They said not now, and kept the door open.",
          "اتصلت شركة إقليمية كبيرة. أرادت شراء «دفتر». كان الرقم أكبر مما تخيّلته سلمى يومًا، وأقل مما صارت تؤمن أن الشركة قد تصبحه. أخبرهما هشام كيف جرى بيع شركته: السعر، والسنوات الـ3 التي اضطر للبقاء فيها، والفريق الذي خسره. وقال: «البيع نهاية جيدة. فقط تأكّدا أنها النهاية التي اخترتماها.» فقالا: ليس الآن، وأبقيا الباب مفتوحًا."),
        lift("Exits", "التخارج",
          "Selling a company is a real ending, with its own terms, timelines and people. Know what you want before the offer arrives.",
          "بيع الشركة نهاية حقيقية، لها شروطها ومواعيدها وناسها. اعرف ما تريده قبل أن يصل العرض.",
          "Public reporting on Uber's acquisition of Careem (2019)", "التغطية العامة لاستحواذ Uber على Careem (2019)")),
      sc("c12s3", t("Riyadh?", "الرياض؟"),
        t("Layla thought the next step was Riyadh. More shops, bigger orders, and wholesalers who already knew Omar. Salma was tempted. But Riyadh meant a different regulator, different payment habits, and a team that knew nobody there. They made a slower plan: one partner wholesaler first, a licence application, and Salma spending 1 week a month there, drinking tea in shops at 7 in the morning, again.",
          "رأت ليلى أن الخطوة التالية هي الرياض: محلات أكثر، وطلبات أكبر، وتجّار جملة يعرفون عمر أصلًا. أُغريت سلمى. لكن الرياض تعني جهة تنظيمية مختلفة، وعادات دفع مختلفة، وفريقًا لا يعرف أحدًا هناك. فوضعا خطة أبطأ: تاجر جملة شريك أولًا، وطلب ترخيص، وأسبوعًا كل شهر تقضيه سلمى هناك، تشرب الشاي في المحلات في السابعة صباحًا، من جديد."),
        lift("Expanding to a new market", "التوسع إلى سوق جديدة",
          "A new country is a new company in many ways: new rules, new payment habits, new relationships. Start with one partner and learn before you scale.",
          "البلد الجديد شركة جديدة من نواحٍ كثيرة: قواعد جديدة، وعادات دفع جديدة، وعلاقات جديدة. ابدأ بشريك واحد وتعلّم قبل أن تتوسع.",
          "Common practice in the region", "ممارسة شائعة في المنطقة")),
      sc("c12s4", t("The fog, a year later", "الضباب، بعد عام"),
        t("On the last evening of the year Salma stood at the window of the small office. The street outside was foggy again. It always would be. But she knew her runway to the week, she slept 7 hours, she told her team the truth, and she wrote every number down. Hisham came in with 2 coffees. “Next year will be harder,” he said. “Good,” said Salma. “I can see a little further now.”",
          "في آخر مساء من العام وقفت سلمى عند نافذة المكتب الصغير. كان الشارع في الخارج ضبابيًا من جديد، وسيظل كذلك دائمًا. لكنها صارت تعرف مدة صمودها بالأسبوع، وتنام 7 ساعات، وتقول لفريقها الحقيقة، وتكتب كل رقم. ودخل هشام بفنجاني قهوة، وقال: «العام القادم سيكون أصعب.» فقالت سلمى: «جيد. صرت أرى أبعد قليلًا.»"),
        lift("Clarity, a year later", "الوضوح، بعد عام",
          "The fog never fully lifts. Founders who last learn to work in it: numbers written down, sleep protected, people told the truth.",
          "الضباب لا ينقشع تمامًا أبدًا. المؤسسون الذين يصمدون يتعلّمون العمل وسطه: أرقام مكتوبة، ونوم محمي، وحقيقة تُقال للناس.")),
    ],
    tools: {
      title: t("Your year", "عامك"),
      sections: [
        { type: "lines", title: t("1. Three things that lifted the fog for us this year", "1. ثلاثة أشياء بدّدت الضباب عنّا هذا العام"), n: 3 },
        { type: "lines", title: t("2. One number we will check every single week", "2. رقم واحد سنراجعه كل أسبوع دون استثناء"), n: 1 },
        { type: "lines", title: t("3. What we will do differently next year", "3. ما سنفعله بطريقة مختلفة العام القادم"), n: 3 },
      ],
    },
  },
];
